### ISSUE TITLE
No "continue;" statement in loops

### ISSUE THREAD

**Issue by CursedFlames** [danielyxie/bitburner#103]
"Unrecognized token: ContinueStatement. This is a bug please report to game developer"

**Comment by Fayti1703** [comment]
Break doesn't work either:
"Not implemented BreakStatement"

**Comment by danielyxie** [comment]
Break statement added in latest version v0.27.1

Continue is a bit more complicated; I'm still working on that

**Comment by danielyxie** [comment]
Continue added in most recent update v0.29.1
