### ISSUE TITLE
Same Faction Listed Twice

### ISSUE THREAD

**Issue by JoshNotWright** [danielyxie/bitburner#1034]
If you have a script that automatically joins factions, and you accept a faction invite manually, it will appear twice on your faction list. The first few times, it went away on refresh, but when I left it alone for a while it became permanent, The automated script isn't functioning properly with it either, it isn't able to pull back any data on it. Here's the save, the faction is The Black Hand.
[bitburnerSave_BN4x0_1628276388.zip](https://github.com/danielyxie/bitburner/files/6947499/bitburnerSave_BN4x0_1628276388.zip)

**Comment by hydroflame** [comment]
Fixed.
