### ISSUE TITLE
Error in the tutorial

### ISSUE THREAD

**Issue by ketsuban** [danielyxie/bitburner#1040]
During the tutorial, when you've just hacked (or tried to hack) the `n00dles` server, you're told to "go to your home server with the `home` command", but doing that just gives the error `Bad command. Please follow the tutorial`. The only way to proceed is to continue to the next instruction and create a script *on `n00dles`*, which works but doesn't really seem like what's intended.

**Comment by hydroflame** [comment]
Ugh, you're right ...
