### ISSUE TITLE
smart supply is dumb?

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1100]
Smart supply will fill up storage and kill all your production if you can produce so much that one cycle of materials fills up your entire warehouse
E.g. if you can store 100 space of materials and it wants to buy 55 space of energy and 55 space of water, it will buy the 55 of one of them and only 45 of the other. Then use only 45 of each. Then next cycle it only has 90 available and still buys 55 of one and 35 of the other. Etc until storage is filled with just energy (or just water, I don't know which of them goes first)

**Comment by Aeraggo** [comment]
In addition, Smart Supply will order more materials even if you're importing that material from another industry (using the Export unlock).

**Comment by Aeraggo** [comment]
#654 has a more detailed description for what sounds like the same concern.
