### ISSUE TITLE
When static RAM doesn't match dynamic RAM, explain common reasons.

### ISSUE THREAD

**Issue by threehams** [danielyxie/bitburner#1145]
The dialog box for static and dynamic RAM calculation not matching reads:

```
Dynamic RAM usage calculated to be greater than initial RAM usage on fn: [functionName]. This is probably because you somehow circumvented the static RAM calculation.
Please don't do that :(
```

This can be more specific:
- The static calculator keeps track of functions encountered (it just doesn't return it right now). This can be compared to the dynamic ones encountered, so this box can include the exact function which wasn't included, instead of guessing based on RAM usage.
- The most common unintentional circumvention is from accessing a property off `ns` dynamically: `ns[name]()`. Mentioning this in the dialog box could help.

Suggested text:
```
NetScript function _[functionName]_ was not included in static RAM calculation. This is usually from:
- circumventing the calculator using `eval()`
- calling a property on `ns` dynamically, such as `ns[script]()`

To fix this, either change your code to call the function directly:
`ns.ftpcrack()`
Or, add this to your script somewhere:
`ns.ftpcrack;`
```

**Comment by hydroflame** [comment]
Great idea!
