### ISSUE TITLE
Set up `prettier` and have it format code on git commit.

### ISSUE THREAD

**Issue by threehams** [danielyxie/bitburner#1149]
`prettier` is an opinionated code formatter which works very similarly to Go's formatter. Using an formatter means never manually formatting code again.

For this issue:
- Set `trailingComma: "all"`
- Run `prettier` over the whole project
- Remove all formatting `eslint` rules, as they're no longer needed
- Set up a precommit hook to run `prettier` automatically on commit.

**Comment by hydroflame** [comment]
That would be cool but prettier takes far too long to execute
