### ISSUE TITLE
Player-owned corporations allow the creation of a seventh division (without a name) per industry

### ISSUE THREAD

**Issue by vmesecher** [danielyxie/bitburner#1174]
Once an industry has 6 divisions, the "Create a new division" button shows up still. However, I believe previously, clicking this button did nothing. Now, it creates a new division (subtracting corporation funds, buying a warehouse, hiring employees, producing materials and products, etc).

Steps to reproduce:
1. Start a new Bitnode that allows Corporations (tested on Bitnode-3 and Bitnode-10).
2. Create a corporation, any industry (tested Software, Food, Agriculture, and Fishing). (For note: I used seed money rather than self-fund when creating the corporation, although I would be surprised if that makes a difference).
3. Expand into the 5 new divisions(excluding the starting one).
4. Click "Expand into new City" - the dialog box should pop up with a blank spot in the dropdown for which city to expand to (I can't quite recall, but I believe this is normal).
![BlankDropdown](https://user-images.githubusercontent.com/7805867/132181863-fe08f0cf-e7bc-4a26-8638-7ad0dfdb7eb6.png)
5. Click Confirm.
6. A new popup stating "Opened a new office in !" will appear, along with a half-vertical-size box in the normal division bar at the top of the screen where other divisions can be chosen.
![7thDivision](https://user-images.githubusercontent.com/7805867/132181851-0e371cab-70c5-4e28-8d01-01537c507798.png)
7. The new division is not functional, in that it cannot produce or sell anything. Employees can be hired and set to tasks, but materials cannot be purchased or sold (haven't tried export) despite having the workers to do so.
![Semi-functional7thDivision](https://user-images.githubusercontent.com/7805867/132181880-d913ac58-daad-4c55-9d74-245f108cd35d.png)
8. New divisions past 7 still trigger the popup, confirmation, and subtraction from corporation funds, but do not add any new divisions (that I can find). However, they do get rid the employees, but not the warehouse of the previous 7th division.

Before trying to buy an 8th division, I had 8.350b corporate funds):
![Pre8thDivisionBought](https://user-images.githubusercontent.com/7805867/132183060-48be443d-ce06-42d2-85ad-ebb519bd4327.png)

After buying an 8th division, I had 4.349b corporate funds (the 0.001b difference is the 3 employees that I auto-hired).
![Post8thDivisionBought](https://user-images.githubusercontent.com/7805867/132183210-9085378f-dc25-4b83-96df-e82ec8f7f4bc.png)

I have also attached a console stacktrace that (I think) popped up as an error when a created the 7th division.
[Error.txt](https://github.com/danielyxie/bitburner/files/7114362/Error.txt)

I attempted to trace where the error is coming from in the source code so I could submit a pull request, but I'm a terrible front-end developer (and React is the blackest magic to me) ☺ Someday!

(As  a sidenote, I have seen [Issue 1170](https://github.com/danielyxie/bitburner/issues/1170) occurring as well.)

Edit: Oh, comments I forgot to add although I don't think these are the issue. I'm running Windows 10 Home Version	10.0.19042 Build 19042 and Firefox Version 91.0.2 (64-bit).

**Comment by vmesecher** [comment]
I don't know exactly where the bug is manifesting from, but I did notice that for the [`NewIndustry`](https://github.com/danielyxie/bitburner/blob/aa91e8aeccbdf5b5f9097bcf0bbe3be3294732e3/src/Corporation/Actions.ts#L14-L24) function, you have these lines as safeguard:

```typescript
export function NewIndustry(
  corporation: ICorporation,
  industry: string,
  name: string,
): void {
  for (let i = 0; i < corporation.divisions.length; ++i) {
    if (corporation.divisions[i].name === name) {
      throw new Error("This division name is already in use!");
      return;
    }
  }
```

Seems like a similar check for `NewCity`, which doesn't have this guardrail, would be a quick fix for the bug for now. If you agree, I'm happy to cut a pull request for it.

**Comment by hydroflame** [comment]
Yeah for sure, but the new city and new industry button should also disappear when there's no more options available.

**Comment by vmesecher** [comment]
Good point. Not sure what the original issue was, but I see from the fix you pushed out tonight that the new city (and presumably new industry) button is gone once 6 cities are reached. Thank you!
