### ISSUE TITLE
Unsure if bug - Corp Smart Supply no longer maintains previous levels of required resources in warehouse before it was turned on.

### ISSUE THREAD

**Issue by vmesecher** [danielyxie/bitburner#1178]
Is this an intentional change? It appears to be based off of (I think) [these lines](https://github.com/danielyxie/bitburner/blame/dev/src/Corporation/Industry.ts#L688-L695), but it creates a problem for industries where required materials are also a production multiplier - namely Software as a starting industry, where production multipliers are relatively more important in the early game (unless I'm totally playing totally wrong).

For example, if in the Software Industry, I had 1000 Hardware to start with, then I turned Smart Supply on, previously it would maintain that same 1000 Hardware, which was useful for boosting production. Now, when Smart Supply is enabled with a surplus of a required material, it shows the correct number on the "Buy" button, but it still subtracts from the materials in the warehouse.

If this isn't a bug, it seems like it would be more intuitive to have the "Buy" button show 0 to reflect that the warehouse supply is being used before purchasing new materials, although I prefer the old behavior 😄 I realize that the Corporation formulas look complex though, so understandable either way.

**Comment by hydroflame** [comment]
Oh ok, I didn't realize that. I'm going to add an extra patch to let you decide wether or not to first use the stored materials.

Using stored materials makes sense for agriculture because it's material don't contribute to the "Production Multiplier"

**Comment by hydroflame** [comment]
Are you on discord?

**Comment by hydroflame** [comment]
I think this is fixed with the latest patch, which allows you to control the behavior.
