### ISSUE TITLE
Release on Steam.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1257]
- [x] 100% Typescript
- [x] 100% React
- [x] 100% Mui
- [x] Include documentation in-game (for offline players)
- [x] Nerf gang in a way that it's ok for them to be available outside BN2 (easily)
- [x] Nerf hashnet snowball
- [x] Bump version to 1.0.0

**Comment by ShinodaII** [comment]
I'm honored to be witnessing this moment alive. Hats off to BigD and hydroflame!!
