### ISSUE TITLE
Terminal command entry disappears when moving to another tab and back to the terminal

### ISSUE THREAD

**Issue by Tryneus** [danielyxie/bitburner#1293]
There are two cases that feel a little broken regarding terminal command input.

------

First, regarding typed commands:
1. input a command, but do not hit 'enter'
2. move to another tab, e.g. `Stats`, then back to `Terminal`
3. observe that the input text is gone (and hitting 'enter' does nothing)

------

Second, when using the command history:
1. enter a couple commands to have some command history, e.g.:
```
[home ~/]> hostname
home
[home ~/]> free
Total:     1024.00GB
Used:       556.50GB (54.35%)
Available:  467.50GB
```
2. hit the 'up' key to load a historical command in:
```
[home ~/]> free
```
3. move to another tab, e.g. `Stats`, then back to `Terminal`
4. observe that the input text is gone, and also that hitting 'up' again will proceed with the next previous command in the history (which means the history position was maintained even though the input itself disappeared):
```
[home ~/]> hostname
```

**Comment by hydroflame** [comment]
Fixed in a minute
