### ISSUE TITLE
UI: Scroll issues on Firefox

### ISSUE THREAD

**Issue by Counterbalance** [danielyxie/bitburner#1299]
Whenever you scroll down on any of the pages accessible from the menu and then switch to another page that doesn't fit on the screen, that new page is shown with the page scrolled down.  This happens on the augmentations, hacknet, stats, stock market and the editor pages.

It is a little bit problematic when working on a script as every time the editor is opened, you have to scroll up first.
The change in 75af7 setting the view height to 110% of the visible height causes the overflow on the editor.
Setting this back to 100vh fixes the problem there.

This does not happen on Chrome or Edge, just Firefox. It seemed to be introduced with the recent UI changes.

**Comment by hydroflame** [comment]
Fixed
