### ISSUE TITLE
Issue copying infos from active scripts textbox

### ISSUE THREAD

**Issue by Metallicow** [danielyxie/bitburner#133]
This isn't exactly a bug, but more of an implementation detail that is the issue.
When highlighting the args in the scriptname.script to copy, the selection is continually reset in the textbox because of updating the other production infos. I'm not sure if it is possible with the toolkit to be able to make the `Threads` and `Args` lines in one textbox and the `production` lines in another without changing the look of the dropdown. The `Threads` and `Args` textbox would not "update" every few seconds and wreak the selection.

Example
```
pserv-24
    EarlyHackTemplate.script
        Threads: 4550
        Args: [ecorp, 1500000000000, 35]
        Total online production: $6,235,424,699,100.00
                                 45,734,488.40 hacking exp
        Online production rate: $118,365,050.52/second
                                868.1630 hacking exp/second
        Total offline production: $0.00
                                  3,772.98 hacking exp
        Offline production rate: $0.00/second
                                 432.1856 hacking exp/second
```

**Comment by danielyxie** [comment]
Should be fixed in latest update (v0.29.0), please let me know if its not

**Comment by Metallicow** [comment]
@danielyxie Nope it is still doing it with v0.29.0

**Comment by danielyxie** [comment]
Now it should actually be fixed lol

**Comment by Metallicow** [comment]
Yep, It works now. Thanks :)
