### ISSUE TITLE
Request: sorting with ls

### ISSUE THREAD

**Issue by Metallicow** [danielyxie/bitburner#136]
I would be nice to have options for sorting by, Alphabetical(regardless of case), Types(.extension), and also the norm. If you can think of any other useful sorting types, thats ok too.

**Comment by ByteCommander** [comment]
I believe sorting first by type/extension (maybe executables and scripts first, then messages, then literature last?) and then alphabetically by filename would be the most useful default.

**Comment by Metallicow** [comment]
Normally a OS's file explorer sorts the types alphabetically A-Z or Z-A when sorting this way, by the extension. Ex: .exe, .lit, .script or .script, .lit, .exe
...then alphabetically by the filename.ext. Ex: Brute.exe, NUKE.exe, SQLInject.exe
