### ISSUE TITLE
free command bug

### ISSUE THREAD

**Issue by PatrickDattilio** [danielyxie/bitburner#137]
Running free on one of my purchased servers while running [MercuriusXeno scripts](https://www.reddit.com/r/Bitburner/comments/70ikjm/progression_scripts_0286/)
returns a negative amount used. I believe used * -1 might be the correct used.
```
[p0 ~]> free
--
Total: 16,384.00 GB
Used: -3,261.80 GB
Available: 19,645.80 GB
```

**Comment by danielyxie** [comment]
I'm not 100% certain what caused it but I fixed what I believed to be the cause in the most recent update v0.29.2. Please let me know if it happens again!
