### ISSUE TITLE
Question: Is icarus.msg decodable?

### ISSUE THREAD

**Issue by Metallicow** [danielyxie/bitburner#140]
@danielyxie 
```
@)(#V%*N)@(#*)*C)@#%*)*V)@#(*%V@)(#VN%*)@#(*%
)@B(*#%)@)M#B*%V)____FIND___#$@)#%(B*)@#(*%B)
@_#(%_@#M(BDSPOMB__THE-CAVE_#)$(*@#$)@#BNBEGB
DFLSMFVMV)#@($*)@#*$MV)@#(*$V)M#(*$)M@(#*VM$)
```

Is this some sort of easter egg, secret message to be decoded, or just to look like some encrypted data to non programmers...???
Please no spoilers, just a basic `Yes` or `No` question answers.

Edit: I am a python programmer and found this read very interesting.
[obfuscating-hello-world.py](https://benkurtovic.com/2014/06/01/obfuscating-hello-world.html)

**Comment by danielyxie** [comment]
It has an explicit message in the center. The rest of it is just random gibberish

**Comment by Metallicow** [comment]
Any chance of having decodable messages on servers? Ex: maybe ROT13 or some such cyphers?
... as a way to teach non-programmers a little of decoding logic?

**Comment by danielyxie** [comment]
Definitely, that would be really cool. The encoded messages/files would probably be used for lore/worldbuilding purposes. There's still a lot of content I want to add so it's not high priority right now though. I've made a note of it on my todo list

**Comment by Metallicow** [comment]
Also, the current version keeps sending me icarus.msg every so many minutes. This is annoying... showing the popup once or some other means of reshowing would be preferable.

**Comment by danielyxie** [comment]
The next update (coming very soon hopefully) addresses that by increasing the time it take to pop up to I think 15 or 20 minutes. It is meant to be a repeating message since this is the first time youve seen it. Once you progress it should no longer repeat

**Comment by Metallicow** [comment]
... `progress` You mean hack the bitnode? or manually read the message? I'm on the original bitnode the 2nd time.
