### ISSUE TITLE
new hacking mission

### ISSUE THREAD

**Issue by ZombGuy** [danielyxie/bitburner#142]
![image](https://user-images.githubusercontent.com/24590134/30937478-862dc288-a39c-11e7-90e9-f8584ae1247d.png)

The game worked the first time kind of, but the second time i opened the game it wouldn't start the timer or anything so i looked at console and found this int he above picture.

**Comment by danielyxie** [comment]
I've made a lot of bugfixes and I've been testing very extensively recently without error, so I think I fixed this. If not, let me know
