### ISSUE TITLE
Code Sharing via Quasi-Git

### ISSUE THREAD

**Issue by Eadrom** [danielyxie/bitburner#143]
It'd be great if there was a more streamlined way to share code.  A very simplified, quasi- version of `git` could work.  People can maintain scripts on github and in-game, repos could be "git cloned" where it just pulls down the latest version of the files in the repo; no .git, no versioning, nothing special, just plain text files.  In-game version of git would be basically just git clone functionality for a public repo.  I imagine this would simplify the coding required.

This would make it way faster and easier when someone updates their set of scripts that you use and you want to update them in-game.  A simple update script that just goes and runs "git clone $URL" on all your servers would mean updating scripts is fast and easy.

**Comment by Eadrom** [comment]
This would be especially cool now that we have user-defined functions and can build libraries.

**Comment by RabidGuy** [comment]
I suspect it would be difficult to interface with github. Pastebin, or sites like it, would be lighter and has been used to fill this role in other games.

**Comment by stavvie34** [comment]
I just created a repo on Github for this exact thing. I've gone through the subreddit and stored a copy of every script that was every posted, in a post or a comment. [Check it out](https://github.com/stavvie34/Bitburner-Community) and let me know what you think.

**Comment by jjspace** [comment]
It would be great to have a way to keep my scripts in git or something similar (or even just a quick way to export them to said sources). I've been playing on two different computers (work and home) and it's a bit of a pain to move scripts between them.

To add to the discussion, while I dont think it's exactly easy to make a full repo you could use a [Gist](gist.github.com) to save them. I know of other programs that use it to sync things like settings. The nice part is you can push and pull from them with just a key and not have to fully log in. (maybe even add an option to export the save there too?)

**Comment by danielyxie** [comment]
Now possible using wget and by importing from external URLs (although functionality is limited)
