### ISSUE TITLE
Request: time stamps

### ISSUE THREAD

**Issue by RafnarC** [danielyxie/bitburner#148]
Optional Time stamp for log entry and the terminal.

**Comment by RabidGuy** [comment]
Alternatively, being able to pass a `prefix` argument to `print` and `tprint` would allow you to kill the existing prefix and add your own timestamp.

```
out = Date.now() + " garbage";
tprint(out, prefix="");  // ... or ...
tprint(out, "");  // , with ...
tprint(out);  // ... yielding the same prefix we see in the current version.
```

This would require `prefix` to default to the script name, which I don't believe is available in netscript. Also, this doesn't force non-user-created programs to display a timestamp. Perhaps, a good solution could have similarities to both ideas.

**Comment by danielyxie** [comment]
Implemented. This is now configurable through Terminal settings (`nano .fconf`)
