### ISSUE TITLE
Fix black background caused by some of the weirder margin or padding.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1622]

**Comment by alainbryden** [comment]
![image](https://user-images.githubusercontent.com/2285037/141875874-15da19fc-b7d5-4956-ae91-1567daa9abae.png)

**Comment by TheCoderJT** [comment]
This issue has been fixed from the looks of it i'm commenting here so other contributors don't waste time like I just did trying to solve this.

**Comment by danielyxie** [comment]
Fixed.
