### ISSUE TITLE
Singularity script Ram error

### ISSUE THREAD

**Issue by RafnarC** [danielyxie/bitburner#163]
I'm not sure how this happen but I'm running a singularity script on bit node 2 and its not increasing the ram cost 
it is only my `getcurrentfaction.script        1               26.00GB` it should  be 152.00 GB based on the editor 

my current save
[https://drive.google.com/file/d/1_9d6BbDplNONQmLeKX5hBEwyOHYIasPL/view?usp=sharing](https://drive.google.com/file/d/1_9d6BbDplNONQmLeKX5hBEwyOHYIasPL/view?usp=sharing)

**Comment by danielyxie** [comment]
Should be fixed now, let me know if its not
