### ISSUE TITLE
Bug in hackAnalyzeThreads, returns -1 when money is positive and less than money available

### ISSUE THREAD

**Issue by jenheilemann** [danielyxie/bitburner#1645]
```js
var scriptThreads = getRunningScript().threads

while(true) {
  if (getServerSecurityLevel(target) > securityThreshhold) {
    weaken(target)
    continue
  }

  money = getServerMoneyAvailable(target)
  if (money < moneyThreshhold ) {
    grow(target);
    continue
  }

  threads = Math.floor(hackAnalyzeThreads(target, money * 0.6))
  threads = Math.min(threads, scriptThreads)
  if ( threads == -1 ) {
    tprint("Threads negative! target ", target, " money ", nFormat(money,"$0.000a"),
      " money * 0.6 ", nFormat(money * 0.6,"$0.000a"),
      " hackAnalyzeThreads ", hackAnalyzeThreads(target, money * 0.6))
    continue
  }
  hack(target, { threads: threads })
}
```

I'm frequently getting debugging messages like:
> get-money.script: Threads negative! target joesguns money $62.500m money * 0.6 $37.500m hackAnalyzeThreads -1

It frequently happens when the server is at max money, but it does not trigger every time it's at max, and I have seen it trigger at less than max money.

**Comment by hydroflame** [comment]
Is this script being executed in ns1 or ns2?

because in ns1 that would be normal

**Comment by alainbryden** [comment]
@jenheilemann So I think the suggestion here is that you've encountered a race-condition in your program.

True, `money >= moneyThreshold` when you stop `grow`ing, but the implication here is that another script running at the same time as this one may have stolen money from the server right before you executed the next line of code. (`hackAnalyzeThreads`). (This is especially possible when coding with `.script` files, which are run one at a time before context is passed back to the game to see what other code needs to run.)

Perhaps you can test this theory by adding a check like this to your if statement:

```javascript
  if ( threads == -1 ) {
    var serverMoneyNow = getServerMoneyAvailable(target);
    if ( money != serverMoneyNow )
      tprint("Whoops, server money changed before we could hack. Money was ", nFormat(money,"$0.000a"),
        " but is now ", nFormat(serverMoneyNow, "$0.000a"))
    else
      tprint("Threads negative! target ", target, " money ", nFormat(money,"$0.000a"),
        " money * 0.6 ", nFormat(money * 0.6,"$0.000a"),
        " hackAnalyzeThreads ", hackAnalyzeThreads(target, money * 0.6))
    continue
  }
```

**Comment by jenheilemann** [comment]
Gotcha! Good to know. I'll probably migrate this script to ns2 to try and avoid the issue. Not at a computer right now, so not able to test, but the explanation makes sense. Thanks y'all!
