### ISSUE TITLE
Gang member assignment drop down doesn't change when assigned by script

### ISSUE THREAD

**Issue by rlandau** [danielyxie/bitburner#1661]
If you are on the Gang member screen, and a script changes a gang members task, the text describing the assigned task changes, but the drop down either stays blank, or stays on the last task. 

![image](https://user-images.githubusercontent.com/6207292/140385738-58fab18a-0a1d-4b90-bdad-a9cde1e4fc79.png)

**Comment by hydroflame** [comment]
Not a bug, what if you wanted to change from one task to another but the UI updated itself as you were trying to modify it.

Weird consequence I know but not a bug.
