### ISSUE TITLE
User-initiated Bladeburner actions should cancel current activities

### ISSUE THREAD

**Issue by trambelus** [danielyxie/bitburner#1663]
Currently, if the user is busy with any non-Bladeburner activity, manually initiating a Bladeburner action will fail promptly with the alert "Your Bladeburner action was cancelled because you started doing something else." Cancelling the previous activity might be a more expected outcome.

**Comment by hydroflame** [comment]
Makes sense.

**Comment by hydroflame** [comment]
Fixed in 1.0.0
