### ISSUE TITLE
getScriptRam has weird issues with player servers that have 1024 GB of ram

### ISSUE THREAD

**Issue by cehnehd3h** [danielyxie/bitburner#168]
I made a batch of 1024 GB RAM servers, and the getScriptRam function always returns 0 when I call it with my script. The script in question is only 2.4 GB. The script in question is as follows:

// a script that maintains a balance and security level as it hacks a server
targetServer = args[0];
while(true) 
{
    if (getServerMoneyAvailable(targetServer ) < args[1]
) 
        grow(targetServer );
    else if (getServerSecurityLevel(targetServer ) > args[2]) 
        weaken(targetServer );
    else 
        hack(targetServer );
}

Here's my full save: 
[bitburnerSave (1).zip](https://github.com/danielyxie/bitburner/files/1577914/bitburnerSave.1.zip)

Run this to get it going:
run maintainhack.script "foodnstuff" 2000000 6

**Comment by sordidfellow** [comment]
Your script is checking the getScriptRam() of autohack.script on a host before it actually copies it to that host, and getScriptRam returns 0 if the script does not exist on the host.

**Comment by danielyxie** [comment]
I agree with sordid

You probably already figured this out, but you just need to change `serverName` to `getHostname()`:

`packageSize = getScriptRam("autohack.script", serverName);`
