### ISSUE TITLE
autocomplete dir

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1681]
Autocomplete doesn't respect script directories not starting with a slash. Example:
run src/scripts/route.js does not work, but run /src/scripts/route.js does

**Comment by fpottbaecker** [comment]
I can confirm, here's is a tiny script to reproduce it:

```js
export function autocomplete(data, args) {
	return [...data.servers];
}

export async function main(ns) {
	ns.tprint(ns.args.join(", "));
}
```

Saved as `bin/test.js`.

Autocomplete on `run bin/test.js n0` produced nothing (or `n00dles.script`).
Autocomplete on `run /bin/test.js n0` produced `n00dles`, as expected.
