### ISSUE TITLE
Formulas.exe should be given in BN5

### ISSUE THREAD

**Issue by MatiasGoldfeld** [danielyxie/bitburner#1702]
I do not have `Formulas.exe`, but I am in BitNode-5 which I believe should let me use the formula API. However, when I call `moneyGainRate()` (and potentially other formula functions), I get the following error:

`formulas.hacknetNodes.moneyGainRate: Requires Formulas.exe to run.`

Looking at the source code (e892e1658556e9826651f818eb18fe9164837743), it looks like the behavior changed from only requiring SF 5-1 or being in BitNode-5 to only requiring `Formulas.exe`. I guess the documentation hasn't been updated, but is this intentional? Should being in BitNode-5 give you `Formulas.exe`?

**Comment by hydroflame** [comment]
Ah, ok yeah. You can still buy it from the dark web but you're right it should give it to you when entering BN5

**Comment by hydroflame** [comment]
Will be fixed next time you install or soft reset
