### ISSUE TITLE
Initiating Bladeburner actions interrupts the current action even when unnecessary

### ISSUE THREAD

**Issue by trambelus** [danielyxie/bitburner#1709]
When the Blade's Simulacrum augment is installed, Bladeburner actions can happen concurrently with other activities. The recent change that made Bladeburner actions interrupt current activities was useful in cases without the augment, but with the augment, it should probably just behave as it did before.

**Comment by hydroflame** [comment]
duh, makes sense

**Comment by hydroflame** [comment]
Fixed in 2 minutes
