### ISSUE TITLE
Can run "buy" command to purchase items on "home"

### ISSUE THREAD

**Issue by wingedRatite** [danielyxie/bitburner#171]
I created an alias that was called "buy" and then tried to connect to "darkweb" and buy items, but I recieved an "ERROR: no such script". "unalias" was also being unsupportive of me so I exported the game, decoded it, changed the name of the alias, recoded it, and reloaded it into the browser. I saved the game and reloaded the browser, then tested to see if the alias worked. When I typed "buy" on "home", it prompted me exactly as how it would on the server "darkweb":

    [home ~]> alias
    alias ident=run ident.script
    alias status=run _InvestmentBroker_Msg.script S
    alias sbuy=run _InvestmentBroker_Msg.script A
    alias sell=run _InvestmentBroker_Msg.script L
    [home ~]> buy
    Incorrect number of arguments. Usage:
    buy -l
    buy [item name]
    [home ~]> buy -l
    BruteSSH.exe - $500,000 - Opens up SSH Ports
    FTPCrack.exe - $1,500,000 - Opens up FTP Ports
    relaySMTP.exe - $5,000,000 - Opens up SMTP Ports
    HTTPWorm.exe - $30,000,000 - Opens up HTTP Ports
    SQLInject.exe - $250,000,000 - Opens up SQL Ports
    DeepscanV1.exe - $500,000 - Enables 'scan-analyze' with a depth up to 5
    DeepscanV2.exe - $25,000,000 - Enables 'scan-analyze' with a depth up to 10
    [home ~]> connect darkweb
    Connected to darkweb
    You are now connected to the dark web. From the dark web you can purchase illegal items. Use the 'buy -l' command to display a list of all the items you can buy. Use 'buy [item-name] to purchase an item
    [darkweb ~]> buy
    Incorrect number of arguments. Usage:
    buy -l
    buy [item name]
    [darkweb ~]> buy -l
    BruteSSH.exe - $500,000 - Opens up SSH Ports
    FTPCrack.exe - $1,500,000 - Opens up FTP Ports
    relaySMTP.exe - $5,000,000 - Opens up SMTP Ports
    HTTPWorm.exe - $30,000,000 - Opens up HTTP Ports
    SQLInject.exe - $250,000,000 - Opens up SQL Ports
    DeepscanV1.exe - $500,000 - Enables 'scan-analyze' with a depth up to 5
    DeepscanV2.exe - $25,000,000 - Enables 'scan-analyze' with a depth up to 10
    [darkweb ~]> home
    Connected to home
    [home ~]> alias buy=buy
    Incorrect usage of alias command. Usage: alias [-g] [aliasname="value"]
    [home ~]> alias buy="buy"
    [home ~]> buy
    Incorrect number of arguments. Usage:
    buy -l
    buy [item name]
    [home ~]> alias buy="dalek.script"
    [home ~]> buy
    Command not found
    [home ~]> alias buy="run dalek.script"
    [home ~]> buy
    Running script with 1 thread(s) and args: [].
    May take a few seconds to start up the process...
    dalek.script: EXTERMINATE
    [home ~]> connect darkweb
    Connected to darkweb
    You are now connected to the dark web. From the dark web you can purchase illegal items. Use the 'buy -l' command to display a list of all the items you can buy. Use 'buy [item-name] to purchase an item
    [darkweb ~]> buy
    ERROR: No such script
    [darkweb ~]> buy
    ERROR: No such script
    [darkweb ~]> buy -l
    ERROR: No such script
    [darkweb ~]> buy HTTPWorm.exe
    ERROR: No such script
    [darkweb ~]> home
    Connected to home
    [home ~]> buy
    Running script with 1 thread(s) and args: [].
    May take a few seconds to start up the process...
    dalek.script: EXTERMINATE
    [home ~]> unalias buy
    Incorrect usage of unalias name. Usage: unalias "[alias]"
    [home ~]> unalias "[buy]"
    No such alias exists
    [home ~]> alias
    alias ident=run ident.script
    alias status=run _InvestmentBroker_Msg.script S
    alias sbuy=run _InvestmentBroker_Msg.script A
    alias sell=run _InvestmentBroker_Msg.script L
    alias buy=run dalek.script
    [home ~]> unalias "[buy=run dalek.script]"
    No such alias exists
    [home ~]> unalias [buy=run dalek.script]
    Incorrect usage of unalias name. Usage: unalias "[alias]"
    [home ~]> unalias "buy=run dalek.script"
    No such alias exists
    [home ~]$
    

I then deleted the game and skipped Exit Tutorial and did this in the terminal:

    Bitburner v0.34.0
    [home ~]> buy
    You need to be connected to the Dark Web to use the buy command
    [home ~]$

I bought the TOR router and tried again.

    [home ~]> buy
    Incorrect number of arguments. Usage:
    buy -l
    buy [item name]
    [home ~]> connect darkweb
    Connected to darkweb
    You are now connected to the dark web. From the dark web you can purchase illegal items. Use the 'buy -l' command to display a list of all the items you can buy. Use 'buy [item-name] to purchase an item
    [darkweb ~]> buy
    Incorrect number of arguments. Usage:
    buy -l
    buy [item name]
    [darkweb ~]> home
    Connected to home
    [home ~]$

So I can "buy" from "home". Maybe I don't know how use "unalias", but I can just use "alias buy=buy" to fix the bad alias call without exporting my save.

**Comment by RabidGuy** [comment]
This is not a bug. You can use the `buy` command while connected to `[home ~]` without using an alias.

The following is an example of creating, using, and deleting an alias.

```
[home ~]> alias sa="scan-analyze"
[home ~]> sa 3
~~~~~~~~~~ Beginning scan-analyze ~~~~~~~~~~
 
>iron-gym
--Root Access: YES, Required hacking skill: 100
--Number of open ports required to NUKE: 1
--RAM: 32

...

[home ~]> unalias "sa"
Removed alias sa
[home ~]> sa 3
Command not found
```

**Comment by danielyxie** [comment]
It looks like the description for 'unalias' is a bit unclear. If you type 

`help unalias`

into Terminal it should give a good example. 

But yes this is not a bug, I chose to let people run `buy` from any server because having to connect to the "Dark Web" to do it just becomes tedious.  (Also, buying from the Dark Web will place programs on the home computer no matter where you run `buy` from)

I'll clarify some of the messages and texts relating to this
