### ISSUE TITLE
Un-awaited calls to "UpdateRamUsage" lead to race conditions when the suddenly complete

### ISSUE THREAD

**Issue by alainbryden** [danielyxie/bitburner#1714]
![image](https://user-images.githubusercontent.com/2285037/141603352-1c54b371-b18a-4ce4-827a-02272366f780.png)

This error message is meant to handle a lack of main function, but lately it's a symptom of newly created/modified scripts that are not fully processed when they are executed by `executeJSScript`. How is this possible?

After running around and seeing that you make sure the newly async functions `write` and `scp` return a promise that awaits `UpdateRamUsage`, I finally figured out the likely cause: It's the un-awaited invocation in the constructor.

![image](https://user-images.githubusercontent.com/2285037/141603478-8cf3526d-1a66-490d-a77d-5fad16848cd8.png)

At first I thought they were innocuous (so what if we are updating RAM usage 2 or 3 times more than we need to?) - but it turns out these calls have destructive side-effects. Every call to `updateRamUsage` terminates in `markUpdated`, which clears the loaded module for the script:
![image](https://user-images.githubusercontent.com/2285037/141603514-7c6f1ca8-4809-45a8-8bea-395f71ee7514.png)

I've found one race condition, but there could be others. This is the one that corresponds to the above error message:
![image](https://user-images.githubusercontent.com/2285037/141603538-25bedb99-c76f-4d86-a9a1-734c4cfcd780.png)

When line 40 is run `await compile(script, scripts);` - the `module` property of the script is re-populated after having been reset by a prior call to `UpdateRamUsage` and/or `markUpdated` - but then on line 42, we `await` another promise, and this is javascript's opportunity to context-switch to some other task - like one of those prior redundant "fire-and-forget" calls to `UpdateRamUsage`! They will reset the module (which was just repopulated) and now the main function is missing, as well as the rest of the code.

---

I'm sure you can come to a decent solution yourself, but from looking around at various usages, it seems to me that we don't necessarily need the un-awaited call to `updatedRamUsage` in the constructor anymore, so long as every usage of `new Script()` follows up with a call to `updateRamUsage`. (unless it has copied these things from another script, in which case no update may be needed)

The "saveScript" method should probably be made async, although I think it's only ever invoked from the ScriptEditor ui, which doesn't appear to have async entry points. Not sure if that matters though - there's probably less chance of a race condition between someone manually editing and saving a file and something trying to run it.

**Comment by alainbryden** [comment]
I just noticed but it looks like `write` is still not an async function: https://github.com/danielyxie/bitburner/blob/dev/src/NetscriptFunctions.ts#L1657

I think all of the code paths return a promise, and I'm honestly not even sure what difference it would make, but it seems like it should be an `async function` instead, and you should be returning `await script.updateRamUsage()` rather than returning the promise object directly? In any event, this is what you did to `scp` when you made it async the other week.

**Comment by alainbryden** [comment]
I had an idea for a workaround. Currently "compile returns nothing, but if it returned the "module" that you await below, it would be atomic, and it wouldn't matter if module get's reset asynchronously a moment later - this script would still have a copy/reference to the module as it was when 'compile' was called.

**Comment by alainbryden** [comment]
Oh and if you're looking for an easy way to reproduce, make a script on home that scp's some script to another server, execs it, then rm's it in a loop.

Might need to do this to all servers in parralel to exacerbate the race condition.

**Comment by theit8514** [comment]
Here is the save file that generates the issue more reliably. `exec()` is called repeatedly with multiple arguments with no control given back to the JS engine using await to actually finish compiling/awaiting the Promise.
[bitburnerSave_1641718946_BN1x1.txt](https://github.com/danielyxie/bitburner/files/7837204/bitburnerSave_1641718946_BN1x1.txt)

**Comment by Snarling** [comment]
I forgot to mention this issue, but this should be fixed by #3985 which is merged.
