### ISSUE TITLE
installBackdoor does not return a Promise<boolean>

### ISSUE THREAD

**Issue by Feodoric** [danielyxie/bitburner#1724]
Docs for the `installBackdoor` singularity function indicate it returns a `Promise<boolean>`:
![Screen Shot 2021-11-15 at 11 08 19 AM](https://user-images.githubusercontent.com/711451/141815309-ac0a2d13-4520-4520-b1a2-fb653e8eb48e.png)

But this does not appear to be true:
https://github.com/danielyxie/bitburner/blob/b990e0e71c3f1b2f814493dd64cb289de9c636fa/src/NetscriptFunctions/Singularity.ts#L597
and 
https://github.com/danielyxie/bitburner/blob/b990e0e71c3f1b2f814493dd64cb289de9c636fa/src/NetscriptFunctions/Singularity.ts#L624

Show the code returning a resolved promise with no boolean value, which appears to the calling code as an `undefined` value.

**Comment by alainbryden** [comment]
Question is, do we fix the API or fix the docs? Would correcting this break backdoor scripts?

**Comment by hydroflame** [comment]
The doc because it either crashes or succeeds.

**Comment by jcollard** [comment]
It appears the documentation is partially fixed. It has the correct return type but the documentation also says:

```
Returns:

Promise<void>

True if the installation was successful.
```
