### ISSUE TITLE
Text fields should accept scientific.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1725]

**Comment by hydroflame** [comment]
corp specifically.

**Comment by phyzical** [comment]
Just to confirm this would require updating all onChange  to accept `1e+3`  for example

**Comment by Master-Guy** [comment]
That's what I'm reading as well.
isNaN() should be able to validate the input for number-only fields.

**Comment by phyzical** [comment]
This is about supporting the new react component that allows i.e `1b`
