### ISSUE TITLE
pre line

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1726]
You know a while back you fixed a bug where in the terminal, padding made from spaces was ignored (e.g. "test      test" became "test test")? That same bug exists in tail windows still. 
I've been using non-breaking spaces for a while (+0160) so I didn't notice, but it should probably be fixed there too
The solution was to have the terminal CSS use white-space: pre-wrap 
Tail windows are currently using white-space: pre-line

**Comment by alainbryden** [comment]
![image](https://user-images.githubusercontent.com/2285037/141875463-b241eb46-46c0-4880-aa4c-8cc2d21dae60.png)
