### ISSUE TITLE
initla rep vs updated rep

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1727]

**Comment by alainbryden** [comment]
![repglitch](https://user-images.githubusercontent.com/2285037/141875395-93026a27-0e7b-4a55-9e6e-e20387802aea.gif)

**Comment by alainbryden** [comment]
#1678 / https://github.com/danielyxie/bitburner/commit/15b3a82a41ee0da1d1926049de9eb72b29f88942
