### ISSUE TITLE
NaN Charisma exp working as CTO

### ISSUE THREAD

**Issue by ArtForz** [danielyxie/bitburner#176]
But you get AGI?
Not quite sure, but looks like
https://github.com/danielyxie/bitburner/blob/3fab52971c69e5870bddd603b4e5fb05dc274b75/src/Company.js#L359
is missing a ,0 and should be
(1.5, 0, 0, 0, 0, 1)

**Comment by danielyxie** [comment]
Fixed in v0.34.2, let me know if there are still issues. Thanks
