### ISSUE TITLE
soft reset should clear terminal and close all log windows

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1774]

**Comment by alainbryden** [comment]
And stop all running scripts?

I often get ongoing Toasts popping up from my scripts while deciding what to choose for my next BN

**Comment by hydroflame** [comment]
I thought it already did but yeah

**Comment by alainbryden** [comment]
You know what, I'm conflating soft-reset with hacking world-daemon. I think soft reset does kill all, but when hacking world_daemon it should probably happen a little sooner.
