### ISSUE TITLE
nano .fconf

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1777]
nano .fconf displays the error "Invalid file. Only scripts (.script, .ns, .js), text files (.txt), or .fconf can be edited with nano"

**Comment by jerlam06** [comment]
I am having the same issue.

**Comment by hydroflame** [comment]
.fconf does not exists

**Comment by hydroflame** [comment]
All the options that used to be in fconf are in options now

Did you find another reference to it?

**Comment by jerlam06** [comment]
Ah ok it makes sense, thanks. 
What do you mean another reference to it? In the docs it still says to use "nano .fconf", if this is what you mean.

**Comment by hydroflame** [comment]
Which doc?

**Comment by jerlam06** [comment]
Here: https://bitburner.readthedocs.io/en/latest/basicgameplay/terminal.html?highlight=fconf

**Comment by hydroflame** [comment]
Thank you
