### ISSUE TITLE
Warnings in console when NS2 scripts call ns.exit or ns.spawn

### ISSUE THREAD

**Issue by cvr-119** [danielyxie/bitburner#1815]
NS2 scripts create warnings in the DevTools console when they call exit functions like ns.exit or ns.spawn:
https://github.com/danielyxie/bitburner/blob/f0a004e75b/src/Netscript/killWorkerScript.ts#L121

**Comment by hydroflame** [comment]
Yeah, it's actually not wrong that shouldnt happen.

**Comment by cvr-119** [comment]
I get the warnings every time as far as I can tell. Running in Chrome on Windows. I've tried creating a script with just ns.exit() in a new game with the same result.

**Comment by hydroflame** [comment]
You're absolutely correct. 

I changed something in the way scripts are run & die a while ago and created this issue.

It shouldn't appear but I need it to because there's an underlying issue that's not fixed.

**Comment by hydroflame** [comment]
I supposed I should remove the warning and open a github issue.
