### ISSUE TITLE
killWorkerScript.ts#L121 warning reminder

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1818]
A little while ago I change something about the lifecycle of scripts and had to add a bunch of "kill" everywhere because they would get clean up in the wrong order, the side effect is that killWorkerScript.ts#L121 had a warning that always printed. Revisit that when (1) I remember and (2) I know how to fix it.

**Comment by phyzical** [comment]
is this still an issue looking at that code its commented out?

**Comment by Snarling** [comment]
I think this can be closed?
