### ISSUE TITLE
Game crashes on load

### ISSUE THREAD

**Issue by LorenzoPane** [danielyxie/bitburner#182]
> Uncaught Error: Module parse failed: C:\Users\danie\Desktop\netburner\src\Constants.js Unexpected token (1140:4)
> You may need an appropriate loader to handle this file type.
> |     "-Minor balance changes to Corporation. Upgrades are generally cheaper and/or have more powerful effects. " +
> |     "You will receive more funding while your are a private company. "
> |     "-Accessing the hacknetnodes array in Netscript now costs 4.0GB of RAM (only counts against RAM usage once)<br>"
> | 
> | }

Introduced in commit: https://github.com/danielyxie/bitburner/commit/9e20856b5f7bfa30ba19d3626268177eb92518b3

**Comment by danielyxie** [comment]
Fixed
