### ISSUE TITLE
Allow suppressing messages from TIX

### ISSUE THREAD

**Issue by boris-stepanov** [danielyxie/bitburner#1821]
Hi!
My trading scripts use Limit/Stop orders which spam the screen after resolving. Refreshing the window is a common morning routine, but the checkbox would be great!

**Comment by hydroflame** [comment]
Ok, I merged something that I hope is what you wanted.

**Comment by hydroflame** [comment]
I hope it does what you want, if not, open another issue.

**Comment by boris-stepanov** [comment]
Sure, could you link a commit, please?
