### ISSUE TITLE
documentation: read and write functions missing

### ISSUE THREAD

**Issue by sschmidTU** [danielyxie/bitburner#1853]
https://bitburner.readthedocs.io/en/latest/netscript/netscriptfunctions.html
https://bitburner.readthedocs.io/en/latest/index.html

At least you can get the JSDoc in the game on hover (Steam version) :)

Btw awesome to have the game on Steam now, congrats! Gonna hunt for achievements a bit :D

**Comment by sschmidTU** [comment]
Also writePort and readPort.

**Comment by sschmidTU** [comment]
They do exist here:
https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.md

But there you don't have e.g. hacknet functions like numNodes and all the other tutorial stuff on one page.

**Comment by hydroflame** [comment]
Right ok, so that is now the "basic documentation" and markdown is the full documentation.

**Comment by sschmidTU** [comment]
Oh, I see. Definitely a good step to call it basic/full documentation, because it was not at all clear to me that the "basic" documentation should be incomplete.
