### ISSUE TITLE
Running connect in the background while editing scripts saves scripts on wrong server.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1861]

**Comment by alainbryden** [comment]
I think there might be a more trivial way to reproduce this.

- Start editing a script at home
- Save and exit (or don't) and head back to the terminal.
- Connect to a new server (e.g. n00dles)
- Launch script editor via the menu
- The script will say it's editing `~Home/scriptname.js` but on save, it's stored on n00dles.

![bug](https://user-images.githubusercontent.com/2285037/145739880-02e8e626-788c-46af-b480-b57a27101961.GIF)
