### ISSUE TITLE
toast() crashes window

### ISSUE THREAD

**Issue by ivanjermakov** [danielyxie/bitburner#1868]
When running `toast()` with any args, the window goes black and doesn't respond. Refresh reloads it back.
Windows 10, Steam version

**Comment by hydroflame** [comment]
Can you do it while activating the debug and taking a screenshot of the `console` ?

**Comment by ivanjermakov** [comment]
![image](https://user-images.githubusercontent.com/26609879/145928758-2423881a-ab9f-45f3-93a7-afbcb8367fdd.png)
It happens when the object/array is passed as a `msg`. Reproducible example:
````
toast({})
````

**Comment by ivanjermakov** [comment]
#1941
