### ISSUE TITLE
Linux users have trouble running the game.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1873]
https://steamcommunity.com/app/1812820/discussions/0/3200367934440912354/
https://steamcommunity.com/app/1812820/discussions/1/3200367934442224107/

**Comment by Redmega** [comment]
Can confirm workaround, adding `--no-sandbox` to the launch options

**Comment by hydroflame** [comment]
Starting the game through steam vs running the app directly attaches the steam overlay to the game process, maybe this causes issues for some distros.
I cannot access the overlay in windows using shift+tab, so maybe disabling it by default (if even possible) might help?

The overlay supports games that use DirectX 7 - 12, OpenGL, Metal, and Vulkan. The overlay will not be active in software-rasterized games.

NOTE: The overlay is automatically disabled for 'Software' app types. If you need the overlay enabled, you can do so by:

    Making sure your Steam account has the Edit App Metadata permission
    Navigate from the App's landing page to > Edit Steamworks Settings > Installation tab > General Installation
    Check box for Enable Steam Overlay for Application
    Publish

**Comment by hydroflame** [comment]
https://www.reddit.com/r/gamedev/comments/mc9s5x/comment/haj3m6m/?utm_source=share&utm_medium=web2x&context=3

**Comment by hydroflame** [comment]
you can kinda see the overlay if you add the launch options
--in-process-gpu --disable-direct-composition
but it's super glitchy

**Comment by hydroflame** [comment]
For what it's worth, under a manjaro VM, I'm getting intermitent issues starting bitburner that seems to disappear when I add the --no-sandbox launch option to the game

**Comment by hydroflame** [comment]
ok this is definitely the issue with steam overlay cropping up again. I don't have time to investigate fully but can you try disabling the overlay and see if that works?
[887836.269959] bitburner[316283]: segfault at 1 ip 00007f5a93b7a185 sp 00007fff3ca08d80 error 6 in gameoverlayrenderer.so[7f5a93b70000+39000]
[888018.852223] bitburner[316433]: segfault at 1 ip 00007fbf1aea0185 sp 00007ffc94558c10 error 6 in gameoverlayrenderer.so[7fbf1ae96000+39000]

**Comment by hydroflame** [comment]
yeah I'm getting a segfault in gameoverlayrenderer even with the overlay disabled in the interface
Ah the gameoverlay error is probably a red herring
https://github.com/ValveSoftware/steam-for-linux/issues/3724#issuecomment-397616101

**Comment by hydroflame** [comment]
I think I've narrowed manjaro crash to the seccomp sandbox
--no-sandbox launch option works, but it also works if instead I use
--disable-seccomp-filter-sandbox

https://chromium.googlesource.com/chromium/src/+/0e94f26e8/docs/linux_sandboxing.md#the-sandbox-1

I think it could be added in the electron main.js but I'm not sure if there's security implications of disabling that layer
// run this at early startup, before app.on('ready')
app.commandLine.appendSwitch('--SWITCH-HERE')

**Comment by jojo2357** [comment]
currently playing through steam no problem, I used the `--no-sandbox` option

os: pop-os 21.10
