### ISSUE TITLE
Missing Corporation API features

### ISSUE THREAD

**Issue by jb9876** [danielyxie/bitburner#1875]
As a user, one way I profit in the corporation is exporting materials from low-market-price cities to higher market-price cities.  I expected to be able to automate this cumbersome process, but I've found two missing features.  Note that the developer may not intend to allow users to do this.  If so, I wouldn't expect the first suggestion to be implemented.

1) As a user, I would expect `marketPrice` to be a property on materials when I call `getMaterial`.  A potentially naive implementation:  https://github.com/jb9876/bitburner/blob/20ffa5a214e081a2429bc85ddbef7e21667cb82e/src/NetscriptFunctions/Corporation.ts#L143

Basically, I'm just asking that a materiel's `bCost` be exposed through the API.

2) As a user, it's near impossible to script the cancelling of one or all exports.  In order to cancel an export, I need to know the amount and target location:  https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.warehouseapi.cancelexportmaterial.md
Unless I've recorded this somewhere, there's no way to know how to remove all exports.  My suggestion is to add a `getMaterialExports(division, city, materialName)` function to return an array of exports that exist on a given material/city/division.  

As a developer, I may want to iterate over all materials in a city.  Right now, there doesn't seem to be an easy way to do this?  `getDivisionMaterials(division)` returning an array of material names would help, as I could iterate over only the desired materials.

(This is my first contribution here, so let me know if I'm out of bounds on anything)

**Comment by phyzical** [comment]
@pigalot is this something we think should be allowed in the corp api do you think?

**Comment by pigalot** [comment]
I don't think bcost will really do anything @jb9876 why exactly do you want it exposed?

**Comment by pigalot** [comment]
I assume bCost is the missing factor you need to work out TA II, if thats the case its up to higher powers but I would suggest not exposing it.

**Comment by phyzical** [comment]
👍 closable

**Comment by jb9876** [comment]
@pigalot @phyzical My motivation in exposing this is around early game optimization of selling things in a Corporation.  The quality / bCost is different across 6 cities in an industry.  This allows a user currently to pick one city to export all goods to and sell from there.  This is at most a 2x to 3x bump in efficiency for the price you can sell your goods.  So, my intention is to optimize the early game with the first industry a user opens up.  

On the other hand, if this exposes TA II too early, this could be a problem.  I haven't used TA II or done a deep-dive into that code.  We could alleviate this by restricting exposing bCost to only materials and not products, maybe?

**Comment by phyzical** [comment]
i guess the issue is corps are already OP.

But at the same time.. i guess the user could just infer this information. granted it would be painful to accurately get this info.

i agree higher powers should decide

**Comment by pigalot** [comment]
Frankly the use case its self is a trap, exporting and then selling is generally not a great idea at this time its something people come up with a lot because they think it "should" be useful but really isn't.
I think this sort of thing can be parked until corps get reworked to be in a more balanced state.
