### ISSUE TITLE
Request: Disable automatic updates in log

### ISSUE THREAD

**Issue by stavvie34** [danielyxie/bitburner#188]
When I'm tailing a script, oftentimes the log feels spammed by information from my actions that I don't care about. 

For instance, every time I take a university course, I'm told all that I gained right afterwords. Or I don't need to know `Sleeping for 10000 milliseconds` every 10 seconds in the log.

If there was a way to disable this, and only show the `print()` sections of the script in the log, that would be great. Just a request.

**Comment by danielyxie** [comment]
Added in v0.34.5
