### ISSUE TITLE
Syntax highlighting highlights functions when included in a variable name.

### ISSUE THREAD

**Issue by JBrown526** [danielyxie/bitburner#1885]
Using the basic script editor, when a variable name contains the name of a function that portion of the name is highlighted as if it were a function.

This should only be highlighted in the case where it is a function, and not a variable.

Running Chrome - Version 96.0.4664.110 (Official Build) (64-bit) on Windows 10.
Using the monokai theme (appears in solarized-dark/light as well)

![image](https://user-images.githubusercontent.com/45610774/146214093-99547f09-f3be-4d58-af1f-2cfeb24d039a.png)

**Comment by JBrown526** [comment]
Note: Only tested with the default script, not sure if the behaviour is the same using ns2.

**Comment by Phlarx** [comment]
I can confirm that this occurs with ns2 scripts as well. (I have a var called `hacktarget`, and the `hack`-portion is colored)

**Comment by aaronransley** [comment]
Noticing the same bug here.
