### ISSUE TITLE
Keyboard mapping not working

### ISSUE THREAD

**Issue by LuisAmorimDev** [danielyxie/bitburner#1887]
My keyboard when im write have caracters wrong, the keys are not like the leanguage of my keyboard and i cant change that in the game.

**Comment by phyzical** [comment]
workaround would be to ask users to use some sort of keyboard software to being english? 

actual solutions would be a kin to adding other multi language support i.e translations

**Comment by Master-Guy** [comment]
Weird thought, but could it be that the Keyboard layout in the Windows settings of @raskilo are set incorrectly?
Using US-international myself as that is the most commonly used layout in the Netherlands, so I cannot reproduce this.
