### ISSUE TITLE
Hacknet production highlighting when it's greater than the money currently in account

### ISSUE THREAD

**Issue by JBrown526** [danielyxie/bitburner#1890]
When looking at hacknet nodes, the production figure is highlighted blue if the player's money is less than the total production of a given node, similar to how the upgrade costs turn blue if they are unaffordable. This seems like unintended behaviour.

Expected behaviour would be for production figure to remain one colour without changing

Running Chrome - Version 96.0.4664.110 (Official Build) (64-bit) on Windows 10.

![image](https://user-images.githubusercontent.com/45610774/146222660-48e95fdd-450b-4de1-81d0-2f35aa993712.png)

**Comment by Penumbra69** [comment]
I was about to report the same thing.  Not critical, but did make me go "Hmm.."
