### ISSUE TITLE
prompt for user input

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1894]

**Comment by hkgnobody** [comment]
You mean adding the feature for scripts so it supports the functionality of "prompt for stdin"?

**Comment by phyzical** [comment]
closable if the above is correct i think, looks to be covered by prompt()

**Comment by Master-Guy** [comment]
prompt() only works for booleans, but they might want to use integers or text?
Personally I don't use either, because we can use arguments.

**Comment by jacktose** [comment]
Closed by #2880?
