### ISSUE TITLE
Add Snippets and Linting in "nano" for better and easier coding

### ISSUE THREAD

**Issue by ToasterUwU** [danielyxie/bitburner#1896]
First of all: Love the Game, perfect for people like me (Sometimes having the urge to program something, but having nothing to do or only super complicated things that are too much for just having fun)

I instantly noticed that the "nano" code editor in the game is VS Code. And since VS Code has this Extension system I thought it would be a very nice idea to make the snippets that are already shown better. Meaning instead of just showing stuff like "scan()" it could show stuff like (sorry in advance for my python syntax here, it's just the only thing that I know very nice.. I'm new to JS and it subversion) "scan(hostname:str)" and if you hold the mouse on the scan function it could show "scan(hostname:str) -> Array[str] \n Scans the machine specified with the hostname for connected machines and returns those hostnames as Array"

I don't know much about how you would make an Extension for VS Code, or if the embedded version of VS Code in the Game even supports extensions, but I would love to see this. It would the coding experience so much better because right now I'm switching between the docs and the game for everything, even just finding out what the return of a function is.

I also would gladly assist in this, so if you think this is important and nice and you need some help, I'm here. I'm an experienced programmer that does programming as a job. I'm just not very experienced with JS, but since Python and JS are almost on the same level (in the context of high and low languages), it's mainly syntax I need to learn.

**Comment by hydroflame** [comment]
Can't fix because the web version of vscode does not support extensions.

**Comment by ToasterUwU** [comment]
OK if an extension is not possible, would it at least be possible to change the recommendet functions to a better way?

Currently there are some none existing functions, and the ones that actually exist are not documented in the preview thing. No parameters, no doc string, nothing but the naked function name.

Can that be changed?

**Comment by hydroflame** [comment]
![Screen Shot 2021-12-23 at 5 59 01 PM](https://user-images.githubusercontent.com/79246165/147297963-e2b4c450-07c6-46c4-9f4a-65af1117a7ca.png)

If you use .js files you have documentation within the game.

**Comment by ToasterUwU** [comment]
Ohh, good to know. I used script files until now.

Thanks.
