### ISSUE TITLE
Pause / Unpause button for tail window.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1899]

**Comment by phyzical** [comment]
is the intention of this feature to be able to pause the actual script? or just to pause its logs?

**Comment by Master-Guy** [comment]
Both would be a good idea, although I'm not sure how hard it is to implement a "pause" for running scripts.
As for pausing the logs: It might be enough to expand the "log size" option beyond 500 lines. Perhaps in style of the game only by doing it per script?
