### ISSUE TITLE
locale for numbers

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1903]

**Comment by phyzical** [comment]
i assume this is about taking the users setting of locale/ adding a new number specific one and supporting https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by Master-Guy** [comment]
If this is about using the regional settings, then I'm against this.
It would create a lot of weird situations where scripts at one time should use dots and at other times commas in decimal fields.
