### ISSUE TITLE
Import failure

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#1924]
[bitburnerSave_1639603115_BN2x3.json.zip](https://github.com/danielyxie/bitburner/files/7722866/bitburnerSave_1639603115_BN2x3.json.zip)
run gang/equipment.js

**Comment by Saynt-Garmo** [comment]
Ahhhhhh I apologize, I tried this one, and looks like its not being compiled right the first time, personally I suspect the ram dodger methods behind it in generating the lists.

**Comment by phyzical** [comment]
hmm this may be fixed? i was able to import it fine and run the script.

unless the issue is that these should not be "failing"

```
[20:36:13] gang.purchaseEquipment: Failed to purchase 'AWM Sniper Rifle' for Gang member '3-Jane'
[20:36:13] false
```
