### ISSUE TITLE
mismatched background color

### ISSUE THREAD

**Issue by sendiriaann** [danielyxie/bitburner#1939]
was fiddling around with the theme editor and found this problem
![image_2021-12-16_094245](https://user-images.githubusercontent.com/94722430/146298338-fcee1862-377e-4ce2-aecb-4aacd2c208bf.png)
as you can see, i've set the backgroundprimary to #fdca55, but when you scroll down the color of the area "below" the screen is bugged and displays the wrong color, and the size of the area depends on the window size (if i  reduce the scale of the window, the bugged area would increase as shown below)
![image](https://user-images.githubusercontent.com/94722430/146298748-80a84db2-5ec5-4196-a061-0ad06d64490f.png)

it's a fairly minor problem, but as the terminal filled with info it became incredibly hard to see any text since i also changed the text color to dark brown. Anyways, for now i'll stick to the OG theme.

**Comment by loganmacdougall** [comment]
The css propties for .css-ifmi9 must be changed to fix this

The "height" needs to be changed from "100vh" to "100%"
The "min-height" needs to be set to "100vh"

![image](https://user-images.githubusercontent.com/50811887/146858485-b8328a04-5d16-485f-b10f-9663b9e943fb.png)
![image](https://user-images.githubusercontent.com/50811887/146858503-712c7305-81b9-4093-b9ce-6e1adddbb69d.png)
![image](https://user-images.githubusercontent.com/50811887/146858544-5bdb4577-9595-4113-ba72-cb6e50f2b37a.png)
