### ISSUE TITLE
Add support for relative imports

### ISSUE THREAD

**Issue by trambelus** [danielyxie/bitburner#1942]
If scripts within directories could import other scripts within the same directory, it might make syntax a bit cleaner. Currently, if you have scripts `dir/a.js` and `dir/b.js`, you can only use an absolute import like `import foo from '/dir/a.js'`, and not `import foo from './a.js'`.

**Comment by Hedrauta** [comment]
🤔 this one could be hard... because it's currently a "fictitious" filesystem... so, the file is actually called `/dir/file.js`, where the `/dir`-part is just added on the front.... 
if i remember right, Hydroflame is working on a real file-system.... but... idk when he had mentioned that 😆

**Comment by alexandreseris** [comment]
i've found a workaround if you use vscode and still get intellisense to work:

my project tree looks like this:
```
code/
    dir1/
        script1.js
        script2.js
    dir2/
        script3.js
        script4.js
    jsconfig.json
    index.d.ts => define ns module
configFilesTopLevel
```

jsconfig.json:
```json
{
	"compilerOptions": {
		"baseUrl": "./"
	}
}
```

you then have to write import this way:
```js
import { yourstuff } from "dir/script.js";
```
vscode understands it and so does bitburner :)


if you use the ns annotation:
```js
/** @param {import(".").NS } ns */
```

---------

Note : even though bitburner accept the following
```js
import { yourstuff } from "/dir/script.js";
import { yourstuff } from "./dir/script.js";
```
vscode doesnt, so dont use it!
