### ISSUE TITLE
ns.scp not working properly in recursive functions.

### ISSUE THREAD

**Issue by RamonNeres** [danielyxie/bitburner#1961]
I made an algorithm to copy a script to all servers I have root access.
When copying the file, it says I'm not awaiting the alert function, which I'm only using to notify the end of the script (and is awaited).
It looks like the first time scp is called, it works fine, but the next call just breaks.

```
const hackedServers = [];
const selfHackScript = 'selfHack.js';

/** @param {NS} ns **/
const autoHack = async (ns, server) => {
	hackedServers.push(server);
	const servers = ns.scan(server);
	servers.forEach(async s => {
		if (ns.hasRootAccess(s)) {
			if(s != 'home') {
				const successfulCopy = await ns.scp(selfHackScript, 'home', s);
				if(successfulCopy) {
					ns.exec(selfHackScript, s);
				}
			}
		}
		if (!hackedServers.includes(s)) await autoHack(ns, s);
	});
};

/** @param {NS} ns **/
export async function main(ns) {
	await autoHack(ns, 'home');
	await ns.alert('Script started on all possible servers');
}
```
Here is my save file, you can just run autoHack.js to replicate the error. There is also a simple script called manual.js that replicate the problem with a simpler script, but the error only shows on the browser's console.
[bitburnerSave_1639694461_BN1x0.zip](https://github.com/danielyxie/bitburner/files/7730817/bitburnerSave_1639694461_BN1x0.zip)

I'm using Opera GX 81.0.4196.61, but also tried Chrome and Edge (not sure about the versions)

**Comment by just1689** [comment]
Also having this issue

**Comment by ErzengelLichtes** [comment]
You're `await`ing inside an `array.forEach`. That doesn't work the way you think it does in Javascript. Turn it into a regular `for(s of servers)` and the issue will go away.
