### ISSUE TITLE
app not closing on steam (windows 10)

### ISSUE THREAD

**Issue by bluebn** [danielyxie/bitburner#1963]
idk why but that shit dont close. I obliterated my mouse by pressing the stop button and when i realised that wasnt going to work i checked my running apps in my taskbar and in task manager but the only way i can stop the app is when i shutdown my computer.

**Comment by hydroflame** [comment]
Pushing patch for this in 5 m

**Comment by MartinFournier** [comment]
Found this alternative possible fix if it still happens, maybe using .once ensure there's no pending event handler not garbage collected?

```js
// Workaround to close all processes / sub-processes after closing the app
electron.app.once('window-all-closed', electron.app.quit);
electron.app.once('before-quit', () => {
    window.removeAllListeners('close');
});
```
https://stackoverflow.com/a/43520274

**Comment by Kegelkerni** [comment]
Same problem here. After closing the game by closing the game window via X-Button Steam doesn't recognize that the game has been closed. Pressing "Anhalten" (german for stop) in the game library inside the Steam App has no effect.

But I don't have to restart windows. Restarting the Steam App solves the problem.

I tried to identify the process that can't be stopped by Task Manager but all I saw is that the four Bitburner processes get stopped as expected.

**Comment by kafuuchino-desu** [comment]
same issue here, running on latest steam release, I have to restart steam to solve this issue

**Comment by phyzical** [comment]
idk.. i have had this happen with all kinda of apps on windows for years kodi for example. wouldn't be surprised if just #windowsthings

**Comment by gedq** [comment]
Still happening. Can close from task manager.
