### ISSUE TITLE
Request: Method to reserve static memory

### ISSUE THREAD

**Issue by ErzengelLichtes** [danielyxie/bitburner#1964]
When using array access on `ns`, the static memory isn't updated. This is problematic when using metaprogramming techniques, for example creating a list of all port opening methods and their associated executables, then testing to see if the executable exists before calling the method (`allTools.filter(i=>ns.fileExists(i.file)).forEach(i=>ns[i.func](host))`). This causes an error about "runtime memory is higher than static memory". 

There should be a method that reserves static memory but doesn't increase runtime memory. For example, `ns.reserve(0.5)` to add 0.5GB to the static RAM but is a null operation at runtime. This way the array access, which adds to the runtime RAM, has some room to execute.

**Comment by hydroflame** [comment]
You can add in your program

    ns.brutessh;ns.ftpcrack;ns.relaysmtp

and it'll count it.
