### ISSUE TITLE
tix functions not defined on steam

### ISSUE THREAD

**Issue by lapryx** [danielyxie/bitburner#1969]
got error:
getPosition is not defined
stack:
ReferenceError: getPosition is not defined
at Module.main (test.js:2:5)
at executeJSScript (file:///A:/Steam/steamapps/common/Bitburner/resources/app/main.bundle.js:1:491432)

when running the following script:
export async function main(TIX) {
TIX.tprint(getPosition("ECP"))
}

The TIX api has been bought

**Comment by lapryx** [comment]
seems i posted the wrong error as i modified the script for some tests anyhow here is the correct error with the corresponding script:
ns.getPosition is not a function
stack:
TypeError: ns.getPosition is not a function
at Module.main (test.js:2:14)
at executeJSScript (file:///A:/Steam/steamapps/common/Bitburner/resources/app/main.bundle.js:1:491432)


export async function main(ns) {
ns.tprint(ns.getPosition("ECP"))
}

**Comment by Phlarx** [comment]
I think the function you are looking for is `ns.stock.getPosition`

**Comment by lapryx** [comment]
aah yes thats the problem, thanks for the help.
