### ISSUE TITLE
Game is stuck

### ISSUE THREAD

**Issue by nsoloviev** [danielyxie/bitburner#1970]
Game is just stucking on this screen:
https://prnt.sc/23e6x9w
Can't do anything except click the buttons at the top
Running game in steam

**Comment by hydroflame** [comment]
Can you click reload > reload & kill all scripts?

**Comment by nsoloviev** [comment]
It doesnt work, and in debug i cant use even console. Should run parameter with -noscripts or like this

**Comment by Degot** [comment]
I have similar issue.. game freezes (any screen) after 20 secs -2 mins... Task Manager shows CPU usage. Game can be killed via taskmgr only.

**Comment by hydroflame** [comment]
It doesn't work as in you can't click it or when you click it it does nothing?

**Comment by Degot** [comment]
> It doesn't work as in you can't click it or when you click it it does nothing?

For me, the freeze was caused by "while(true)". during this freeze i couldn't click anything in UI, except menu (ie reload no scripts). + I noticed that during this freeze , mouse scroll was working and UI was 'scrolling' process list,
