### ISSUE TITLE
RAM calculation incorrectly includes user-defined names

### ISSUE THREAD

**Issue by Phlarx** [danielyxie/bitburner#1973]
Variable names are included when determining the RAM cost of a script.

Example:
This script is calculated to require 6.60GB of RAM:
```typescript
/** @param {NS} ns **/
export async function main(ns) {
    var buy = 12;
    var sell = 34;
    return sell - buy;
}
```
But this almost identical script is calculated to require only 1.60GB of RAM:
```typescript
/** @param {NS} ns **/
export async function main(ns) {
    var vbuy = 12;
    var vsell = 34;
    return vsell - vbuy;
}
```

The *names* `buy` and `sell` are apparently costing 2.50GB each.

---
The same thing occurs with function names:
This script is requires 4.10GB of RAM:
```typescript
function buy() {
	ns.print('bought');
}

/** @param {NS} ns **/
export async function main(ns) {
	buy(ns);
}
```
While this script is requires only 1.60GB of RAM:
```typescript
function buyIt() {
	ns.print('bought');
}

/** @param {NS} ns **/
export async function main(ns) {
	buyIt(ns);
}
```

---
Discovered using ns2, on the current Steam version as of the time of this report (v1.1.0 78939b1c).

**Comment by hydroflame** [comment]
Yeah there's really no way to fix this tbh without a tremendous amount of work, #wontfix
