### ISSUE TITLE
docs: Singularity functions missing

### ISSUE THREAD

**Issue by sschmidTU** [danielyxie/bitburner#1975]
From the perspective of a new player, I can't find any info on singularity functions in either the basic or full documentation.
For example, `commitCrime()`, `travelToCity()` or `universityCourse()` aren't listed in the full documentation:
https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.md

Also, if I were a new player and found Source File 4 in the source file list promising "Singularity functions", since there's basically no info on them in the current documentation, I wouldn't know what that means or allows me to do.
Maybe add a link to the (new) singularity functions docs (similar to how BN5 links to Intelligence)?
https://bitburner.readthedocs.io/en/latest/advancedgameplay/sourcefiles.html
maybe link this page:
https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.md

**Comment by pacmanninja998** [comment]
If I'm interpreting Singularity right, you'll get them with specific hidden achievements throughout later gameplay.
https://bitburner.readthedocs.io/en/latest/advancedgameplay/sourcefiles.html
