### ISSUE TITLE
Freezing the game breaks steam

### ISSUE THREAD

**Issue by Phamhoanggiabao** [danielyxie/bitburner#1976]
OS: Windows 10
Version: Steam
Creating an NS2 script that infinitely loops causes the game to completely freeze, not even reloading and kill all scripts work. And when closing the game, steam still thinks it's still open and can't stop it. Having to close it by using task manager.

Script:
```
/** @param {NS} ns **/
export async function main(ns) {
   while(true) {
   
   }
}
 ```

**Comment by Hedrauta** [comment]
so.... you're doing nothing, for several billion times per sec, and get surprised, that it will freeze the game?
try add an `ns.sleep(1)` into the while.loop.... it will run fine then ;)

**Comment by Hedrauta** [comment]
oh... and it will be `await ns.sleep(1)` ofc..... forgot that one 😆

**Comment by Hedrauta** [comment]
to clarify:

```js
/** @param {NS} ns **/
export async function main(ns) {
   while(true) {
   await ns.sleep(1)
   }
}
```
would run the while-loop for ~1000 times per sec.... while without the sleep, your game ( or your browser ) would try to run it as fast as possible.... which may does spam the game/browsers engine with alot work...

i did some testing.... if you run this code with a 1 sec sleep (1000)  and do run it with some "fluffy" arguments, you can run it about 5k times before starts "lagging" and at about 15k-20k times before it's slowing down really hard

**Comment by Phamhoanggiabao** [comment]
> so.... you're doing nothing, for several billion times per sec, and get surprised, that it will freeze the game? try add an `ns.sleep(1)` into the while.loop.... it will run fine then ;)

To Clarify: what I'm talking about is that the reload and kill all scripts function on steam doesn't work and when closing out of the game, steam still thinks that it's still running and can't stop it, having to use task manager to close it
(Also if you are wondering why I am freezing the game. Well that's because it's for an achievement)

**Comment by Phamhoanggiabao** [comment]
Fixed thanks to new update
