### ISSUE TITLE
scp the file shouldn't have worked if the host cant be found 

### ISSUE THREAD

**Issue by Ramoranion** [danielyxie/bitburner#1988]
Hello, first of all: I just started your game and its fun so far.
Now to the bug report...

I connected to n00dles and copied a file to nectar-net. After that I tried to connect to nectar-net from n00dles. But it didn't works, because the host is not found. 
Accordingly to that, I shouldn't be able to connect the file directly from n00dles to nectar-net or am I mistaken?

I will leave you a screenshot as attachement. Please ignore the filetransfer to home. It does not has anything to do with the bug I think.
![Bild_2021-12-18_011501](https://user-images.githubusercontent.com/38407088/146621653-c8e93df4-2a9d-4794-b649-91739521917d.png)

I wish you all the best a nice christmas!

**Comment by Ramoranion** [comment]
And I would consider this low prority, so no need to rush

**Comment by hexnaught** [comment]
I guess in some ways it is a bit odd that we can copy files cross-network without 'direct access'...

While fairly new to the game (started playing yesterday) I imagine this may break peoples 'home command and control' scripts versus them having to make a worm-style script to progressively traverse the network host-to-host, 'infecting' and copying files as they went.
So I envision implementing this would be a fairly drastic change to peoples gameplay but moving towards a bit more (in some ways) realistic approach. I personally would welcome it, if that is the direction the maintainers/community would like to go in.

**Comment by hydroflame** [comment]
oh, i see, wont fix because of how the game works but will change msg
