### ISSUE TITLE
Servers with no RAM

### ISSUE THREAD

**Issue by Barmp** [danielyxie/bitburner#1990]
I'm not sure if the server names are the same for all players, but two of the servers I've just gotten access to have no RAM. Seems odd, I wasn't sure if this was a misconfiguration or intentional stumbling block for players to overcome, I didn't find anything specifically mentioning it in the documentation.

Below is the output of a scan-analyze command with an example of servers showing 0.00 for the RAM as an example. 

-> n00dles
--Root Access: YES, Required hacking skill: 1
--Number of open ports required to NUKE: 0
--RAM: 4.00GB

----> zer0
------Root Access: YES, Required hacking skill: 75
------Number of open ports required to NUKE: 1
------RAM: 32.00GB

--------> phantasy
----------Root Access: YES, Required hacking skill: 100
----------Number of open ports required to NUKE: 2
----------RAM: 32.00GB

**------------> comptek
--------------Root Access: NO, Required hacking skill: 384
--------------Number of open ports required to NUKE: 3
--------------RAM: 0.00GB**

----------------> zb-institute
------------------Root Access: NO, Required hacking skill: 737
------------------Number of open ports required to NUKE: 5
------------------RAM: 32.00GB

-> foodnstuff
--Root Access: YES, Required hacking skill: 1
--Number of open ports required to NUKE: 0
--RAM: 16.00GB

----> nectar-net
------Root Access: YES, Required hacking skill: 20
------Number of open ports required to NUKE: 0
------RAM: 16.00GB

--------> silver-helix
----------Root Access: YES, Required hacking skill: 150
----------Number of open ports required to NUKE: 2
----------RAM: 64.00GB

**------------> crush-fitness
--------------Root Access: YES, Required hacking skill: 251
--------------Number of open ports required to NUKE: 2
--------------RAM: 0.00GB**

------------> avmnite-02h
--------------Root Access: YES, Required hacking skill: 209
--------------Number of open ports required to NUKE: 2
--------------RAM: 32.00GB

**Comment by hydroflame** [comment]
normal
