### ISSUE TITLE
tryWritePort doesn't check for basic types

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#2011]

**Comment by HtheChemist** [comment]
tryWritePort signature definition is: 
`tryWritePort(port: number, data: string[] | number): Promise<boolean>;`

However writePort simply push in the array. It should not accept an array in data. Should probably be:
`tryWritePort(port: number, data: string | number): Promise<boolean>;`

**Comment by phyzical** [comment]
i assume we want to just do the same check as writePort
