### ISSUE TITLE
corp "expand to new industry" button isn't disabled when low on money.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#2019]

**Comment by deathly809** [comment]
Where is this button defined?  I could only find it in the giant minified engine.bundle.js file.

**Comment by phyzical** [comment]
![image](https://user-images.githubusercontent.com/5182053/152807614-3d3e75de-4b39-4571-adc0-6a3e14611fbc.png)

![image](https://user-images.githubusercontent.com/5182053/152807661-4cf16c98-7f7d-4e3b-bf54-926b02945aa0.png)

this this still an issue or by disabled is there another style that should be getting applied?
