### ISSUE TITLE
bitnode-2: rounding issues

### ISSUE THREAD

**Issue by kitoma** [danielyxie/bitburner#202]
I've been running my gang in bitnode-2 for a while, and now I have this on my territory screen:

```
Slum Snakes
(Power: 1,013.967315): 100.03%

Tetrads
(Power: 58.351783): -0.00%

The Syndicate
(Power: 57.690790): -0.00%

The Dark Army
(Power: 58.403190): -0.00%

Speakers for the Dead
(Power: 58.464013): -0.00%

NiteSec
(Power: 57.538042): -0.00%

The Black Hand
(Power: 58.145106): -0.00%
```

Seems like some computation / rounding issues there.

**Comment by danielyxie** [comment]
This is due to floating point precision issues. It's pretty minor IMO. In v0.36.1 I updated it to cap out the displays at 0 and 100 (i.e. it should now display only numbers between 0 and 100 now, even if the actual underlying value is slightly off)
