### ISSUE TITLE
Various documentation updates

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#2027]
getHackTime(), getWeakenTime(), getGrowTime() 
Influenced by: currentSecurityLevel of host, Hacking Level of player, ...?

hackAnalyze(), growthAnalyze()
Influenced by: currentSecurityLevel of host, ...?

grow(), hack(), weaken()
The percentage is calculated when the method finishes executing. security level is checked once at the start (to determine how long the operation takes) and once at the end (to determine its effect) (from MAGEKING)

**Comment by hexnaught** [comment]
> grow(), hack(), weaken()
> The percentage is calculated when the method finishes executing. security level is checked once at the start (to determine how > long the operation takes) and once at the end (to determine its effect) (from MAGEKING)

Is it worth also clarifying in the docs/method dockblocks that by default, these commands use all available script threads as per `-t <number>`. (_I quickly check `ns.hack()` in game and didn't see this included_).

As per discord:

> hydroflame  — 16/12/2021:
>   No one needs to set the optional argument of hack btw
>   Specially not this early in the game
>   hack(hostname) will use all possible threads the script was started with.

**Comment by phyzical** [comment]
anything else still missing?
