### ISSUE TITLE
Going offline with clock shenanigans can cause huge debt.

### ISSUE THREAD

**Issue by jankatancic** [danielyxie/bitburner#2039]
So the game froze, or well the "create program" so i killed all scripts and restarted the game and now im in -1m money. 
![slika](https://user-images.githubusercontent.com/19192014/146677822-60ecb562-5e8f-4d6a-9be8-2add69b7ee15.png)

**Comment by phyzical** [comment]
How should we handle this? try to detect the shenanigans and tell them off? 😆

**Comment by alainbryden** [comment]
One way I can see this being not-shenanigans is if they were studying or working out at a gym (which can now be done in the background without Focusing - opening up this sort of issue for the first time)

Normal offline calculations could have applied all those studies and put them in debt.

Either way - this is not a bug, going into debt while studying is an intended game-mechanic. There are plenty of ways to get out of debt.

**Comment by phyzical** [comment]
unless this issue applied hydro agree -ve should go away (for courses and gym) https://github.com/danielyxie/bitburner/issues/2205
