### ISSUE TITLE
Shift+Tab doesn't open achievements overview in Steam

### ISSUE THREAD

**Issue by Kegelkerni** [danielyxie/bitburner#2043]
In every Steam game that offers achievements (at least the ones that I know) the keyboard shortcut Shift+Tab opens the achievements overview. I would highly appreciate if Bitburner could do the same.

**Comment by hydroflame** [comment]
known but idk how ot fix

**Comment by Kegelkerni** [comment]
It's absolutely ok that you don't know everything but why did you close this issue then? There are up to 100 contributors who could potentially solve this problem for you. All you (or danielyxie?) have to say is "Yes, sooner or later I would like this feature to be part of Bitburner" or "No, for the following reason I don't want this to be implemented". Now that I (and perhaps many others) know that we could start working on that missing feature you demotivated me by closing this issue with a strange reason.

**Comment by hydroflame** [comment]
Fair

**Comment by phyzical** [comment]
(maybe related)? https://www.reddit.com/r/gamedev/comments/mc9s5x/has_anyone_successfully_integrate_steam_overlay/

i havnt looked into how steam overlays work very deep though.. it also looks like we may have the electron app gulping shift+ tab (due to tab being an accessibility feature of browsers)

**Comment by Master-Guy** [comment]
> Fair

So which one is it? :P
`Yes, sooner or later I would like this feature to be part of Bitburner`, or `No, I don't want this to be implemented`

**Comment by phyzical** [comment]
its not a matter of if its a matter of how to fix the issue with it
