### ISSUE TITLE
1.2.0 unable to rename script

### ISSUE THREAD

**Issue by RagingRhino224** [danielyxie/bitburner#2051]
after the 1.2.0 update I have been unable to rename the script in the script editor. I am new to the game however I have found it impossible to change the name of a script, and seeing as the value that recognizes the script is based off of the name I am unable to make more than a single usable script. I used to be able to change it at the top left of the script editor however after the update it just displays "newfile.script", which doesn't allow me to change the name. might not be a bug, might just be stupid but so far that's the only way I know how to create a new script.

**Comment by Rez855** [comment]
I do have plans to add a create script button for the editor in the future but for now the only way to create one is to go to your terminal and type "nano [Your File Name]" and it will create it for you.

**Comment by User2564** [comment]
I haven't heard of any editors that allow for most/full operations after the open file in question has been renamed/moved without first prompting the user to reload or close the file as it doesn't exist.

Files can be renamed via the mv command, which has the following syntax (which as a potentially boring side note is the general structure for the vast majority of Linux commands.); `command [source] [target]` e.g. `mv start.ns start-1.0.ns` will rename the file `start.ns` to `start-1.0.ns`.

>type "nano [Your File Name]" and it will create it for you.

Unfortunately that does not seem to be present any more:
```
[home ~/]> nano file

Invalid file. Only scripts (.script, .ns, .js), or text files (.txt) can be edited with nano

[home ~/]> 
```

**Comment by phyzical** [comment]
imho mv is fine. but i am a dev soo
