### ISSUE TITLE
Contract is not visible

### ISSUE THREAD

**Issue by nsoloviev** [danielyxie/bitburner#2066]
I looked at the contract, then pressed focus and then returned, the contract was closed, but if I write 
"run contract-403320-Chongqing.cct" 
Then I get: There's already a Coding Contract in Progress

**Comment by hydroflame** [comment]
Need repro steps

**Comment by LegitPanda** [comment]
@hydroflame I stumbled upon this bug too
More detailed reproduction:
1. Start working at a job/faction
2. Work on something else simultaneously 
3. Start a coding contract (CC)
4. Focus back to the job you were on before
5. Go back to the terminal, try to start the CC again. Note that the CC window is closed but the window state still thinks we're in the CC.

It's a pretty minor bug, a save and reload will reset the window state back to normal. 
Great work btw, I hope this game encourages a lot more people to learn to code.
