### ISSUE TITLE
Startup Notification to notify Dev.. ?

### ISSUE THREAD

**Issue by CitizenPoe** [danielyxie/bitburner#2072]
Screenshot below: 

![image](https://user-images.githubusercontent.com/83760252/146818866-78ccc66a-5a9c-4597-9f27-955ccda48122.png)

Attached save file titled: RECOVERY.JSON as per instructions - Had to rename it to .pdf because git doesnt allow json files.
[RECOVERY.json.pdf](https://github.com/danielyxie/bitburner/files/7747408/RECOVERY.json.pdf)

**Comment by hydroflame** [comment]
Ok, it's something about scripts not saving a field but idk how to repro. Pretty sure you can play anywau
