### ISSUE TITLE
When hovering over a job with no higher positions/stat requirements, empty box shows up

### ISSUE THREAD

**Issue by hexnaught** [danielyxie/bitburner#2074]
Has no higher positions/stat requirements:
![image](https://user-images.githubusercontent.com/1098786/146820193-7934108c-4e62-4ff8-9add-c625dfadb148.png)

Has position with stat requirements:
![image](https://user-images.githubusercontent.com/1098786/146820220-a1742ea7-5ace-4557-8b47-afb07d1c0774.png)

**Comment by hydroflame** [comment]
Known and part of a bigger "job refactor" issue.
