### ISSUE TITLE
Killed script still running

### ISSUE THREAD

**Issue by AlphaOneProject** [danielyxie/bitburner#2080]
Hi!
Game version: PC, Windows 10 through Steam.
I launched [this script](https://pastebin.com/F9J0G0Bw), it worked fine but when I needed to kill it I typed `ps` then `kill ${proc_pid}` of the matching process. I tried later on with the same results killing it from the `Active Scripts` side panel.
It disapeared from `ps` as expected and the `Active Scripts` side panel.
What was unexpected:
- The script was still logging in the [debug console](https://pasteboard.co/YCUJNDAYMnWy.png).
- The script was still performing actions like checking, buying and selling stocks.

What I expected:
- The killed process should have stopped.

I went around this issue by restarting the game after "killing" the process. This was not a one-time thing however and I'm still having this issue each time I use this specific script. I'm not sure if this is a issue in my script but I'm not launching any external scripts (afaik).

**Comment by hydroflame** [comment]
Upload your save file.

**Comment by AlphaOneProject** [comment]
Hi, [here it is](https://gofile.io/d/omgoZt)!

**Comment by phyzical** [comment]
is exact issue is the sleep function, rather the setTimeout inside the promise.

if i switch out for `ns.sleep` `kill` it works.

imo closable

**Comment by AlphaOneProject** [comment]
It works! I was not aware ns.sleep was a thing.
Thank you for clarifying!

**Comment by phyzical** [comment]
🎉 @AlphaOneProject it may have not been when you raised the ticket :)
