### ISSUE TITLE
Can create program in one browser tab and do other things in another browser tab

### ISSUE THREAD

**Issue by lodenrogue** [danielyxie/bitburner#2081]
I'm playing the browser version of the game: https://danielyxie.github.io/bitburner/

I can have one tab opened and creating a program like DeepscanV1.exe and at the same time I have another tab open and I can be editing scripts or creating another program like FTPCrack.exe.

I don't think this is the intended behavior.

**Comment by hydroflame** [comment]
Sure but you can only save one of them. It's normal.
