### ISSUE TITLE
`ns.getPlayer()` documentation is missing RAM usage

### ISSUE THREAD

**Issue by hexnaught** [danielyxie/bitburner#2084]
Reported via `H3draut3r` on discord.

>ns.getPlayer() will not show any Ram-Usage on Script-Editors notification ( as so the Docs dont tell any ram-usage 
> https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.getplayer.md

![image](https://user-images.githubusercontent.com/1098786/146853971-ba4039e1-1de6-433e-9919-b0d133b13e7a.png)

**Comment by Hedrauta** [comment]
< --
