### ISSUE TITLE
Script Editor goes off screen

### ISSUE THREAD

**Issue by ghost** [danielyxie/bitburner#2088]
I am on the steam version on windows.
If your tabs opened goes off the screen, the entire Script Editor becomes wider than the screen.
This is extremely annoying as you can't fully view the code you are editing, or view the right sidebar.

I've provided a video:
https://user-images.githubusercontent.com/8596803/147029433-0705613a-43ef-49b1-9e3b-ed0fa57f8404.mp4

**Comment by Kebap** [comment]
video shows this happening with very long file names. 
same is happening for me with 5-10 reasonably long file names, depending on your resolution size.
workaround shown in video seems to use a mouse (?) with vertical scrolling.
other workaround is to grab and drag a tab title to the far edge of the screen, thereby scrolling the whole editor.

**Comment by phyzical** [comment]
We should be enforcing a max tab size and then provide a hover display for full file name.
