### ISSUE TITLE
Weird caching issue on purchased servers

### ISSUE THREAD

**Issue by R3TROATTACK** [danielyxie/bitburner#2089]
There seems to be a caching issue with purchased servers, I'm not too sure on how to replicate this and I'm not sure if it applies to standard servers or not but the issue seems to be fixed now after manually deleted the electron app's cache.

Here is a list of things we tried doing before I deleted the cache:
https://discord.com/channels/415207508303544321/415247422638522395/922732438789181460

**Comment by hydroflame** [comment]
Yeah this is a complicated issue and it's logged in another issue on gituhb.
