### ISSUE TITLE
Hacknet Nodes are completely pointless in endgame

### ISSUE THREAD

**Issue by Aeolun** [danielyxie/bitburner#2093]
You can spend literally trillions on them, but have them end up only producing 400k/second.

![image](https://user-images.githubusercontent.com/1116482/146941964-a84da83b-be82-4fe7-962f-cb8e94b63f4a.png)

**Comment by hydroflame** [comment]
Yup

**Comment by Aeolun** [comment]
I’ll take that as a ‘wont-fix’ 😛
