### ISSUE TITLE
Feature request getRunningScript()

### ISSUE THREAD

**Issue by WiseMack** [danielyxie/bitburner#2096]
According to bitburner.ns.getrunningscript.md
getRunningScript() has three arguments
filename string | number --> which refers to the name of the script (finishes in .script)
hostname string --> server running the script
args (string | number)[] --> arguments of the script

all three are _required_, but what do I do when I don't know the args of the script I need?

What I want is a change to the code, make it so 
`getRunningScript("script","server");`
returns an array with every instance of this "script" running on <this> server
this way I can go through the results to find the one I need
```
var scripts=[];
scripts=getRunningScript("script","server");
for (var i=0;i<scripts.length;i++){
    tprint(scripts[i]);
}
```
You could even leave the old method behind, making args optional
```
getRunningScript("script","server"){returns array of running scripts}
getRunningScript("script","server","arg"){returns specific script}
```

**Comment by theit8514** [comment]
You could use the [ns.ps](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.ps.md) method to get a list of all the scripts with arguments then call `getRunningScript` with those arguments.

**Comment by hydroflame** [comment]
Yeah no I can't change that function when it's already possible using other means.
