### ISSUE TITLE
`require` and `import` are not fully accounted for in NS2 scripts.

### ISSUE THREAD

**Issue by NeoVance** [danielyxie/bitburner#2097]
Not sure exactly what is happening with `require`, but it seems to be behaving like it might be webpack's require method. Which reminds me... I haven't gone hunting for access to `__WEBPACK_REQUIRE__` resources yet. Might give me access to some sweet internal game functions.

```javascript
async function main(ns) {
    // results in module not found error message.
    const t = require('{script file name}');
}
```

On the other hand, `import` is pretty damn useful, since it allows the user to import JS modules from another source like the local file system, or a remote address. I don't know if this is on purpose or not, but this is something I wouldn't mind keeping. I would much rather write my JS libraries in vscode then the built-in script editor honestly. And I would for sure like to take advantage of some existing js libraries without having to re-write them in game from scratch.

```javascript
async function main(ns) {
    let infect;
    try {
        // failed to resolve module '/lib/infect.js'
        infect = await import("/lib/infect.js");
    } catch (e) {
        // loads a remote module
        infect = await import("https://ga.jspm.io/npm:infect@0.4.6/infect.js" /* also works with file:// */);
    }
    // use imported library
}
```

**Comment by NeoVance** [comment]
On a side note. I was able to read through the source and do something similar to create my own dynamic import function that works for in game scripts.

```javascript
/** @param {NS} ns **/
export function inject(ns, func) {
	return (...args) => func(ns, ...args);
}

/** @param {NS} ns **/
export async function load(ns, module) {
	if (!moduleCache[module]) {
		const text = await ns.read(module);
		const content = new Blob([text], { type: 'application/javascript' });
		moduleCache[module] = URL.createObjectURL(content);
	}

	ns.tprintf("Import %s", moduleCache[module]);
	return import(moduleCache[module])
		.then(m => Object.assign({ __esmodule: true, __url: moduleCache[module] }, m));
}

/** @param {NS} ns **/
export default async function initialize(ns) {
	const require = inject(ns, load);
    ns.atExit(() => {
		Object.keys(moduleCache)
			.forEach((k) => {
				URL.revokeObjectURL(moduleCache[k]); // Delete blobs when the script exits
				delete moduleCache[k]; // Prevent webkit memory leaking like crazy.
			});
	});
	return require;
}
```

**Comment by hydroflame** [comment]
Wont' support because that's complicated af

`import x from Y` at the top of the screen IS supported.

**Comment by Penumbra69** [comment]
Dang .. I was hoping to use the dynamicity of the js `import()` system to provide cover for only importing functions for which the character has the source file for... Without having the dynamic `import()` facility, this means I can't easily make a dynamic script which scales to the character's skills and/or current status.

Maybe I can use the above hackaround, but as you say - that's complicated a.f.

**Comment by Penumbra69** [comment]
Fair enough -- I'm working to implement your solution right now.. Thanks!

**Comment by Penumbra69** [comment]
No worries - @NeoVance -- thanks!  
I see what's up now.

I was trying to import a file/module which only would work for a source-code-4 user, so I pushed all of the Singularity functions into there -- but some use RAM of course, and by importing the module like this, the scanner will bark every time.  I can only do this with non-NS functions, or ones that require 0 RAM. (Unless you know a hackaround?)

This would work beautifully for any other imports though!

P

**Comment by NeoVance** [comment]
Yeah, you have to wrap `ns` functions, or export a proxy of some kind because of the way the ram counter works. Thats why my import is structured the way it is.

You can `.then` the dynamic `import` that loads the module, to either run an initializer function in the module:

```
return import(moduleCache[module])
                .then(m => m.initializer(ns)) // initialize the module with ns.
		.then(m => Object.assign({ __esmodule: true, __url: moduleCache[module] }, m));
```

 or replace the module members with wrapped versions of the functions.

```
// module
export function purchaseTor(ns) { // dependency as argument
    return ns.purchaseTor() // use the actual ns reference
}

// replace
return import(moduleCache[module])
                .then(m => Object.keys(m).map(k => (...args) => m[k](ns, ...args))) // replace with injected ns.
		.then(m => Object.assign({ __esmodule: true, __url: moduleCache[module] }, m));
```
