### ISSUE TITLE
Undeletable file

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#2114]
1. create any .txt file via ns.write (if you don't already have a .txt hanging around)
/** @param {NS} ns **/
export async function main(ns) {
  ns.write('my-test-file.txt', 'any value', 'w')
}

2. in the terminal, run ls and note that the .txt file is listed with the other text files and is colored green in the default color scheme. 
3. nano my-test-file.txt
4. do not save (or do save, i don't think it matters, just opening the file with nano)
5. return to the terminal, and run ls. Now the text file is colored yellow, and is organized with the script files. 
6. Now ns.rm and terminal rm do not work. The save file lists the txt file with scripts.

**Comment by phyzical** [comment]
i think this is resolved?

![image](https://user-images.githubusercontent.com/5182053/153173320-6320574e-9fe4-4562-b676-8bab25ccc87d.png)
