### ISSUE TITLE
wget with / causes bad files

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#2115]

**Comment by phyzical** [comment]
to confirm i think this is the bug? 
```
/** @param {NS} ns **/
export async function main(ns) {
	await ns.wget("https://gist.githubusercontent.com/ramzs/35fa68c0e4c83e4b66d2137d8364dbd6/raw/281998608078700ed213bad1cc019b31a5b2cccd/PaymentNotificator.gs", "/file.txt", "home")
}
```

![image](https://user-images.githubusercontent.com/5182053/153177893-a44e6261-97d3-49f3-9340-c5fec266ac54.png)


it works if i use `file.txt` 
if i use `/file.txt` it saves it as a directory called / that you cannot cd into and cannot ls

**Comment by phyzical** [comment]
on a side note should we even allow this anymore given the vscode integration?

**Comment by phyzical** [comment]
related https://github.com/danielyxie/bitburner/issues/2991
