### ISSUE TITLE
dark web displays weird with timestamps

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#2130]

**Comment by Hedrauta** [comment]
so,  you mean the `buy -l` command?
Thinking about it, adding a few .padEnd() to fix the positioning may be smarter, instead of move it down a line 🤔

**Comment by Hedrauta** [comment]
oh... i see
🤔

**Comment by Hedrauta** [comment]
So, it needs somehow the timestamp in front of the program, if a timestampfformat is set...
Maybe adding the timestamps to the Terminal.printRaw ? .... _ugh_  that's too hard stuff for me... 
but somehow it should be possible to printraw with the timestamp in front of it 🤔

**Comment by phyzical** [comment]
i think this is fixed?

![image](https://user-images.githubusercontent.com/5182053/153211934-4568b9f1-5576-4469-96b2-978594ef64f1.png)

**Comment by Hedrauta** [comment]
Looks fine to me? 🤔
I mean, if you're using a unix timestamp (`T`)  it does looks this way too...  They are just all send at the same time 😉
