### ISSUE TITLE
If a server is backdoored you should be able to connect directly to it.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#2138]

**Comment by aaronransley** [comment]
Would love to see this; my first intuition was that it would work this way.

**Comment by Aeolun** [comment]
I would love to connect directly to any server I can directly connect to through AutoLink.exe. Having to run the scan-analyze command first is a bit of a chore.

**Comment by CodyneKen** [comment]
I think it's related, getServerMaxRam and such don't work for servers more than 3 deep, even after getting the deepscans. I think the depth of access was hardcoded.
Not directly related but same spirit.
