### ISSUE TITLE
"Accessing" hacknetnodes array in commentary counts for ram usage.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#214]
the script 

```
// hacknetnodes
print("hello world");
```
costs 5.40GB of ram to execute

expected 1.4GB (base cost).

Not really a big deal but interesting bug.

(FYI THIS GAME IS FUCKING AWESOME, THANK YOU)

**Comment by jaguilar** [comment]
It shouldn't cost this much in dev. The new ram calculation can tell that what's in a comment is not an identifier.

**Comment by danielyxie** [comment]
Should be fixed in the latest update v0.36.1 thanks to @jaguilar 

Let me know otherwise
