### ISSUE TITLE
Deleting then recreating a text file of the same name restores contents

### ISSUE THREAD

**Issue by mikomyazaki** [danielyxie/bitburner#2146]
Steps to reproduce:

1. `nano test.txt` within terminal.
2. Write something in the file, then save and close nano.
3. `rm test.txt` within terminal.
4. `nano test.txt` within terminal.
5. Contents of file is whatever you typed into the file you deleted.

**Comment by hydroflame** [comment]
Yeah thats' because of the localStorage stuff, we have to get rid of that.
