### ISSUE TITLE
nuking the iron-gym server leads to hangs

### ISSUE THREAD

**Issue by Ghost1988nl** [danielyxie/bitburner#2157]
during one of my runs (save-file included), using both script and manual porting and nuking of the iron-gym server leads to the interface hanging requiring a reload +kill all scripts. 

[bitburnerSave_1640281234_BN1x0.zip](https://github.com/danielyxie/bitburner/files/7770733/bitburnerSave_1640281234_BN1x0.zip)

**Comment by Hedrauta** [comment]
🤔  i have an AutoNuke run too.... works fine for me... maybe one of your scripts will cause the issue 😏

**Comment by Ghost1988nl** [comment]
Thank… but as i have stated using both a script and a **manual** approach even after the reload and kill all scripts function so no scripts running leads to the same issue.

**Comment by hydroflame** [comment]
Can't repro on Steam or web.

**Comment by Ghost1988nl** [comment]
Yeah It disappeared after a full wipe and haven’t been able too reproduce it using the same scripts myself either
