### ISSUE TITLE
terminal actions grow and weaken give no exp

### ISSUE THREAD

**Issue by TangleSpider** [danielyxie/bitburner#2159]
Looking at bitburner/src/Terminal/Terminal.ts, the function finishHack includes the function player.gainHackingExp, giving the player hacking experience after hacking using the terminal command "hack". 
However, the functions finishGrow and finishWeaken don't include the function player.gainHackingExp, and the player gains no exp after using the "grow" or "weaken" commands in the terminal. 
Using the "grow" or "weaken" commands does display a message that hacking experience is gained, which is inconsistent with the code.

I would make a pull request, but I don't know what the intentions are either:
1) Should grow or weaken give hacking experience when used as terminal commands?
OR
2) Should grow or weaken not give hacking experience and the experience gain message be removed when used as terminal commands?

**Comment by phyzical** [comment]
looks to be resolved
