### ISSUE TITLE
[Feature Request] Support for other programming languages

### ISSUE THREAD

**Issue by UltraBlackLinux** [danielyxie/bitburner#2161]
Hey there,
I think this is a very cool project, but I myself hate the JS syntax since find it very confusing.
C++ is currently my favourite language, and I noticed that [this]([https://github.com/root-project/cling) exists.
This of course doesn't mean that there shouldn't be support for other languages as well.
Does this have a chance of being implemented?
Thanks!

**Comment by hydroflame** [comment]
Nope

**Comment by UltraBlackLinux** [comment]
> Nope

Btw please look at the link I noticed that I messed it up
