### ISSUE TITLE
Roulette compares previous bet with current roll

### ISSUE THREAD

**Issue by Snarling** [danielyxie/bitburner#2165]
See attached video (Bets/rolls posted below):

Bet 31 (previous bet was 18) : Roll 18 - Win
Bet 29 : Roll 31 - Win
Bet 22 : Roll 30 - Lose (10% "+1" roll)
Bet 5 : Roll 22 - Win
Bet 27 : Roll 5 - Win
Bet 0 : Roll 28 - Lose (10% "+1" roll)
Bet 30 : Roll 0 - Win
Bet 10 : Roll 30 - Win
Bet 8 : Roll 10 - Win
Bet 33 : Roll 8 - Win
Bet 15 : Roll 33 - Win
Bet 19 : Roll 15 - Win

https://user-images.githubusercontent.com/84951833/147301244-728a667c-3564-4db3-a823-c3b1b7053080.mp4

**Comment by phyzical** [comment]
having a quick look at the source i highly doubt this is still the case?

we are `Math.floor(rng.random() * 37);` and then rng has current date + playtime randomness

also the state for last roll cannot leak down into the play setTimeout

imo closable
