### ISSUE TITLE
Moving a file to subfolder and overriding a file there results in error

### ISSUE THREAD

**Issue by ezylot** [danielyxie/bitburner#2168]
Steps to reproduce:

- Create a file `nano test.js`
- Create a second file in a subfolder `nano folder/test2.js`
- Move first file to subfolder and use the same name as the second file `mv test.js folder/test2.js`
- **Error Message : Something went wrong...please contact game dev (probably a bug)**
- **Files are not modified**

@Hedrauta created the following gif
![grafik](https://cdn.discordapp.com/attachments/415213413745164318/923752423846199336/gif_7.gif)

Local Breakpoint and evaluate:
![grafik](https://user-images.githubusercontent.com/5598040/147305649-ac776306-5897-464e-9f59-c4ce0d327034.png)

**Comment by phyzical** [comment]
![image](https://user-images.githubusercontent.com/5182053/153221471-73f3ec8f-5e51-4e9d-87e5-d26e3c95d2f1.png)
closable
