### ISSUE TITLE
Blackjack cards aren't unique

### ISSUE THREAD

**Issue by Cireminer** [danielyxie/bitburner#2171]
![image](https://user-images.githubusercontent.com/4282246/147308946-4105b1a2-4e96-4433-8cb8-89bdb5342ce1.png)

We each got dealt a ten of diamonds. This was my first hand.

**Comment by solarshado** [comment]
May be intentional. If memory serves, it's not unusual in casinos to play blackjack with two or more decks shuffled together.

Still probably be a good idea to explicitly mention this in-game though.

**Comment by dwRchyngqxs** [comment]
Blackjack uses [5 decks](https://github.com/danielyxie/bitburner/blob/dev/src/Casino/Blackjack.tsx#L48)
