### ISSUE TITLE
Documentation inconsistent - nano .fconf

### ISSUE THREAD

**Issue by michael-hart-github** [danielyxie/bitburner#2173]
This was already brought up in https://github.com/danielyxie/bitburner/issues/1777, but it is still a problem, even though that issue was closed.

[The documentation](https://bitburner.readthedocs.io/en/latest/basicgameplay/terminal.html#configuration) mentions using the command `nano .fconf`. That configuration section should probably be stripped out marked with a TODO of some kind.

Cheers.

**Comment by Hedrauta** [comment]
All the options that used to be in fconf are in options now

_Originally posted by @hydroflame in https://github.com/danielyxie/bitburner/issues/1777#issuecomment-993789639_

==> 
![pic](https://i.imgur.com/Bi9lQD3.png)

**Comment by michael-hart-github** [comment]
@Hedrauta, yep. The problem is that the reference is still in the documentation and should be removed.

**Comment by dwRchyngqxs** [comment]
`nano .fconf` isn'tmentionned anymore in the documentation, this issue can be closed.
