### ISSUE TITLE
array.push seems to be missing from arrays in autocomplete.

### ISSUE THREAD

**Issue by ewanm89** [danielyxie/bitburner#2178]
On the Steam version of the game, using the following autocomplete function:
```js
export function autocomplete(data, args) {
	if (args.length == 1) {
		var completions = [];

		for (let i = 0; i <= 20; i++) {
			completions = completions.push(Math.pow(2, i).toString());
		}
		return completions;
	}
	if (args.length == 2) {
		return [...data.servers];
	}
}
```
And getting this error of it not finding the push function even though completions is an empty array (checked with the debugger, and the function is there for use in the debug console):
```
236efd1d9e-fd22-4fa0-bdfb-d1fc412c88f4:38 Uncaught (in promise) TypeError: completions.push is not a function
    at Module.autocomplete (blob:file:///6efd1d9e-fd22-4fa0-bdfb-d1fc412c88f4:38)
```

Given this is standard Javascript library stuff, this is confusing to me.

**Comment by hydroflame** [comment]
Nothing I can do about that that's just JSDoc not hinting correctly.

**Comment by ewanm89** [comment]
Well, I would say, we should probably be able to push to an array anyway. Of course, in this particular situation, I have array indices I can use to work around the issue. But I don't see why we can't have pop() and push() available?
