### ISSUE TITLE
Loss of all Augmentations on joining my First Bitnode

### ISSUE THREAD

**Issue by lokesh1197** [danielyxie/bitburner#2180]
After installing *The Red Pill*, and then hacking the w0r1d_d43m0n server. I selected Bitnode 1 and after the soft reset I have no Augmentations.

I lost nearly 60 Augmentaions. If this is how it is supposed to be then it should be mentioned in the tutorial/documentation. It feels like I wasted a lot of time for nothing. If it is bug then please let me know what should I do next.

Thanks for this wonderful game.

**Comment by hydroflame** [comment]
That's normal, you got a new powerup in return, it's called `SF1.1`, check your augmentations page.
