### ISSUE TITLE
Better PDF documentation

### ISSUE THREAD

**Issue by locriacyber** [danielyxie/bitburner#2182]
Currently, the PDF version only has "Chapter 1", because all the content is under Chapter 1. Also, the changelog is in the table of content, making it very long.

![image](https://user-images.githubusercontent.com/74560659/147374546-23e9d443-55e4-4d5a-8e7b-3f6c057302ee.png)

said PDF documentation: https://bitburner.readthedocs.io/_/downloads/en/latest/pdf/

**Comment by hydroflame** [comment]
Needs investigation

**Comment by phyzical** [comment]
possibly closable given all the auto generated docs?

**Comment by locriacyber** [comment]
What auto docs? I need some offline downloadable documentation that is searchable outside the game. HTML is fine too.

**Comment by phyzical** [comment]
https://github.com/danielyxie/bitburner/tree/dev/markdown is what i was referring to
