### ISSUE TITLE
Command NUKE.exe not found

### ISSUE THREAD

**Issue by mpapirkovskyy** [danielyxie/bitburner#2186]
After playing a bit it seems I can't use programs anymore
did nothing besides following tutorial and scripting doc

```
[n00dles ~/]> home
Connected to home
[home ~/]> ls
csec-test.msg                 hackers-starting-handbook.lit 
j0.msg                        j1.msg                        
j2.msg                        
AutoLink.exe   BruteSSH.exe   DeepscanV1.exe NUKE.exe       fl1ght.exe     
buy-server-8gb.script hack-template.script  n00dles.script        
[home ~/]> connect n00dles 
Connected to n00dles
[n00dles ~/]> ls
hack-template.script 
[n00dles ~/]> NUKE.exe
Command NUKE.exe not found
```

[bitburnerSave_1640426802_BN1x0.zip](https://github.com/danielyxie/bitburner/files/7775694/bitburnerSave_1640426802_BN1x0.zip)

**Comment by hkgnobody** [comment]
i believe the correct cmd should be "run NUKE.exe"?

**Comment by mpapirkovskyy** [comment]
I swear I tried that also and failed, but now it works :) I guess it was my glitch. Thanks.
