### ISSUE TITLE
Address already in use [ERROR]

### ISSUE THREAD

**Issue by ToasterUwU** [danielyxie/bitburner#2188]
![image](https://user-images.githubusercontent.com/43654377/147385199-ad6b43c3-c5da-414b-92bd-5cc4bdced701.png)

I got this pop-up while I was buying stuff on the dark web. To be more precise I was holding the delete key to delete the thing I just bought and was about to buy another thing. But deleting the big S in "ServerProfiler.exe" was too much to ask I guess xD

No worries, just wanted to report the bug.

**Comment by hydroflame** [comment]
Pretty sure it's fixed because it's configurable now?
