### ISSUE TITLE
cannot ns.write to subfolder

### ISSUE THREAD

**Issue by CrazyMLC** [danielyxie/bitburner#2189]

**Comment by Hedrauta** [comment]
Maybe did something wrong on the folders name? Bc, works perfect for me <.< 
![gif (8)](https://user-images.githubusercontent.com/20142298/147386308-c48bc6a1-89db-4dfa-b731-789afd7deaae.gif)

**Comment by timotheeandres** [comment]
I had a similar issue, make sure that the path starts with `/` for it to work properly.
