### ISSUE TITLE
High stat multipliers cause weird combat stat experience progress bars:

### ISSUE THREAD

**Issue by ewanm89** [danielyxie/bitburner#2190]
As per title, see agility looking like it is backwards.
![image](https://user-images.githubusercontent.com/135458/147388971-5493115a-fcbf-475b-ad1a-6b72499a7fb5.png)

Hack level and Charisma Level seem fine.

**Comment by LeviPesin** [comment]
I have the same bug. If you hover on such "backward" skill, you will see strange experience value like 543.750/543.662 104.54%.

**Comment by ewanm89** [comment]
Looks like an overflow issue then, mine with changing quickly :D

**Comment by MartinFournier** [comment]
Anybody still sees this issue? There was a fix related to this but it may not have handled all the cases.

**Comment by phyzical** [comment]
imo lets close it and that them reopen if it comes back
