### ISSUE TITLE
Steam Cloud Savefiles

### ISSUE THREAD

**Issue by GekoShell** [danielyxie/bitburner#2191]
I think it would be helpful if the Steam version of the game had a way to enable cloud saves. It would be beneficial to people with several computers and would act as a more secure backup in the case of the player's save becoming corrupt or broken. Thanks :)

**Comment by smmalis37** [comment]
For reference: https://github.com/greenheartgames/greenworks/blob/master/docs/cloud.md

**Comment by MartinFournier** [comment]
The cloud feature has been added in https://github.com/danielyxie/bitburner/pull/2781 but it has not hit production yet. The `--export-save` flag is just a helper tool to grab the save file out of the game without going through the app.

**Comment by phyzical** [comment]
closable i would say
