### ISSUE TITLE
using :w to close edited files doesn't actually write file instantly

### ISSUE THREAD

**Issue by kafuuchino-desu** [danielyxie/bitburner#2194]
I'm running on steam release for bitburner, when I'm done editing sth I always use :w to exit editor, but somehow the file is not actually changed instantly, I'll have to wait for a few seconds before cat shows me latest changes I've made to the file.

**Comment by kafuuchino-desu** [comment]
BTW can you guys make :wq work together? bc I think most of vim users are used to type :wq to exit editor and somehow editor doesn't accept this command, not sure if It's work as intended or a bug 🤣

**Comment by phyzical** [comment]
looks to be closable `MonacoVim.VimMode.Vim.defineEx("wqriteandquit", "wq", function () {`
