### ISSUE TITLE
Tail Issue 

### ISSUE THREAD

**Issue by willypatty** [danielyxie/bitburner#2198]
If I move the tail all the way to the top of the screen to a certain point you can't close it. It blocks part of the screen and I can't remove it.

**Comment by apixdae** [comment]
Same effect happens when you drag it to the bottom of the screen. Possible solution is to clamp the y position to the screen's vertical bounds.

**Comment by willypatty** [comment]
Ok thanks. Another way that worked was to just close and reopen the game and it was gone. Thanks for the tip.

**Comment by hydroflame** [comment]
dup
