### ISSUE TITLE
Should everything executable via terminal be executable via script?

### ISSUE THREAD

**Issue by eugenpt** [danielyxie/bitburner#2203]
Clickable links to be produced via `ns.tprint()`? like `AutoLink.exe` is able to

`connect` action via script execution?

**Comment by ErzengelLichtes** [comment]
This is more of a question for the discord, TBH.

* [`ns.connect`](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.connect.md) does exist, but you need to get pretty far in the game to be able to use it.

* Links are unique to scan-analyze.

The (appropriately) hacky solution is to use `document.getElementById("terminal-input")` to get the element that you type into and then use that to interact with the terminal. This costs 25GB. Check on reddit for a complete script.

**Comment by eugenpt** [comment]
Wow! Thanks for such a detailed reply!! I will play further, did not realize the depth of the game.
