### ISSUE TITLE
Courses let you go into negative balance

### ISSUE THREAD

**Issue by clienthax** [danielyxie/bitburner#2205]
Started a course, left it running overnight apparently.
Came back to find myself in 59m debt
Also seems you can start courses while being in negative balance.

![image](https://user-images.githubusercontent.com/1056270/147501567-f1550e18-a1d2-46a4-8f53-871b17ef4b08.png)

**Comment by hydroflame** [comment]
Normal part of the game.

**Comment by hydroflame** [comment]
You know what fair enough I will make it so you can't go into negative.

**Comment by ErzengelLichtes** [comment]
We need a way to take out "student loans" then.

**Comment by phyzical** [comment]
based on the response from other ticket will just focus on fixing the debt issue in this bug

**Comment by Snarling** [comment]
@hydroflame given that there's an achievement for hitting a certain negative balance, I think we can go back to saying this is a normal part of the game and close this issue.
