### ISSUE TITLE
Text editor issue at tutorial 

### ISSUE THREAD

**Issue by koorlan** [danielyxie/bitburner#2222]
Hi, i just discovered the game today and try to play on the server hosted here:
  danielyxie.github.io

Unfortunately i'm not able to continue the tutorial because editor's openning seems to be broken. Maybe i'm missing something ?

I'm facing a : Object.fromEntries  is not a function.. 

Please find a screenshot below
![image](https://user-images.githubusercontent.com/3740701/147630931-680819ac-8e35-4d63-b0d6-08e461829b37.png)

Thanks for all the game looks very good 

Korlan

**Comment by hydroflame** [comment]
Can you open the console log and see if there's any error?

Are you behind a firewall?

**Comment by koorlan** [comment]
Here is the console log when just launching the game, no command entered

```
/bitburner/main.bundle.js:19 TypeError: Object.fromEntries is not a function
    at X (/bitburner/main.bundle.js:1)
    at F (/bitburner/main.bundle.js:19)
    at Object.load (/bitburner/main.bundle.js:19)
    at Object.then.e (/bitburner/main.bundle.js:19)
Object.then.catch.e @ /bitburner/main.bundle.js:19
/bitburner/main.bundle.js:1 Hostname of the server thats being added: ecorp
y @ /bitburner/main.bundle.js:1
/bitburner/main.bundle.js:1 The server that already has this IP is: ecorp
y @ /bitburner/main.bundle.js:1
/bitburner/main.bundle.js:1 Uncaught (in promise) Error: Error: Trying to add a server with an existing IP
    at y (/bitburner/main.bundle.js:1)
    at b (/bitburner/main.bundle.js:1)
    at Object.load (/bitburner/main.bundle.js:19)
    at Object.then.catch.e (/bitburner/main.bundle.js:19)
```

I'm running it on Chrome Version 71.0.3578.98 (Build officiel) (64 bits)

On firefox nightly 97.0a1 (2021-12-28) (64 bits)   no issue.. maybe chrome is too old ?

**Comment by hydroflame** [comment]
Oh, yes that's definitely a chrome too old problem.


It's available on Steam too.

**Comment by koorlan** [comment]
Okay many thanks, maybe we could add control at startup blocking game launch if browser not supported ?
