### ISSUE TITLE
`while`can replace all `if` and `for` 

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#223]
This is a minor point but it kinda makes the RAM costs of `for` and `if` irrelevant.  

    if (cond) {
        statements...
    }

can be replaced with

    while(cond) {
        statements...
        break;
    }

and I'm sure you can figure how all `for` can be replaced for `while`

on one hand this is a game about "hacking" so maybe the players should be rewarded for bending the rules. on the other it "forces" the player to make less readable code in order to save a few MB.

**Comment by danielyxie** [comment]
loops and conditionals no longer cost RAM in v0.39.0
