### ISSUE TITLE
Joe's guns title flickering in details view

### ISSUE THREAD

**Issue by mheydem** [danielyxie/bitburner#2239]
The title in Joe's guns details view is flickering after selecting it form the city view.
See attached video.
This occurs at the instance currently running on https://danielyxie.github.io/bitburner

https://user-images.githubusercontent.com/16156696/147773959-56cdf1df-3d79-42a4-8049-f0eae10f975b.mov

 I have taken the following actions with Joe's guns
- not installed any backdoor at any server
- not opened any ports of any server
- connected to the server joesguns - also flickering when not connected
- Applied to be an Employee at Joe's guns
- Quit the Job at Joe's guns
- Selected "Infiltrate Company" for Joe's guns, but canceled it

I guess it is not a feature.

**Comment by hydroflame** [comment]
It is a feature.

**Comment by mheydem** [comment]
> It is a feature.
Oh really. How is that?

**Comment by hydroflame** [comment]
When you backdoor a server the associated company starts doing that.

**Comment by mheydem** [comment]
I read about the backdoor feature in the game's documentation, but haven't used it yet.
Is another trigger possible?

**Comment by Marthgun** [comment]
I could be wrong but it may do this if you're currently residing in the server. or you open all the ports. I think this may have happened to me. you'd have to do some testing @mheydem

**Comment by mheydem** [comment]
I could reproduce this behaviour on the current dev branch, but not on last release tag v1.0.2
Steps to reproduce:
1. in terminal: run NUKE.exe server
2. in terminal: hack server
3. in city view: visit the corresponding server location
4. in city view: flickering title in locations detailed view
Tested this for
- joe's guns
- foodnstuff
- iron gym
I also exported my current game progress and imported it into my local instance:
- git checkout dev -> reload -> flickering
- git checkout v1.0.2 -> reload -> not flickering

**Comment by MartinFournier** [comment]
Manual hacks using the terminal do install a backdoor on the server, however using ns.hack() through a script will not.

To install a backdoor through scripts you would have to use another command available later in the game.

**Comment by mheydem** [comment]
> Manual hacks using the terminal do install a backdoor on the server, however using ns.hack() through a script will not.
> 
> To install a backdoor through scripts you would have to use another command available later in the game.

Is this the expected behavior?

**Comment by MartinFournier** [comment]
Yeah, it might not be clear enough though.

Backdoor command used not to exist, so late game you'd have to manually connect to servers to run the hack command manually to install a backdoor while you had scripts doing pretty much everything else automatically. So ns.backdoor was added back then, but manual hack always worked that way.

**Comment by mheydem** [comment]
The flickering is not in v1.0.2. This is a little confusing.
But the current dev branch shows the expected behavior described by @MartinFournier.
