### ISSUE TITLE
Focus not in script editor on terminal script call

### ISSUE THREAD

**Issue by Marthgun** [danielyxie/bitburner#2246]
Whenever I enter something like `nano x.script`, it enters me into the editor, I ctrl+a to select all and it doesn't select the text within, making me have to put focus into the editor to get at the text. am i doing something wrong?

also, is there a shortcut to save and close a script? ctrl+s does not close the script in the editor window.

**Comment by phyzical** [comment]
may be related https://github.com/danielyxie/bitburner/issues/2308

**Comment by Master-Guy** [comment]
In the current version (Steam, today) using `nano` puts the focus in the correct window.
@Marthgun FYI: The shortcut to save and close the script is advised ingame as well: CTRL+S to save, followed by CTRL+B to close.
