### ISSUE TITLE
Using js workers

### ISSUE THREAD

**Issue by BinarSkugga** [danielyxie/bitburner#2254]
I've tried to use a web worker inside the a test script without success unfortunately. Are workers supported or am I doing something wrong ? Both test.js et worker.js are in my home dir.

```javascript
// test.js
/** @param {NS} ns **/
export async function main(ns) {
	ns.disableLog('ALL');

	let worker = new Worker('worker.js');
	var y = 0;

	worker.onmessage = function(event) {
		y = event.data;
	};

	while(y <= 1000) {
		await ns.sleep(100);
		ns.print(y);
	}

	worker.terminate();
}
```

```javascript
// worker.js
let x = 0;

while(x <= 1000) {
	x += 1;
	postMessage(x);
	sleep(100);
}
```

I run it using: `run test.js; tail test.js`. When running this, `y` is always 0 and never receives the event's data.

**Comment by hydroflame** [comment]
No they're not supported.
