### ISSUE TITLE
using Map.get increases ram use by 2GB

### ISSUE THREAD

**Issue by reacocard** [danielyxie/bitburner#2257]
using Map.get increases the ram use estimate by 2GB

minimal reproduction:
```
/** @param {NS} ns **/
export async function main(ns) {
    var m = new Map // 1.6GB
    m.set("foo", "bar") // 1.6GB
    m.get("foo") // 3.6GB ?!
}
```

this can be worked around with `m["get"]("foo")` but that's rather awkward.

**Comment by SagePtr** [comment]
Even more, this takes extra 2Gb too:
```
/** @param {NS} ns **/
export async function main(ns) {
	function get() {}
	get();
}
```

**Comment by hydroflame** [comment]
Yeah kindof unfixable.

**Comment by olee** [comment]
You can instead use `map['get'](...)` which will not affect the static ram calculation 👍 
However, I would really like to see this fixed in some way.... (see https://github.com/danielyxie/bitburner/issues/2717)
