### ISSUE TITLE
Corporation dividend payout amount and taxes seem incorrect

### ISSUE THREAD

**Issue by norbby42** [danielyxie/bitburner#2261]
Platform: Steam, PC Build ID 7928103 (Dec 23, 2021)
BitNode: 3, Corporatocracy

I have a corporation running with these stats:
```
Total Revenue: $21.792m / sec
Total Expenses: $4.466m / sec
Publicly Traded: Yes
Owned Stock Shares: 900.000m
Total Stock Shares: 1.500b
```

Setting Dividends to 50% yields the following information:
```
Retained Profits (after dividends): $8.611m / sec
Dividend Percentage: 50%
Dividends per share: $0.006 / sec
Your earnings as a shareholder: $3.599m / sec
```

----

**Issue 1:**  The tax rate does not behave as expected

I own 900 / 1500 = 60% of the company's shares, and expect to receive a baseline of $8.611m * 0.6 = $5.166m / sec

BUT!  I have not purchase either tax upgrade, so the expectation is that value is decreased by 15% to $4.391m / sec.

The actual amount that the UI tells me I will receive is $3.599m / sec, which is a noteworthy difference from $4.391m / sec.

It appears the use of Math.pow to apply the tax rate in addition to the BitNode multiplier in Corporation.tsx is applying a pretty hefty penalty beyond what is expected.
It's important to note that I am in BiteNode 3, so CorporationSoftCap == 1.0.  Were I in another bitnode, this would be a fair bit harsher.

----

**Issue 2:** The reported payout does not match actual payout

The UI says I will earn $3.599m / sec.
However, careful observation of my monetary value via the player widget at the top right shows that I only appear to gain that amount roughly once per corp cycle - every 10 seconds.

I verified this with the following script while no other scripts were running on any server, I had no hacknet nodes purchased, no gang, not working or performing any task/crime/etc, or any other source of income that I could identify:

```
export async function main(ns) {
	let prevMoney = ns.getPlayer().money;
	while (true) {
		await ns.asleep(10000); // 10 seconds = 1 corp cycle
		const money = ns.getPlayer().money;
	
		ns.tprint("Player funds delta since last cycle: " + ns.nFormat(money - prevMoney, "($0.00a)"));	

		prevMoney = money;
	}
}
```

Results:
```corptest.js: Player funds delta since last cycle: $3.61m
corptest.js: Player funds delta since last cycle: $3.62m
corptest.js: Player funds delta since last cycle: $3.62m
corptest.js: Player funds delta since last cycle: $3.62m
corptest.js: Player funds delta since last cycle: $3.62m
```

Over a duration of 10 seconds, I am receiving $3.62m.  This is a yield of $362k / sec, a roughly _**10x**_ difference from the $3.599m / sec the corporation UI promises.

**Comment by Almabali** [comment]
I second this, the global money/sec from dividend is wrong. IT gets me the right player money when I have corporation boost (from beign offline), but once the boost expired, I get that money only once per market cycle, so 1/10...

Please fix, this is a dire issue in itself, sloving an already slow BN.

Also, the dividend m/s is either calculated wrong, or the tax rates are around 40%...
![image](https://user-images.githubusercontent.com/23095683/147878795-41297868-9877-4469-a3e7-7a685b350d22.png)

**Comment by gisenberg** [comment]
Just chiming in to say that I'm seeing the same issue with dividend payouts being an order of magnitude off.

**Comment by Yirka** [comment]
I'll add to this with numbers from my own corporation.

Within getDividends() on line 145 of Corporation.tsx I've found that:
```
cycleProfit = 149148676.84874848
totalDividends = 149148676.84874848
dividends = 107718488.83520724
```
At this point everything is correct based on the percentage of shares that I own as well as the fact that profit is calculated once every 10 seconds (14,9m * 10 = 149m). 

As mentioned in an earlier comment, the game uses the following formula to calculate taxes:
```
return Math.pow(dividends, BitNodeMultipliers.CorporationSoftCap + upgrades);
```
Where
```
dividends = 107718488.83520724
BitNodeMultipliers.CorporationSoftCap = 1
upgrades = -0.15
```
Yields the mathematical expression
```
107718488.83520724^0.85 = 6721198.38429
```
Which is 
```
6721198.38429 / 107718488.83520724 = 0.0624
or
93.76% effective tax rate
```
This is where the order of magnitude comes from mentioned in another comment.
This 93.76% tax rate is far, far off the `dividendTaxPercentage = 50;` found within the same file.


Additionally, having had both of the upgrades (reducing tax by 5% and 10% respectively) would've changed the expression to:
```
107718488.83520724^1 = 107718488.83520724
```
Which, quite obviously, is the equivalent of paying _**no tax at all**_, rather than the expected 35%

I've made a PR resolving this issue over at https://github.com/danielyxie/bitburner/pull/2932

**Comment by BrianLDev** [comment]
Bumping this one up as I'm running into the same issue as of Mar 16th (in BN 12.0).

**Net income (rounded down):**  $15.5t
**Total Shares:**  1b
**Shares owned:**  900m (90%)
**Calculated "earnings as a shareholder" (before tax):**  $13.95t
**Tax rate:**  Unknown... should be listed on summary page.  (Note: I purchased the Corporate lobbying and Shady Accounting tax reduction options)
**Actual "earnings as a shareholder" (after tax):**  $110.985m
**Effective tax rate:  99.999% WTF?!**
![image](https://user-images.githubusercontent.com/16980550/158661421-1d1bcaf1-7671-4589-a9db-d216a83d2bde.png)

**Comment by samuei** [comment]
I'm 99% sure that the source of this is the Bitnode multiplier for corporate valuations hitting the dividend math, which is nonsensical. If that multiplier is meant to decrease dividends, then it needs to change the sale price of items to harm the total revenue, not cause a sort of mirage-profit effect. I don't recommend that, as it will utterly cripple corporations in bitnodes where the multiplier is high, which is poor game design (if you don't want corporations in a node, just turn off corporations in that node). It also reinforces the idea that the corporations are a minigame and not a part of the same universe as the rest of the game, which is also poor game design.

**Comment by phyzical** [comment]
yeah ive got a pr that disables corps when the multiplier is below 0.15, suggested as the turning point as a workaround for the time being

**Comment by bzzz-dmg** [comment]
> Bumping this one up as I'm running into the same issue as of Mar 16th (in BN 12.0).
> 
> **Net income (rounded down):** $15.5t **Shares owned:** 900m out of 1b (90%) **Calculated "earnings as a shareholder" (before tax):** $13.95t **Tax rate:** Unknown... should be listed on summary page. (Note: I purchased the Corporate lobbying and Shady Accounting tax reduction options) **Actual "earnings as a shareholder" (after tax):** $208.872b **Effective tax rate: 98.5% WTF?!** ![image](https://user-images.githubusercontent.com/16980550/158661421-1d1bcaf1-7671-4589-a9db-d216a83d2bde.png)

Effective tax rate here is actually **99.85%** because even though the UI shows "$208b / sec", it is actually per production cycle (per 10 seconds).

It is weird that the variable `dividendTaxPercentage` isn't used anywhere in the code. It is initiated as 50, then updated according to upgrades by -5 and by -10, but not used in actual dividends calculation.

**Comment by samuei** [comment]
@bzzz-dmg That seems to have been factored out [in November](https://github.com/danielyxie/bitburner/commit/3112dc60c089bf5dadd3166bcdf903b623067006#diff-071444aed4cb04cfff370bda97a79c4c4a03d6f01e4d1e285be795ff0ed1de37), perhaps accidentally?
