### ISSUE TITLE
Active Script Log Popout Stuck At Top Of Screen

### ISSUE THREAD

**Issue by Marthgun** [danielyxie/bitburner#2263]
I can't get it down. it's stuck under the gray ribbon where Edit; reloads; fullscreen; debug are located. I pushed it up with fervor and grace. It is stuck. Help me. I've tried 300 times to get that hand icon to pull it down. It refuses.
btw why is Edit the only one capitalized? I think the should all be capitalized.

feature request: desktop notifications using the game code so i can notify myself of stuff.

**Comment by hydroflame** [comment]
dup
