### ISSUE TITLE
Recovery Mode Activated - Error: Trying to add a server with an existing IP

### ISSUE THREAD

**Issue by MichaelJFishman** [danielyxie/bitburner#2264]
### Version Info
Steam, Bitburner v1.2.0.
The save is originally from Windows, then transferred to Mac.
Loading the recovery file into brave `Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)` on Mac also starts recovery mode, with the same errors showing in the dev console.

### Reproduction and workaround
This occured when loading my save. The scripts that were running, along with the save itself, are below. The main script was `simple_hack_manager.js`, which imports from or runs the other scripts.
Reloading and killing all scripts fixes this issue.

After reloading and killing all scripts, I tried to reproduce this issue by running `simple_hack_manager.js`, exporting my save, and importing the save. This did not trigger recovery mode, but did kill all scripts. 
I then re-ran `simple_hack_manager.js`, saved the game without exporting the save file, closed and reopened the game. My scripts were still running.

### Scripts and save file
My save file, and the scripts that were running, are in [this](https://gist.github.com/MichaelJFishman/e879e307334ed2a1db8cc5bc8359f669) gist. The main script running was `simple_hack_manager.js`, which used functions exported by the other scripts.

### Errors from debug console:

```
main.bundle.js:19 TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at e (main.bundle.js:1)
    at e (main.bundle.js:1)
    at e (main.bundle.js:1)
    at X (main.bundle.js:1)
    at new s (main.bundle.js:1)
    at N (main.bundle.js:1)
    at F (main.bundle.js:1)
    at Object.load (main.bundle.js:19)
    at main.bundle.js:19
```

```
main.bundle.js:1 Hostname of the server thats being added: ecorp
y @ main.bundle.js:1
```

```
main.bundle.js:1 Uncaught (in promise) Error: Error: Trying to add a server with an existing IP
    at y (main.bundle.js:1)
    at b (main.bundle.js:1)
    at Object.load (main.bundle.js:19)
    at main.bundle.js:19
    at async main.bundle.js:19
```

### Thanks!
This game is very cool. This should be a whole genre.

**Comment by MartinFournier** [comment]
Great report thanks.

Interestingly, the decoded recovery.json (it's base 64) is truncated so not valid JSON
![Code_mQ8F9ZiAQX](https://user-images.githubusercontent.com/1521080/147851011-dfbdb4ba-1dfe-402d-a3a5-de8760791c16.png)

**Comment by MichaelJFishman** [comment]
I was wondering why the JSON didn't look very JSON-like before. Thanks for telling me it's base 64 encoded!

I just checked, and the original save file is not truncated: ![image](https://user-images.githubusercontent.com/37938241/147851145-16a06c2b-0156-4455-9ef0-9f57acbc1508.png)

I think the gist won't let me upload the entire file - thought it didn't warn me it was truncating it. When I copy my file to the gist, and then back out, I get a truncated version. [Here](https://drive.protonmail.com/urls/V2GJCDPEA4#FBqHQeKHkgAg) is the recovery file in protondrive.

**Comment by Master-Guy** [comment]
[RECOVERY3.json.txt](https://github.com/danielyxie/bitburner/files/8266754/RECOVERY3.json.txt)

Not sure how long Protondrive keeps it. Attached it directly here.
