### ISSUE TITLE
ns.sleep locks if a dictionary element called `.hack` is accessed immediately preceeding

### ISSUE THREAD

**Issue by atnoslen** [danielyxie/bitburner#2268]
`.sleep()` and `.asleep()` are locking up client (going to 100% CPU on game thread).  I have several while loops that wait for certain gang training with a sleep to wait until after next tick.  The second loop locks up on the first `.sleep()`.  Of interest, I have several sleeps going on, all work, but this one consistently hangs.

This started to occur about an hour ago.  I assume it is game state related given it is reproducible only at this one particular `sleep()`.

![image](https://user-images.githubusercontent.com/3331625/147856527-7e64010b-5093-45d5-9fed-78cd26b77997.png)

This occurs on reload, including reloading entire game host machine.  

Relevant section of code.

gang.ns line 225-253
246 is affected sleep.

```
            while (updatedMemberData.str < stats.str || updatedMemberData.def < stats.def || updatedMemberData.dex < stats.dex || updatedMemberData.agi < stats.agi) {
                // Wait longer
                await ns.sleep(2000);

                updatedMemberData = ns.gang.getMemberInformation(memberName);

                ns.print(memberName + ' (ascending): Stats:' + 
                    ' Str (' + updatedMemberData.str + '/' + stats.str + ')' +
                    ' Def (' + updatedMemberData.def + '/' + stats.def + ')' +
                    ' Dex (' + updatedMemberData.dex + '/' + stats.dex + ')' +
                    ' Agi (' + updatedMemberData.agi + '/' + stats.agi + ')'
                );
            }


            ns.gang.setMemberTask(memberName, 'Train Hacking');
            ns.print(memberName + ' (ascending): Set task to Train Hacking');

            while (updatedMemberData.hack < stats.hack) {
                ns.print('before sleep');
                // Wait longer
                await ns.sleep(2000);  // Locks up here

                ns.print('after sleep');
                
                updatedMemberData = ns.gang.getMemberInformation(memberName);

                ns.print(memberName + ' (ascending): Stats:' + ' Hack (' + updatedMemberData.hack + '/' + stats.hack + ')');
            }
```

We can see the sleep in the first loop works while the second sleep locks.  This was working fine until an hour ago.

Have attempted `.sleep()` and `.asleep()`, both have same impact.  

Save
[bitburnerSave_1641058413_BN2x1.zip](https://github.com/danielyxie/bitburner/files/7798010/bitburnerSave_1641058413_BN2x1.zip)

**Comment by atnoslen** [comment]
Of interest, while tying this, after last reload, there appears to be some fragment of code running somewhere, even after a reload and kill all script.  I have no processes running (running a `ps`).  Yet, there is still my main loop from `gang.ns` running as two new gang members have been recruited by automation, without a script running.

I don't believe it is my current script as some of the functionality is not working proper (I don't see changing tasks, which means the only part that is functioning in this hidden process is recruiting members).

**Comment by atnoslen** [comment]
This is due to accessing an entry of a dictionary with `.hack`.

This code works.

```
while (updatedMemberData['hack'] < stats['hack']) {
	ns.print('before sleep');
	// Wait longer
	await ns.sleep(2000);

	ns.print('after sleep');
	
	updatedMemberData = ns.gang.getMemberInformation(memberName);

	ns.print(memberName + ' (ascending): Stats:' + ' Hack (' + updatedMemberData['hack'] + '/' + stats['hack'] + ')');
}
```

This code fails, locking on the sleep just after accessing the `.hack` property.

```
while (updatedMemberData.hack < stats.hack) {
	ns.print('before sleep');
	// Wait longer
	await ns.sleep(2000);

	ns.print('after sleep');
	
	updatedMemberData = ns.gang.getMemberInformation(memberName);

	ns.print(memberName + ' (ascending): Stats:' + ' Hack (' + updatedMemberData.hack + '/' + stats.hack + ')');
}
```

**Comment by DyspC** [comment]
I have a similar issue after getting today's update but no signs of .hack field access in any of my running scripts (just reading data from a port and resolving contracts)

```js
export async function main(ns) {
	const flags = ns.flags(flagDefs);
	logger.configure(ns, flags["log"]);

	let pid = ns.run("crawl.js", 1
		, "--log", "WARN"
		, "--macro", "ls-cct");
	logger.debug("Started crawl.js with PID %d", pid)
	await ns.sleep(3);
	// await ns.asleep(3000);

	let counter = 0;

	const ph /* NetscriptPort */ = ns.getPortHandle(reservedPorts[portName]);
	while (!ph.empty()) {
		counter++;
		// { serverName: o.server, contractName: cct }
		let contractMetaData = ph.read();
```

**Comment by Snarling** [comment]
Misdiagnosed issue. The game does not do any oversight of your code other than when you call ns functions, there is no functional difference between `object.hack` and `object["hack"]`.
