### ISSUE TITLE
Scripts can ignore "dynamic RAM" limit using try-catch

### ISSUE THREAD

**Issue by apricotorange** [danielyxie/bitburner#2273]
Example:

```
export async function main(ns) {
  try { await eval('ns.hack("n00dles")') } catch { }
  await eval('ns.hack("n00dles")');
}
```

The first call to ns.hack() throws the dynamic RAM error, but the script catches that error so it doesn't terminate.  The second call to ns.hack() doesn't throw an error.

**Comment by hydroflame** [comment]
duplicate

**Comment by apricotorange** [comment]
Are you sure this is a duplicate?  I don't see any open issue related to this.
