### ISSUE TITLE
Array Jumping game description is confusing

### ISSUE THREAD

**Issue by Reithan** [danielyxie/bitburner#2281]
Searching for this today, saw previous issue #494

The inclusion of the word "exactly" in this contract description makes the task a bit ambiguous.

It feels like this word could be dropped and it would be more understandable.

**Comment by Kebap** [comment]
Current description seems very understandable to me, much better than the linked issue. How does your suggestion improve it?

> Each element in the array represents your MAXIMUM jump length at that position. This means that if you are at position i and your maximum jump length is n, you can jump to any position from i to i+n. 
>
>Assuming you are initially positioned at the start of the array, determine whether you are able to reach the last index exactly.

**Comment by Zayitskin** [comment]
The final word of that description, "exactly", is incorrect from my testing. For example:
If the input was [1,2,3], if the goal is to exactly reach the final index then this input has no valid solution, since no index is i+n away from the final index. But the coding contracts seems to think that this puzzle does have a valid solution, so if you tell it it has no solution, it says you are wrong.

**Comment by Reithan** [comment]
Yes, the term "exactly" here would imply that you need to land your final jump EXACTLY, PRECISELY, SPECIFICALLY onto the final index, meaning the final jump must be an EXACT i+n jump...which based on the results, and the rest of the instructions, doesn't seem to be the case.

And, EVEN IF there is some argument to be made that 'exactly' here may be semantically correct in some respect - it adds nothing to the description. It can be omitted without changing any of the meaning of the instructions, and its omission would remove a possible confusion point for some users.

**Comment by Kebap** [comment]
> Yes, the term "exactly" here would imply that you need to land your final jump EXACTLY, PRECISELY, SPECIFICALLY onto the final index

That much is true indeed.

> meaning the final jump must be an EXACT i+n jump...

That does not follow. You can also use a shorter jump to land exactly there.

> And, EVEN IF there is some argument to be made that 'exactly' here may be semantically correct in some respect - it adds nothing to the description. It can be omitted without changing any of the meaning of the instructions, and its omission would remove a possible confusion point for some users.

Fair enough.
