### ISSUE TITLE
AI Core is invalid in Smart Supply feature (Corporation

### ISSUE THREAD

**Issue by Almabali** [danielyxie/bitburner#2293]
In BN3, Corporation for the Healthcare industry, the AI Cores smart supply toggler throws an error.

![image](https://user-images.githubusercontent.com/23095683/147890941-762418e1-4623-4ad4-be09-a2808f011370.png)

**Comment by Jedimaster4559** [comment]
I'm not in a position right now to implement a solution to this bug, but I think it's probably something wrong with the check on this line of code:
https://github.com/danielyxie/bitburner/blob/bb34d6b582c29c13ea3538b908a051e57329842b/src/Corporation/Actions.ts#L236

**Comment by phyzical** [comment]
closable no longer an issue
