### ISSUE TITLE
hackAnalyze(<server>) returns 0 even though hack(<server>) runs and steals a non-zero % of money.

### ISSUE THREAD

**Issue by adalius** [danielyxie/bitburner#2294]
My script does:
let perhack = ns.hackAnalyze(maxServer);
let neededhack = Math.floor(0.5 / perhack);

In this instance, maxServer = "megacorp".

It worked fine for days, yet today it started behaving odd as the following code was generating only hack threads and nothing else (this code is used to figure out how many hack threads I need so the rest can be weaken/grow threads). 

So I ran some debug tests using tprint and came across the issue that 'ns.hackAnalyze("megacorp");' was returning 0. Not near 0, but === 0. This was resulting in neededhack = Infinity.

This seems like an error because if I run hack("megacorp"); it succeeded just fine and stole money, so clearly the % stolen per thread is not, in fact, 0 as the function reported. 

I ended up doing a ternary on perhack so it returns 0.01 if perhack is 0 so that neededhack woudln't equal Infinity as a kludge on my end.

**Comment by phyzical** [comment]
this can be closed a duplicate
