### ISSUE TITLE
Can't exec multiple times in one script?

### ISSUE THREAD

**Issue by kimihiro64** [danielyxie/bitburner#2296]
Using latest on steam, have a hack.js script which is the generic hack on a target, an infect script which loads the hack.js script onto a server to run to hack some target, and am writing an infectall.js script which just iterates through a list of hosts and runs infect.js on them. For some reason, all calls to exec after the first fail with exit code 0 and no information about why it failed to start. Whether the infect.js script is run from home or loaded onto the server to be infected and run there, still fails with exit code 0. Also does not matter if this happens in a for loop or if it's just each line copied and pasted with a different host.

**Comment by SirGouki** [comment]
This may not actually be an issue with bitburner, but an issue with your code.  Post it in a code block on here and I'll look at it.

**Comment by hydroflame** [comment]
To run the same script on the same host just add garbage arguments
