### ISSUE TITLE
Dynamic Script imports

### ISSUE THREAD

**Issue by fpottbaecker** [danielyxie/bitburner#2300]
It would be nice to have some means of dynamic script imports (with some limitations) available.

Use Cases:
* Automatic (re)start / remote-run helper script autocompletion (use the autocomplete function of the desired script)
* Dynamic service/deamon script configuration (I have a file monitor script that provisions a server for the deamon to run on, but I would like to provide priorities etc. as an exported config object).

**Comment by hydroflame** [comment]
Too complicated and easily feasable with exec + write

**Comment by fpottbaecker** [comment]
I think the first use case cannot really be performed easily using exec and write.

If I want to access any export besides `main` I would have to create a temporary script which imports the target member of the target file, run it and access its logs.

In case of `autocomplete` forwarding (e.g. (re)starting a script with a single command or executing a script across multiple servers), It would be preferable to have dynamic imports.

Personally, I think it would be okay to have a simple implementation, like not trying to analyze static ram usage and just throwing an error if the dynamic ram usage exceeds the static usage (similar to accessing `ns` members via subscript), or only allowing specific functions (like `autocomplete`) and objects without function members to be imported dynamically.
