### ISSUE TITLE
sorry lol

### ISSUE THREAD

**Issue by peepow** [danielyxie/bitburner#2305]
nevermind ab my last bug report i did ctrl+b to save and close script but it's ctrl+cmnd+s now lol
<img width="158" alt="mystery meat" src="https://user-images.githubusercontent.com/97028539/147942251-397d5c88-4e89-4d1a-b3ac-d60d5778c087.png">

**Comment by theit8514** [comment]
Please close the previous issue instead of opening another one. Thanks!

![image](https://user-images.githubusercontent.com/1175401/147946348-b4673e04-2852-4613-962c-ab64c4cc6f2e.png)
