### ISSUE TITLE
Incorrect server security increase on hack?

### ISSUE THREAD

**Issue by void-spark** [danielyxie/bitburner#2307]
I noticed in testing the outcomes of hacks that something seemed off in how much server security increases.

First up, some assumptions, if these aren't correct, my bug report is also invalid:
- Hacking takes a percent of the available money on the server.
- This percentage scales linearly with amount of threads, so if one thread steals 5%, 10 threads steal 50%.
This seems to match the code: ```let moneyDrained = Math.floor(server.moneyAvailable * percentHacked) * threads;```
(https://github.com/daanflore/bitburner-1/blob/4fb1dbf2e3ea8a83a569eee5cf8d5e3522dbd7c8/src/NetscriptFunctions.ts#L361)
- Based on the above, it would make sense that  the maximum amount of threads needed, would be the amount of threads needed to steal 100%, regardless of available money on the server.

But if I look at the code to determine the maximum threads needed, it's quite different:
```let maxThreadNeeded = Math.ceil((1 / percentHacked) * (server.moneyAvailable / server.moneyMax));```
(https://github.com/daanflore/bitburner-1/blob/4fb1dbf2e3ea8a83a569eee5cf8d5e3522dbd7c8/src/NetscriptFunctions.ts#L355)

Instead of what I would have expected:
```let maxThreadNeeded = Math.ceil(1 / percentHacked);``` (how many threads needed to steal 100%)

As a result maxThreadNeeded becomes lower then it should be if there is less money available on the server.
Since maxThreadNeeded is (only) used to calculate the security increase, the increase is lower then it should be.

I guess it could be intended as a game mechanic so that there's less security increase if less money is gained, but the variable names don't suggest that was intended, and the math doesn't hold up very well either:
```let maxThreadNeeded = Math.ceil((1 / percentHacked) * (server.moneyAvailable / server.moneyMax));```
gives us the threads needed to hack 100%, multiplied by the fraction of max money available.
Sounds reasonable, but it's a upper limit that's calculated, the use is:
``` server.fortify(CONSTANTS.ServerFortifyAmount * Math.min(threads, maxThreadNeeded));```
If I allocate the thread count needed to steal half available money, and the available money is half the max, this compensation would have no effect, since both threads and maxThreadNeeded are the same value.

If the aim really was to give less security increase, if there was less money available, then better would be:
``` server.fortify(CONSTANTS.ServerFortifyAmount * Math.min(threads, maxThreadNeeded) *  (server.moneyAvailable / server.moneyMax));```

With:
```let maxThreadNeeded = Math.ceil(1 / percentHacked);```

Hope this makes sense, it easily gets complicated :)
Thanks!

**Comment by zeddrak** [comment]
may be related to #2454

**Comment by zeddrak** [comment]
PercentMoneyHacked = % of available money stolen with 1 hack thread.
So, maxThreadNeeded should be the number of threads needed to reach 100% hack amt (or 1/percentHacked, as you say)
There's no reason to involve MaxMoney at all...
