### ISSUE TITLE
Keyboard mappings and game play.

### ISSUE THREAD

**Issue by roysta** [danielyxie/bitburner#2308]
Bitburner v1.2.0 (4fb1dbf2) - Windows 10 - Steam

The script editing screen has changed the way it captures input.
The mapping for ctrl/cmd + s and ctrl/cmd + b now seem to capture the physical keycode and not the intended character.
The issue for me is that I use a dvorak layout on a qwerty keyboard.
 - The qwerty b and the dvorak x use the same key; no more using ctrl - x to cut text in a script file because it closes the editor.
 is it possible to make these keys configurable?

**Comment by prayforwinter** [comment]
I also use the Dvorak keyboard and can report that this wasn't an issue before the previous release.

**Comment by Master-Guy** [comment]
`charCode` and `keyCode` are deprecated and should be replaced with `.key`
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#browser_compatibility

A table with all keyCodes is listed here:
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

They should be replaced with the key strings found here:
https://www.w3.org/TR/uievents-key/#key-string
