### ISSUE TITLE
Corporations, product price is stuck

### ISSUE THREAD

**Issue by Almabali** [danielyxie/bitburner#2311]
For all industries that have Product, the cost and sell price of them is not depending on the ratings they have (e.g. no reason to put in a lot of money for better products....)
IT seems like the first product's rating determines all the rest's cost and sell price.

Just adding a new product won't change prices.
Removing (discontinuing) ALL products of the industry and creating a new one will set a new price.
![image](https://user-images.githubusercontent.com/23095683/147935071-3ab1a314-94d7-403b-a61e-895fee52c3a7.png)

**Comment by phyzical** [comment]
i think this is closable,

when i add more funds it increases the rating and thus the sale cost.

i think the users issue here is that they dont have enough in business
