### ISSUE TITLE
Apostrophes in Contract filenames causes issue with RUN command

### ISSUE THREAD

**Issue by Duguall** [danielyxie/bitburner#2314]
Ran across a coding contract named: 
`contract-179472-Joe'sGuns.cct`

using this as part of the terminal command `run` causes it to extend the ' string to the end of the line and combining all arguments afterwards until next '
ie:
`run primefactors.js  contract-179472-Joe'sGuns.cct n00dles` will return args:
`["contract-179472-Joe'sGuns.cct n00dles"]`

`run primefactors.js  contract-179472-Joe''sGuns.cct n00dles` will return args: (isolating problem)
`["contract-179472-Joe''sGuns.cct, n00dles"]`

`run primefactors.js  contract-179472-JoesGuns.cct n00dles` will return args: (recommended solution remove ' from contract namegen)
`["contract-179472-JoesGuns.cct, n00dles"]`

`run primefactors.js  contract-179472-Joe\'sGuns.cct n00dles` will return args: (alternative solution, backslash cancel)
`["contract-179472-Joe'sGuns.cct, n00dles"]`

`run primefactors.js  contract-179472-Joe\'sGuns.cct n00dles` will return args: ( what backslash currently returns)
`["contract-179472-Joe\\'sGuns.cct n00dles"]`

Console debug:
`|DELIMITER|home|DELIMITER|primefactor.js|DELIMITER|codingcontract.getData: Cannot find contract 'contract-179472-Joe'sGuns.cct n00dles' on server 'home'<br><br>Stack:<br>primefactor.js:L4@Module.main`

**Comment by nickofolas** [comment]
It should work fine when surrounding the filename with quotes when calling the script, i.e. `run primeFactors.js "contract-179472-Joe'sGuns.cct" n00dles`.

**Comment by SirGouki** [comment]
Given that the terminal is there to simulate an actual terminal emulator, this is not a bug.  bash would not like file names with that kind of character in it either, until you escape it or quote it.  Same thing with file names that contain spaces, even in windows.

**Comment by MatthewTh0** [comment]
It's definitely annoying though as, for example, you can't write to your own home computer with apostrophes from what I've found, so my early on approach of copying the contract data using a script (to a .txt file) and naming it based on the contract's name broke only when Joe's guns contracts were found since it made an invalid file path.

**Comment by phyzical** [comment]
i agree its just terminal being terminal.

the user has any options
* copy files off to home and rename
* using "" around strings
* provide some other flag say ASP and replace that within your script to a ' before calling solve
