### ISSUE TITLE
ns.fileExists and ns.getScriptRam fail for files inside subdirectories

### ISSUE THREAD

**Issue by JayAndCatchFire** [danielyxie/bitburner#2322]
`ns.fileExists` and `ns.getScriptRam` both fail for files that exist within subdirectories.  `ns.fileExists` returns false even when the file is there according to `ls` in the terminal.  `ns.getScriptRam` returns `0`.

**Comment by SlyCedix** [comment]
are you calling the functions with their absolute paths starting at the root?

`ns.fileExists('/path/to/file.js')`

**Comment by JayAndCatchFire** [comment]
Ah, no, I wasn't.  I tried with `~/path/to/file.ns`, but I didn't realize that the home directory is the same as the root directory.  So `/path/to/file.ns` works where I'd expect `~/path/to/file.ns` to also work.  :+1:
