### ISSUE TITLE
UI Very slow to update after steam upgrade to v1.2.0

### ISSUE THREAD

**Issue by emilekberg** [danielyxie/bitburner#2323]
The other day my steam version upgraded and since the UI is very slow to update. It seems to update every 5 second or so. this goes for all income, scripts running etc as well. 

clicking to open details about a server in the active script tab takes about 2-3 seconds generally. it was not like this before steam updated the version. It's running v1.2.0

**Comment by emilekberg** [comment]
Actually, it seems to be related to the active scripts tab. it only occurs if i have this open. If i go to any other tab, script activities and income flow as normal.

**Comment by phyzical** [comment]
closable as without a gamefile sort of impossible to reproduce
