### ISSUE TITLE
Changes to grandchild scripts do not cause grandparent scripts to recompile / rehash file blobs

### ISSUE THREAD

**Issue by smolgumball** [danielyxie/bitburner#2336]
Reproduction details here:
https://gist.github.com/smolgumball/cae45f9b71906ed81c50151243d5bfb0

1. Place all files in `/bug__stuck-blobs/` in game
2. `run /bug__stuck-blobs/entry.js`
3. Note UUID and ghost emoji
4. Modify `/bug__stuck-blobs/deepDep.js` to remove ghost emoji prepended to UUID
5. Re-run `/bug__stuck-blobs/entry.js`
6. Note that ghost emoji is still present

It seems that updates to `/bug__stuck-blobs/deepDep.js` are not being considered since intermediary `/bug__stuck-blobs/dep.js` file has not been modified.

cc @theit8514 due to your recent involvement w/ hashing + blob caching

**Comment by smolgumball** [comment]
@theit8514 Checking in on this since these issues began after [your commits re: caching file blobs](https://github.com/danielyxie/bitburner/pull/2172); wondering if we can revert or add some kind of option to disable while a fix is in flight?

Other folks are reporting as well:
#2408
#2413
#2560

**Comment by theit8514** [comment]
I have been testing this change but have not had a chance to clean it up and create the PR. I have had no issues with regression so far on this commit and it recompiles the dependency tree on save of a script file. The middle script (parent) will be forcibly evicted from the cache as the blob url changes for the grandparent script. 

https://github.com/danielyxie/bitburner/compare/dev...theit8514:grandparent-script-cache?expand=1
