### ISSUE TITLE
Being able to export/import scripts as/from actual files to make it easier to share them

### ISSUE THREAD

**Issue by Lauriichan** [danielyxie/bitburner#2340]
Currently I can't see a option to export script files from the game as an actual for example "script.ns" file.
If there is one please tell me and I'll close this issue.

So I'm currently sharing about 20 scripts for Bitburner with friends and updating them is quite a lot of work. As far as I know you currently can only open the script in Bitburner, copy the content, paste it somewhere else. I think it would be a lot easier if you would have like a "Export All Scripts" button to easily export each script file that is on your home server in the root directory into a folder on your computer.

Like that maintaining for example a git repository with scripts would be a lot easier.
Just change everything you need in the editor and afterwards click on that "Export All Scripts" button and select the folder you want to export it to.

The same would go for importing them, a "Import Scripts" button somewhere, select a folder or just a script file and then it imports it root directory of the home server.

As example the button could be located in the Options menu where the Game Import and Game Export button is.

**Comment by hydroflame** [comment]
download * 

and vscode

**Comment by Lauriichan** [comment]
I actually struggle setting up all of that
And would prefer to use the ingame editor instead of needing to use an external editor.
I never used TypeScript / NPM and such things before and having to install and use such things just to get autocomplete and stuff to **share scripts more easily** isn't worth the effort in my opinion.
If I would understand JS / TS more I would make a PR for such an export / import button but I wouldn't go on and learn it more deeply just to be able to share my scripts easier
