### ISSUE TITLE
Latest update made ns.getPlayer() use 30+ gb of ram

### ISSUE THREAD

**Issue by vorpalhex** [danielyxie/bitburner#2347]
Example code causing this:
```
const hostDifficulty = ns.getServerRequiredHackingLevel(host);
	if (hostDifficulty > ns.getPlayer().hacking) {
		ns.print(`Host ${host} is too difficult, skipping...`);
		return
	}
```

Images showing in-game ram estimate:

<img width="603" alt="uncommented" src="https://user-images.githubusercontent.com/482903/148153406-95a9bdb2-14ed-49a3-b09d-2443ded065e3.PNG">
<img width="626" alt="commented" src="https://user-images.githubusercontent.com/482903/148153408-92d0702a-3e6d-4c42-9509-f9d2bd8bd409.PNG">

This was working fine before the latest update and using the expected ram amount. Game reports as `v1.2.0` on the main menu.

**Comment by hydroflame** [comment]
You have SF4.2?

**Comment by hydroflame** [comment]
Sorry, I know what the issue is.
