### ISSUE TITLE
.ns not getting copied from within .ns after Steam update

### ISSUE THREAD

**Issue by EyrkkiSkye** [danielyxie/bitburner#2351]
Have a script that runs and copies over a set of .ns to each server I have root access to, but suddenly since I updated in steam they won't copy over via the script anymore. I can manually use the scp command, but for some reason it's not working coming from a script.

I manually copied one over and re-ran my script, and the log says that it was overwritten, but now there's a large blank space.

Just went back to an old save and removed the copies from n00dles and re-ran my script.. And while the log says they were copied over, when I ls in n00dles, they are not there, just a blank spot of this size>> |                        |

Using:

ns.scp('file.ns', 'hostname')

Even running it in a single instance and removing the array that's in place, and just listing a single file and manually inputting the hostname in a test script, the same issues happens.

That's what has led me to thinking that the update on steam may have messed up something, or I may have missed part of the update info if something in there mentioned a change to language/syntax. 

Using the terminal and scp commands in there to manually copy over files works fine, just seems to be trouble via script.

**Comment by EyrkkiSkye** [comment]
Changed the .ns files to .js files and things seem to run again, copying properly

**Comment by BSFishy** [comment]
I as well have a script that does something similar and am experiencing something similar. However, in my case, I am using `.js` files, and when I run it, the game freezes and I have to restart. I'll work on a minimal example so it is easier to debug.
