### ISSUE TITLE
Gang Issue: Interface Breaking Error

### ISSUE THREAD

**Issue by Playegage** [danielyxie/bitburner#2359]
In the GangOtherInfo Interface there are spaces in the names of most of the other gangs. This causes the interface to not realize that they are properties and it becomes impossible for the player to get their info using the ns.gang.getOtherGangInformation() function. Currently the function returns the object but trying to access it only allows the Tetrads and NiteSec info to be gotten. This of course makes the option of automating when to switch to territory battles much more difficult than it needs to be.

The error is found in  GangOtherInfo which is stated in the code as being an auto generated file created by API Documenter. I have copied the page and highlighted the errors below for clarity. In the interface they should use underscores instead of spaces, "Slum_Snakes", or no spaces at all, "SlumSnakes" but without knowing how these are generated I cannot say which would work better or if either would at all.

[Home](./index.md) &gt; [bitburner](./bitburner.md) &gt; [GangOtherInfo](./bitburner.gangotherinfo.md)

## GangOtherInfo interface

<b>Signature:</b>

```typescript
export interface GangOtherInfo 
```

## Properties

|  Property | Type | Description |
|  --- | --- | --- |
| --> ["**Slum Snakes**"](./bitburner.gangotherinfo._slum_snakes_.md) | [GangOtherInfoObject](./bitburner.gangotherinfoobject.md) |  |
| --> ["**Speakers for the Dead**"](./bitburner.gangotherinfo._speakers_for_the_dead_.md) | [GangOtherInfoObject](./bitburner.gangotherinfoobject.md) |  |
|  -->["**The Black Hand**"](./bitburner.gangotherinfo._the_black_hand_.md) | [GangOtherInfoObject](./bitburner.gangotherinfoobject.md) |  |
|  -->["**The Dark Army**"](./bitburner.gangotherinfo._the_dark_army_.md) | [GangOtherInfoObject](./bitburner.gangotherinfoobject.md) |  |
|  -->["**The Syndicate**"](./bitburner.gangotherinfo._the_syndicate_.md) | [GangOtherInfoObject](./bitburner.gangotherinfoobject.md) |  |
|  [NiteSec](./bitburner.gangotherinfo.nitesec.md) | [GangOtherInfoObject](./bitburner.gangotherinfoobject.md) |  |
|  [Tetrads](./bitburner.gangotherinfo.tetrads.md) | [GangOtherInfoObject](./bitburner.gangotherinfoobject.md) |  |

**Comment by SagePtr** [comment]
I see no problem here:
```
/** @param {NS} ns **/
export async function main(ns) {
	const result = ns.gang.getOtherGangInformation();
	ns.tprint(JSON.stringify(result['The Dark Army']));
}
```
Or NS1:
```
var r = gang.getOtherGangInformation();
tprint(JSON.stringify(r['The Dark Army']));
```
Print me what they should print.

**Comment by Playegage** [comment]
Oh I see, I didnt consider treating it as a json. That's on me. Thanks.
