### ISSUE TITLE
[Documentation] PDF Source-File list truncated

### ISSUE THREAD

**Issue by doug-w** [danielyxie/bitburner#2363]
The PDF docs at https://bitburner.readthedocs.io/_/downloads/en/stable/pdf/ have a table for what source files do.  It's trying to put the entire table on a single page and gets truncated instead mid way through, as of today it's cut off halfway through BN-8.

![image](https://user-images.githubusercontent.com/202737/148264582-a2688a17-49dd-43cc-8fab-314214e60009.png)

**Comment by phyzical** [comment]
in a similar vein to this one https://github.com/danielyxie/bitburner/issues/2182 closable in favor of auto docs?
