### ISSUE TITLE
Feature Request: Warn before action which will cancel in-progress company work

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2368]
When the player is working for a company in the background and attempts to start any activity which would terminate the job, e.g. training at a gym or committing a crime, the game should give a pop-up dialogue which warns the player that doing this will require ending their work session early and asks the player to confirm if they want to do that. This would be valuable because:
* Terminating a company work session early has an irreversible cost in that 1/4 or 1/2 of the already-earned reputation gain is lost
* There are many actions one can take while working, and it is not always clear _a-priori_ whether any given one will terminate your work session. (Obviously starting work with another company or faction will do so, and I've discovered experimentally that training at a gym or university or committing a crime will too, while buying a server, eating noodles, or restarting the game are safe, but I have no idea what, say, attempting an infiltration or getting healed at the hospital would do.)

A similar warning about terminating a backgrounded work session with a faction would also be nice, but is less important since there's no permanent cost to ending those early, so if the player does so by accident they can simply restart the work. However, it _would_ be nice to at least have a notification informing the player their faction work session *has* ended, so that they know to restart it.

**Comment by hydroflame** [comment]
This whole work thing has to be reworked so I'm going to close this because it will become irrelevant.
