### ISSUE TITLE
hackExp function not working on some servers

### ISSUE THREAD

**Issue by fmay95** [danielyxie/bitburner#2372]
I tried to write a script that helps me get as much Exp as possible, and wanted to finetune it with hackExp Formula. However, using hackExp on darkweb returns a runtime error:
<img width="598" alt="BBerr" src="https://user-images.githubusercontent.com/19251102/148286339-19f7cea7-a8fc-4dc1-a4fa-d46600639eb9.PNG">

**Comment by macdjord** [comment]
While the fact that you got a runtime error is definitely a bug, darkweb has a maximum money of $0, so it doesn't make much sense as a hacking target.

**Comment by fmay95** [comment]
Yes, but that’s not the topic here. HackExp should return the Exp gotten, and hacking/weakening/growing darkweb also earns you Exp. If I just want to maximize Exp, money doesn’t matter.
