### ISSUE TITLE
NeuroFlux Governor does not affect Bladerunner multipliers, despite saying it applies to ALL multipliers

### ISSUE THREAD

**Issue by MerlindlH** [danielyxie/bitburner#2375]
Hey there :) 
 Just bought NeuroFlux Governor to level 7 in BN6, because it said it "increases ALL multipliers by 1%" per level (see ![here](https://user-images.githubusercontent.com/8302493/148299840-1f589cc9-7814-41b9-8055-b218b33f6563.png)) and I hoped it would help with my Bladerunner missions.  
Afterwards, I found out this sadly doesn't hold for the Bladerunner stats (see ![here](https://user-images.githubusercontent.com/8302493/148299876-3f89534d-a729-484b-98e2-e1dc64f3fff2.png)), which was a bit unexpected.
Luckily, it still helps with the other base stats :)
 
Should be reproducible in every game instance in BN6.  Nothing special.

Thank you for your work!

**Comment by hydroflame** [comment]
Normal because it would be OP. But I understand the confusion
