### ISSUE TITLE
`ns.exit` does not exit fast enough

### ISSUE THREAD

**Issue by danielschemmel** [danielyxie/bitburner#2376]
Calling `ns.exit()` [should exit the program immediately](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.exit.md) (possibly after executing exit handlers from `ns.atExit`). It seems to me as if the exit is delayed until the next time user code releases control.

This basically means that I usually have to do `ns.exit();ns.exit();` to achieve the intended effect...

Example:
```
[home ~/]> cat test.js
/** @param {NS} ns **/
export async function main(ns) {
	ns.exit();
	if(ns.args[0]) {
		ns.tprint("This line is unreachable");
	}
	throw "This line should also be unreachable";
}
[home ~/]> run test.js "safety net"
Running script with 1 thread(s), pid 1 and args: ["safety net"].
[home ~/]> run test.js 
Running script with 1 thread(s), pid 2 and args: [].
RUNTIME ERROR
test.js@home

This line should also be unreachable
```

**Comment by rune0018** [comment]
async sometimes use real parallel threads on your pc in order to run faster so because you didnt await it will act unpredictable

**Comment by danielschemmel** [comment]
Sure, that may be the reason for the current behavior, but an `exit` function should still perform whatever is necessary to actually exit.
