### ISSUE TITLE
Bladerunners (BN6) do not collect regular passive reputation for ANY faction

### ISSUE THREAD

**Issue by MerlindlH** [danielyxie/bitburner#2377]
I'm currently in BN6 and just realized that I cannot earn passive reputation for ANY faction (not just for the Bladerunners), despite their information text saying so, e.g. the one in Volhaven:
![this image of the Volhaven faction screen](https://user-images.githubusercontent.com/8302493/148304055-4f4359e1-9085-4b35-9d8e-e3f112dfe01d.png) 
In previous BitNodes, the passive gain did work though (but I do not recall whether it ever did in BN6 for me)

Maybe I did miss some information along the way, but the BN6 description text didn't state anything in this direction, e.g. compared to the one in BN2 which did explicitly state such a mechanism. The absence of this feature is bit sad, since other factions also have useful Augmentations for Bladerunners (e.g. for combat stats)

Here my savefile [save file](https://github.com/danielyxie/bitburner/files/7818370/bitburnerSave_1641425039_noPassiveReputationReport.zip)

Thanks in advance :)

**Comment by BrianLDev** [comment]
I ran into this problem today as well.

**Comment by BrianLDev** [comment]
I just submitted a PR to fix this one.  As soon as it's accepted we can mark it closed.

**Comment by phyzical** [comment]
@BrianLDev btw you can add "fixes #ISSUE_NUMBER" in the pr description and github does magic to link them :)
