### ISSUE TITLE
[UI Bug] Moving window titlebar out of view

### ISSUE THREAD

**Issue by poi2poi** [danielyxie/bitburner#2379]
hey have a little UI bug.. i always manage to move my log windows so far to the top of the screen that the titlebar gets hidden and I can't move or close them anymore. Would be great to fix that!

thanks for the good work

**Comment by Marthgun** [comment]
#2263 
I have the same problem and posted about it. It should at least either be stopped prior to the toolbar or be drawn on top of it.

**Comment by zeddrak** [comment]
That is a desired feature by many, so it persists.
To recover the lost windows, zoom out, move it, zoom in.
Apparently a lot of people see this as a feature.
