### ISSUE TITLE
Use powers of 1024 for memory amounts

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2383]
When displaying larger amounts of memory, it appears prefixes are being calculated as if they were powers of 1000 rather than 1024. E.g.:
```
[pserv-m20-00 ~/]> free
Total:       1.05PB
Used:      210.63TB (20.09%)
Available: 837.95TB
```
'pserv' means this is a purchased server, and 'm20' means it has 2^20 GB of ram, i.e. exactly 1 PiB.

**Comment by hydroflame** [comment]
Yeah and if it was the other way around someone would file the reverse bug
