### ISSUE TITLE
Display cost & rep requirement for augs even if prereq not yet met

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2384]
Currently, if you cannot buy an aug yet because you down own its prereq, its cost and required faction reputation are hidden. You can get an upper & lower bound on these values by sorting the list by those values, and the values don't change, so the gameplay value added by hiding them is minimal, but not having the exact values makes it annoying to try to plan out how much money and rep you need before your next reset.

**Comment by phyzical** [comment]
this has either been resolved or there is a miss understanding. this is all possible now.

`getAugmentationRepReq`
`getAugmentationPrice`
`getAugmentationRepReq`

**Comment by macdjord** [comment]
@phyzical:

- I'm aware there are script functions which can get this information; I'm talking about what information the GUI of the 'Purchase Augmentations' screen displays
- Those are Singularity functions, so they're not available until you unlock them in BN-4

**Comment by phyzical** [comment]
fair enough,

but the ui it does show prereqs on a per faction basis on the purchase augmentations screens.

and that is correct they are singularilty functions to reward payers to do that bitnode, automating the game isnt meant to be an option its meant to be part of the progression of the overall game.
