### ISSUE TITLE
Faction security work & field work stat effects do not match descriptions

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2387]
- The description for 'Field work' says: "Your effectiveness [...] is based on all of your stats. You will gain exp for all stats."
- The description for 'Security work' says: "Your effectiveness [...] is based on your combat stats. You will gain exp for all combat stats."
- Currently, I have 3221 Hack, 450 Cha, and 133 to 171 for my combat stats

My expectations, based on this:
- I will gain faction rep faster from field work than security work, since my combat stats are the lowest of my stats
- From field work I will gain exp in all stats; from security work I will gain combat stats but not Hack or Cha
- In all stats where security work gives me exp, it will give me more than field work does to compensate for not giving as many different types.

Instead, working for Volhaven I observed the following:
- From field work:
  ```text
  94.076 (8.111 / sec) reputation for this faction
  
  42.158 (3.634 / sec) hacking exp
  
  15.792 (1.361 / sec) strength exp
  15.792 (1.361 / sec) defense exp
  15.792 (1.361 / sec) dexterity exp
  15.792 (1.361 / sec) agility exp
  
  13.160 (1.135 / sec) charisma exp
  ```
- From security work:
  ```text
  97.625 (8.876 / sec) reputation for this faction
  
  19.989 (1.817 / sec) hacking exp
  
  22.463 (2.042 / sec) strength exp
  22.463 (2.042 / sec) defense exp
  22.463 (2.042 / sec) dexterity exp
  22.463 (2.042 / sec) agility exp
  ```
I.e. security work is giving me *more* faction rep than field, and also giving me Hack exp when it shouldn't be. Also, while its giving more combat exp, its giving *less* Hack exp than field.

**Comment by Undeemiss** [comment]
I don't understand what the problem is here, beyond that security work should be listed as giving a little bit of hacking exp. It never made any claims about the scaling of these actions; my understanding is that field work intentionally scales worse than security work because it's easier to gain stats in general than specifically to gain physical stats.
