### ISSUE TITLE
Request(/Bug?): Documentation on how offline earnings is inherited between processes

### ISSUE THREAD

**Issue by Knyffen** [danielyxie/bitburner#2389]
My current hacking setup works in three layers:
1. A top level process that determines which servers are most profitable to hack. Runs on home. Dynamically spawns/kills hacking handlers.
2. A hacking handler. Runs on home. It is given a server to manage as an argument and then it automatically calls actual hacking processes on various servers.
3. The actual hacking process. Only runs the `ns.hackServer`/`ns.growServer`/`ns.weakenServer` commands.

I have noticed that whenever a layer 3. processes finish (by reaching the end of the function), the layer 2. process that started it has an increase in earnings and experience. However, when the layer 2 process ends (either via `ns.exit`, `return`, or when another process kills it with `ns.kill`), the layer 1 process remains at zero earnings and zero experience.

This behavior prevents me from having any substantial offline earnings.

I am currently using the steam version on windows, but it should be platform-agnostic.

I don't know if it is a bug, as it might very well just be that there is an undocumented requirement for when earnings and experience is inherited between processes. My request is therefore for that requirement to be documented. If it turns out to be a bug, tell me, and I will prepare a MWE script.

Thank you for your time. :-)

**Comment by phyzical** [comment]
is this not valid? layer 1 doesnt do any actions and thus earns nothing

unless we expect these sort of stats to trickle up? 
higher powers question

**Comment by Knyffen** [comment]
The layer 2 process doesn't do any actions either, yet when the layer 3 process finishes the layer 2 process inherits its earnings/hour number.

Just to be clear: I don't know how its _supposed_ to work (which is the entire point of the ticket), but I have just noticed the inconsistency in that the layer 2 process inherits the earnings of the layer 3 process (once it finishes), yet the layer 1 process doesn't inherit the earnings of the layer 2 process.

Personally, I think it makes sense to have the stats trickle up, since it allows the player to write more modular (often cleaner) scripts without being punished by having practically no offline earnings.

**Comment by phyzical** [comment]
ah yep the fact it trickles up one layer, i agree it should probably bubble up all the way and is probably a bug, thanks or the reply.

**Comment by phyzical** [comment]
@Knyffen so i had a look at exit and kill, and it looks like they just simply don't return the result rather just do.

i have a fix for this but i was wondering if you could provide some simple replication scripts?

**Comment by phyzical** [comment]
@Knyffen quick one where is the "total earnings per script actually found" having a hard time finding the right place to workout how it works

**Comment by Snarling** [comment]
It looks like this was fixed during one of the major edits to launching scripts. Here is a test script and test output I used to verify:

```js
//testLayers.js
/** @param {NS} ns */
export async function main(ns) {
	const layer = ns.args[0] || 1;
	const lastLayer = layer === 5;
	ns.tprintf(`${"  ".repeat(layer - 1)}Started layer ${layer}.`)
	if (!lastLayer) ns.run("testLayers.js", 1, layer + 1);

	// Hack n00dles until it is successful, but only for the last layer.
	if (lastLayer) while (!await ns.hack("n00dles"));

	// Wait until this script has some profit. Then print this script's income and exit.
	let profit;
	while (!profit) await ns.asleep(1000).then(() => profit = ns.getRunningScript().onlineMoneyMade);

	// Print script profit, then exit after 1s.
	ns.tprintf(`${"  ".repeat(layer - 1)}Layer ${layer} detected profit of \$${profit}`);
	await ns.asleep(1000);
}
```

```
[03:57:32] [foodnstuff ~/]> run testLayers.js 
[03:57:32] Running script with 1 thread(s), pid 66 and args: [].
[03:57:32] Started layer 1.
[03:57:32]   Started layer 2.
[03:57:32]     Started layer 3.
[03:57:32]       Started layer 4.
[03:57:32]         Started layer 5.
[03:59:11]         Layer 5 detected profit of $287
[03:59:12]       Layer 4 detected profit of $287
[03:59:14]     Layer 3 detected profit of $287
[03:59:16]   Layer 2 detected profit of $287
[03:59:18] Layer 1 detected profit of $287
```
