### ISSUE TITLE
`atExit` does not execute properly if script is killed during `sleep`

### ISSUE THREAD

**Issue by timotheeandres** [danielyxie/bitburner#2391]
When killing a script that was awaiting on `ns.sleep`, the `atExit` function cannot be called properly. Am I doing something wrong, or is this a bug?

Steps to reproduce:
1. Run the following script:
    ```Javascript
    /** @param {NS} ns **/
    export async function main(ns) {
        ns.atExit(() => ns.tprint(ns.ls("home")));
    
        await ns.sleep(1000 * 60);  // Kill process during the sleep
    }
    ```
2. Kill the script during its sleep

Expected behaviour:
See the content of home printed in the CLI

Actual behaviour:
Nothing is printed, error is raised:
![image](https://user-images.githubusercontent.com/25198539/148351917-c2455cfe-76d8-4f6d-93f9-8063313b833d.png)

**Comment by Domanoc** [comment]
It works when using `ns.asleep`

```javascript
/** @param {NS} ns **/
export async function main(ns) {
    ns.atExit(() => ns.tprint(ns.ls("home")));

    await ns.sleep(1000 * 60);  // Kill process during the sleep
}
```

guessing it has to do with the blocking nature of `ns.sleep`

**Comment by timotheeandres** [comment]
I see... Thanks for the tip! However, I feel like this is still a bug, since `atExit` cannot be properly used if the script contains `sleep`

**Comment by Domanoc** [comment]
I can reproduce the same error with `ns.exit()` to close the script.

```javascript
/** @param {NS} ns **/
export async function main(ns) {
    ns.atExit(() => ns.tprint(ns.ls("home")));

    ns.exit();
}
```

**Comment by jacktose** [comment]
It seems like the problem is simpler: `ns.atExit(f)` fails if `f()` calls any `ns` function. Is that true, or do I have a different problem?
(If that's true, what use is `atExit`?)

I can replicate it with just:
```javascript
export async function main(ns) {
    ns.atExit(() => ns.tprint('foo'));
}
```
or for that matter:
```javascript
export async function main(ns) {
    ns.atExit(ns.tprint);
}
```

**Comment by phyzical** [comment]
i think its more the fact of needing ns inside another "script"  though i could be incorrect with this thinking, rather the was atExit calls the passed function
