### ISSUE TITLE
Add option to run command to open started script's logs

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2393]
Add a command-line option - I suggest '-f' for 'follow' - which can be passed to the `run` command on the terminal which causes the logs for the script which run starts to be immediately opened, as if the `run` command were immediately followed by a `tail` command, e.g.:
```text
> run -f foo.ns bar baz zip
```
Is equivalent to:
```text
> run foo.ns bar baz zip ; tail foo.ns bar baz zip
```

**Comment by Kebap** [comment]
already added, as there is `--tail` option already, but it's not mentioned in `help run`
