### ISSUE TITLE
tprint tprintf and percent signs

### ISSUE THREAD

**Issue by Kebap** [danielyxie/bitburner#2399]
```js
/** @param {NS} ns **/
export async function main(ns) {
    ns.tprint("10%");   // --> 10%
//  ns.tprintf("10%");  // unexpected token error!
// however
    ns.tprintf("10%%"); // --> 10%
    ns.tprint("10%%");  // --> 10%%
}
```

Same input should have same output.

Related: https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?redirectedfrom=MSDN&view=msvc-170

**Comment by hydroflame** [comment]
Normal, tprintf takes in a string to format

**Comment by Kebap** [comment]
> Normal, tprintf takes in a string to format

Fair enough, only that format is explained nowhere
