### ISSUE TITLE
Crime functions too much RAM cost

### ISSUE THREAD

**Issue by Leorias** [danielyxie/bitburner#2400]
Somehow my script requires 161 GB of Ram. I would suspect that it requires much less than that.
Each of the Crime functions (commitCrimes, getCrimeChance) have Ram cost of 5 GB in their description but when I implement them my RAM cost rises by 80 GB.

/** @param {NS} ns **/
export async function main(ns) {
	var crimes = ["Shoplift", "Rob store", "Mug someone", "Larcency"]
	while (true) {
		for (let i = 0; i < crimes.length; i++) {
			if (ns.getCrimeChance(crimes[i]) == 100) {
				ns.commitCrime(crimes[i])
			}
		}
	}
}
![image](https://user-images.githubusercontent.com/84665910/148411105-2428bf03-807c-47e6-b69a-73f2c1b3cf6c.png)

**Comment by hydroflame** [comment]
Expected with the SF4 changes
