### ISSUE TITLE
Feature Request: EXPORT keyword for Corporation sales

### ISSUE THREAD

**Issue by tkprocat** [danielyxie/bitburner#2402]
Since Sales happends before Exports, having a material like Water setup to sell for MAX (or PROD in some cases) prevents the material from being exported since they're all gone. 

So either Exports needs to happen before Sales or a quick workaround would be to add an "EXPORT" keyword that sums up all exports and you'll be able to to MAX-EXPORT for sales amount.

I can try and make a pull request if the last option is alright.

**Comment by phyzical** [comment]
i think the issue with making exports before sales is that users live right on the edge of max storage, so if we did exports before sales we would end up with issues in the inverse direction
