### ISSUE TITLE
"Amount of RAM" should have a unit

### ISSUE THREAD

**Issue by aposp** [danielyxie/bitburner#2403]
Maybe this has already been discussed, but I've noticed several places in the documentation (`getPurchasedServerCost()`, `purchaseServer()`) where it is unclear how much the `ram` argument is. I don't think it's obvious beyond a doubt that the unit is GB as opposed to bytes, for instance.

**Comment by SirGouki** [comment]
It's in GB, and it is actually fairly obvious given the output of other similar commands, and the fact that every server I've seen in the game reports in GB as the starting unit, and that even `getServerMaxMemory()` and `getServerMemoryUsed()` report in GB, even if your purchased servers/home computer have TB of ram.  Also, every command that has its RAM usage documented in the tool tip uses GB for its cost, even if its significantly lower than that (i.e. most calls which cost 0.01GB, or even the ones that cost 0.00GB like `sleep()`)

It wouldn't hurt to have one of the first things the game tells you be that "All commands referencing RAM are in GB", but it is also pretty obvious if you pay attention and play the game for around 15 minutes that that is whats going on.  you could also just print `getPurchasedServerCost(8)` and compare it to the tech shop in Sector12 for the 8GB server and see that the cost matches.

**Comment by aposp** [comment]
Why go through any of that detective work when the documentation could just state it, considering it's technical documentation. I don't buy that "you should be able to do the work to figure out the intent" is a better answer than just putting units in the documentation.

**Comment by SirGouki** [comment]
Its not detective work when its right in front of you from the moment you first open a script.
