### ISSUE TITLE
scriptKill() documentation is inconsistent

### ISSUE THREAD

**Issue by aposp** [danielyxie/bitburner#2405]
The function signature lists `scriptname` and `hostname` as required arguments, but the one example provided only has the `scriptname` argument. Is `hostname` optional or is the example incorrect?

**Comment by adalius** [comment]
Where do you see this example? The github page for it shows both args, the autocomplete/function signature popup doesn't show an example for me at all, but it does show both args in the definition...

**Comment by aposp** [comment]
Here https://bitburner.readthedocs.io/en/latest/netscript/basicfunctions/scriptKill.html

![image](https://user-images.githubusercontent.com/42613926/148634223-a2b4829c-b392-4fe7-84b9-2a7076969175.png)
