### ISSUE TITLE
Documentation Ram Cost

### ISSUE THREAD

**Issue by Muchaszewski** [danielyxie/bitburner#2411]
Since all methods in the documentation have Ram costs associated with them, I think it would be nice to have Ram directly in the list of commands.

Instead of 
<html>
<body>

Method | Description
-- | --
exec(script, host, numThreads, args) | Start another script on any server.. 

</body>
</html>

It should be
<html>
<body>

Method | Description | Ram Cost
-- | -- | --
exec(script, host, numThreads, args) | Start another script on any server.. |  1.3 GB

</body>
</html>

I think this would be nice to easily scan for "free" or "cheap" methods that can upgrade our scripts without opening every single one. Especially useful for new-comers

**Comment by hydroflame** [comment]
Documentation is autogenerated, SOL
