### ISSUE TITLE
Feature: Run netscript code directly from terminal

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2414]
I propose that a new terminal command be created which takes a single Netscript expression, evaluates it, and prints the result.

There are many items of information, and not a few operations, which are possible from scripts but have no GUI - checking the price of or buying servers of non-standard sizes, checking a server's growth rate, etc.. I often find myself writing and running one-off, single-line scratch scripts to interact with these aspects of the API. It would be nice if I could skip going to the editor and just run these script command directly from the terminal.

* The command might be named `netscript`. If we imagine Netscript as an actual scripting language, then `netscript` would be its notional interpreter, and would presumably have have something like Python & Bash's `-c` option to take its script from the command-line
  * Alternately, we could consider `run` to be the interpreter, and just add a `-c` option to it
* The execution would be restricted to a single expression - not a statement
* The expression would be evaluated as Netscript 1; none of the advantages of Netscript 2 really matter for a one-line one-off, and Netscript 1, since its already interpreted rather than being transformed and executed by the browser, is easier to restrict as described below
* None of the async functions are available - so no initiating hacks, etc.; we already have terminal commands for that - and none of the print functions would be available, since the result of the expression will be printed automatically. Also, dangerous Javascript functions such as `eval` would be disabled, to avoid abuse.
* Optional: The `netscript` command can take an option `-N` or `--no-print` which suppresses printing the result of the evaluation

Examples:
```text
[home ~/]> netscript getPurchasedServerCost(Math.pow(2, 11))
280284364.79999995
[home ~/]> netscript purchaseServer('test', Math.pow(2, 11))
test
[home ~/]> netscript purchaseServer('test', Math.pow(2, 11))
test-0
[home ~/]> netscript deleteServer('test')
true
[home ~/]> netscript deleteServer('test')
false
[home ~/]> netscript --no-print deleteServer('test-0')
[home ~/]> netscript getBitNodeMultipliers().HackingLevelMultiplier
1
[home ~/]> netscript sleep(10)
[Error Dialogue: "Function `sleep()` is not available in the `netscript` command; write a script and use `run` instead"]
[home ~/]> netscript hack("n00dles")
[Error Dialogue: "Function `hack()` is not available in the `netscript` command; write a script and use `run` instead"]
[home ~/]> netscript var foo = getPurchasedServerCost(Math.pow(2, 11))
[Error Dialogue: "The `netscript` command can only evaluate an expression, not a statement; write a script and use `run` instead"]
[home ~/]> netscript while (true) {}
[Error Dialogue: "The `netscript` command can only evaluate an expression, not a statement; write a script and use `run` instead"]
[home ~/]> netscript getPurchasedServerCost(Math.pow(2, 11)); getPurchasedServerCost(Math.pow(2, 12))
280284364.79999995
Command getPurchasedServerCost(Math.pow(2, not found
```

**Comment by SirGouki** [comment]
I agree, however you can implement this yourself to some extent:

```js
//in main
eval(args[0]); //evaluates javascript in a string passed in as an argument.  this is JavaScript NOT netscript
```

I don't know how many commands work in this though, because of the game refusing to do certain things with this command, yet encouraging it for something else.  

you'd use that script like this (notice the differing quotes, this would be a requirement):
`run parser.js "ns.tprint('Hello, world');"`
