### ISSUE TITLE
Incorrect detection of RAM cost of scripts

### ISSUE THREAD

**Issue by MRGRD56** [danielyxie/bitburner#2426]
Steps to reproduce:
1. Open new JS file with `nano` and paste the following code:
```js
/** @param {NS} ns **/
export async function main(ns) {
    const path = 'https://example.com/path/to/file.js';
    const fileName = /.*\/(.*)$/.exec(path)?.[1];
}
```
The script requires **2.90 GB** of RAM.

2. Remove or comment the following line:
```js
const fileName = /.*\/(.*)$/.exec(path)?.[1];
```
Now we have:
```js
/** @param {NS} ns **/
export async function main(ns) {
    const path = 'https://example.com/path/to/file.js';
    //const fileName = /.*\/(.*)$/.exec(path)?.[1];
}
```
Now the script requires **1.60 GB** of RAM.  
Consequently, `RegExp.exec` call costs 1.3 GB of RAM, although I suppose it shouldn't.

3. Replace that line with the following:
```js
const fileName = (/.*\/(.*)$/)['exec'](path)?.[1];
```
The script still requires **1.60 GB**, even though it does the same thing as in step 1

**Comment by c-goldschmidt** [comment]
Looks pretty intentional, some default js functions just seem to come at a cost (i.e. document.getElementById seems to cost around 10GB).

Note that you could technically also circumvent other ram costs via `ns['hack']()`, but the game will definitely detect that during dynamic ram analysis and present you with an error dialog. If it does that for this script too, i suppose it's intentional.

**Comment by MRGRD56** [comment]
```js
/** @param {NS} ns **/
export async function main(ns) {
	const path = 'https://example.com/path/to/file.js';
	const fileName = (/.*\/(.*)$/)['exec'](path)[1]; //1.30 GB
	const hostname = ns.getHostname(); //0.05 GB

	const scriptName = ns.getScriptName();
	const ram = ns.getScriptRam(scriptName); //0.01 GB
	ns.tprint(ram);
}
```

I run this script and I don't get any error dialogs. And the script requires only **1.75 GB** to run. Also, no errors occur when I run it with:
```js
...
	const fileName = (/.*\/(.*)$/).exec(path)[1]; //1.30 GB
...
```
And the script consumes **3.05 GB**.

But when I run something like this:
```js
/** @param {NS} ns **/
export async function main(ns) {
	const scriptName = ns.getScriptName();
	const ram = ns['getScriptRam'](scriptName); //0.01 GB
	ns.tprint(ram);
}
```
I get the error you've described.

**Comment by ballardrog** [comment]
Another example that comes up is when using Maps.

repro.js:
```javascript
/** @param {NS} ns **/
export async function main(ns) {
	new Map().get("foo");
}
```

`mem repro.js` prints:
```
This script requires 3.60GiB of RAM to run for 1 thread(s)
 2.00GiB | stanek.get (fn)
 1.60GiB | baseCost (misc)
```

**Comment by hydroflame** [comment]
We know but it's insanely hard to fix.

**Comment by archowl** [comment]
I too was annoyed by this, so I fixed it in my fork: https://github.com/archowl/bitburner/tree/static_alt. Sadly, hydroflame wasn't interested in the fix, so it requires running the game from source and cherry-picking the patches locally.
