### ISSUE TITLE
Invalid stock symbol passed into getStockPrice()

### ISSUE THREAD

**Issue by rharvest** [danielyxie/bitburner#243]
Specifically, scripts error when passing **FLCM** to getStockPrice(). I checked, all other stocks passed OK. Bug is repeatable.

Update: I've tested getStockPosition() with **FLCM** and received the same error - literally "Invalid stock symbol passed into getStockPrice()". Note, getStockPrice() when I was using the getStockPosition() function. It appears you've duplicated the error text from getStockPrice() in the getStockPosition() function.

Thought: Is it possible that the recent typo fix to Fulcrum Technologies is causing a mismatch in my existing game? Maybe when I ascend and rebuy WSE/TIX it will remap **FLCM** to the corrected spelling.

**Comment by danielyxie** [comment]
> Is it possible that the recent typo fix to Fulcrum Technologies is causing a mismatch in my existing game? Maybe when I ascend and rebuy WSE/TIX it will remap FLCM to the corrected spelling.

Yeah...great catch. Didn't even think of this when I fixed the typo. It should be fixed the next time the Stock market gets reset (installing Augs). Let me know if not

**Comment by rharvest** [comment]
Problem indeed resolved after installing augmentations. I've made a PR for the error in the throw as well if you've not already amended it.
