### ISSUE TITLE
Negative time/money and loss progress exercising 

### ISSUE THREAD

**Issue by Tavofn** [danielyxie/bitburner#2430]
I was idle for a while at the gym and I came back with my save reverting back to last import save, unable to leave gym, and negative time and money? Is this new?

![bit2](https://user-images.githubusercontent.com/29978587/148560051-47cfab91-7f36-45bc-85c9-dc00251a4c7a.PNG)

**Comment by hydroflame** [comment]
Did your clock reset?

**Comment by Tavofn** [comment]
Now that I recall, yes I adjusted the clock recently, thank you
