### ISSUE TITLE
Feature: Add a function to get the players current money per second

### ISSUE THREAD

**Issue by Playegage** [danielyxie/bitburner#2434]
I believe that a useful function to add would be one that allows the player to get their current money per second earned by the combination of all money making methods such as scripts, nodes, servers, gan, ect. It would probably work best as a Singularity function since the use I thought of for it would be in the case of training at the gym or university and stopping if your money per second drops below the desired amount.

**Comment by Eugney** [comment]
You can make a script to do this

**Comment by Playegage** [comment]
You may be able to to get the script income with getScriptIncome() but I cant find a way to get the income from the gang with a command.

**Comment by Eugney** [comment]
getGangInformation(): GangGenInfo; moneyGainRate

**Comment by Playegage** [comment]
It wasn't showing up when i typed it in. Thanks.
