### ISSUE TITLE
Tutorial gets stuck after the first script if you hit back

### ISSUE THREAD

**Issue by jjspace** [danielyxie/bitburner#2442]
I created and saved the first script but then I wanted to go back a tutorial step to read it again but got stuck as there is no longer a forward button on the tutorial prompts and it doesn't count the `nano` command as part of the tutorial anymore.

![2022-01-07_15-39](https://user-images.githubusercontent.com/8007967/148604925-11435ac4-6fe6-426c-9272-135e56f4634c.png)

**Comment by OneOfMany07** [comment]
Still broken today.  Also tutorial seemed to jump steps on me (hence my need to press the back button and get stuck).

When told to create the first script it said to press ctrl-s then ctrl-b (to save then exit nano).  After ctrl-s it saved and closed the app, then the next step of the tutorial was to run "free" on n00dles.  But it'd made me "home" to create my script initially, so I wasn't on that server.  And the terminal wouldn't let me "connect n00dles" to fix my state to match the tutorial's expectations "Bad command.  Please follow the tutorial" is all I get now.
