### ISSUE TITLE
n00dles might not be 16GB RAM

### ISSUE THREAD

**Issue by fddemora** [danielyxie/bitburner#2444]
![n00dles](https://user-images.githubusercontent.com/58346374/148608020-65218e13-958e-4a4d-adec-913f7471125f.PNG)
https://bitburner.readthedocs.io/en/latest/guidesandtips/gettingstartedguideforbeginnerprogrammers.html

I would disagree here since n00dles is 4.00GB RAM. 
I'd make a pull request but I'm not sure where to find the file.

**Comment by heap-underflow** [comment]
The rst source is here: [doc/source/guidesandtips/gettingstartedguideforbeginnerprogrammers.rst](https://github.com/danielyxie/bitburner/blob/master/doc/source/guidesandtips/gettingstartedguideforbeginnerprogrammers.rst)
