### ISSUE TITLE
alt+j shows a blank screen

### ISSUE THREAD

**Issue by hlopetz** [danielyxie/bitburner#2450]
that's how it looks for me:
![image](https://user-images.githubusercontent.com/645340/148618828-495419ba-0942-4077-b77f-35d973bf312d.png)
i am a part-time employee in these companies (tbh, i have no idea for what i am)
![image](https://user-images.githubusercontent.com/645340/148619029-ee706337-1a9f-47fa-b0f7-2eb213c7a761.png)

steam version 1.3 for MacOS X

**Comment by hydroflame** [comment]
Upload save file.

**Comment by hlopetz** [comment]
[bitburnerSave_1641763757_BN1x0.json.zip](https://github.com/danielyxie/bitburner/files/7835988/bitburnerSave_1641763757_BN1x0.json.zip)
