### ISSUE TITLE
ns.fileExists gives incorrect result for some filenames

### ISSUE THREAD

**Issue by Sleaker** [danielyxie/bitburner#2455]
I created a script to check if a remote file exists on my local system and came across an odd issue:

scping "A-Green-Tomorrow.lit" to home and then calling `ns.fileExists("A-Green-Tomorrow.lit")` will return false, even though the file scp is successful. other lit files seem to work fine, but appear to be all lowercase. I've attempted to pass the file name as lower case only, but this also returns false.

**Comment by TheMas3212** [comment]
looks like its a simple case of when checking literture files the code does a toLowercase() on the filename to check but not the file being checked
```
      for (let i = 0; i < server.messages.length; ++i) {
        if (filename.toLowerCase() === server.messages[i]) {
          return true;
        }
      }
 ```
 but checking the definition of server.messages indicates it could also container an object despite being typed as a string[] so i need to double check that
 should have a pr to fix this shortly though
