### ISSUE TITLE
Hacknet node display bug

### ISSUE THREAD

**Issue by Almabali** [danielyxie/bitburner#2457]
After buying 30+ hacknet nodes quickly with a script, the hacknet node menu layout broke up a bit, in multiple places:
![image](https://user-images.githubusercontent.com/23095683/148639148-4c8df58c-71c6-4ada-9fda-7e9933387cdb.png)
![image](https://user-images.githubusercontent.com/23095683/148639171-b01d74f7-7f5b-48af-9cf3-5971a53fd1d1.png)
![image](https://user-images.githubusercontent.com/23095683/148639183-c5240a44-3caf-47aa-acb8-c00cb601ee45.png)

**Comment by Hedrauta** [comment]
🤔 
maybe set the width of the layout into a fixed width..... 🤔 
let me take a look on that <.<
