### ISSUE TITLE
Weird case of "missing main function"

### ISSUE THREAD

**Issue by c-goldschmidt** [danielyxie/bitburner#2463]
I've got a script scheduling scripts on basically all servers. For some reason i get the following error a lot:

```
RUNTIME ERROR
/net_funcs/grow.js@hack-4
Args: ["b-and-a"]

/net_funcs/grow.js cannot be run because it does not have a main function.
```

...here's the content of grow.js:
```js
/** @param {NS} ns **/
export async function main(ns) {
    const target = ns.args[0];
    await ns.grow(target, {stock: true});
}
```

the script is definitely fully uploaded to the server, as my process of uploading is:
```js
if (!serversAvailable.includes(server)) {
     await ns.scp(files, 'home', server);
     serversAvailable.push(server);
     await ns.writePort(AVAILABLE_CHANNEL, JSON.stringify(serversAvailable));
}
```
so the script scheduling runs will not try to execute anything before the necessary scripts are deployed to the service.
i also see that it just fails sometimes, kinda non-deterministically. looking at the running script also shows this script running with various parameters: 
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/16539922/148644093-5390fe88-672b-4ac2-90b8-4e9da2231f09.png">

In general this issue doesn't seem to break anything, as the scheduler picks up free ram and just tries again. it's just very annoying, because i often get a batch of these at once.

[Edit] i see that the "compile" function is asynchronous. my scheduler is using "ns.exec" quite rapidly, might be a concurrency issue?

[edit2] played around with the debugger: so `await script.module` seems to return an empty sting when this happens. `script.code` does contain the full (and valid) code.

**Comment by hydroflame** [comment]
known, duplicate

**Comment by Penumbra69** [comment]
> known, duplicate

To? Issue # or link to issue we can watch?
