### ISSUE TITLE
Modifying running scripts to invalid syntax can prompt recovery screen

### ISSUE THREAD

**Issue by MartinFournier** [danielyxie/bitburner#2466]
How to replicate:

* `nano test.script`
```js
while (true) {
    weaken("foodnstuff");
    print("Doing stuff.");
    sleep(5);
}
```
* `run test.script`
* save game
* `nano test.script`
* Add invalid syntax ie: `print("Doing stuff.";`
* save game
* reload
* get recovery screen

**Comment by phyzical** [comment]
@MartinFournier this one is closable correct?
