### ISSUE TITLE
NS: printing "undefined" shows "null"

### ISSUE THREAD

**Issue by tpajenkamp** [danielyxie/bitburner#2477]
Printing `undefined` using the `print` or `tprint` function in a script shows `null`. It would be much more helpful if it displayed the string `undefined`.

Steam version, Windows 10.

Example NS1:
```js
tail();
print(undefined);
tprint(undefined);
tprintf("%s", undefined);
```

Example NS2:
```js
/** @param {NS} ns **/
export async function main(ns) {
	ns.tail();
	ns.print(undefined);
	ns.tprint(undefined);
	ns.tprintf("%s", undefined);
}
```

Output:
```
[home ~/]> run printtest.js 
Running script with 1 thread(s), pid 703 and args: [].
printtest.js: null
undefined
```

**Comment by Xynrati** [comment]
this is presumably due to the conversions performed on objects within print/tprint and not printf/tprintf (as they accept strings + args)

**Comment by heap-underflow** [comment]
The two functions behave differently for arrays and objects as well 
```js
    let arr = [1,2,3]
    let obj = {a:'a', b:'b', one:1}

    for(let x of [arr, obj]){
        ns.tprint(x)
        ns.tprintf("%s", x)
    }
```
```
dev-print.js: [1,2,3]
1,2,3

dev-print.js: {"a":"a","b":"b","one":1}
[object Object]
```

I haven't looked at the code, but the top (`tprint`) looks like it's being passed through something like `JSON.stringify()` and the bottom (`tprintf`) is just using `.toString()`.

And `JSON.stringify()` coercing `undefined` to `null` makes sense as while `null` is defined in the JSON spec, `undefined` isn't.

I don't know whether this a bug though.  Both functions have their own uses.

**Comment by phyzical** [comment]
hmm is this even worth fixing? i guess the question is, what would changing the result of `null` to `undefined` really change.

is it that people are parsing the results of logs to do other things?

**Comment by tpajenkamp** [comment]
I cannot decide if it's worth fixing, but for me, it was a problem while debugging a script. I relied on the printed text being accurate so that I discarded possibilities that could have resulted in `undefined` instead of `null`. Now that I know of it, it is no longer an issue for me.
If `ns.print` and `ns.tprint` are not being changed, please consider documenting this behavior in their function descriptions. These functions are not suited as direct replacement of `console.log`.

**Comment by phyzical** [comment]
👍 i agree maybe some comment of "undefined" can become "null" may help new players/non devs understand the concept (something that is just part of our brain 😆 )
