### ISSUE TITLE
In game achievements not unlocked + missing icons

### ISSUE THREAD

**Issue by metalax** [danielyxie/bitburner#2480]
After the most recent update added achievements tab in-game, I received a flurry of anouncments for achievements already unlocked on Steam. However I noticed that some that are unlocked on Steam were not unlocked in-game.

Those missing.
You'll need upgrade for this one
Gains!
UNACHIEVABLE

Also, the "Free money!" achievement is missin it's icon in-game.

**Comment by SagePtr** [comment]
This issue looks resolved, should be closed
