### ISSUE TITLE
Race Condition in exec() and updateRamUsage()

### ISSUE THREAD

**Issue by theit8514** [danielyxie/bitburner#2499]
When a script is first loaded and executed, the script `compile()` process calls `script.updateRamUsage()`, which calls `script.markUpdated()` which resets the `script.module` to blank.

In certain situations this can lead to a race condition. Most notably, this causes a race condition in `exec()` which is not an async function which starts a workerScript that returns a Promise. Repeated `exec()` calls to the same script can result in multiple compiles running simultaneously, which some return this error:
```
RUNTIME ERROR
/scripts/root.js@home
Args: ["omega-net", false]

/scripts/root.js cannot be run because it does not have a main function.
```

[Save with issue occurring on startup](https://cdn.discordapp.com/attachments/415213413745164318/929662261788823602/bitburnerSave_1641718946_BN1x1.json)

The likely fix to this is to have `exec()` be async (breaking existing scripts), or have `exec()` wait briefly to return so the compile can occur. The solution for the above save is to add `await ns.sleep(1)` after the `exec()` call.

**Comment by alainbryden** [comment]
Glad it's not just me anymore :)
https://github.com/danielyxie/bitburner/issues/1714

**Comment by theit8514** [comment]
Closing as duplicate of https://github.com/danielyxie/bitburner/issues/1714. Thanks!
