### ISSUE TITLE
db is not defined

### ISSUE THREAD

**Issue by ghost** [danielyxie/bitburner#250]
Currently getting this error whenever a timer is run. This also causes the timer to stop.

[#1 - analyze](https://this.is-a-professional-domain.com/70f098.png)
[#2 - hack](https://this.is-a-professional-domain.com/6afbec.png) (includes error)

Running Firefox Nightly 60.0a1 on Arch Linux x86_64
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

```
TypeError: db is undefined
engine.bundle.js:55735:9
BitburnerSaveObject.prototype.saveGame
https://danielyxie.github.io/bitburner/dist/engine.bundle.js:55735:9
checkCounters
https://danielyxie.github.io/bitburner/dist/engine.bundle.js:7284:13
updateGame
https://danielyxie.github.io/bitburner/dist/engine.bundle.js:7240:9
idleTimer
https://danielyxie.github.io/bitburner/dist/engine.bundle.js:7175:13
```

**Comment by danielyxie** [comment]
Seems like somethings wrong with indexedDB

Did saving work before?

**Comment by bubmet** [comment]
no, it's never worked for me

**Comment by danielyxie** [comment]
Could you try updating Nightly to 62.0a1? 

I downloaded 60.0a1 to test and got a similar error (not exactly the same, but related to IndexedDB as well). I tested it on 62.0.a1 and it works fine

**Comment by bubmet** [comment]
Updated, still getting the same error with a different call stack.

```
TypeError: db is undefined engine.bundle.js:55735:9
BitburnerSaveObject.prototype.saveGame
https://danielyxie.github.io/bitburner/dist/engine.bundle.js:55735:9
init/<
https://danielyxie.github.io/bitburner/dist/engine.bundle.js:8023:13
```

**Comment by bubmet** [comment]
After checking, there's an InvalidStateError being logged:
> A mutation operation was attempted on a database that did not allow mutations.

**Comment by danielyxie** [comment]
I think that due to the issues with 60.0a1, the database was left in an unexpected state that my code can't handle. I don't know how to fix it off the top of my head but I'll look into it. 

If you don't want to wait for that, I think you can just clear the indexedDB like so:

> Options -> Privacy & Security on the left -> Manage Data under "Cookies and Side Data" -> Remove all site data for danielyxie.github.io/bladeburner

**Comment by bubmet** [comment]
Hm, that didn't help.

**Comment by danielyxie** [comment]
Could you paste or post a pic of the console errors that come up when you start a new game and try to save (by deleting indexedDB data or by deleting the save through the game's options)

**Comment by bubmet** [comment]
[Image](https://this.is-a-professional-domain.com/7ea04d.png)

**Comment by bubmet** [comment]
[Image](https://this.is-a-professional-domain.com/10e696.png)

**Comment by danielyxie** [comment]
I can't say for sure, but I believe that you have some setting that prevents you from using indexedDB (Are you in private browsing mode?)

I'll have to add something in that prevents the TypeError exception from being thrown even if indexedDB cant be opened

**Comment by hydroflame** [comment]
Too old, can't reproduce.
