### ISSUE TITLE
ns.purchaseTor() uses 32GB of RAM instead of 2GB

### ISSUE THREAD

**Issue by CoralCarl** [danielyxie/bitburner#2501]
My script RAM requirement jumps from 9.25GB to 41.25GB as soon as I put the command in. (Steam)

Edit: The same applies to purchaseProgram apparently, is the documentation just wrong? 32GB seems absurd though.

**Comment by XxKingsxX-Pinu** [comment]
Due to SF 4.1 rework, each Singularity function uses x16|x4|x1 depending on level of SF 4.x

please close issue if you can
