### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by IMASU2137** [danielyxie/bitburner#2509]
ever since i left job at foodnstuff, i can't acces the location from map. opening job tab or trying to go there displays just a black screen that goes away only when i refresh with f5

**Comment by ExNarc** [comment]
![image](https://user-images.githubusercontent.com/30580059/148779663-24685fda-bd64-4803-a596-d0cc1822a6a3.png)
I am error in this case. i left job at foodnstuff. then i click and view other location. and it happen with this error.

**Comment by hydroflame** [comment]
Fixed in latest release, if save files are still broken let me know (preferably on discord)
