### ISSUE TITLE
wget analog

### ISSUE THREAD

**Issue by norrit** [danielyxie/bitburner#251]
I saw a couple people mentioning a basic implementation of git would be great, and while I agree, I feel it would probably be very time intensive to do. I was wondering if maybe using something like the following to approximate wget, and feeding it the raw url for a github repo.

`$.get("https://raw.githubusercontent.com/danielyxie/bitburner/master/README.md", function(data){
  alert("Data: " + data);
});`

I scanned your source trying to determine how files were being managed in game with the write function. I'll probably spend a little more time on it tomorrow.

**Comment by hydroflame** [comment]
@danielyxie This is actually impossible because gist/pastebin/ghostbin don't want to cooperate with code requesting their raw content. It would require getting (and maybe paying) for a API key for each of these websites.

Should close as can't support/won't support.

**Comment by danielyxie** [comment]
Added for both Terminal and Netscript in v0.40.3 - v0.40.4.  It doesnt work with most websites due to CORS issues, but does work for a few notables ones like githubraw
