### ISSUE TITLE
Feature Request: Corporation API should expose (all) functionality that is available in the Corp UI

### ISSUE THREAD

**Issue by kriber82** [danielyxie/bitburner#2510]
When trying to transition from (tedious) manual management of my Corporation (in BN-3) to scripted management, I quickly hit several roadblocks. Most of those stem from a disparity between UI capabilities and API capabilities.

I would like to see support for the following features in the Corporation/Warehouse/Office APIs:
- bulk buy of materials (if researched for division)
- read-access to effectiveness of materials for production multiplier for a division
- reading of material buy/sell prices
- reading of material buy/sell rates
- read-access to consumed and produced materials of an industry
- function to read "production equation" for a division
- function to simply assign employees amounts to jobs like in "Auto Mode" in UI
- function to predict costs of warehouse upgrade
- function to configure which materials Smart Supply may take from warehouse
- function to enumerate divisions

The following functions have no direct pendant in the UI, but would also be helpful:
- read access to storage room per unit of material
- maybe function to read materials needed for production at full capacity (could be coupled to smart supply unlock)

**Comment by pigalot** [comment]
I have started to look at this see [discord thread](https://discord.com/channels/415207508303544321/930286146913718293/930286148444626984) for details.

**Comment by pigalot** [comment]
This should be closeable now
