### ISSUE TITLE
Feature: ns.gang function to check the new multiplier that will apply after a gang member is ascended

### ISSUE THREAD

**Issue by Playegage** [danielyxie/bitburner#2524]
What the title says. Presently you can get the current multiplier and the points but unless I am missing something you cannot get the new multiplier without ascending them first. Obviously you can look yourself but that doesn't help much when you want to have a script make them ascend when their new multiplier will be a certain number higher than the previous one.

**Comment by SagePtr** [comment]
https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.gang.getascensionresult.md

**Comment by Playegage** [comment]
Thanks, glad i was just missing it
