### ISSUE TITLE
(API Breaking Change) rename functions in stanek namespace to decrease collision with generic functions

### ISSUE THREAD

**Issue by TheMas3212** [danielyxie/bitburner#2529]
width
height
charge
clear
canPlace
place
get
remove

**Comment by phyzical** [comment]
@TheMas3212 is this still an issue?

**Comment by TheMas3212** [comment]
just double checked in a3c599e6 web version and yes it still an issue

**Comment by phyzical** [comment]
i still think we just need to fix the ram checker tbh, i got close but it broke ram usage from selective importing ;(
