### ISSUE TITLE
The doc

### ISSUE THREAD

**Issue by Developer-2021** [danielyxie/bitburner#2545]
In "Joining your first faction: CyberSec".
Connect the CSEC should be going through the foodstuff server.
![image](https://user-images.githubusercontent.com/80497194/148863248-c403274c-8558-441c-b2c0-32b37bb94c83.png)

**Comment by Knieperd** [comment]
This will show you the network for all servers that are up to 2 “nodes” away from your home computer. Remember that the network is randomly generated so it’ll look different for everyone. Here’s the relevant part of my scan-analyze results:

It is a randomly generated network, so it can be different for everyone. The doc gives Iron-Gym as an example.

Not an issue, it's intended.

**Comment by Developer-2021** [comment]
Thanks~ Knieperd
