### ISSUE TITLE
Hashnet Server Increase Maximum Money Bug

### ISSUE THREAD

**Issue by Sniffy12** [danielyxie/bitburner#2547]
Upon hitting 10 trillion dollars on the ecorp server, the gains per hash expenditure dropped from 2% down to 0.04%.  Now each purchase is adding only 4 billion dollars to the server money max instead of 200 billion.

**Comment by MartinFournier** [comment]
That's normal, there's diminishing returns once past the soft cap.

```ts
/**
 * Change this server's maximum money
 * @param n - Value by which to change the server's maximum money
 */
changeMaximumMoney(n: number): void {
  const softCap = 10e12;
  if (this.moneyMax > softCap) {
    const aboveCap = this.moneyMax - softCap;
    n = 1 + (n - 1) / Math.log(aboveCap) / Math.log(8);
  }

  this.moneyMax *= n;
}
```
