### ISSUE TITLE
Folder refactor

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#2557]
Every file in the game should match `[a-zA-Z0-9\-_](/[a-zA-Z0-9\-_])*\.(js|script|txt)`. Note the lack is leading slash in ALL files. Foldered or not.

Make a function to sanitize filename (convert // to /, remove leading slash, etc, take a look at electron.tsx)
Make another function that validates a filename (to catch weird extension and other invalid characters like spaces)
Write a save file migration that sanitizes all txt and scripts.
Make the txt and scripts array on server `private`, will narrow down everything that uses them.
Write a function called like `BaseServer.prototype.findFile` so that nothing needs read access to the private arrays

**Comment by daanflore** [comment]
Do not know if my issue is related to my "problem" in the game:
 Bug reports that I was making:
Seems like when you ns.exec command contains a script in a sub folder when you do not start it with / the system does not detect that it is already running and start the script as a new process
![image](https://user-images.githubusercontent.com/10918566/149638155-dbab59af-027e-45e8-abc3-1d90314d070e.png)


- [ ] Save file:
githubIssue-bitburnerSave_1642281820_BN1x0.txt](https://github.com/danielyxie/bitburner/files/7875918/githubIssue-bitburnerSave_1642281820_BN1x0.txt)

- [ ] Steps to reproduce:
run the script startup.js multiple times and you will see that home server runs same server multiple times

- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616):
Bitburner v1.3.0 (bab67866)


Would the new match logic prevent the problem with ns.exec I notices?
Or are they not related.

**Comment by phyzical** [comment]
@daanflore  yeah it basically is 👍 


also https://github.com/danielyxie/bitburner/issues/1935 may be related
