### ISSUE TITLE
Faction reputation not added until leaving faction screen

### ISSUE THREAD

**Issue by poi2poi** [danielyxie/bitburner#2569]
I've had been doing hacking contracts for Daedalus, after it said I've gained enough reputation, I clicked on 'Stop faction work' but the faction reputation doesn't get added until I click 'back' again to get to the factions overview, when I click Daedalus again, the reputation get's rewarded.

Imho, faction reputation should be updated as soon as I stop working.

**Comment by MartinFournier** [comment]
This should be fixed since we reverted the "previous page" feature.
