### ISSUE TITLE
Daedalus early invite

### ISSUE THREAD

**Issue by poi2poi** [danielyxie/bitburner#2571]
I've installed all Bladerunner Augs + the earliest from Daedalus, after running my hacking scripts, my Hackexp. was at around 2390 immediately, after a minute I've got an early Invite from Daedalus, before I reached Hacking Exp 2'500, so I joined and donated money for reputation. After reaching Hack Exp 2'500 I've got another invite from Daedalus, resetting my faction reputation.

**Comment by hydroflame** [comment]
Needs investigation, likely unreproducable.

**Comment by deathly809** [comment]
You can get 2500 hacking or a bunch of other stuff which explains why you got added before 2500.  But the double addition is a little funky.

```ts
    (this.hacking >= 2500 ||
      (this.strength >= 1500 && this.defense >= 1500 && this.dexterity >= 1500 && this.agility >= 1500))
```

**Comment by zeddrak** [comment]
One of these must not be getting set correctly, as they should prevent double invites.
(bitburner/src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx 
```
2127    !daedalusFac.isMember &&
2128    !daedalusFac.alreadyInvited &&
```

**Comment by poi2poi** [comment]
I don't remember that I've ever had my strength skills and so on above 100, so this can't be the reason why I've got invited

**Comment by phyzical** [comment]
hmmm @poi2poi did you mean this happened right after you installed all the bladerunner augs?

i would wager a guesssss something went wrong and the "state" was still held onto from before the augmentation or your scripts were still running and something grabbed onto an old instance that basically decided "yep he needs the invite" 

but as the main "State" knew what was up it invited you again, asif you were never invited.

(no faction rep should be carried across an augmentation install right?)
