### ISSUE TITLE
Quitting an action has no effect on player.focus

### ISSUE THREAD

**Issue by Feodoric** [danielyxie/bitburner#2577]
Unsure if this is intended or not. Cancelling an action either through the UI or with singularity `ns.stopAction()` leaves the `player.focus` flag untouched. This results in scenarios where `ns.isBusy()` returns false, but `ns.isFocused()` returns true.

**Comment by deathly809** [comment]
Not sure where UI call is located, but If you call stopAction it just returns you to the terminal, I see elsewhere that there is usually a stopFocusing before the return.

```ts
    stopAction: function (): any {
      helper.updateDynamicRam("stopAction", getRamCost(player, "stopAction"));
      helper.checkSingularityAccess("stopAction");
      if (player.isWorking) {
        if (player.focus) {
          Router.toTerminal();
        }
        const txt = player.singularityStopWork();
        workerScript.log("stopAction", () => txt);
        return true;
      }
      return false;
    },
```

**Comment by deathly809** [comment]
For the cancel button I see that the finishWork does not unset focus, for cancel or finishing after 8 hours.  All the others do, I can do a PR to fix both.

**Comment by phyzical** [comment]
i have 100% seen this behavior when i was trying to implemented optional focus to commitCrime, i just assumed it was by design tbh. most places kind of ignore it and override it anyway i.e in the singularity functions.

**Comment by Hoekstraa** [comment]
Still happens on dev as of today;
![issue shown](https://user-images.githubusercontent.com/19653491/163249245-a44e64c8-229d-4d71-9452-f8d083e1f2ea.png)
