### ISSUE TITLE
Runtime Error information easy to lose permanently

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2583]
When a script has a runtime error, the game generates a dialogue box listing the error message and traceback. However:
- Interacting with any part of the game outside this dialogue box - say, by trying to switch to the script editor to look at the line the error message references - causes the dialogue box to close without warning or confirmation
- Once the dialogue box is closed, there is AFAIK no way to reopen it or otherwise access this message

Effectively, the *only* way to debug a runtime error is to immediately copy the error message into a text file outside the game so that you can actually interact with the game in order to investigate the error, and if you accidentally close the dialogue box without doing this, your chance to debug that error is gone permanently.

**Comment by smolgumball** [comment]
Maybe bitburner could write those errors to some kind of "system_errors.txt" file in your home root?

In the mean time, if you open devtools (Debug -> Activate via Steam or F12 in Chrome) you should be able to see those logs get written to the browser console.
