### ISSUE TITLE
Softlock due to Singularity functions

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2595]
I created a script that would repeatedly commit crimes for me. However, I made a mistake in my loop conditions, causing the script to continue indefinitely. Every time it started a new crime, I would be forcibly returned to the 'crime in progress' screen; since the crime it was using was homicide, which takes 2-3s to complete, I simply didn't have enough time to cancel the crime, get to the active scripts tab, find the errant script, and kill it before being dragged back to the 'crime in progress' screen and forced to start again.

There needs to be a way to manage scripts that singularity functions can't block. A couple options off the top of my head:
- A toggle on the status pane in the upper-right corner. When this toggle is activated, all singularity functions are disabled (as if the player didn't have Sourcefile-4 unlocked
- Make the 'Active Scripts' tab an overlay, like the status pane or a script log window, which can be opened at any time and be interacted with without affecting or being affected by whatever is happening in the main window.
- Any time a singularity function changes the player's view, pop up a toast which identifies what script that was and which has a button that opens said script's log window

**Comment by macdjord** [comment]
@Ornedan Yes, that's what I ended up doing; that's why I called it a soft-lock rather than a game-breaking save-destroying bug.

**Comment by technolem** [comment]
You can add ns.tail() to your loop, that way you always have access to the kill button. By putting it in the loop it'll re-open if you accidentally close it.

**Comment by phyzical** [comment]
closable as well an infinite loop is an infinite loop

also thought i would add that i have put in a  PR to have optional focus flag to commit crime which would fix the issue

https://github.com/danielyxie/bitburner/pull/2844
