### ISSUE TITLE
If work shift finishes while offline, no reputation is added

### ISSUE THREAD

**Issue by xon52** [danielyxie/bitburner#2604]
If I begin working, do something else simultaneously, quit, and then return, the work screen is still progressing. I can then stop work and take half the rep.
If I do the same but return after 8 hours, I get nothing.

**Comment by zeddrak** [comment]
On mine, the message SAYS 0 rep is gained, but the rep was actually awarded (the corresponding faction opened up and everything)

**Comment by xon52** [comment]
Yeah, you know what, I find this pretty confusing. Now it seems to be stopping me working if I log in early?
I will close this as it's obviously changed/changing.
