### ISSUE TITLE
Sandboxing doesn't work on (Manjaro) Linux with steam

### ISSUE THREAD

**Issue by arch-user-france1** [danielyxie/bitburner#2605]
If I start the game without sandboxing mode it works fine, but with sandboxing it just doesn't do anything (not even open a window) and after like a half minute it opens a window that instantly closes and the game stops.

**Comment by MartinFournier** [comment]
@debian-user-france1 Would you retry with sandbox in the latest version? If the problem was because of Steam, you'll now get a better error message.

**Comment by debian-user-france1** [comment]
Still doesn't work

**Comment by debian-user-france1** [comment]
#1873

**Comment by phyzical** [comment]
closable as duplicate maybe
