### ISSUE TITLE
Favor and Bitnode multipliers are applied twice when working for a faction

### ISSUE THREAD

**Issue by YannikL** [danielyxie/bitburner#2615]
When doing work for a faction, the favor and Bitnode multipliers are applied twice:
Once in getHackingWorkRepGain (and the respective functions for other work types) through mult(f)
```js
function mult(f: Faction): number {
  let favorMult = 1 + f.favor / 100;
  if (isNaN(favorMult)) {
    favorMult = 1;
  }
  return favorMult * BitNodeMultipliers.FactionWorkRepGain;
}

export function getHackingWorkRepGain(p: IPlayer, f: Faction): number {
  return (
    ((p.hacking + p.intelligence / 3) / CONSTANTS.MaxSkillLevel) *
    p.faction_rep_mult *
    p.getIntelligenceBonus(1) *
    mult(f)
  );
}
```
and then once more in the workForFaction() function:
```js
export function workForFaction(this: IPlayer, numCycles: number): boolean {
  const faction = Factions[this.currentWorkFactionName];

  //Constantly update the rep gain rate
  switch (this.factionWorkType) {
    case CONSTANTS.FactionWorkHacking:
      this.workRepGainRate = getHackingWorkRepGain(this, faction);
      break;
    case CONSTANTS.FactionWorkField:
      this.workRepGainRate = getFactionFieldWorkRepGain(this, faction);
      break;
    case CONSTANTS.FactionWorkSecurity:
      this.workRepGainRate = getFactionSecurityWorkRepGain(this, faction);
      break;
    default:
      break;
  }
  let favorMult = 1 + faction.favor / 100;
  if (isNaN(favorMult)) {
    favorMult = 1;
  }
  this.workRepGainRate *= favorMult;
  this.workRepGainRate *= BitNodeMultipliers.FactionWorkRepGain;
```

Seems unintended, but if it's not, there is at least some unwanted code duplication.

**Comment by deathly809** [comment]
There is also duplicate rep given from being offline in certain cases.  That should probably be fixed too :(

**Comment by QuantumRipple** [comment]
The duplicate favor multiplier was removed with commit (5126d72742755af7806c63c62b76e938bc3369f0) but the duplicate `BitNodeMultipliers.FactionWorkRepGain` is still present. Favor and BitNode multipliers are also both duplicated in `startFactionWork(...)` but it has no effect because the values that function sets are immediately updated/overwritten by `workForFaction(...)`.
