### ISSUE TITLE
faction issue

### ISSUE THREAD

**Issue by iminemantis** [danielyxie/bitburner#2626]
I have joined the faction "slum snakes", i am playing in the second bit node, the one that lets you have gangs. for some reason the slum snake are selling every single augmentation augmentation that is in the game including things such as the red pill and QLink which i have not even heard of.
You can delete this section

![image](https://user-images.githubusercontent.com/90356983/149578183-ec875e71-c8cc-464e-bac4-e388fa513e70.png)

- [ https://mega.nz/file/hX5ABL5B#Qjnie9WH5QQMiSFXgMv5S8TrrY2fuWnVAZSP-PDNBnU ] Save file
- [ N/A ] Minimal scripts to reproduce the issue
- [ i dont know what caused this glitch ] Steps to reproduce
- [ v1.3.0 03488268 ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by MartinFournier** [comment]
This is normal, that's how the Gangs feature work, you'll buy all your augs through your gang.

**Comment by phyzical** [comment]
closable
