### ISSUE TITLE
[Feature Request] Ctrl+C in terminal should erase current input

### ISSUE THREAD

**Issue by SrBrahma** [danielyxie/bitburner#2632]
Having to backspace everything is a little boring. In Linux you can Ctrl+C in the terminal to clear all the current input without having to backspace everything.

**Comment by RasmusLindroth** [comment]
I would like `Ctrl`+`U` to clear all text before the cursor and `Ctrl`+`K` to clear all text after the cursor.

**Comment by SrBrahma** [comment]
Didn't know about them, nice!

Beware that in zsh, as I tested, Ctrl+U clears the entire input. bash have the behavior you mentioned.

**Comment by phyzical** [comment]
closable
