### ISSUE TITLE
scp typing missing overload

### ISSUE THREAD

**Issue by greghornby** [danielyxie/bitburner#2633]
https://github.com/danielyxie/bitburner/blob/62ac7f7d170b14bb7a9988411d7c6f17e690f058/src/ScriptEditor/NetscriptDefinitions.d.ts#L4822

Missing overload for having no source, just destination

```
scp(files: string | string[], destination: string): Promise<boolean>;
scp(files: string | string[], source: string, destination: string): Promise<boolean>; 
```

**Comment by deathly809** [comment]
They cheat.  If the destination is empty, they assume that the source is the destination and automatically select the current server as the source.  I agree that an overloaded method would be better.

https://github.com/danielyxie/bitburner/blob/62ac7f7d170b14bb7a9988411d7c6f17e690f058/src/NetscriptFunctions.ts#L1119
