### ISSUE TITLE
Grow can be NaN

### ISSUE THREAD

**Issue by deathly809** [danielyxie/bitburner#2635]
Looks like sometimes we grow infinitely (I suspect divide by 0 or related issues).  If we are okay with not so accurate values, could just do (server.val + epsilon) to ensure no NaN values.

![image](https://user-images.githubusercontent.com/1381210/149602680-6fd3d1b0-08fa-4416-8402-da9a10bf0aa3.png)

**Comment by timotheeandres** [comment]
I also noticed this when I used `grow()` on a server which had 0 money on it. Definitely a division by 0.

**Comment by zeddrak** [comment]
Are you in a bitnode with a BitNodeMultipliers.ScriptHackMoney == 0?

One recent correction that I know was made was to include the BitNodeMultipliers.ScriptHackMoney, but that shouldn't create this behavior where it wasn't before, as the 0 case would be the same either way.

**Comment by timotheeandres** [comment]
For me it was on Bitnode 1 that this error appeared

**Comment by deathly809** [comment]
@hydroflame  Idk about how this looks.  Still seems janky.  Maybe we can have a lower bound of $1 so that the value is an actual number?

![image](https://user-images.githubusercontent.com/1381210/149650229-a83ea892-edd0-46cd-905d-0cf24a75a84f.png)

**Comment by deathly809** [comment]
Also, we seem to be handling the growth output in different ways.  In one code path we computed the value twice and ignored the first computation lol.  We also format it different in some places.

**Comment by zeddrak** [comment]
[My Discord discussion in developement](https://discord.com/channels/415207508303544321/459097632896188436/934590171066802187)

> Ok, concerning the growAnalyze, I have a couple of options to deal with the infinity issues:
> https://github.com/danielyxie/bitburner/issues/2635
> https://github.com/danielyxie/bitburner/issues/2628
> 
> Option 1) Just retun Math.min(growAnalyze normal value, server.moneyMax) --- this basically assumes a minimum of $1 server and ignores the extra power added to grow ($1/thread) and so will return larger values than actually needed (potentially MANY times larger in some case. Theoretical example: if it takes 100 threads to double - grow x2 - a certain server with moneyMax of $200, then 100 threads is all that would be needed to grow it to max from $0, but this naïve solution is returning 200)
> 
> Option 2) Is basically to use a first order differential equation - ie, how many threads it takes is dependent on how many threads you need... I'll look up one of the approximation techniques for that kind of first order differential equation and use that (most approach very quickly, and we only need to get to an error <1 since integer threads anyways). This has the added advantage of taking into consideration the extra grow power for non-full grows as well.
> 
> Opinions?
> (Follow-up: If we go with option 1, should I also change the previously discussed functions to behave accordingly - eliminating the infinity thing entirely? Basically, this would change the mechanic for growing <$1 servers to assume $1, instead of $1/thread, consistently.)

**Comment by phyzical** [comment]
probably closable as a duplicate
