### ISSUE TITLE
~~Growth effectiveness with more threads should be exponential~~ Wiki is wrong

### ISSUE THREAD

**Issue by PhantomDerp** [danielyxie/bitburner#2651]
suppose each grow increases the amount of money by 1% (1.01)
If I use 2 threads to grow, it multiplies the money by 1.02
If I use 2 grow calls in different scripts, it multiples by 1.01 then 1.01 again, multiplying by 1.0201 in total

For my sanity and CPU, please make increasing the threads exponentiate automatically.

growthrate ^ threads instead of growthrate * threads

Just incase this is already how it's done, here's where I got it https://bitburner.readthedocs.io/en/latest/netscript/basicfunctions/grow.html

**Comment by PhantomDerp** [comment]
This makes a pretty big difference at higher program counts (blue vs red)
![image](https://user-images.githubusercontent.com/42085302/149643622-ec4e3187-8624-4d7a-9092-60427ed1c32a.png)

**Comment by SagePtr** [comment]
Isn't it?
https://github.com/danielyxie/bitburner/blob/8b69fd7faa5e29cd7d72f4bb8aad6e6c3f6cbf24/src/Server/formulas/grow.ts#L23

**Comment by PhantomDerp** [comment]
I guess it is. The wiki needs to be fixed then.

Btw, where are the formulas for hacking and weakening?

**Comment by zeddrak** [comment]
I don't see where the wiki says that grow is increased linearly with threads?
As for formulas, there are the free ones:
[growthanalyze](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.growthanalyze.md)
[growthanalyzesecurity](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.growthanalyzesecurity.md)
and there are the more robust ones that come with formulas.exe
[hacking formulas](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.hackingformulas.md)

**Comment by PhantomDerp** [comment]
Oh did I forget to close this
