### ISSUE TITLE
Corporation - Smart Supply will not disable by material

### ISSUE THREAD

**Issue by atnoslen** [danielyxie/bitburner#2681]
- [x] Save file
  - [bitburnerSave_1642433014_BN3x0.zip](https://github.com/danielyxie/bitburner/files/7882940/bitburnerSave_1642433014_BN3x0.zip)

- [x] Minimal scripts to reproduce the issue
  - No script in use
- [x] Steps to reproduce
  - Enable Smart Supply globally at a city
  - Disable one material

    ![image](https://user-images.githubusercontent.com/3331625/149796662-cfce2f3a-3619-46b0-a341-59d87f53ac83.png)

  - Material remains blue and continues to be bought

    ![image](https://user-images.githubusercontent.com/3331625/149796566-84dce3ad-d7e4-4d14-ac89-60d03ff97211.png)

- [x] Version
  - Bitburner v1.3.0 (9fdc3ac5)

**Comment by atnoslen** [comment]
Partially related to #2293.  In the above screenshot, robots is disabled in the Smart Supply dialog, but enabled (and is buying) in the material screen.  AI Cores is enabled in Smart Supply (can't disable due to #2293), but is not enabled/buying in material screen.  Though, Smart Supply was working at one point as there is a buy order that I did not set.

**Comment by phyzical** [comment]
was this caused by using the api by chance?
