### ISSUE TITLE
Active scripts navigation UI bounces around when viewing last page

### ISSUE THREAD

**Issue by Sleaker** [danielyxie/bitburner#2686]
For control scripts that actively launch multiple other scripts in quick succession it becomes impossible to navigate the list once the last page has been reached as the footer UI which controls rows per page and back continually pops up and down as scripts are destroyed/started up.

This can make finding a specific script on servers with many active scripts difficult to find in the active scripts page.

UI elements that control navigation should be locked in place elements so they don't bounce around:
Fix 1) move the navigation elements to the header, 
Fix 2) Fill in empty rows until 'rows per page' has been reached.

Side feature: make the search box filter out any scripts that don't have the name, not just the servers with them running.

**Comment by phyzical** [comment]
if this hasn't been addressed i think it would be a good idea. i know i've had a hard time clicking the right script sometimes.
