### ISSUE TITLE
Game Crashes on Singularity Augmentation installation

### ISSUE THREAD

**Issue by Katterton** [danielyxie/bitburner#2688]
### How did this happen?
Tried to install Neuro Governor via Singularity 
Please fill this information with details if relevant.

- [ ] Save file
- [x] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'name')
* Page: Work
* Version: v1.3.0 (949f5549)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a
[main.zip](https://github.com/danielyxie/bitburner/files/7889076/main.zip)

**Comment by Playegage** [comment]
I had the same issue. It happend for me when I had manually stated working at a company and had that focused. When I tried reloading without scripts running and ran everything again once I stopped working it didnt die so idk if that is part of the issue.

**Comment by ethall** [comment]
I also added a `ns.stopAction()` call immediately before `ns.installAugmentations()` and it seems to have resolved things.

**Comment by Katterton** [comment]
> I also added a `ns.stopAction()` call immediately before `ns.installAugmentations()` and it seems to have resolved things.

thanks for the tip
