### ISSUE TITLE
"Big Network" Achievement unlocks at 31 hacknet nodes

### ISSUE THREAD

**Issue by Shades84** [danielyxie/bitburner#2697]
Bitburner v1.4.0

**Comment by SagePtr** [comment]
The achievements are recalculated every minute, so it fires not instantly

**Comment by Shades84** [comment]
Ahh, okay, I was unaware of that. It fired off after the 31st so I wrongly
associated them.

**Comment by zeddrak** [comment]
@Shades84, if this has resolved your issue, please consider closing it to save poor Hydro some time. ;)

**Comment by Shades84** [comment]
Oh I didn't realize that was something I needed to do
