### ISSUE TITLE
Feature: Add function to get base price of augment rather than current price(including the multiplier) or a function to sleeve that returns the price of their augments

### ISSUE THREAD

**Issue by Playegage** [danielyxie/bitburner#2700]
This is more of a readability thing, but I like my scripts to output what the cost of something is when they are waiting to buy it. At the moment there isn't a way to get the price of an augment for a sleeve, unless I am missing it which would be ideal. For since sleeve augs dont increase in price, they are only the same price as normal augs when you don't have any queued.

**Comment by zeddrak** [comment]
You can use the sleeve api [sleeve.getsleevepurchasableaugs](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.sleeve.getsleevepurchasableaugs.md) which returns all available augs for a sleeve and their cost.

You can use the functions to build an array in BN1, then hardcode it into a script which you can later import if you want to keep the raw base values.
