### ISSUE TITLE
Contracts only generate while game is running

### ISSUE THREAD

**Issue by Sleaker** [danielyxie/bitburner#2709]
Contracts seem to have a chance to generate every 10 minutes, but never generate while the game is offline. 
When user logs in after being offline for a while it would make sense for the contract generation to generate contracts as if the game had been online for the whole period.

**Comment by phyzical** [comment]
while this may be the case, we may handle it as part of the bonus time (the way the game handles "offline gains") 

if it currently doesn't this is how i suggest we could handle this, if it was to be considered.

**Comment by xRalic** [comment]
I was going to go ahead and implement this, but pull request #1695 added this **commented** section of code into ``Engine.ts``, which would seem to fix the problem:

```js
      // Generate coding contracts
       let numContracts = 0;
       if (numCyclesOffline < 3000 * 100) {
         // if we have less than 100 rolls, just roll them exactly.
         for (let i = 0; i < numCyclesOffline / 3000; i++) {
           if (Math.random() < 0.25) numContracts++;
         }
      } else {
         // just average it.
         numContracts = (numCyclesOffline / 3000) * 0.25;
       }
       console.log(`${numCyclesOffline} ${numContracts}`);
       for (let i = 0; i < numContracts; i++) {
         generateRandomContract();
       }
```
Is there any reason why this isn't the current implementation?
