### ISSUE TITLE
Change Stanek.get() to .getFragment() to prevent collisions

### ISSUE THREAD

**Issue by trhr** [danielyxie/bitburner#2717]
Currently, the .get() function causes a 2GB increase in ram due to the way Bitburner parses the text to determine function calls. However, .get() is a common method on a number of JavaScript built-ins, like Set and Map, Reflect, etc.

Dev team needs to have a policy not to conflict methods unnecessarily. It wrecks IDEs, too.

**Comment by Ninetailed** [comment]
This looks like the same issue as in #2639

**Comment by trhr** [comment]
It may have the same fix, but avoiding collisions with Javascript built-ins is a different problem than your own functions colliding with themselves.

**Comment by zeddrak** [comment]
Same symptoms and even root cause maybe, but yeah, different problem.

**Comment by olee** [comment]
@hydroflame why close this issue? I think this would be a good proposal to fix a really common naming conflict with eg. Map and Set get function.

**Comment by AesSedai** [comment]
I use typescript and compile it to ES6, and using classes with private variables (eg: `#foo`) it generates JS private class field getters that is also triggered by this:
```
var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
```
So, using private variables causes a +2GB script RAM usage :(

**Comment by trhr** [comment]
yeah I just replaced all my .get() calls with ["get"]... my IDE throws a fit, but what are ya gonna do, contribute to an open source project? lol.

**Comment by AesSedai** [comment]
I'd consider it, if the maintainer didn't [close a PR addressing the issue without providing any feedback](https://github.com/danielyxie/bitburner/pull/2815) or [basically say it's a `wontfix`](https://github.com/danielyxie/bitburner/issues/2426#issuecomment-1008087958). But what are ya gonna do, amiright?
