### ISSUE TITLE
Gang member tasks don't update in gang screen when changed through script

### ISSUE THREAD

**Issue by tvanderpol** [danielyxie/bitburner#2718]
**Game Version**: Bitburner v1.4.0
**Steps to reproduce**:

- Run a script that changes a gang member's task on a timer
- Go to gang screen

**Expected:** See the task that the member is assigned to change as the script changes it
**Actual:** The stats (money, respect, wanted level, total respect) and the description seem to change, but the actual task in the drop down does not.

**Comment by zeddrak** [comment]
I have also noticed this, though I don't know that updating the actual dropdown is a good solution (anyone tested what this would do if you had the drop down open when a script update happened).
I did notice that the descriptions to the right update correctly. So perhaps just adding a label with the "current task" listed below the dropdown that updates with api calls (and manual dropdown selection,)

**Comment by zeddrak** [comment]
I have uploaded a potential fix (see link above this comment), but I need someone to test it for me (I haven't got Node working yet). I'll create the pull request once someone has confirmed this fix works as desired.

**Comment by phyzical** [comment]
just wanted to add i tried to fix this on the dropdown directly 👍
