### ISSUE TITLE
scp_ok = scp("existing.script", "non-existing-hostname"); never returns

### ISSUE THREAD

**Issue by rcpao** [danielyxie/bitburner#2725]
Minimal scripts to reproduce the issue:
existing.script:
var scp_ok = scp("existing.script", "non-existing-hostname");

Steps to reproduce
[home ~/]> nano existing.script
var scp_ok = scp("existing.script", "non-existing-hostname");
[home ~/]> run existing.script
Running script with 1 thread(s), pid 206 and args: [].
[home ~/]> tail existing.script 
scp: Invalid hostname or IP: non-existing-hostname
[home ~/]> ps
(PID - 206) existing.script
[home ~/]> kill existing.script
Killing existing.script

Bitburner v1.4.0 (1e126d40) from Steam running in Ubuntu 20.04.3

**Comment by Master-Guy** [comment]
Also failing for wget in NS1.
Gives an invalid error as well:

![image](https://user-images.githubusercontent.com/566429/159130566-4db31015-55ca-4cf0-b2e0-3fea0cbc5348.png)
