### ISSUE TITLE
'Find All Valid Math Expressions' contract description does not specify order of evaluation, unary minus

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2732]
The description for the 'Find All Valid Math Expressions' contract type asks the player to "Return all possible ways you can add the +, -, and * operators to the string such that it evaluates to the target number". It does not specify what order of operations the player should assume.

My initial solution assumed that the generated expressions would be evaluated in plain left-to-right order like a calculator, e.g. `1*2+3*4` = `(((1*2)+3)*4)` = 20. This worked for some problems, but later failed. My next solution, which assumes that all multiplication is done first, then addition and subtraction are done left-to-right, and this has worked so far, so I'm assuming its the right answer.

Similarly, the way the contract is worded doesn't make clear whether unary minus is allowed, e.g. whether `2*-2` ('two times minus-two') is a valid way to get -4, or `-1+3` to get 2. I am assuming it's not, since my solver doesn't consider them and its solutions have been accepted, but the contract ought to make that clear.

**Comment by zeddrak** [comment]
PR #2769
