### ISSUE TITLE
Add `ns.expr` function

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2733]
It would be useful to have a NetScript function `expr()` which evaluates a mathematical expression as the terminal command `expr` does. (Yes, Javascript `eval()` exists - but that's _too_ powerful for this purpose.)

**Comment by smolgumball** [comment]
What's the use case for this vs. just using native JS operators? 

i.e. why is:
```js
ns.print(ns.expr("2 + 2"))
```

better than:
```js
ns.print(2 + 2)
```

**Comment by zeddrak** [comment]
I mean, all expr does is use eval, soo...
[terminal/commands/exp](https://github.com/danielyxie/bitburner/blob/dev/src/Terminal/commands/expr.ts)

```
  // Sanitize the math expression
  const sanitizedExpr = expr.replace(/s+/g, "").replace(/[^-()\d/*+.]/g, "");
  let result;
  try {
    result = eval(sanitizedExpr);
  } catch (e) {
    terminal.error(`Could not evaluate expression: ${sanitizedExpr}`);
    return;
  }
  terminal.print(result);

```

**Comment by phyzical** [comment]
yeah.. this is clearly to help solve coding contracts (or to avoid converting a string to a number maybe?). i vote no,  it should be something found in user's  helper scripts
