### ISSUE TITLE
You can work out at a gym while in a different country

### ISSUE THREAD

**Issue by hyphz** [danielyxie/bitburner#2740]
Ver: Bitburner v1.4.0 (49de4a28)

Reproduction:
Go to a Gym (eg, Powerhouse in Sector-12) and start working out
Click "do something else simultaneously"
Click "travel" and go somewhere else (eg, Chongqing)
You are now still working out at Powerhouse while halfway across the planet!

While it is "in theme" for field work, study, and hacking jobs and contracts to be possible remotely, it doesn't make much sense for working out.

**Comment by zeddrak** [comment]
It's your remote virtual trainer... ... ...
Haven't you noticed how much security those gyms have? They're coding GODS! You think a little thing like you not being there is gonna stop them? Pushah....  ;)
