### ISSUE TITLE
Loading game with 1000s of scripts running crashes since (49de4a28)

### ISSUE THREAD

**Issue by phtnk** [danielyxie/bitburner#2743]
v1.4.0 (49de4a28) on steam, Win10 - savegame included

My game keeps crashing on current save since latest release on steam, it worked "fine" before.

Situation:
- Game has ~20.000 scripts running - a few controllers and the rest simple executors for hack/grow/weaken.
- Scripts ran fine for quite some time, so no glaring issues with the code

Still, on my PC, because of the many scripts running (before the latest patch):
- CPU load ~10-15% all the time, Ram ~2.5-3GiB
- loading the game took ~15 seconds, sometimes suggesting it is stuck and asking if it should kill all scripts. It always loaded, though.
- quitting the game didn't quit the process. It kept running in the background with said 2.5GiB ram and 10% CPU load. Always had to kill it in the task manager.

Once I kill all scripts, these problems go away, including not quitting properly.
Am I missing some more effective way of running things here that doesn't require me to have thousands of scripts running to maximise returns?

**Error**
Since last patch I'm stuck on the loading screen, it either gets to asking me to kill all scripts, or - way worse - it goes into rage mode, makes my screens flicker and ultimately kills my graphics driver and consequently my second monitor - and if it feels good, a few more processes along the way. The game completely quits after that. I'm forced to restart my PC.

If I start the game and immediately choose reloads/'reload and kill all scripts' it starts fine and also exits without problems as well.
I attached the save game, which should be enough to demonstrate the problem, I guess.
[bitburnerSave_1642720248_BN1x0.zip](https://github.com/danielyxie/bitburner/files/7916214/bitburnerSave_1642720248_BN1x0.zip)

**Comment by waffleattack** [comment]
I think on windows there is a launch method that kills all scripts on game load, might be a temp fix for you

**Comment by phyzical** [comment]
i think this might relate to the recent scripts logging, i will try disabling the component to confirm

**Comment by phyzical** [comment]
so i gave it a crack on the web version of dev and running alot of scripts did not seem to cause any issues whatsoever, granted this was just a simple series of scripts on only home that just slept every second for a 120 seconds. if anyone else tries to replicate this we may need to try harder or it does not affect the web version and only the electron version.


![Mar-05-2022 11-36-42](https://user-images.githubusercontent.com/5182053/156866253-f811269b-ad47-4c88-8dfe-fd830f25c1d0.gif)

**Comment by phyzical** [comment]
i have also tried the mac electron app im confident it isnt the scripts alone, but it maybe a combination of what the scripts are doing aswell as other features maybe say corp and gangs?

**Comment by Master-Guy** [comment]
Just imported this save file, and all seems to be running well.
Loading time around 10 seconds, not that many scripts running though..

![image](https://user-images.githubusercontent.com/566429/159113568-5de2e00f-1fa9-4c47-b64f-c28a12f288cb.png)

![image](https://user-images.githubusercontent.com/566429/159113552-7cd5a97d-d696-4286-aff5-d8873c21128a.png)
