### ISSUE TITLE
[Feature Request] Option to have time stamp for terminal commands

### ISSUE THREAD

**Issue by julian94** [danielyxie/bitburner#2748]
## Summary
It would be quite convenient to have a simple timestamp in the terminal so you can see when you ran commands. This would give both a sense of time when playing and let players see when they ran commands.

### Example  
```  
[13:37 - home ~/]> ls  
csec-test.msg                 hackers-starting-handbook.lit   
j0.msg                        j1.msg                          
j2.msg                        nitesec-test.msg              
BruteSSH.exe NUKE.exe     fl1ght.exe   
[13:38 - home ~/]> cat j0.msg  
[home ~/]>   
```

**Comment by MartinFournier** [comment]
It's already in the options menu

![firefox_nV6LZVLj6M](https://user-images.githubusercontent.com/1521080/150631110-22c7bf9a-9f9e-42d5-9ca2-7153a7cc181d.png)
![firefox_HOvI0KEgVg](https://user-images.githubusercontent.com/1521080/150631111-8a77ab97-e01a-43ee-89c4-48dd3d82b06f.png)

**Comment by julian94** [comment]
Well that'll teach me to not check twice. Thanks man.
