### ISSUE TITLE
State in common modules no longer shared

### ISSUE THREAD

**Issue by drch-** [danielyxie/bitburner#2749]
Repro steps:

```javascript
// shared.js
let _someGlobal = Math.random();
export { _someGlobal as someGlobal };
```
```javascript
// test01.js
import { someGlobal } from "./shared";
export async function main(ns) {
   ns.tprint(someGlobal);
}
```
```javascript
// test02.js
import { someGlobal } from "./shared";
export async function main(ns) {
   ns.tprint(someGlobal);
}
```

Previous behavior would run the same instance of the shared library in both functions.  Starting some time today, the behavior changed to the following:
```text
[home ~/]> run test01.js 
Running script with 1 thread(s), pid 82 and args: [].
test01.js: 0.7471063129033213
[home ~/]> run test01.js
Running script with 1 thread(s), pid 83 and args: [].
test01.js: 0.7471063129033213
[home ~/]> run test02.js
Running script with 1 thread(s), pid 84 and args: [].
test02.js: 0.7183806629240053
```

Expected behavior: both test01.js and test02.js have the same output.
Actual: test01.js and test02.js have different output, however they are consistent for the individual scripts.

Version: Bitburner v1.4.0 (49de4a28) (Steam)

**Comment by davidsiems** [comment]
Pretty sure this is what changed the behavior: https://github.com/danielyxie/bitburner/commit/77f525c98cd82d5282fe37ec1d84102fca17fea5
