### ISSUE TITLE
[Bug?] tryWritePort cannot write arrays in NS1 but can in NS2

### ISSUE THREAD

**Issue by BinarySpike** [danielyxie/bitburner#2750]
Using bitburner v1.4.0 (steam edition?)

You cannot write arrays to ports with `tryWritePort` using a `.script` file, but you can with a `.js` file.

```javascript
// portsTest.script
var i = 0;

clearPort(1);

var values = ["SOMETHING REALLY LONG", "SOMETHINGE ELSE REALLY LONG TOO"];

while (tryWritePort(1, values)) {
	i++;
	var input = readPort(1);
	print('portsLength ' + i + " peek: " + input[0] + " " + input[1]);
}

tprint('portLength ' + i);
```

fails by printing `portsLength xxx peek: undefined undefined`

``` javascript
// portsTest.js

/** @param {NS} ns **/
export async function main(ns) {
	var i = 0;

	ns.clearPort(1);

	var values = ["SOMETHING REALLY LONG", "SOMETHINGE ELSE REALLY LONG TOO"];

	while (await ns.tryWritePort(1, values)) {
		i++;
		var input = await ns.readPort(1);
		await ns.print('portsLength ' + i + " peek: " + input[0] + " " + input[1]);
		await ns.sleep(0);
	}

	await ns.tprint('portLength ' + i);
}
```

Works successfully with `portsLength 1145 peek: SOMETHING REALLY LONG SOMETHINGE ELSE REALLY LONG TOO`

**Comment by zeddrak** [comment]
because your scrupt version isn't waiting for the port read, try
	var input = readPort(1);
	wait(2000)
	print('portsLength ' + i + " peek: " + input[0] + " " + input[1]);

**Comment by zeddrak** [comment]
It's been so long since I used ns1 scripts I don't even remember if it can be waited for?

**Comment by BinarySpike** [comment]
`await` is a syntax error in ns1 scripts:
```
Error processing Imports in test.script:
SyntaxError: Unexpected token (1:17)
```

It's an issue with ns1.  I'm not sure how it gets translated, but the type definition is `String | Number` and the implementation is `any`.  AFAIK ns2 uses the implementation directly, so it's not an issue.

**Comment by phyzical** [comment]
is ns1 still supported? i thought i remember reading somewhere it is not
