### ISSUE TITLE
cannot access file dir c:/

### ISSUE THREAD

**Issue by k4zter** [danielyxie/bitburner#2753]
wasn't able to access c:/ and had to use a script to remove all contents in the file to get rid of the folder even tho the game fully recognizes that there is a file there with c:/

![bitburner_MtzGpkFVIv](https://user-images.githubusercontent.com/50892886/150626082-19540555-7b97-457a-8d05-9101571cbb9a.png)

Bitburner v1.4.0 (49de4a28)(steam)

**Comment by phyzical** [comment]
just to confirm (this is obviously windows right?)

or have you created a folder called c:/? 

didn't relise we give bitburner access to the hardrive.. 
i assume we dont otherwise thats pretty scarey....

**Comment by k4zter** [comment]
yeah it was a folder i pushed from VSC and it took the file dir of my folder on my pc...

**Comment by phyzical** [comment]
hmm might be something to ask int he discord channel for VS code. (but we can try to repo it and see what happens) 👍

**Comment by phyzical** [comment]
@lordducky hey thought i would tag you on this one, any chance this can be added as part of your webserver updates :). tldr we just need to make sure that we cant save invalid directory names i.e `c:\` and `/` as these cannot be `cd` into once they are copied across
