### ISSUE TITLE
[Bug?] growthAnalyzeSecurity different than growth security implementation?

### ISSUE THREAD

**Issue by BinarySpike** [danielyxie/bitburner#2755]
`growthAnalyzeSecurity` is returning `0.04`.  However, the actual change is `+0.1`

```
[joesguns ~/]> grow
[||||||||||||||||||||||||||||||||||||||||||||||||||]
Available money on 'joesguns' grown by 1.081402%. Gained 8.360 hacking exp.

Security increased on 'joesguns' from 15.100 to 15.200
```

The [implementation](https://github.com/danielyxie/bitburner/blob/dev/src/NetscriptFunctions.ts#L652) of `growthAnalyzeSecurity` is
```javascript
growthAnalyzeSecurity: function (threads: any): number {
      return 2 * CONSTANTS.ServerFortifyAmount * threads;
    },
```

The [implementation starts at `processSingleServerGrowth`](https://github.com/danielyxie/bitburner/blob/dev/src/Server/ServerHelpers.ts#L70) and calculates [`usedCycles` in `numCycleForGrowth`](https://github.com/danielyxie/bitburner/blob/07fe3c1906b569799652cd1f7a36de2abe306802/src/Server/ServerHelpers.ts#L49)
```javascript
// ServerHelpers.ts -> processSingleServerGrowth Line ~94
let usedCycles = numCycleForGrowth(server, server.moneyAvailable / oldMoneyAvailable, p, cores);
    usedCycles = Math.min(Math.max(0, Math.ceil(usedCycles)), threads);
    // vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
    server.fortify(2 * CONSTANTS.ServerFortifyAmount * usedCycles); // <-- ##### !!!! #####
    // ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// ...

// ServerHelpers.ts -> numCycleForGrowth Line ~49

export function numCycleForGrowth(server: Server, growth: number, p: IPlayer, cores = 1): number {
  let ajdGrowthRate = 1 + (CONSTANTS.ServerBaseGrowthRate - 1) / server.hackDifficulty;
  if (ajdGrowthRate > CONSTANTS.ServerMaxGrowthRate) {
    ajdGrowthRate = CONSTANTS.ServerMaxGrowthRate;
  }

  const serverGrowthPercentage = server.serverGrowth / 100;

  const coreBonus = 1 + (cores - 1) / 16;
  const cycles =
    Math.log(growth) /
    (Math.log(ajdGrowthRate) *
      p.hacking_grow_mult *
      serverGrowthPercentage *
      BitNodeMultipliers.ServerGrowthRate *
      coreBonus);

  return cycles;
}
```

Hack is not affected the same (but still slightly different) from [`hackAnalyzeSecurity`](https://github.com/danielyxie/bitburner/blob/dev/src/NetscriptFunctions.ts#L553) and the [implementation](https://github.com/danielyxie/bitburner/blob/dev/src/NetscriptFunctions.ts#L391).

And increases values as expected:
```
stats.script: hackAnalyzeSecurity: 0.002
...

[joesguns ~/]> hack
[||||||||||||||||||||||||||||||||||||||||||||||||||]
Hack successful on 'joesguns'! Gained $9.544k and 8.360 hacking exp

Security increased on 'joesguns' from 15.204 to 15.206
```

Am I missing something or is `growthAnalyzeSecurity` wrong?

**Comment by zeddrak** [comment]
Ahh, yep - this is related to the +$1/grow thread - with is increasing the effect of your grow, but then calculating threads (and sec increase) based on that increased effect...

Should be fixed by my overhaul once Hydroflame gives me a definitive mechanic ruling.
I'll add your issue to the list...
[discord discussion](https://discord.com/channels/415207508303544321/459097632896188436/934590171066802187)

**Comment by phyzical** [comment]
closable as a dup
