### ISSUE TITLE
Add missing git tags

### ISSUE THREAD

**Issue by MartinFournier** [danielyxie/bitburner#2756]
## Add missing git tags

I recommend you add the missing tags for version updates in the repository. I stopped listing revisions around 2 years ago.

```sh
git tag v0.43.1 9137c2427415c4dc344876a3c30ee445d92ebe4f
git tag v0.44.0 f1e43a86db09fa2dbc1e334c5ab6a907fef50c18
git tag v0.44.1 f2b4ae86926bb1a7977a36bd4a002ef16da74ebc
git tag v0.45.1 29c5c9b99d397cab675166439417a41e48dbf17e
git tag v0.46.1 2e9b028174623b6ddde3a47ced94dc66fcfd16ea
git tag v0.46.2 7417fb6ef8f3b62b4c5f4263da771a5195425039
git tag v0.46.3 bcb198220d9a2745e71d2389ef2a1355b9c6c58b
git tag v0.47.0 15a324a9466d360cc6f7be844076c799fe33889b
git tag v0.47.1 433b399de9397b805181dc89c8e1a024e6490dbe
git tag v0.47.2 59cf1d5baf78ccca32dfefe80717cbb1d284c23a
git tag v0.47.3 e9dfe3c3896329a135f96302e372c46926ff5101
git tag v0.48.0 56441b8e34b595d31e0f90354f47ab84ec72fac8
git tag v0.49.0 123628ec0b81383516e727f5a88c7262c99c84cd
git tag v0.49.1 a00c253dcb2768dd7ecb90f555be5e94ac2e8429
git tag v0.49.3 31e9f65f0622a4dec8f8133420b3fe8c44b59ae3
git tag v0.50.2 69124e7146003aad1acfc245bce9e62073750865
git tag v0.51.0 e572c6dad8793ba5a9ca6c1e76041c6eedd324f9
git tag v0.51.1 db2bf79e3b9e2fae7835a95597d1513ab1849662
git tag v0.51.2 925e96345da94b9f994f0be97c953cbcbad3793c
git tag v0.51.3 4e5ebcfe6f6bf08f7b040ff68383e7ac57821b4d
git tag v0.51.4 135df8703c651e17e0a1eae5a534c6f08ad215c1
git tag v0.51.5 b2aafea656bf1cbe4c143b62c35eba607af2d7d0
git tag v0.51.6 52a80ad23612562be51a8b7f9dd2c82b6553e39a
git tag v0.51.7 c9b5aaa2f74daa7323ae4ceb84ab63bf3b2c31ef
git tag v0.51.8 d96ad9fa6e8f94beb992c558b72e4a45352979dc
git tag v0.51.9 b28f60705697041be4bdf8213a4a91d089f1a290
git tag v0.52.1 8c9f78394b70d94dbba0b4e610eea88cb9eab190
git tag v0.52.2 67e5e413e4d98fb45caeb55f1427ea1bae8cb00a
git tag v0.52.3 e4b2a6853d713551cc31ec057e617da2a976abdf
git tag v0.52.4 1a1a43c1cea63f892c7946223d31157b8030403c
git tag v0.52.5 df457a0c6e07d847d22232ea28fc1d771832419a
git tag v0.52.6 474befa0919542b46656c29d9264c0447db3b74a
git tag v0.52.7 a564957092320bfb6c4df1175afb48733c26a953
git tag v0.52.8 6d2b8b4f6fb41ed74525653eea654922155eca2f
git tag v0.52.9 42704d86957482386f2197b27429490909b4ff22
git tag v0.53.0 cb31954b082fea47f8fe74632100c9fbf3c4e8ed
git tag v0.54.0 74906cc9e6498d728f93193096885214b172d16f
git tag v0.55.0 50cf362b3bd93255325bfa741a2911dedd33cedd
git tag v0.56.0 87c63cde59299c15de252e00acb6e29e69c420a7
git tag v0.57.0 c96c7e3d2e8bace9b983cff7b308c3031bf3c636
git tag v1.0.0 c87e9bdf843a05322e081d3527185483ca26e824
git tag v1.0.1 f3fa2a7c791a9166aa6a3b457776a4c47b4b4b58
git tag v1.1.0 3c27893aa30158fdd04ef2dc93f8cba1f13d6ece
git tag v1.2.0 02605090df38914ee5a288aedcc711d611d3e2fa
git tag v1.3.0 faf8389befec1b74133c6da6f892a6a7f951acdc
git tag v1.4.0 05cbc25a8fed73b9982925526940d65e55a842a1
git push --tags
```

---

v0.43.1 9137c2427415c4dc344876a3c30ee445d92ebe4f
v0.44.0 f1e43a86db09fa2dbc1e334c5ab6a907fef50c18
v0.44.1 f2b4ae86926bb1a7977a36bd4a002ef16da74ebc
v0.45.1 29c5c9b99d397cab675166439417a41e48dbf17e
v0.46.1 2e9b028174623b6ddde3a47ced94dc66fcfd16ea
v0.46.2 7417fb6ef8f3b62b4c5f4263da771a5195425039
v0.46.3 bcb198220d9a2745e71d2389ef2a1355b9c6c58b
v0.47.0 15a324a9466d360cc6f7be844076c799fe33889b
v0.47.1 433b399de9397b805181dc89c8e1a024e6490dbe
v0.47.2 59cf1d5baf78ccca32dfefe80717cbb1d284c23a
v0.47.3 e9dfe3c3896329a135f96302e372c46926ff5101
v0.48.0 56441b8e34b595d31e0f90354f47ab84ec72fac8
v0.49.0 123628ec0b81383516e727f5a88c7262c99c84cd
v0.49.1 a00c253dcb2768dd7ecb90f555be5e94ac2e8429
v0.49.3 31e9f65f0622a4dec8f8133420b3fe8c44b59ae3
v0.50.2 69124e7146003aad1acfc245bce9e62073750865
v0.51.0 e572c6dad8793ba5a9ca6c1e76041c6eedd324f9
v0.51.1 db2bf79e3b9e2fae7835a95597d1513ab1849662
v0.51.2 925e96345da94b9f994f0be97c953cbcbad3793c
v0.51.3 4e5ebcfe6f6bf08f7b040ff68383e7ac57821b4d
v0.51.4 135df8703c651e17e0a1eae5a534c6f08ad215c1
v0.51.5 b2aafea656bf1cbe4c143b62c35eba607af2d7d0
v0.51.6 52a80ad23612562be51a8b7f9dd2c82b6553e39a
v0.51.7 c9b5aaa2f74daa7323ae4ceb84ab63bf3b2c31ef
v0.51.8 d96ad9fa6e8f94beb992c558b72e4a45352979dc
v0.51.9 b28f60705697041be4bdf8213a4a91d089f1a290
v0.52.1 8c9f78394b70d94dbba0b4e610eea88cb9eab190
v0.52.2 67e5e413e4d98fb45caeb55f1427ea1bae8cb00a
v0.52.3 e4b2a6853d713551cc31ec057e617da2a976abdf
v0.52.4 1a1a43c1cea63f892c7946223d31157b8030403c
v0.52.5 df457a0c6e07d847d22232ea28fc1d771832419a
v0.52.6 474befa0919542b46656c29d9264c0447db3b74a
v0.52.7 a564957092320bfb6c4df1175afb48733c26a953
v0.52.8 6d2b8b4f6fb41ed74525653eea654922155eca2f
v0.52.9 42704d86957482386f2197b27429490909b4ff22
v0.53.0 cb31954b082fea47f8fe74632100c9fbf3c4e8ed
v0.54.0 74906cc9e6498d728f93193096885214b172d16f
v0.55.0 50cf362b3bd93255325bfa741a2911dedd33cedd
v0.56.0 87c63cde59299c15de252e00acb6e29e69c420a7
v0.57.0 c96c7e3d2e8bace9b983cff7b308c3031bf3c636
v1.0.0 c87e9bdf843a05322e081d3527185483ca26e824
v1.0.1 f3fa2a7c791a9166aa6a3b457776a4c47b4b4b58
v1.1.0 3c27893aa30158fdd04ef2dc93f8cba1f13d6ece
v1.2.0 02605090df38914ee5a288aedcc711d611d3e2fa
v1.3.0 faf8389befec1b74133c6da6f892a6a7f951acdc
v1.4.0 05cbc25a8fed73b9982925526940d65e55a842a1

**Comment by phyzical** [comment]
seems responsible for debugging what things looked like at certain tags (shortcuts)
