### ISSUE TITLE
Sleeves can do faction work for a managed gang, and cause recovery screen when nav to Sleeves

### ISSUE THREAD

**Issue by armoredsky** [danielyxie/bitburner#2761]
steps to reproduce: 
* manage a gang
* programmatically have 1 sleeve work for your managed gang faction as a field worker. 
* click on the sleeve tab
* boom: recovery screen
 
Minimal script
`ns.sleeve.setToFactionWork(0, "your managed gang faction", "field")`

**Comment by TheMas3212** [comment]
fixed in 8eccdf16e
