### ISSUE TITLE
[Feature request] RAM at "Active Scripts" overview

### ISSUE THREAD

**Issue by Gamb0t** [danielyxie/bitburner#2765]
It would be great to see the maximum RAM of each server enlisted in "Active scripts" and also how much RAM a script uses. This would help to identify scripts that waste ressources or even block the pipeline and help to plan efficient script scheduling.

Even if it just comes as another program one has to create/buy first for more convenience like autolink or it could be an enhancement that comes with the serverProfiler. 

It could be another item like "Args", "Threads", "Online Time" and show up like "4 GB / 128 GB".

**Comment by phyzical** [comment]
i like this idea, ive had a similar urge. 
granted when most players hit this point they are people building their own uis to display such information
