### ISSUE TITLE
in Corporations 'Use same sell amount for all cities' applies across divisions for products of same name

### ISSUE THREAD

**Issue by bunglist** [danielyxie/bitburner#2766]
**Steps to reproduce the issue**
- Create two Corporation divisions that have products (e.g. Software and Tobacco)
- Create a product in each division with the same name, e.g "Product A"
- Once complete set sell price for Product A in one division with "Use same sell amount for all cities" set
- Check other division, sell price settings will have applied there also
- Version of the game: Bitburner v1.4.0 (49de4a28) Steam on Linux

**Expected behaviour**
- "Use same sell amount for all cities" should only apply within the division it is set regardless of product name

**Comment by phyzical** [comment]
@bunglist is this still an issue?

its just looking at the source

the api does ` const product = division.products[productName];` so it has to be specific to the division

and the ui call it passes in the product object so this should be isolated to the division also

**Comment by phyzical** [comment]
Closable can confirm it doesnt leak across divisions anymore
