### ISSUE TITLE
Spoiler Warning Documentation

### ISSUE THREAD

**Issue by tmajibon** [danielyxie/bitburner#2776]
In part request, in part ask for guidance so I can possibly do it myself.

In the markdown can we put the endgame functions under a spoiler warning or such?

I went to edit it myself but a comment in the markdown says it's auto-generated, and I don't know the tool and how it's set up to run/correct it?

At the very least, we could put "Spoiler for Endgame" into the descriptions of the relevant parts?

**Comment by zeddrak** [comment]
I don't know the exact process (so not sure how/if spoiler is handled), but here's the documentation on contributing as a documentor. (I have used this information to make several successful documentation submissions myself, but none exactly like you are asking to do.)
[contributing to documentation](https://github.com/danielyxie/bitburner/blob/dev/CONTRIBUTING.md#as-a-documentor)
