### ISSUE TITLE
Bladeburner Bonus Time continues to decrement after completing a Black Op

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2794]
I just completed running a Bladeburner Black Op while having Bonus Time saved up. During the op, the bonus time decremented at ~5s per realtime second. When the op completed, the bonus time *continued* to decrement, despite the fact that Black Ops are not repeatable so I was no longer performing any Bladeburner action.

Version: Bitburner v1.4.0 (a3c599e6)

**Comment by hydroflame** [comment]
Normal, there are other events in bladeburner that take up time.
