### ISSUE TITLE
Underlining with autolink.exe is almost invisible

### ISSUE THREAD

**Issue by kotenok2000** [danielyxie/bitburner#2795]
- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
Install AutoLink.exe
run scan-analyze

- [x] Version of the game, Bitburner v1.4.0 
![Снимок экрана (115)](https://user-images.githubusercontent.com/8822292/150866745-0f6dcf12-88d1-4c72-801c-9031d737c96e.png)

also scan does not produce clickable addresses
![Снимок экрана (116)](https://user-images.githubusercontent.com/8822292/150878622-d70279aa-94ef-4af5-99c9-10c052e639e6.png)

**Comment by RoahNo** [comment]
Hey yall, just created a PR that makes the links a bit nicer to the eye, @hydroflame would you like for me to tackle scan not making clickable links or do you view that as a feature of scan-analyze?
