### ISSUE TITLE
Script Editor hijinx (Illegal invocations abound)

### ISSUE THREAD

**Issue by storm6436** [danielyxie/bitburner#2799]
### How: Attempted to edit a script.
Minimal scripts to reproduce the issue: breakout.js (Included in save)
Steps to reproduce: 
(Inconsistent reproduction, but frequent enough I'm finally filling this out)
run the following
'reset all'
'cm'
'run overseer.js'
'autopop'
'run breakout.js 5' <- # is largely irrelevant, any valid can trigger (valid: 0-5)

Then attempt to open the script editor, either by the navigation pane or via terminal with nano.

Notes: Have checked file integrity, etc. several times.

### Environment

* Error: TypeError: Illegal invocation
* Page: ScriptEditor
* Version: v1.4.0 (49de4a28)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

(Just whack the fake file extension. It's a bit odd to ask for a save file that's less than a MB and autoreject it based on extension.)
### Save 
[RECOVERY_BITBURNER_1643078738.json.notreallya.zip](https://github.com/danielyxie/bitburner/files/7930242/RECOVERY_BITBURNER_1643078738.json.notreallya.zip)

**Comment by phyzical** [comment]
@storm6436 is this still an issue?

**Comment by storm6436** [comment]
Not sure? I'll have to check what patch supposedly fixed it and do some
testing once I get in a place that won't poleaxe my BN13 progress. Just
started the node yesterday and... it's slow.

**Comment by storm6436** [comment]
Yeah, got another crash just now. Not sure if you guys need me to upload that recovery file or not.

**Comment by phyzical** [comment]
@storm6436 all good, just wanted to confirm before trying to replicate ill let you know where i get

**Comment by borisflagell** [comment]
Still a valid issue as of 1.7.0
