### ISSUE TITLE
Corporation stock price grows exponentially when there are no private investors

### ISSUE THREAD

**Issue by bmartin1234** [danielyxie/bitburner#2800]
Steps to reproduce:
- Buy a corporation
- Get corporation to be profitable ($1m or so should be plenty) [edit: possibly you can skip this step]
- Go public WITHOUT having any private investors
- Buyback all shares
- Wait for stock price to grow

It looks like shares owned by the player are not counted in the divisor for share price, so in this scenario target share price = valuation.

See /src/Corporation/Corporation.tsx line 189

<img width="810" alt="bitrunner_corp_price" src="https://user-images.githubusercontent.com/98372340/150907941-65c0935d-cb11-4254-972f-bc9412917016.png">

**Comment by phyzical** [comment]
good spot, now whether this should be adjusted not sure (i would say probably? as corps are too op)
leaving to higher powers
