### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name') (at "Work")

### ISSUE THREAD

**Issue by tmajibon** [danielyxie/bitburner#2804]
### How did this happen?

This is an inconsistent error, and so far has only happened when I'm not actively watching. But as far as I can tell, I believe it's happening when my singularity script tries to install augments. Not every time, but sometimes.

My best theory is that, since there's some job work code shortly after this step that it could be the script not closing immediately when running this command (I hadn't tested that yet because I wanted to wait for it to happen again and capture the error first)

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'name')
* Page: Work
* Version: v1.4.0 (49de4a28)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by tmajibon** [comment]
Here's my singularity script for reference (forgive the lack of commenting and general mess of the code, if needed I can go through an add thorough documentation to make it readable)

[singularity.gamma.js.txt](https://github.com/danielyxie/bitburner/files/7935335/singularity.gamma.js.txt)

**Comment by tmajibon** [comment]
Was poking at the environment after making the comments (can send save, but github won't accept it as an attachment, even when renamed to the right extension, likely because it's 35MB)

All factions are removed, some of the port opening programs are gone, this further makes me suspect it's happening mid-augment-install and could be a condition of the script not ending immediately with the installaugments command?

Could someone check if the command immediately ends the script or if it just waits for the environment to shut it down? And perhaps check the order of operations for the environment shutting down scripts, it *should* be doing it immediately before clearing any of the rest of the environment?

**Comment by kelick** [comment]
I think i hit the same issue under https://github.com/danielyxie/bitburner/issues/2931

**Comment by phyzical** [comment]
i agree closable as dup
