### ISSUE TITLE
Global variables seem to be broken

### ISSUE THREAD

**Issue by rglazebrook** [danielyxie/bitburner#2805]
Global variables don't seem to be working for me in v1.4.0 (49de4a28).

According to the documentation, 
`Any global variable declared in a ns2 script is shared between all instances of that script. `

And this had been working for me in v1.3.0. However, in v1.4.0 that functionality seems to be broken.

Here's a minimal example:

```
let testMsg = "BAD";
/** @param {NS} ns **/
export async function main(ns) {
	const [msg] = ns.args;
	if (msg) {
		testMsg = msg;
	}
	while(true) {
		ns.print(testMsg);
		await ns.sleep(2000);
	}
}
```

If I copy that script to two different servers and run one with an argument of `GOOD`, that server will output the `GOOD` message. However, if I run the same script on the second server with no argument, it will output the `BAD` message.

![bitburner-global-var-bug](https://user-images.githubusercontent.com/2517006/151022416-dd8af0b6-65aa-4a6b-9d0a-dc72e8001457.png)

**Comment by rglazebrook** [comment]
Could you please let me know why this was closed? I was using this functionality, and now my scripts are broken, with no updates to the documentation to explain what has changed.

**Comment by symphony** [comment]
From what I understand every time the second script is called the variable is being initialized to the default value "BAD". Maybe you need a second check to see if it was initalized already and if so then to leave the value alone.

**Comment by phyzical** [comment]
or use ports, i wouldn't be surprised if the variable is lost as the script is destroyed
