### ISSUE TITLE
Bug/Clarification: When in a gang, sleeves cannot get augmentations from other factions

### ISSUE THREAD

**Issue by Cireminer** [danielyxie/bitburner#2808]
https://github.com/danielyxie/bitburner/blob/master/src/PersonObjects/Sleeve/SleeveHelpers.ts#L40

The code there will return early if the player is in a gang, meaning only augs from the player gang are available.

**Comment by phyzical** [comment]
hmmmm, makes sense it shouldnt.

but if this should be changed im not sure.

leaving to higher powers

**Comment by alainbryden** [comment]
This was fixed by https://github.com/danielyxie/bitburner/pull/2938 and can be closed.
