### ISSUE TITLE
Duplicate sleeves have the option to install Netburners augmentations while in a gang

### ISSUE THREAD

**Issue by Cireminer** [danielyxie/bitburner#2810]
Issue: 
https://github.com/danielyxie/bitburner/blob/master/src/PersonObjects/Sleeve/SleeveHelpers.ts#L63
Checks here imply that Netburners augmentations should not be available for duplicate sleeves. However, if the player is in a gang, Netburners augs will be available for the sleeve - https://github.com/danielyxie/bitburner/blob/master/src/PersonObjects/Sleeve/SleeveHelpers.ts#L47

Save:
[bitburnerSave_1643137226_BN10x0.zip](https://github.com/danielyxie/bitburner/files/7936415/bitburnerSave_1643137226_BN10x0.zip)

Version: 49de4a28

To reproduce: Go to the Manage Augmentations screen for the duplicate sleeve while in a gang with enough reputation to make some Netburners augs available for installation (save attached)
![image](https://user-images.githubusercontent.com/4282246/151042371-f13c7d4b-5496-42fb-aac3-3b1f14217cdb.png)

**Comment by Cireminer** [comment]
Looks like it can also get The Red Pill, even when the gang does not offer that augmentation.
[bitburnerSave_1643203677_BN10x0.zip](https://github.com/danielyxie/bitburner/files/7942041/bitburnerSave_1643203677_BN10x0.zip)

**Comment by phyzical** [comment]
@Cireminer  hmm is it possible that this is by design so that the other issue https://github.com/danielyxie/bitburner/issues/2808 isnt an issue unless im miss understanding the first issue? 

i.e is there augmentations missing from the "gang faction" or is every aug avail and thus makes both issues redundant?
