### ISSUE TITLE
getPurchasedServerCost() >=128 wrong?

### ISSUE THREAD

**Issue by Futty87** [danielyxie/bitburner#2812]
Hello,
![image](https://user-images.githubusercontent.com/54290993/151079721-02119073-13a6-4885-b723-5c731c9beabf.png)

Is this calculation from 128GB correct?
Version 1.4.0

**Comment by tmajibon** [comment]
What seems wrong to you about it?

**Comment by Guillermo-Santos** [comment]
if you are confused, use "ns.nFormat(ns.getPurchasedServerCost(i),"0.000a")" to see the cost, so that they are more readable.

or if the problem is the cost, so you know server cost are lower to home ram cost.

**Comment by macdjord** [comment]
@Futty87 Do you mean the fact that, up to 2^6, the prices are linear, but from 2^7 onward, they get more expensive per-GiB each time? That's an intended - if regrettably poorly documented - feature; on Bitnode 1, all the prices are linear, but most of the other bitnodes make bigger servers more expensive as a way of increasing the difficulty.

**Comment by Futty87** [comment]
> That's an intended - if regrettably poorly documented - feature; on Bitnode 1, all the prices are linear, but most of the other bitnodes make bigger servers more expensive as a way of increasing the difficulty.

ok in this case it's not a bug, it´s a feature.
Thank you!
