### ISSUE TITLE
Achievement 'Here comes the money!' Not Triggering

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2817]
The achievement 'Here comes the money!' is supposed to be granted for having over $1q in cash; I have > $1.5q, but have not received the achievement.

Save: [bitburnerSave_1643180450_BN2x0.txt](https://github.com/danielyxie/bitburner/files/7939564/bitburnerSave_1643180450_BN2x0.txt)

Version: a3c599e6

**Comment by MartinFournier** [comment]
That's normal, the check is 1**Q** not 1**q**, so for ` Player.money >= 1e18`

```ts
const extraFormats = [1e15, 1e18, 1e21, 1e24, 1e27, 1e30];
const extraNotations = ["q", "Q", "s", "S", "o", "n"];
```
