### ISSUE TITLE
QoL: Job/Promotion applications should list the job title you are applying for

### ISSUE THREAD

**Issue by JBrown526** [danielyxie/bitburner#2823]
Currently when you apply for a job there is a hover over listing out the requirements for the job, this should include the job title the application would be for (i.e. Software Engineering Intern, Junior Software Engineer etc.).
![image](https://user-images.githubusercontent.com/45610774/151151025-47a82ab9-0651-4e58-9a9f-346d29e8e4e2.png)

**Comment by macdjord** [comment]
Duplicate:  #2394
