### ISSUE TITLE
QoL: When you reach the highest 'rank' at a job, the application button should indicate this

### ISSUE THREAD

**Issue by JBrown526** [danielyxie/bitburner#2824]
Currently, when you achieve the highest rank in a job (e.g. CEO, CTO etc.) the application button remains and the hover box appears as empty.
![image](https://user-images.githubusercontent.com/45610774/151152049-dcf74ab3-9c8e-4a05-a27d-8c3e32844fd2.png)

There should be better indication that further promotion is not possible in the role without clicking on the button to see the no further promotions message:
![image](https://user-images.githubusercontent.com/45610774/151152268-f0408ac4-c078-4a35-8ec0-b8aa3a0acb63.png)

At minimum, the hover box should have a message saying "no further promotion available".
Optionally, the button could also be greyed out.

**Comment by macdjord** [comment]
Duplicate:  #2394
