### ISSUE TITLE
Gangs feature needs documentation

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2828]
There is no out-of-game (and almost no in-game) documentation for how gangs are supposed to work. I managed to get through BN2 using [this](https://www.reddit.com/r/Bitburner/comments/e4z6ju/wip_crime_gang_bladeburner_guide/) two-year-old guide on Reddit, plus occasionally reading the source code. Now I'm on another BN, and I can't even figure out how to *start* a gang - I've joined the Slum Snakes faction, but the 'Form gang' button isn't showing up. The guide suggests that you need different amounts of negative karma to form a gang on different bitnodes, but we have (supposedly) complete documentation for the bitnode multipliers and 'karma required for gang' is not among them.

Version: a3c599e6

**Comment by zeddrak** [comment]
As far as I know, you need approximately -54k karma to start a gang, this has been the same for all BN's I've played in.
It's not documented anywhere that I could find either, nor explained well. I just used the API to constantly try to create a gang every few seconds.

**Comment by macdjord** [comment]
Note that the question of 'Why can't I start a gang?' is only one part of what needs to be documented. The whole process and mechanics of gangs needs to be explained.

**Comment by phyzical** [comment]
yeah part of the issue with this one is i thiiink its meant to be a motivation for the user to find out how/why in the source code.

(encouraging users to understand why things don't work how they expect)

there is probably a consideration on spoilers also
