### ISSUE TITLE
Remove defeated NPC gangs from territory page

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2829]
AFAICT, once an NPC gang is reduced to 0 territory, it will never regain any nor will it clash with you again. However, these defeated gangs continue to be listed on the 'Territory' tab, slowly regaining power that will never affect anything. The interface would be cleaner if these gangs were removed from the list entirely - possibly instead being added to a separate list on the same page of 'defeated opponents' (without, of course, showing their now-irrelevant power or win chance).

Version: a3c99e6

**Comment by phyzical** [comment]
seems like a reasonable request.

leaving to higher powers
