### ISSUE TITLE
Bug: leaving vim editor results on changing it to nano

### ISSUE THREAD

**Issue by LemmonPa** [danielyxie/bitburner#2830]
while using vim as editor if i change the tab (changing to terminal) and going back results in changing from vim editor to nano editor.
it's like it changing from vim mode to nano mode
first time opening editor:
![pic-selected-220126-1149-23](https://user-images.githubusercontent.com/53460243/151159652-8be3bb54-0c03-41fd-a0be-8255ac16e1aa.png)
changing tab:
![pic-selected-220126-1148-53](https://user-images.githubusercontent.com/53460243/151159742-270e27d9-82a2-4722-9802-e34d377606d7.png)
going back to editor:
![pic-selected-220126-1150-12](https://user-images.githubusercontent.com/53460243/151159787-d02bbb73-a3fd-41a6-9dcb-d4d29997de5d.png)

//linux _ steam bitBurner v14.0.2 ??

**Comment by JParisFerrer** [comment]
If you click on the Options gear in that screenshot, there is a "vim mode" toggle. I've found that if you toggle that, then going to terminal and back loads in as vim mode. Otherwise, I experience the same behavior you mention where `vim file` doesn't change the default to vim mode

**Comment by stefanmohl** [comment]
The option isn't the global options, it is the *editor* options!

**Comment by JohannesPertl** [comment]
Has there been a change? There is no vim mode option. There is an option in the Misc settings of the global options, but it doesn't do anything either.

Edit: Had to close the already open file, then it opened in vim correctly
