### ISSUE TITLE
Find All Valid Math Expressions contains an incorrect example

### ISSUE THREAD

**Issue by zaskokus** [danielyxie/bitburner#2835]
```
(...)
NOTE: Numbers in the expression cannot have leading 0's. In other words, "1+01" is not a valid expression Examples:

Input: digits = "123", target = 6
Output: [1+2+3, 1*2*3]

Input: digits = "105", target = 5
Output: [1*0+5, 10-5]
```
The last example provided should contain: `Output: [1*0+5, 0+5*1, 10-5]` also the contract does not specify if `5*1+0` differs from `0+1*5` or not. While it does not differ mathematically, contract should at least give a hint on that. I believe that was partially adressed by https://github.com/danielyxie/bitburner/pull/2769 as of "Normal order of operations applies" but should be expanded further.

**Comment by zeddrak** [comment]
You can't re-arrange the digits, you can only add symbols. So 0+5*1 isn't valid, neither is 5*1+0. This also resolves the issue of equivalent, but re-ordered (5*1+0 and 0+1*5 are not both possible for a single given input.)
(Can be closed.)

**Comment by zaskokus** [comment]
@zeddrak The whole contract is as follows:
```
Find All Valid Math Expressions
You are attempting to solve a Coding Contract. You have 10 tries remaining, after which the contract will self-destruct.


You are given the following string which contains only digits between 0 and 9:

7392383093

You are also given a target number of 29. Return all possible ways you can add the +, -, and * operators to the string such that it evaluates to the target number.

The provided answer should be an array of strings containing the valid expressions. The data provided by this problem is an array with two elements. The first element is the string of digits, while the second element is the target number:

["7392383093", 29]

NOTE: Numbers in the expression cannot have leading 0's. In other words, "1+01" is not a valid expression Examples:

Input: digits = "123", target = 6
Output: [1+2+3, 1*2*3]

Input: digits = "105", target = 5
Output: [1*0+5, 10-5]
```
Despite of my best efforts I can not see what you just said. It is very unclear that the input string has to remain in its original order.

**Comment by zeddrak** [comment]
correct.
`you can add the +, -, and * operators to the string` (no permission is given to re-arrange the string)

**Comment by zaskokus** [comment]
It did not say that I can't touch it either. Some better wording would make it much more clear. I'm not a native English speaker and that was truly confusing until you cleared it up.
