### ISSUE TITLE
Missing property "maxRamExponent" in server metadata

### ISSUE THREAD

**Issue by froxxxy** [danielyxie/bitburner#2840]
I just stumbled over servers with zero ram, i.e.:

```
[crush-fitness ~/]> free

Total:     0.00B

Used:      0.00B (0.00%)

Available: 0.00B
```

I assume this happens because of missing declaration of property `maxRamExponent` in `serverMetaData`,   in `/src/Server/data/servers.ts`. (Bitburner v1.4.0 (a3c599e6))

List of Servers with this issue:

ecorp
megacorp
b-and-a
nwo
clarkinc
4sigma
kuai-gong
fulcrumassets
stormtech
defcomm
infocomm
icarus
taiyang-digital
galactic-cyber
aerocorp
zb-def
applied-energetics
deltaone
nova-med
zeus-med
syscore
comptek
johnson-ortho
crush-fitness
snap-fitness
The-Cave
w0r1d_d43m0n

Furthermore server `w0r1d_d43m0n` is missing the property `networkLayer`, I don't know if this could cause issues, too.

**Comment by zeddrak** [comment]
Servers with zero ram is intentional (as far as I can tell). Not every server is meant to be that type of a resource (especially those last two...).

**Comment by froxxxy** [comment]
If that's the case it's quite ugly I think...

also:

```
[crush-fitness ~/]> analyze
Analyzing system...
[||||||||||||||||||||||||||||||||||||||||||||||||||]
crush-fitness: 
Organization name: Crush Fitness
Root Access: YES
Can run scripts on this host: YES
Backdoor: NO
Required hacking skill for hack() and backdoor: 243
Server security level: 37.870
Chance to hack: 47.62%
Time to hack: 3 minutes 40.599 seconds
Total money available on server: $52.749m
Required number of open ports for NUKE: 2
SSH port: Open
FTP port: Open
SMTP port: Closed
HTTP port: Closed
SQL port: Closed
[crush-fitness ~/]> 
```

It says `Can run scripts on this host: YES` there. This is weird behaviour if it's intentional to NOT use this server as resource.

**Comment by zeddrak** [comment]
Well, I can confirm at least that w0r1d_d43m0n is supposed to be missing network layer (SPOILER: at least when first created).
Also, you can run scripts (like manual hack, etc.) on those servers...

**Comment by froxxxy** [comment]
I still think it's ugly, but I will survive this. :)
