### ISSUE TITLE
Bug: [Corporations] Material Demand and Competition Ranges erroneous?

### ISSUE THREAD

**Issue by daziegler** [danielyxie/bitburner#2843]
I was sifting through the source code to understand why I had some unexpexted behaviour (AI Core sell rates where all over the place, even though no visible changes were made), and found the following inconsistency: 
Some demand- and competition ranges are set to things like [80, 9] instead of the presumably correct [80,99] or sth along these lines.

``` javascript
case "Robots":
  this.dmd = 90;
  this.dmdR = [80, 9]; // This is unexpected
  this.cmp = 90;
  this.cmpR = [80, 9]; // This too
  // ... more code
case "AI Cores":
  this.dmd = 90;
  this.dmdR = [80, 99]; // This seems like it should be, [smaller number, larger number]
  this.cmp = 90;
  this.cmpR = [80, 9]; // This too
  // ... more code
```

It seems this happened in the following commit:

https://github.com/danielyxie/bitburner/commit/c4cb7daac586b9a5ff93ca794d54c954d833af3c#diff-cc7aaa27b613e9c12e88fdc66faa2ce9dbbbd62cef8df85e68cf032215a2f762L137

In case this is actually a bug and someone has the correct numbers I can make a PR, just didn't want to bother in case it's working as intended.

**Comment by hydroflame** [comment]
Yeah that looks like a bug for sure.
