### ISSUE TITLE
Webpack-dev-server broken after commit 8c9be166

### ISSUE THREAD

**Issue by SagePtr** [danielyxie/bitburner#2847]
After commit 8c9be166, the webpack dev server (which is run by ```npm run start:dev```) doesn't watch for changes anymore. To make the game apply changes, you need to manually recompile everything, restart the dev server and reload the tab. Which is VERY annoying compared to the previous scheme when the changes automatically applied and the tab was hot-reloaded.
The last good commit is 26d5e4da.

**Comment by Sevenrou** [comment]
I think you can use `npm run watch:dev ` to watch for changes.

**Comment by smolgumball** [comment]
Also noticing this behavior, as well as some webpack errors re: `module './screenshot.png' not found.` 

Doing an `npm install` also results in package.lock changes, which leads me to believe the latest lockfile hasn't been committed with recent changes?

**Comment by hydroflame** [comment]
Fixed.
