### ISSUE TITLE
Gang member ascend bonus lowered after player installing augments

### ISSUE THREAD

**Issue by Brady-Edwards** [danielyxie/bitburner#2849]
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by SagePtr** [comment]
It's feature, not a bug. Added in 1.4.0.

**Comment by Brady-Edwards** [comment]
Thank you! Sorry for accidentally sending the report before filling it in too.
