### ISSUE TITLE
ns.growthAnalyze gives vastly incorrect values

### ISSUE THREAD

**Issue by zeddrak** [danielyxie/bitburner#2853]
[discord discussion](https://discord.com/channels/415207508303544321/459097632896188436/935354169370476626)

Basic problem:
Grow adds grow threads, then multiplies
GrowthAnalyze doesn't take this bonus into account, and so return much larger thread counts than are actually needed
This problem is exacerbated by the fact that the internal code uses these massive overestimates when pro-rating the security gains for overgrows.

**Comment by zeddrak** [comment]
Some proposed solutions (only use one of these):
#2855
#2858

**Comment by dwRchyngqxs** [comment]
The solution using Newton-Raphson method #2881
