### ISSUE TITLE
BladeBurner City Population Problem Limiting Script Efficiency

### ISSUE THREAD

**Issue by Playegage** [danielyxie/bitburner#2861]
There should be a function to get the accuracy or range of error for the synthoid population of a given city. The moment the only way to do so is to take the hardest operation or black op and get its difficulty. If the numbers match then you have 100% accuracy, if not then you don't. But that only works early game. Late game when you have stats high enough, everything becomes 100% chance even if you have low accuracy, thereby making it impossible to tell if you are still in the city with the highest population.

**Comment by phyzical** [comment]
closable as a duplicate
