### ISSUE TITLE
BladeBurner City Chaos Problem

### ISSUE THREAD

**Issue by Playegage** [danielyxie/bitburner#2862]
There should be a skill or augment to increase the amount of chaos that you remove with each run of Diplomacy. As it stands it is not nearly enough because of diminishing returns. Lets say you are at a 2% reduction with your charisma. Now lets say that you want to stop doing things at 100 chaos and resume at 50. 100-2%=98 then 98-2%=96.4 then 96.4-2%=94.472 and so on and so forth. It doesn't matter if you start lowering it at 100 or 100000, what matters is how far down you want it to go. If you want to go from 100% of the current value to 50% of the current value it will always take the same about of time, which is a long time, because every time you remove 2% of the total, the next time you obviously remove 2% less.

Below is the current process to reach 50% going down 2% at a time. It takes 35 iterations running for a total of 35 minutes. If you were to try to get rid of it full then to reach 1%, because reaching 0 even is impossible when reducing by percentage, it would take 228 iterations or 3.8 hours to complete. If an upgrade allowed you to get the reduction even just up to 5% then it would take only 15 minutes to get down to 50% and 90 iterations over an hour and a half to reach 1%.

Currently, the players charisma has to hit 4300~ to get to an effectiveness of 5%.

The below function in Bladeburner.tsx should incorporate the upgrade when making its calculation.

getDiplomacyEffectiveness(player: IPlayer): number {
    
    // Returns a decimal by which the city's chaos level should be multiplied (e.g. 0.98)
    
    const CharismaLinearFactor = 1e3;
    const CharismaExponentialFactor = 0.045;

    const charismaEff = Math.pow(player.charisma, CharismaExponentialFactor) + player.charisma / CharismaLinearFactor;
    return (100 - charismaEff) / 100;
  }

**Comment by zeddrak** [comment]
1) There is a rounding threshold, as well as a (much earlier) practical threshold that make it possible to reduce it to effectively 0.
2) There is a bladeburner skill to reduce the time it takes to do each diplomacy,
3) There are quite a few augments that increase cha and cha gain rate.
4) Diplomacy isn't the only way to reduce chaos...

**Comment by phyzical** [comment]
(might be worth asking in discord for some help on this one)
