### ISSUE TITLE
Unclear instruction for coding contract "Sanitize Parentheses in Expression"

### ISSUE THREAD

**Issue by timotheeandres** [danielyxie/bitburner#2865]
Version: BitBurner 1.4.0 (49de4a28)

In the coding contract "Sanitize Parentheses in Expression", the following sentence is written:
> "If it is impossible to validate the string the result should be an array with only an empty string"

along with the example:

> `")( -> [""]`

Now, I understood from this that if a string cannot be validated without having to remove the parentheses, an emptry string must be returned. However, when I got the input ")aa))(a" and submitted as an answer `[""]`, it was considered wrong.

Digging into the code, I ran the solver on the data, and the solution was `["aaa"]`. So, either the documentation is misleading and the sentence should be removed, or the solver should return `[""]` when it removed all parentheses.

**Comment by zeddrak** [comment]
I mean, it says
> remove the minimum number of invalid parentheses in order to validate the string

So I don't know why you would think it'd have to be validated without removing parenthesis (removing parenthesis is literally the task, it's just about removing as few as possible).

It also doesn't say to remove letters, so aaa would be a valid solution with the minimum number (all) of the parenthesis removed.

The empty string is for when there are no letters (like in the example) and all strings have been removed..

**Comment by trhr** [comment]
Ahhh.. I have never been able to figure this out, because "aaa" is not a valid expression. I thought it was looking for a minimum of aaa() or something similar. Clarifying it to say "return all the letters" would go a long way.

**Comment by zeddrak** [comment]
Yeah, I think one of the other ones mentions that, I'll see if I can find it and clone the text.

**Comment by zeddrak** [comment]
But aaa is just a variable name? So it'd be valid, right?  ;)

**Comment by zeddrak** [comment]
I think the idea is that things like aa(a) and a(aa) would be valid expressions, whereas a()a or a(a)aa would not...

**Comment by zeddrak** [comment]
So the letters create sort of anchor points or the like. It's not just return the letters (though you can't remove them, so they will all be in the final string).

**Comment by phyzical** [comment]
is there any words saying something along the lines of " the minimum removed parenthesis can also be all the parenthesis removed" ? maybe that would make it painfully obvious?
