### ISSUE TITLE
exec() function confusing

### ISSUE THREAD

**Issue by Cyakat** [danielyxie/bitburner#2866]
In the documentation, the exec() function says that it takes an array as the fourth argument but it actually just takes multiple arguments that can be either a string, number, or boolean. When I tried to pass an array, I got an error.

https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.exec.md

![image](https://user-images.githubusercontent.com/36944093/151672640-8d51f15d-f47f-4b02-878d-d80813d04dc2.png)

This just appears in the documentation.

**Comment by zeddrak** [comment]
I believe the ... of ...args indicates that the array is to be expanded in the parameter list.

**Comment by dowinter** [comment]
Indeed, this is a language feature, variable parameter lists are always denoted with `...args`.
If you WANT to use an array, you can simply explode it:
```
let args = ["arg0", 1, true, "arg3"]
ns.exec("/management/analyze.js", "home", 1, ...args)
```

**Comment by Cyakat** [comment]
Ah ok. I had never really seen that before but that makes sense. I work usually but i'm still learning. Cool to know though. Thanks!

**Comment by zeddrak** [comment]
can close?

**Comment by sirlancelot** [comment]
Note the spread operator `...args`. This is JavaScript feature and is not specific to Bitburner. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by phyzical** [comment]
closable

**Comment by Cyakat** [comment]
I'll close this I realize that I am still new to js and have more to learn. Thanks for your help

**Comment by worc** [comment]
the docs are still wrong, it doesn't take an actual array. if you try to pass one through, the game throws an error and says that the object isn't a valid argument.

it's also not spread syntax but _rest parameters_: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters

it's a very different situation. you don't _pass in_ an array. instead, your list of arguments is _converted_ into an array in the body of the function.
