### ISSUE TITLE
Feature request - have log pick up console.warn() message

### ISSUE THREAD

**Issue by climatebrad** [danielyxie/bitburner#2870]
I'm not a good enough Javascript coder to know if this is possible - if it's not, please DNF this, but it would be wonderful if console.warn() could be picked up by the log in the same way that throwing an exception is picked up.

Use case is being able to write functions without passing ns to them and being able to print messages to the log without calling ns.print().

**Comment by waffleattack** [comment]
if you don't want to have to pass ns to every function, you can create a global variable ns i believe

**Comment by climatebrad** [comment]
There are various problems that can cause.

**Comment by phyzical** [comment]
sadly i dont think the ns spam will go away anytime soon

its just so intertwined 

closable imo

**Comment by hydroflame** [comment]
Not feasable. That's now how js works.
