### ISSUE TITLE
Add empty directorys and mkdir command

### ISSUE THREAD

**Issue by L0ric0** [danielyxie/bitburner#2871]
Version Bitburner v1.4.0

At the moment directorys are automatically deleted when the last file in them is removed which is quite confusing and unintuitive. Also no command like `mkdir` exists which makes it quite hard to discover that one can create directories with the editor.

**Comment by phyzical** [comment]
+1 for this i see no reason to remove dirs on last file (on principle), 
but maybe there's an underlying reason int he source code

and +! to a mkdir function i remember wanting it back when i first started playing, although you can achieve it with other commands. 

so there are current workarounds.

happy to try to implemented if accepted

**Comment by hydroflame** [comment]
folders are fake this isn't feasable.
