### ISSUE TITLE
connect to IP doesn't work

### ISSUE THREAD

**Issue by Soyaro666** [danielyxie/bitburner#2877]
Heyho. I just tried to connect to a server using it's IP as suggested by the help page of connect. It told me that I couldn't directly connect to that IP.

Terminal-input and -output, relevant passages marked:
[home ~/]> help connect
Usage: connect [hostname]
Connect to a remote server. The hostname **or IP address** of the remote server must be given as the argument 
to this command. Note that only servers that are immediately adjacent to the current server in the network can be connected to. To 
see which servers can be connected to, use the 'scan' command.

[home ~/]> scan
Hostname        IP       Root Access
**n00dles         3.3.9.6**  Y
foodnstuff      12.9.1.0 Y
sigma-cosmetics 66.4.3.0 Y
joesguns        81.7.0.1 Y
hong-fang-tea   80.3.7.5 Y
harakiri-sushi  84.2.9.9 Y
iron-gym        91.0.5.3 Y
[home ~/]> connect 3.3.9.6
**Cannot directly connect to 3.3.9.6**

reproduced in steam-version 1.4.0 (49de4a28), and browser-version 1.4.0 (a3c599e6)

**Comment by trhr** [comment]
yeah, this has been broken for a while. i can't think of a single use-case where i'd want to connect via IP, particularly since hostnames tab-complete and IPs don't. i'm guessing the function was removed from the game but the help text wasn't updated.

**Comment by Soyaro666** [comment]
well. ingame there might be no reason. I just tried to write it "realistically" where I would pick the IP as soon as possible to avoid spamming dns requests. I guess for immersion reasons the player should have a slight speed increment when using IP-address instead of hostname whenever time is a factor, but first the IP needs to be working...

**Comment by phyzical** [comment]
@Soyaro666 could you please refactor the issue to be a feature request, given the last reply :)

**Comment by hydroflame** [comment]
No documentation should say you can connect by IP.
