### ISSUE TITLE
Retiring all synthoids in a city causes your population estimate to become 100% inaccurate

### ISSUE THREAD

**Issue by ionori** [danielyxie/bitburner#2879]
Retiring all synthoids in a city causes your population estimate to become 100% inaccurate, and you have to grind field analysis hundreds of times to get it back to normal. Without reading the code, I'm guessing the game generates a few million synthoids if there are 0 left in the city, but does so after updating your estimated population to 0, making the estimate 100% wrong.

How to reproduce:
Run raids until the synthoid population is a few million strong
Note the success chance of ops and population estimate
Run more raids until the population reaches 0
Note the success chance of ops is now 0-100%

Running Bitburner v1.4.0 (49de4a28) from Steam

Here's a save that's 2 raids away from the bug
[synthoid genocide bug.zip](https://github.com/danielyxie/bitburner/files/7965929/synthoid.genocide.bug.zip).

**Comment by zeddrak** [comment]
Yes, you have no KNOWN synthoids in the city, therefore you have no information to estimate from and anything is possible. Try running some investigations and see if your estimate increases (it probably will)...
