### ISSUE TITLE
Sleeve 'getTask' SleeveTask is missing className

### ISSUE THREAD

**Issue by Cireminer** [danielyxie/bitburner#2884]
https://github.com/danielyxie/bitburner/blob/master/src/NetscriptFunctions/Sleeve.ts#L166
sl.className is required to determine which class the sleeve is currently enrolled in, similar to gymStatType

SleeveTask interface - https://github.com/danielyxie/bitburner/blob/master/src/ScriptEditor/NetscriptDefinitions.d.ts#L1025

**Comment by phyzical** [comment]
@Cireminer to confirm this is just about it missing from netscript definition correct?

**Comment by vladtepesch** [comment]
@phyzical currently it seems to be not possible to get the classes name that a sleeve is currently taken as it is missing in the netscript interface
