### ISSUE TITLE
No Singularity functions exist to automate buying WSE account and TIX api

### ISSUE THREAD

**Issue by bmartin1234** [danielyxie/bitburner#2889]
Bitrunner v1.4.0 (49de4a28)

There does not appear to be any api function to buy a WSE account, buy the TIX api, or buy the 4S data api.

How am I supposed to destroy a bitnode afk with a single run command? Am I supposed to just NOT USE the stock market?

**Comment by zeddrak** [comment]
They're in the TIX interface [Tix](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.tix.md)
purchase4SMarketData()
purchase4SMarketDataTixApi()

**Comment by bmartin1234** [comment]
Ah yes, you're correct!

But what about purchasing a WSE account?

**Comment by zeddrak** [comment]
I think you're meant to get those through BN 8 (If I remember the number correctly, maybe it's a different one)

**Comment by phyzical** [comment]
might be closable?
