### ISSUE TITLE
SUGGESTION: API for connect terminal command

### ISSUE THREAD

**Issue by ismotee** [danielyxie/bitburner#2893]
I was wondering is there any chance of getting connect method to ns API? There's almost every other command from terminal in API so it is a little bit strange that connect isn't there. It has obvious use cases when the User/Player wants to search host and connect to it using scripts.

I'd expect `ns.connect(host: string)` to work so that terminal would try to connect to the host.

There's connect method right now but it seems to do something completely different than expected. (I haven't played to the point where `Singularity.connect()` makes any sense. Also it costs 32GB so I guess it's not the same connect I'm searching for.)

(Alternative solution would be possibility to run native commands of the terminal for example  `ns.systemRun("connect " + hostName + "; cd myScripts; run hackEmAll.js")`. Even though I suggest this alternative approach I'm not a big fan of it. The approach would be quite hard to implement mem reservation-wise.)

**Comment by tyrope** [comment]
`Singularity.connect()` is what you're looking for. If you're not at the point where you need that yet, you don't need `ns.connect()` either.

**Comment by ismotee** [comment]
Ok. Good to know. Although 32GB seems pretty high price for such a low level command.
