### ISSUE TITLE
Able to create two divisions in same industry.

### ISSUE THREAD

**Issue by tyrope** [danielyxie/bitburner#2899]
[Save file (Rename from .txt to .json, due to github limitation)](https://github.com/danielyxie/bitburner/files/7986727/multipleDivisions.txt)

### Minimal scripts to reproduce the issue
```js
ns.corporation.createCorporation("TestCorp", true);
ns.corporation.expandIndustry("Agriculture", "Agri1");
ns.corporation.expandIndustry("Agriculture", "Agri2");
```
### Minimal steps to reproduce the issue
1) Notice how in the save file the corporation has both 'Foodworks' (an unfortunate misnomer on my end) and 'AgriWorks' divisions, both working the agriculture industry.

### Steps to reproduce
Script above.

### Version of the game
v1.4.0 (49de4a28) - Steam

**Comment by phyzical** [comment]
ill take this one should be an easy fix 👍
