### ISSUE TITLE
[Feature Request] Add Scroll Arrows to Script Editor Tab bar

### ISSUE THREAD

**Issue by Chrisch3n** [danielyxie/bitburner#2900]
**Version**: Bitburner v1.4.0 (49de4a28) - Steam Version

**Current behavior** (If you don't miss a UI element):
- You have to "scroll" the Script Editor tabs by grabbing a tab with the mouse and moving it to the edges, if the number of tabs do not fit the game window.
- Furthermore, if you view another window (e.g. Terminal), you have to "scroll" to it again (Generally not a big problem but without scrolling quite annoying).

Both behaviors are visible in the GIF.
Note: Unlike shown in the GIF (small window for recording), the actual code stays readable and does not scroll out of view, so this is not a concern at normal size.
![Current](https://user-images.githubusercontent.com/19817826/152194690-ca5d1f27-9000-47c3-8090-b37d294ab73d.gif)

**Suggested behavior**:
- It would be great if you could add scroll arrows like in web browsers to the tab bar in the Script Editor to make scrolling easier.
- To keep the last active tab visible, if you return to the Script Editor, would be good as well, but is not necessary.
Quick concept shown in orange: 

![withArrows](https://user-images.githubusercontent.com/19817826/152195135-9842a94c-a2bf-4852-baa8-c089d0bb73eb.png)

**Comment by phyzical** [comment]
hmm i agree we should have a way to allow the user to get back,

@Chrisch3n mind trying a few things for me
* if you leave the editor and come back does it reset?
* if you hold shift and scroll does it go left and right instead of up and down?

**Comment by Chrisch3n** [comment]
@phyzical 
> * if you leave the editor and come back does it reset?

I'm not 100% sure, if I understand your question correctly, but the current behavior is:
1. I "scroll" to a Tab outside of the normally visible area (let's say, I have 20 Tabs open and want the 20th, to make it extreme) and select that Tab, to work on the script OR I create a new script with "nano", that opens a tab outside the visible area in that example
2.  I switch to the "Terminal" (or any other game window outside the "Script Editor") and then return to the "Script Editor" without doing anything else
3.  After returning, the actual script in Tab 20 will still be active and visible, but the Tab bar won't keep its last scroll position. It jumps back to the default position, meaning Tab 1 is visible on the left side, then Tab 2 and so on until the screen "ends" and you have to scroll to see the active Tab in the Tab bar.

If you want to copy-paste or cross-reference between 2 scripts outside the visible area, this behavior can get annoying, but I'm aware, that I can just close the other currently unnecessary tabs. - That's why I just noted that behavior as "could be improved", and not as a bug or big problem.


> * if you hold shift and scroll does it go left and right instead of up and down?

Yes it does. Both in the actual script and in the Tab bar.
This solves my main problem, thank you. I was not aware, that this feature existed. I only tried normal scrolling, because that's what I knew from the browser-tabs. 
Maybe a corresponding hint can be added to the manual or game in addition or instead of the scrolling arrows to help other users.

**Comment by phyzical** [comment]
@Chrisch3n happy to help, i agree its somthing we need to work on maybe some sort of dropdown once they get too far out or something.

yeah turns out that shift+alt is a common accessibility thing so you can use it with many other applications :)

actions for this issue:

* add some tips/hints as workaround
* as for the too many tabs situation, this might help https://github.com/danielyxie/bitburner/issues/2132

Oh and there is also a pr to try to even distribute the tabs down to minimum size of i think 20px but that wont really help here as you would still have too many tabs
