### ISSUE TITLE
[Feature Request] Save Script Editor Tabs automatically

### ISSUE THREAD

**Issue by Chrisch3n** [danielyxie/bitburner#2901]
**Version**: Bitburner v1.4.0 (49de4a2) - Steam Version

**Current behavior:**
- Unsaved scripts within the Script Editor are discarded or reset to old values, when the game is closed. 

**Expected/Suggested behavior:**
- _[Preferred]_ Scripts will be automatically saved, every time the "Game saved" popup appears (As they have already a filename assigned to them) or alternatively at least a Save on normal shutdown of Bitburner (Optionally with a pop-up like: "You have unsaved files. Do you save or discard them.")
**OR**
- _[Less optimal]_ Clear warning in documentation and In-game, that scripts have to saved manually (and regularly if crash happens) before closing the program to avoid data loss
- And a more visible distinction between saved and unsaved files (The small "*" behind the filename can easily be ignored) - Ideas:
  - A different color of the saved/unsaved tabs in the Script Editor
  - A red notification dot (like for augmentations) with a "u" for unsaved ones
  - A Floppy-Icon for saved scripts and/or a crossed out Floppy-Icon for unsaved ones (This variant could let users think, that clicking the icon will save the script, and is therefore less optimal if not implemented this way)

**Reason**: The usual behavior of a program, especially if you already assign a filename to a file (here via: "nano xyz.js") is, to save the progress and this was my working hypothesis here as well (Especially with the regular "Game saved" popup). 
I have already lost time intensive scripts on 2 occasions because I closed the program without saving, and was unaware, that I had to (I'm apparently not a quick learner ;) ). My currently existing scripts are more or less based on luck, because I pressed the Save-button on instinct, but if you forget an opened script, it's gone or reset to its old values.
This is not really beginner-friendly (and for me unexpected behavior)

**Comment by phyzical** [comment]
if accepted: maybe we can look at making this a user option?

i dont think we should do it be default. what if the user didnt want it to save, say they clicked away to check a constant or something and then they left a blaring error in their code but was not ready to save.

**Comment by phyzical** [comment]
(sadly theres a whole pile of roadblocks with why things "reset" on game restart)

once you start become a coding god ;) , it may make more sense but imagine your trying to add functionality to a magic script while its running (min, maxing to the extreme) and it just crashes mid way through a big operation when in reality you were still trying to tweak it for the next run.

Oh and might be worth looking in the vscode integration. the editor is great, but eventually you will be looking for something like it im sure.
