### ISSUE TITLE
Working for a faction when 'ns.installAugmentations()' drops into recovery mode

### ISSUE THREAD

**Issue by dampersand** [danielyxie/bitburner#2902]
upon running `ns.installAugmentations()` WHILE focused and working for a faction, the game installs all augs and then drops into recovery mode.  This happens regardless of arguments passed to ns.installAugmentations() (this prevents the cbScript argument in ns.installAugmentations() from being run)

![recovery](https://user-images.githubusercontent.com/4218669/152252772-913846b0-9d19-423f-a360-87ff96773efb.png)

fun side effect, after hitting this screen, the floppy disk 'save' icon in the overview is now permanently red in my game. Not the bug, but a fun aside. :)

**Save files**
The following is a save file that I have doctored to reliably reproduce the issue, but I can also provide both the save file where the crash happened (twice) in the wild, or the save file created from the recovery splash.
[debug.txt](https://github.com/danielyxie/bitburner/files/7990593/debug.txt)

**Minimal scripts to reproduce**
assume an augmentation is purchased and staged for install, and that the player has accepted an invite from Tian Di Hui:
```/** @param {NS} ns **/
export async function main(ns) {
ns.workForFaction("Tian Di Hui", "Hacking Contracts", true)
ns.installAugmentations()
}
```

**steps to reproduce**
From the debug save file above, run "/wintermute/debug.js", which emulates the test scenario above.  the script should cause the crash.

**Version of the game:** Bitburner v.1.40 (49de4a28)

Godspeed, you fantastic, wonderful human beings.

**Comment by pd** [comment]
Happened to hit this with console open so was able to grab the stacktrace:

```
TypeError: Cannot read properties of undefined (reading 'name')
    at w (WorkInProgressRoot.tsx:50)
    at to (react-dom.production.min.js:157)
    at Lo (react-dom.production.min.js:180)
    at Ws (react-dom.production.min.js:269)
    at ju (react-dom.production.min.js:250)
    at Ou (react-dom.production.min.js:250)
    at xu (react-dom.production.min.js:250)
    at fu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18) {componentStack: '\n    at w (file:///F:/SteamLibrary/steamapps/commo…/Bitburner/resources/app/main.bundle.js:1:278700)'}
```

**Comment by phyzical** [comment]
@pd @dampersand do you guys happen to have a save file to replicate this? i have a fix but i want to test it to confirm what the new outcome would look like

**Comment by phyzical** [comment]
ah all good found your save file in another linked issue
