### ISSUE TITLE
Sleeves do not reset location when starting a new BitNode

### ISSUE THREAD

**Issue by inigo** [danielyxie/bitburner#2905]
On starting a new BitNode, everything about existing sleeves is reset apart from their location. The player's location is reset to Sector-12. A new sleeve's location is set to Sector-12. The existing sleeves' locations should be reset along with the player.

To reproduce:

* Move all sleeves to a non-Sector-12 city
* Finish the BitNode
* In the new BitNode, observe that the sleeves are still wherever they were in the previous BitNode.

This looks like it would be a change to Sleeve#prestige.

**Comment by waffleattack** [comment]
I fixed this in #2906
