### ISSUE TITLE
All game state lost after some time on an "idle" tab?

### ISSUE THREAD

**Issue by jjarava** [danielyxie/bitburner#2907]
Hi!

I've come back to the game after a few days "off it" and the game seems to be lost/state deleted

I had an open tab for the game, on an minimised window - and I was expecting to get the "you've been training for XXX time" (that was what I was doing) or "you've been offline for XXX hours" but I got the "new tutorial" and 1k $$$ (vs several billion I had 😢 )

In case it's relevant, I'm using Safari on macOS 12.1

Thanks!

(PS: Adding the save file I get right now, but you'll see it's pretty scant)
- [bitburnerSave_1643902640_BN1x0.json.zip](https://github.com/danielyxie/bitburner/files/7995999/bitburnerSave_1643902640_BN1x0.json.zip)

Version of BitBurner - latest (v1.3.0). Which has worked before so I don't think it's an artefact of "Upgrade"?

**Comment by phyzical** [comment]
this one might be a bit hard to repo, but i would argue it might be safari + tab minimized related...

@jjarava did it like do a full refresh or did you say not restart over those "few days"
