### ISSUE TITLE
Faction favor seems locked at 3

### ISSUE THREAD

**Issue by StrikerTwo** [danielyxie/bitburner#2921]
My faction favor with BitRunners stays at 3 even when my reputation is currently 179k.
If I calculate the formula from https://github.com/danielyxie/bitburner/blob/dev/src/Faction/formulas/favor.ts manually it should be 106.
Am I missing something?
With Netburners I have a favor of 10 with a rep of 39 (just from running hacknet nodes, I guess)...

Version: Bitburner v1.4.0 (a3c599e6)

**Comment by TheMas3212** [comment]
favor is only gain when you install augments

**Comment by StrikerTwo** [comment]
If that's the case, it's pretty pointless, no?
I need rep to buy the augments in the first place. I have trillions of dollars and nothing to spend them on while grinding reputation... so I thought donations would be the solution to that. But I can't donate without favor.

**Comment by StrikerTwo** [comment]
Okay, got it. I gain favor for the reputation I have when installing augments. Thanks for pointing me in the right direction.
