### ISSUE TITLE
Clicking default theme should reset default theme

### ISSUE THREAD

**Issue by mricher-git** [danielyxie/bitburner#2927]
I just changed a theme value, I didn't like the result, so I click default at the bottom, and nothing happens. One would expect the default to return. I didn't realize modifying a value would in-fact modify a built-in default, especially considering the text:

Replace the current theme with a pre-built template using the buttons below.

Modifying the values shouldn't affect the pre-built templates IMHO, there should be a "Custom" theme if that's going to remain the case, ideally in the future add an option to save your theme as a named template.

**Comment by phyzical** [comment]
hmm @mricher-git i think this is a miss understanding all it does is rest the values that appear in the popup, i.e line height.

What you would want to do is choose the default theme again.

as for `ideally in the future add an option to save your theme as a named template.` feel free to reword this issue as a feature request. 

otherwise should be closable imo

**Comment by mricher-git** [comment]
That's the thing, it doesn't reset the values. Go into theme edit, change anything you like, and close it. Open it again, click default, nothing happens, it doesn't reset any values, as if my changes overwrote the defaults.

IMHO it shouldn't overwrite the defaults. I should click default and get the default.

**Comment by phyzical** [comment]
Oh wait... i was doing the style editor.

i gave it a quick try and it looks like clicking "default" works only once and then you cant reset it back cause it thinks its already using default even though you override something again... (is my guess)

do you mind confirming if you see this happening?

as a work around for now it looks like refreshing the page restores your ability to press "default" again.

**Comment by phyzical** [comment]
as for how to fix this will just have to be careful that this isnt by design for whatever reason but proably just a bug with it thinking its already running default.
