### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (at "Terminal")

### ISSUE THREAD

**Issue by ErDietze** [danielyxie/bitburner#2928]
### How did this happen?

Start game on Android Chrome via link from Golem and step to the second step of the tutorial 

### Environment

Huawei p20 pro, Chrome Browser 

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Terminal
* Version: v1.4.0 (a3c599e6)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Linux; Android 10; CLT-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.98 Mobile Safari/537.36
* Features: lang=de cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by phyzical** [comment]
@ErDietze what is golem? 

i doubt we support a mobile devices but worth a quick repo test

**Comment by phyzical** [comment]
id say closable
