### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name') (at "Work")

### ISSUE THREAD

**Issue by kelick** [danielyxie/bitburner#2931]
TypeError: Cannot read properties of undefined (reading 'name') (at "Work")

APpears to be a duplicate occurrence of:
https://github.com/danielyxie/bitburner/issues/2804

I was running a larger script which just finished doing faction work:
- looping over ns.workForFaction('Chongqing', 'hacking', true);
And was starting to call into code to purchase augments when the crash occurred.

This has happened several times while I was away, but this is the firsttime I saw it well enough to get an idea of where the script was.

I jumped back into the game and it appears that my script may have completed in calling 
ns.installAugmentations('script.js'); and installed my augments. ...

* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.3

[RECOVERY_BITBURNER_1644196451.zip](https://github.com/danielyxie/bitburner/files/8011683/RECOVERY_BITBURNER_1644196451.zip)
6

**Comment by dampersand** [comment]
Betcha this is the same as mine:
https://github.com/danielyxie/bitburner/issues/2902

**Comment by phyzical** [comment]
closable as dup
