### ISSUE TITLE
Suggestion : An integrated moding sysstem

### ISSUE THREAD

**Issue by Alidonis** [danielyxie/bitburner#2937]
hello ! i've played this game a bit and with the open source context, tought this suggestion was a good idea. let me explain.

1st implementation (downloadable only) : a modding folder 
Players would be able to integrate their code with files and modify the game's behavior via script packages

2nd implementation (steam only) : workshop integration 
Using the workshop as a mod manager, people could have a sepparate modding tool included with the steam versions (For example, look at scrap mechanic's modding tool) which would create the package, and modders would do what they'd do best.

**Comment by phyzical** [comment]
* what sort of mods were you thinking?

could we not just request a PR and add it directly into the game? 
maybe adding the ability to use custom "forks" could be a way around this? granted there is alot of security implications doing this... so im kind of against it form the get go but an interesting request 

i.e if its adding more BNs id argue we should get it into the game for everyone to enjoy

Where as if it was custom themes hell yeah take away responsibility from the main game onto the mod providers

**Comment by Alidonis** [comment]
Well when i think mod i think a system where you can code your own mod without having to PR merge your additions. i thougth about a system with hooks where mod developer can add new method to netscript 1 or 2, maybye make their own programing language based on netscript. not my best idea, but i still think it's good because hooks can be coded such that they don't frick up everything to an unusable level. PRs could add new hooks to the game and such make the game's modding feature kept up to date

**Comment by Alidonis** [comment]
Also custom themes in general are a good idea

**Comment by zeddrak** [comment]
You can fork the game to create your own offshoot for your own use. But please note that the current [contributor license](https://github.com/danielyxie/bitburner/blob/dev/README.md#contribution) leaves copyright with the original contributors, not with bitburner's owner. A license is then granted to the author (and transferred as appropriate) to use their contributions relatively freely. Just be aware that publishing code that doesn't belong to you can be a problem unless you get permission from every contributor involved (the blame can be consulted).

Having said that, there are ways in JS to overwrite existing functions, so it's entirely possible to provide your code as a separate code file and provide options, or another interface, to enable them. They could also be easily enabled via the debugger by providing a simple start-up command that can be typed into the debugger to initialize your code.

**Comment by Alidonis** [comment]
that's great, but i'm no developer.
