### ISSUE TITLE
Stanek's Gift feature needs documentation

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2939]
There is no out-of-game (and almost no in-game) documentation for how Stanek's gift is supposed to be used. Some things that need to be explained somewhere:

- Can you get more fragments - either new types or multiples of the same type - and if so how?
- Can you increase the size of the grid, and if so how?
- Do multiple fragments of the same type, e.g. 2 +hack skill fragments, stack, and if so, additively or multiplicatively? What about booster fragments?
- If a booster fragment is adjacent to multiple cells of an active fragment, does the active fragment get boosted just once, or once per adjacent cell?
- How do the charge mechanics work? (In particular, the following facts need to be mentioned:)
  - That you can charge with multiple threads and this makes a difference
  - That charging with N threads once is not the same as charging with 1 thread N times
  - That adding more charges can actually reduce the fragment's power if it reduces the average number of threads per charge
- The Church augments talk about reducing, then eliminating, the penalty from Stanek's gift. What penalty? And what's its value before buying the first reduction augment?
- What happens to the Gift when you install augments? Does it get reset?

Note: I've figured out most of these for myself (with the exception of 'how can I get more fragments?', where I'm assuming the answer is 'you can't'), mostly by reading the code. But this information should have been provided to me, either in the game or in the manual.

Version: a3c599e6

**Comment by hydroflame** [comment]
The stanek UI should offer a popup or give a .lit files like corporations.

Check with me before implementing
