### ISSUE TITLE
Corporation API - going into debt upgrading warehouses

### ISSUE THREAD

**Issue by rj45** [danielyxie/bitburner#2942]
It's possible to use the Corporation API to buy warehouses and go significantly into debt. This can screw you over if you go into so much debt that an investment won't cover the debt. But there's reasons you might want to do this, and it gives a significant advantage. It can also be abused to drop your stock price to zero and basically then print money with a zeroed out stock price (not sure on exact details there, though, I can find out if need be)

The issue is the warehouse upgrade API call is missing a check to make sure you can actually afford the upgrade. The fix should be trivial.

After some discussion, though, we decided that we like this mechanic to an extent. We think it's fair and realistic to allow a bit of debt, but we think how much debt you can go into should be limited. Perhaps a reasonable limit is 5 or 10x the cost of the warehouse upgrade. So you can go negative only that far. Feel free to solicit other opinions on a reasonable and fair amount of debt to allow, though.

I am thinking if the API allows some limited amount of debt, though, the stock price should not be tanked by it, so there needs to be a check to prevent that. Maybe there should be a check to prevent it going to zero? I am not sure.

Potentially, as a balance measure, doing this could cause a lot of employee unhappiness? That might be more work than it's worth but seams like a reasonable penalty. 

If this is added, it should also be considered to allow someone manually playing to use the UI to go into debt buying warehouses as well... to be fair to the manual players. I think it's reasonable that the same limit be enforced in both places.

- [x] Version of the game, e.g. Bitburner v1.4.0 (a3c599e6)

**Comment by phyzical** [comment]
the other idea i randomly thought of during this discussions is maybe a new concept of "debt collectors" where if your too far into debt they can take just shut down your corporation, another user had a good suggestion if this was considered where you could "fight off" the debt collectors based on your stats., that way if the user wanted to cheese it there would be a valid use case to allow debt (then this should be an achieve also imo) this user said "You liquidated the liquidators" it s just tooo perfect imo :D 

Maybe the more in debt the more stats required to stop the debt collectors shutting down your company, so it becomes a thing that players can still choose how far into debt they can go

An alternative idea could be to allow the user to "bribe them" but this would be harder to allow via the api (what if you didn't want to bribe them)/

OFC the other way to approach this would be to just not allow going into debt.

@pigalot did you have any opinion on this? (incase your already planning to fix this in the future)

**Comment by pigalot** [comment]
The first step is to fix the bug, the only way you should be able to go into debt is when buying mats so fix that.
Anything else is balance and mechanics and that is not something contributors handle.

**Comment by phyzical** [comment]
👍 understandable just ideas, will look at fixing this
