### ISSUE TITLE
Contract data can exceed popup, becoming unreadable unless using script

### ISSUE THREAD

**Issue by aaronliu0130** [danielyxie/bitburner#2944]
- [x] Save file: [bitburnerSave_1644368939_BN1x0.txt](https://github.com/danielyxie/bitburner/files/8028588/bitburnerSave_1644368939_BN1x0.txt)
- [x] Minimal scripts to reproduce the issue: None
- [x] Steps to reproduce:
1. Open my save file and connect to `comptek`
2. `run contract-503125-CyberSec.cct`
3. Notice that the data goes outside the prompt box
![image](https://user-images.githubusercontent.com/11874211/153103055-938429f8-9147-47a3-a9d6-8da5ac62a44c.png)
- [x] Version of the game:. Bitburner v1.4.0 (49de4a28)
[bitburnerSave_1644368939_BN1x0.txt](https://github.com/danielyxie/bitburner/files/8028588/bitburnerSave_1644368939_BN1x0.txt)

**Comment by zeddrak** [comment]
does zoom out remedy this (at least as a stop-gap)
Also, as html, you should be able to copy the lines (by dragging from line above to line below); at which point you can paste the data into notepad (or whatever). Again, this is more a work-around, but it does at least provide an immediate remedy.

**Comment by aaronliu0130** [comment]
1. I use the steam release, and even with developer tools I don't think I can zoom out.
2. I just use getData()

On Feb 9, 2022, at 10:49 AM, zeddrak ***@***.***> wrote:

﻿

does zoom out remedy this (at least as a stop-gap)
Also, as html, you should be able to copy the lines (by dragging from line above to line below); at which point you can paste the data into notepad (or whatever). Again, this is more a work-around, but it does at least provide an immediate remedy.

**Comment by aaronliu0130** [comment]
Ah nvm I found the zoom out button.

On Feb 9, 2022, at 11:04 AM, aaron liu ***@***.***> wrote:

﻿
1. I use the steam release, and even with developer tools I don't think I can zoom out.
2. I just use getData()

On Feb 9, 2022, at 10:49 AM, zeddrak ***@***.***> wrote:

﻿

does zoom out remedy this (at least as a stop-gap)
Also, as html, you should be able to copy the lines (by dragging from line above to line below); at which point you can paste the data into notepad (or whatever). Again, this is more a work-around, but it does at least provide an immediate remedy.
