### ISSUE TITLE
documentation popups ignore @inheritdoc

### ISSUE THREAD

**Issue by Moire9** [danielyxie/bitburner#2945]
Methods that use `@inheritdoc` are not shown as inheriting documentation - it simply shows _`@inheritdoc`_ in the documentation popup.

```js
class NT extends NS {
	constructor() {}
	/** @inheritdoc */ clearLog() {}
}

/** @type NS */
let ns;
/** @type NT */
let nt;

function foo() {
	ns.clearLog();
	nt.clearLog();
}
```
![Documentation displayed, as expected](https://user-images.githubusercontent.com/31591796/153106708-90ca42fd-cec9-4ddf-a9ab-24462fd063d8.png) 

![Super documentation *not* displayed](https://user-images.githubusercontent.com/31591796/153106775-1087ecb8-92f6-48e6-ba01-e8eaad3fdedc.png)

Running v1.4.0 49de4a28

**Comment by hydroflame** [comment]
monaco problem, can't fix it.
