### ISSUE TITLE
BN-7 descriptions misses important change to BN-1

### ISSUE THREAD

**Issue by fdellwing** [danielyxie/bitburner#2946]
Current text:

```
In this BitNode you will be able to access the Bladeburner API, which allows you to access Bladeburner functionality through Netscript. Furthermore: 

The rank you gain from Bladeburner contracts/operations is reduced by 40%
Bladeburner skills cost twice as many skill points
Augmentations are 3x more expensive
Hacking and Hacknet Nodes will be significantly less profitable
Your hacking level is reduced by 65%
Hacking experience gain from scripts is reduced by 75%
Corporations have 80% lower valuations and are therefore less profitable
Working for companies is 50% less profitable
Crimes and Infiltration are 25% less profitable
```

> Bladeburner skills cost twice as many skill points

This is true, but also you gain half as many skill points (1 every 6 level instead of 1 every 3). This means it takes four times more ranks to gain the same skills.

This should be included in the description.

**Comment by macdjord** [comment]
@fdellwing AIUI, the text in the Bladeburner tab which says you gain points at 1/6 ranks is incorrect; you gain them at the normal 1/3 rate.

**Comment by fdellwing** [comment]
I understand. Closing this in favor of #2936
