### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'comments') (at "ScriptEditor")

### ISSUE THREAD

**Issue by lecommander** [danielyxie/bitburner#2948]
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
I exported the json on chrome and imported it in Edge
--> use nano on scripts

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'comments')
* Page: ScriptEditor
* Version: v1.4.0 (a3c599e6)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.55
* Features: lang=de cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
``
[RECOVERY_BITBURNER_1644484087.json.txt](https://github.com/danielyxie/bitburner/files/8039650/RECOVERY_BITBURNER_1644484087.json.txt)
`

**Comment by phyzical** [comment]
@lecommander hey i was able to import and open your script in nano without any issue. or are you saying this only occurs of edge?
