### ISSUE TITLE
Random "<script> has no main function" errors after copying script with `ns.scp()`

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2953]
I have a script which does the following:
```javascript
/** @param {NS} ns **/
export async function main(ns) {
	// Servers to run weaken scripts on; defaults to current server
	const host_servers = (ns.args.length > 0) ? ns.args : [ns.getHostname()];

	// Script names
	const script_weak = "/superhack/weak_min.js";

	// Copy scripts to host servers
	for (const host_server of host_servers) {
		if (host_server == ns.getHostname()) { continue; }
		await ns.scp(script_weak, ns.getHostname(), host_server);
	}
	await ns.sleep(100);

	... // (Code which runs weak_min.js on the host servers with various arguments, at 10s intervals)
}
```
Sometimes, when I run this script, I get runtime errors from some of the servers telling me that `/superhack/weak_min.js` has no main function.

* It doesn't always happen, and when it does, it doesn't affect every server
* When it does happen, more than one server is affected
* It only ever happens on the first batch of scripts launched; when the second batch is launched 10s later, they always all work
* There doesn't seem to be any pattern I can find to which servers are affected
* There may be a correlation between which servers are affected and which servers already had a copy of `/superhack/weak_min.js` which got overwritten by the scp operation
* At one point, I thought the problem was a race condition, where `ns.scp()` would return after the script had been successfully copied but before the new copy had been analyzed and compiled, which is why I added the `ns.sleep()`, but this didn't fix the problem, even when I increased the sleep time to 10s.
* This is very likely related to #2295, but is clearly not an exact clone, since adding `sleep()` didn't fix it

Version: a3c599e6

**Comment by macdjord** [comment]
@phyzical ... you have to export main for netscript to work? Or at least that's what the netscript tutorial says.

**Comment by phyzical** [comment]
ah derp sorry, havn't played in a few days 😆 disregard

**Comment by Faustvii** [comment]
This most likely the same issue as described here https://github.com/danielyxie/bitburner/issues/1714

**Comment by hydroflame** [comment]
duplicate

**Comment by Penumbra69** [comment]
> duplicate

To? Can we get a issue # or a link?
