### ISSUE TITLE
Can launch multiple copies of a script with same arguments on same host using `exec()` from multiple servers

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2956]
* Create the following scripts on `home`:
  * `test_run.js`:
  ```javascript
  /** @param {NS} ns **/
  export async function main(ns) {
  	const deploy_from_servers = [
  		"n00dles",
  		"foodnstuff",
  		"sigma-cosmetics",
  		"joesguns",
  		"hong-fang-tea",
  		"harakiri-sushi",
  		"iron-gym",
  	];
  	const host_server = "home";
  	const test_script = "/test_sleep.js";
  
  	for (const deploy_from_server of deploy_from_servers) {
  		ns.connect(deploy_from_server);
  		ns.exec(test_script, host_server);
  		ns.connect("home");
  	}
  }
  ```
  * `test_sleep.js`:
  ```javascript
  /** @param {NS} ns **/
  export async function main(ns) {
  	await ns.sleep(60 * 1000);
  }
  ```
* Run `test_run.js` from the terminal (Singularity functions required)
* Check active scripts; you will find 7 copies of `test_sleep.js` all running on `home`, all with the same arguments (i.e. none)
* These script entries will behave very oddly; it is impossible to open the logs tab for one of them if the logs tab for another is already open, and if you expand one of them in the active scripts tab, then hit the 'kill' button, the killed script will vanish, but the next script's entry will spontaneously expand in its place

Version: a3c599e6

**Comment by phyzical** [comment]
i think the fact you can run multiple scripts with the same args is valid.

But the log bug is probably a bug related to scripts getting confused or rather not being unique enough.

**Comment by macdjord** [comment]
@phyzical No, by design you cannot run multiple copies of the same script with the same arguments on the same server; if you try the game will refuse to run it and tell you that the script is already running.

**Comment by phyzical** [comment]
welll... this has either changed or its now a bug. last time i launched my batchers i remember seeing plenty of the same scripts.

ill have a look at my scripts and give it a try, maybe i was taking on multiple arguments.

**Comment by hydroflame** [comment]
Nah this is weird a.f.
