### ISSUE TITLE
Function to generate 0-reward coding contracts for testing

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2957]
I'm currently working on an automated contract-solving suite, but it's slow going, mostly because I cannot create my interfaces or test my solutions without an actual contract of a given type.

I propose two new functions be added, to allow players to practice contract and test solvers without needing to wait for real contracts of the appropriate type:
* `ns.codingcontract.listContractTypes()`: Returns a list of all the types of coding contract in the game. 0GB RAM cost.
* `ns.codingcontract.generateSampleContract(contractType, host?, name?)`: Causes a contract of the given type to be immediately spawned. Such a contract will always have a reward of $0. If possible, such contracts will give the player unlimited attempts. Returns the name of the generated contract, or the empty string on failure.
  * `host`: Server on which to create the contract; default to the server the script is running on
  * `name`: Filename to give the contract; must end in '.cct'; defaults to a random filename of the form `contract-######-test.cct`

**Comment by MaWo2** [comment]
I really like this idea. It would really help me, too.
It would also push this game even more into the educational direction.

However, I am not sure, whether RAM cost is really an issue here. In most use-cases, people would spawn the test contract only once, most likely from the terminal or a separate script. Accordingly, the RAM-cost is neglectible (as long as it is not extremely high).

Therefore, I was wondering, whether this function might be something you could buy from the darknet, for instance, or develop at a certain level.
A completely different approach: Make it a degree at the University.
