### ISSUE TITLE
Incorrect editor tab highlighting when editing files with same name on different servers

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2958]
* Open a file in the editor on one server: `home; nano foo.js` 
* Connect to a different server: `connect iron-gym`
* Open a file with the same name as the first one: `nano foo.js` 
* Go to the editor and select the tab for either file
* The tabs for both files will be highlighted

Version: a3c599e6

**Comment by phyzical** [comment]
realted https://github.com/danielyxie/bitburner/issues/2228
