### ISSUE TITLE
Closing file in editor sometimes asks to save changes when nothing has changed

### ISSUE THREAD

**Issue by macdjord** [danielyxie/bitburner#2959]
Closing a script by clicking the 'X' button on its tab at the top of the screen will sometimes ask if you want to save changes, even though the tab was not showing the 'unsaved changes' asterisk. 

Note: Every time this has happened, it has been a file I *thought* I had already saved, so I believe the problem is that the editor is asking to save changes when there are none, but it's possible the files *had* changed and I'd forgotten, in which case the actual bug is 'editor not displaying unsaved-changes asterisk'.

Version: a3c599e6

**Comment by phyzical** [comment]
@macdjord mind giving exact repo steps please?

**Comment by macdjord** [comment]
@phyzical Don't have them; that's why I said 'sometimes'.

**Comment by phyzical** [comment]
im sorry but there is only so much time one can dedicate to a plethora of bug reports, without enough information bugs get closed to reduce the load of trying to fix more important bugs.

**Comment by OriginalRobotWizard** [comment]
This is super easy 100% reproducible:
1. nano test.txt
2. Close and save
3. Start over at 1 (popup to be asked to save will be displayed every time for .txt files)

**Comment by phyzical** [comment]
thx is it only txt files by chance?

**Comment by OriginalRobotWizard** [comment]
Yes, it only happens with .txt files. Not with .js, .script, or .ns files.
