### ISSUE TITLE
(REQUEST) - HTTPS requests to external IP addresses or DNS addresses

### ISSUE THREAD

**Issue by Brutalbeard** [danielyxie/bitburner#2970]
# About
I've been trying to learn more about the ELK stack, and think this would be a great way to get used to the visualizations in Kibana. 

To that end, I'm wanting to POST stocks data to a local machine on my network that has elastic and kibana running. 

We currently have WGET, but would love to be able to specify the method and fire off some data.

### Meta

- [*] Save file
- [*] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
[bitburnerSave_1644782573_BN8x0.json.zip](https://github.com/danielyxie/bitburner/files/8056533/bitburnerSave_1644782573_BN8x0.json.zip)

**Comment by MartinFournier** [comment]
You can use `window.fetch` directly in your scripts (https://developer.mozilla.org/en-US/docs/Web/API/fetch).

**Comment by Brutalbeard** [comment]
Time to go over engineer something!!

**Comment by Brutalbeard** [comment]
In case anyone out there wants to see example code that would send a successful request for me. Was iterating through each stock symbol with a `for` loop.

```js
const elasticUrl = "your.url"

for(let symbol of ns.stock.getSymbols()) {
    let logMe = {
        "@timeStamp": new Date(),
        message: {
	    askPrice: ns.stock.getAskPrice(symbol),
	    bidPrice: ns.stock.getBidPrice(symbol),
	    price: ns.stock.getPrice(symbol),
	    symbol: symbol
        }
    }
    
    window
        .fetch(`${elasticUrl}/bb.${symbol.toLowerCase()}/_doc/`, {
	    method: "POST",
	    body: JSON.stringify(logMe),
	    headers: {
                "Content-Type": "application/json",
                "Accept": "*/*"
        }
    })
    .catch(e =>{
        ns.print("Failure: ", e)
    })
}


```

**Comment by Brutalbeard** [comment]
@MartinFournier I was totally supposed to be working today....

Love the game man, thanks to you and the rest of the team for working so hard on it!

**Comment by phyzical** [comment]
👍 love the idea 😆

**Comment by Brutalbeard** [comment]
:-D

Works great too! Might turn this into a little library file that I can import into other scripts. Get an index called "muggings-per-hour" lol
