### ISSUE TITLE
corporation.unlockUpgrade spends money even if upgrade already exists

### ISSUE THREAD

**Issue by dampersand** [danielyxie/bitburner#2974]
The corporation 'unlockUpgrade' method does not appear to perform any checking to see if an upgrade already exists before deducting money from the corporation's account.

To reproduce the issue, simply have access to the corporation api, start a fresh corporation, and run the following:
```
ns.corporation.unlockUpgrade("Smart Supply")
ns.corporation.unlockUpgrade("Smart Supply")
ns.corporation.unlockUpgrade("Smart Supply")
```

This is on bitBurner 1.4.0 (49de4a28)

I can provide a save file if necessary, but this is pretty simple to replicate.  let me know!

**Comment by zigdon** [comment]
Just got burnt by this too :(
