### ISSUE TITLE
Bluetooth drivers crashing

### ISSUE THREAD

**Issue by Kadozu** [danielyxie/bitburner#2984]
Bitburner v1.4.0 (49de4a28)

I have noticed that if I try to watch videos on VLC media player while BitBurner is running on steam it sometimes causes my bluetooth drivers to crash. I am using windows 10 and I have not noticed this issue with other games. I had it crash the other day while in bitnode 3 a few times and now it just happened again in bitnode 10 so it does not seem to be a bitnode specific bug. My headphones are WH-XB700 from Sony and I use an Insignia USB BT adapter. It has only happened while I have multiple scripts running in BitBurner but I almost always have scripts running during gameplay so that may be irrelevant. Unfortunately I am not able to provide more info at this time but since i couldn't find any other similar bug reports I am posting this one in case anyone else is having the same issue.

**Comment by phyzical** [comment]
i would guess your pc is just running out of ram, maybe monitor that and see if it correlates at all.

**Comment by Kadozu** [comment]
It just happened again while my ram usage was at 67% so I do not believe that is the problem. I have 8gb of DDR3 ram if that info helps.

**Comment by hydroflame** [comment]
Yeah this is unfortunate but the game uses electron which is an established library outside my control and also doesn't use sound. So there's literally nothing I can do about this.
