### ISSUE TITLE
It's possible to miss some end of node achievements by leaving the bitverse too soon

### ISSUE THREAD

**Issue by Feodoric** [danielyxie/bitburner#2992]
Almost all of the challenge achievements require the current bitnode to be in a finished state as part of their precondition. The achievement checking code runs once every 300 game cycles/60 seconds. It is possible to complete a node, enter the bitverse and prestige into a new bitnode in the window between achievement checks. 

One possible fix for this would be to always run the achievement checking code when routing to the bitverse.

**Comment by SagePtr** [comment]
It's fixed here: #2726
Probably not in the production build yet.
