### ISSUE TITLE
command line parser bugs on processing `-t` and  `--tail`

### ISSUE THREAD

**Issue by vladtepesch** [danielyxie/bitburner#2999]
According to documentation the `run` command arguments `-t` and `--tail` have to be following directly to the script name. ( -->  https://bitburner.readthedocs.io/en/latest/basicgameplay/terminal.html#run - at least `-t` is mentioned there)
But the parser also interprets them as special arguments if they are later in the arg list. this prevents them to be passed to the executed script.

for example starting a `runon` script (that is supposed to start a script on a remote server)
``` 
run runon.js pserv-5 somescript.js -t 500 --tail omnitek
```
where the script itself is supposed to process the `-t` and `--tail` parameter did not see them and itself gets executed with 500 threads

**Comment by mbrannen** [comment]
I believe this might be a misunderstanding of the command and intended usage.

From the docs
`run [file name] [-t] [num threads] [args…]`

Translating that to the command you wrote looks like this
`run [file name = runon.js ] [-t] [num threads = 500] [args… = {'pserv-5', 'somescript.js', '--tail','omnitek'}]`

I would suggest somescript.js having arguments that you can then pass when `exec()` is to run it from runon.js

**Comment by vladtepesch** [comment]
> I believe this might be a misunderstanding of the command and intended usage.
> 
> From the docs `run [file name] [-t] [num threads] [args…]`
> 
> Translating that to the command you wrote looks like this `run [file name = runon.js ] [-t] [num threads = 500] [args… = {'pserv-5', 'somescript.js', '--tail','omnitek'}]`
> 
> I would suggest somescript.js having arguments that you can then pass when `exec()` is run from runon.js Try taking out the `-t 500` and using just `500` instead.
> 
> So in runon.js you might find something like this:
> 
> ```
> //exec(script, hostname[, numThreads=1[, args...]])
> exec(scriptToRun, serverToRunOn, threads,  serverToHack)
> ```

according to the docs the `-t` argument has to be passed right after the script name to be processed by the command line interpreter (I would expect the same for `--tail`).  This implies that if I pass `-t` not as the second argument it should be visible within the `ns.args` array but that is not the case.

I wanted my `runon.js` to parse for the optional `-t number` parameter and pass its number to the `ns.exec` call.

so at the end according to the docs the following should happen:
(this obviously works)

    > run script.js -t 1000 123 foo bar

should run the script `script.js` with 1000 threads and the arg array `[123, 'foo', 'bar']`

but this does not work as described:

    > run script.js 123 foo bar -t 1000 

should  (according to the docs) run the script `script.js` with 1 threads and the arg array `[123, 'foo', 'bar', '-t', 1000]`. 
But instead it has the same result as the first command.
