### ISSUE TITLE
Bug: (Bitnode 8) Insane Corporation payout with dividend of 1e-99

### ISSUE THREAD

**Issue by kriber82** [danielyxie/bitburner#3003]
In bitnode 8 i founded a corp to see what happens.
Unexpectedly there were payouts (but very very bad).
Surprisingly payouts decreased with increasing dividend percentage.
So I tried what happens when I go below 1 percent (0,000000000000001 in german locale) and, as assumed, payouts increased.
When I committed that dividend and reopened the dividend window the fraction of zero was presented in exponetial form (1e-15 or similar).
Then I modified the dividend to 1e-99 and got a payout of several $100t in a company with a revenue of under $1m/s.

Savegame: [bitburnerSave_1645208094_BN8x0.zip](https://github.com/danielyxie/bitburner/files/8099482/bitburnerSave_1645208094_BN8x0.zip)
Version: v1.4.0 49de4a28 (steam version)

**Comment by kriber82** [comment]
> was this via the api or via the ui?

via the UI

**Comment by pigalot** [comment]
interesting I always assumed corps were disabled on 8, maybe they should just be disabled it would be easier than making them a trap.

**Comment by TheMas3212** [comment]
so looked into this
the cause seems to be in BN8 specfically the BitNodeMultipliers.CorporationSoftCap is 0
so in src/Corporation/Corporation.tsx#L145
```js
  getDividends(): number {
    const profit = this.revenue - this.expenses;
    const cycleProfit = profit * CorporationConstants.SecsPerMarketCycle;
    const totalDividends = (this.dividendPercentage / 100) * cycleProfit;
    const dividendsPerShare = totalDividends / this.totalShares;
    const dividends = this.numShares * dividendsPerShare;
    let upgrades = -0.15;
    if (this.unlockUpgrades[5] === 1) {
      upgrades += 0.05;
    }
    if (this.unlockUpgrades[6] === 1) {
      upgrades += 0.1;
    }
    return Math.pow(dividends, BitNodeMultipliers.CorporationSoftCap + upgrades);
  }
```
`BitNodeMultipliers.CorporationSoftCap + upgrades` evaluates to `0 - 0.15`
so when the dividends are raised to that power its getting raised to a negative power
amusingly this causes the effect to be worse the closer the corperation profit is to 0

**Comment by pigalot** [comment]
Yeah I assumed as much, I think the best bet would be to do the same as is done with BB and add something to prevent you starting a corp in 8 that way it doesn't confuse new people.

**Comment by TheMas3212** [comment]
yea, probably also good to add a Math.max to getDividends anyway just incase the issue comes up in a different node

**Comment by hydroflame** [comment]
Corp should be prevented in 8
