### ISSUE TITLE
BUG: Parent dir `..` relative path not working

### ISSUE THREAD

**Issue by jjayeon** [danielyxie/bitburner#3004]
BUG: Parent dir shortcut `..` results in an error message: `Failed to resolve module specifier "../a". Invalid relative url or base scheme isn't hierarchical.`

REPRO: Two scripts, `/a.js` and `/test/b.js`:
`a.js`:
```
/** @param {NS} ns **/
export async function main(ns) {

}

export default function a(ns) {
	ns.tprint("foo");
}
```
`/test/b.js`:
```
import a from "../a";

/** @param {NS} ns **/
export async function main(ns) {
	a(ns);	
}
```

`run test/b.js` should see output `foo`; instead above error occurs.

Bitburner v1.4.0.

**Comment by t-wolfeadam** [comment]
Not sure if this is a bug or intentional, but all scripts run from your root directory. How it works right now is you would have `import a from "a"` the top of `/test/b.js`

**Comment by jjayeon** [comment]
> Not sure if this is a bug or intentional, but all scripts run from your root directory. How it works right now is you would need to have `import a from "a"` the top of `/test/b.js`

i've been using absolute paths in the meantime, which seems to work fine.  up to hydro on whether this gets changed or not

**Comment by hydroflame** [comment]
intentional tbh because that's a PITA to deal with.
