### ISSUE TITLE
isRunning or scriptRunning not working for scripts inside folders

### ISSUE THREAD

**Issue by afillatre** [danielyxie/bitburner#3006]
Version : 1.4.0 (49de4a28)

**Running scripts**
_t1.script_
```
while(true) {}
```

_myFolder/t2.script_
```
while(true) {}
```

When I execute the following script:
```
print(isRunning("t1.script", getHostname()))
print(isRunning("myFolder/t2.script", getHostname()))
```

I get the following result:

```
true
false
```

So it seems `isRunning` (and `scriptRunning` as well) is not working for scripts located inside a folder

**Comment by phyzical** [comment]
i think this relates to another issue around relative files

```
print(isRunning("./t1.script", getHostname()))
print(isRunning("./myFolder/t2.script", getHostname()))
```

does this work?

**Comment by afillatre** [comment]
No, it does not work either.

Also `getScriptRam` does not seem to work either, so yes, it may be due to the file path. I tried leading with a `/` as well, but same result.

**Comment by phyzical** [comment]
another thought, is the hostname just home for your current testing? or as it maybe going wrong for external servers?

**Comment by afillatre** [comment]
Yes it's "home", and I tried both with "home" and `getHostname()`

**Comment by dowinter** [comment]
Im not sure if anything has been fixed for this, but calling 
```
ns.tprint(ns.isRunning("/myFolder/t2.script", getHostname()))
```
(notice no leading `.`) yields `true` for me, so this might not be an issue (anymore)

**Comment by dowinter** [comment]
Not sure if anything has been done in the meantime to change file behaviour, but 
```
tprint(isRunning("/myFolder/t2.script", getHostname()))
```
yields `true` for me (notice no leading `.`), so this might be (now) closable

**Comment by djfranke** [comment]
I can confirm, that the leading '/' makes scriptRunning work as expected (still not working without it). ( Version 2.0.2).
The same behaviour is true for the 'exec' command - without this exact syntax, a script in a folder can be executed twice with the same parameter (I tried without parameter and a single threat).
