### ISSUE TITLE
Corrupted save after entering a (wrong?) price formula in corporation mode

### ISSUE THREAD

**Issue by KonscienceGit** [danielyxie/bitburner#3007]
### How did this happen?
After setting a sell price for a software  product (Software division in corporation mode) the game went into recovery mode.
Any further attempt to acces this corp division result in the game going into recovery mode.
I might have written an invalid character or formula in the product price field.

Please fill this information with details if relevant.

- [x] Save file
- [x] Steps to reproduce: load the attached save, go to Corp tab, open the "Software div" division of the corporation.

### Environment

* Error: SyntaxError: Unexpected number
* Page: Corporation
* Version: v1.4.0 (49de4a28)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
[bitburnerSave_1645393681_BN3x0.json.txt](https://github.com/danielyxie/bitburner/files/8104979/bitburnerSave_1645393681_BN3x0.json.txt)

PS: I'd like to recover my save if possible... Would gladly do it myself if i'd knew what the save file content would mean. If not I have a backup before entering the bitnode, it's a couple week of playtime but I can live with it.

**Comment by InDieTasten** [comment]
It might have to do with the fact that one of your product names has a trailing whitespace character:
![image](https://user-images.githubusercontent.com/7047377/154944788-b90d167e-ecce-4a94-8dde-680c2d8cfc2f.png)

When you see random ASCII characters from a-zA-Z0-9 and ending with == signs at the end (referring to the file save format), you can assume it's going to be base64. Especially, when the first two characters are "ey", which translates to an opening curly brace "{" in base64.

You can decode the file content via base64 and get a json object. The json object will look something like this:
![image](https://user-images.githubusercontent.com/7047377/154945424-5bdfeae0-cd88-401a-a04a-050d6234532d.png)

In some of those properties you will find additional JSON objects encoded as JSON strings, like PlayerSave and AllServersSave. You need to unescape them, format them, and you get something like I've posted in the first screenshot.

I will leave actually fixing the save up to you. Just look at fixing your save file as if it was part of the BitNode :D

**Comment by InDieTasten** [comment]
Just noticed you were mentioning prices. You want want to check the sCost field as well and try some other values.
You could also consider removing the product altogether.

At whoever willing to fix the cause of this: It looks like the savegame file integrity is fine. Just that the game can't cope with some of the values inside of it. I guess there is some missing validation or error checking in that portion of the code.

**Comment by phyzical** [comment]
@InDieTasten thanks for doing a through debug, there is a few issues and prs i think to address the issues with the sell price input, ill try and find them and link them up.

**Comment by phyzical** [comment]
https://github.com/danielyxie/bitburner/pull/2757/ this may fix it.

**Comment by KonscienceGit** [comment]
Thank you so much for the fast answers and thorough explanations!

I will take a look at this after work

**Comment by KonscienceGit** [comment]
Can confirm that removing the trailing whitespace from the product name in the save file solvedmy issue (which was crash on opening the software division, where the product was sold).

**Comment by InDieTasten** [comment]
Trailing whitespace in the product name would different from the referenced 2757 @phyzical May this should be tracked as a separate issue.

**Comment by phyzical** [comment]
Oh your right its the product name not the sell amount deerp >.> ill remove that comment.
