### ISSUE TITLE
Suggestion: Display a players Bitverse tree progress on the stats page (collapsible). Also a shareable mini display of Bitverse node progress.

### ISSUE THREAD

**Issue by BrianLDev** [danielyxie/bitburner#3011]
A group of people on Discord were talking about wanting to view and/or share an image of their progress through the Bitverse tree while in the middle of a Bitnode, but there isn't really a safe way to do that without using Bitflume (which erases your progress).

It would be great to have a (collapsed) display of a players progress through the Bitverse tree on the Stats page, that players could uncollapse and view and also screenshot to share with others.  It should also have an arrow pointing to the current BN they are working through.

**BONUS FEATURE:**  In addition to displaying the Bitverse tree, underneath that create a smaller, condensed (and somewhat spoiler free) version of progress through the Bitverse tree nodes.  Since there are 13 BitNodes with 3 levels each, it could be represented with 13 icons each divided into 3 slices.  Each icon would represent some feature about the BN (i.e. BN2 could have an icon of a fist for gang fighting).  All 13 icons and slices will start "empty", only showing the outline.  When a player completes a level of a BN, then 1 slice (1/3 of the icon) will be filled in with color.

Example image of Bitverse tree:
![image](https://user-images.githubusercontent.com/16980550/155020982-b536f9c7-2acb-4eee-9618-eb43ab49d7c8.png)

**Comment by phyzical** [comment]
ooo or maybe like some of the advent of code ascii arts it kind of branches out as an animation maybe a simple left to right sort of approuch

**Comment by hydroflame** [comment]
you can look at your source files under augmentation
