### ISSUE TITLE
Clarify that Bitburner is not FOSS software

### ISSUE THREAD

**Issue by trhr** [danielyxie/bitburner#3013]
The license agreement included with bitburner is about as far from copyleft / free use / GPL as a software license can get.

Since the software clearly targets new developers, I'm afraid somebody is going to get burned hard by not understanding the ins-and-outs of software licensing. FOSS licenses protect new developers.

Under my reading of the current license, forking this project is prohibited, as a fork would violate the license's terms:

**For educational purposes only, you, the end-user, may use portions of the Source Code, such as particular
routines, to develop your own software, but may not duplicate the Source Code.**

Of course, Big D can create whatever terms he wants, but it seems fairly dishonest to provide the source code on a platform that supports - and encourages - forking the software, when that would patently violate the terms of the software. A notice that this is not FOSS/GPL, and that additional limitations apply, is in order.

**Comment by trhr** [comment]
I'm launching a foss-compliant fork at https://github.com/trhr/fossburner

**Comment by danielyxie** [comment]
My intention is not to prevent people from forking the project. If that's how the license reads then I can address it.

As for clarifying that this is not FOSS software, where do you think that should happen? In the README?

**Comment by trhr** [comment]
> As for clarifying that this is not FOSS software

That would be appreciated. If you'd throw a link to the FOSS version in there as well, even better.

**Comment by trhr** [comment]
Just for accuracy, did you break your left or your right arm? I'll go with your left unless I hear back.

```
  const BigDLeftArm = new Augmentation({
    name: AugmentationNames.BigDLeftArm,
    repCost: 1.25e6,
    moneyCost: 2.5e12,
    info:
      "The left arm of a legendary biohacker that was broken in a snowboarding accident. " +
      "Increases hacking ability at the expense of dexterity.",
    hacking_mult: 1.3,
    dexterity_mult: 0.7
  });
  BigDLeftArm.addToFactions(["BioHackers"]);
  if (augmentationExists(AugmentationNames.BigDLeftArm)) {
    delete Augmentations[AugmentationNames.BigDLeftArm];
  }
  AddToAugmentations(BigDLeftArm);
```

**Comment by trhr** [comment]
Just to clarify, your license is a straight copy of iD Software's Doom license. Which, famously, was ported to GPL and became dual-licensed software. So, while I'd love for you to make this FOSS-compliant, I also understand that you're clearly saying "no," and so I don't expect anything else with regards to changing your license or your readme. But you _could_.

**Comment by waffleattack** [comment]
In the section right about it gives rights to copy and modify the source code...

**Comment by trhr** [comment]
> In the section right about it gives rights to copy and modify the source code...

That's not the same as free (_libre_). Upon rereading, however, I agree with you. The Source Code is modifiable. However, the art, music, data, etc is not, and is not even distributable.

The problem is that Big D used a license he didn't understand and doesn't fit the game. Doom's original source code launch specifically did not include doom's assets - art and media. While users could modify the source code, they could not actually distribute a version of Doom, because Doom obviously includes data files (.wads) that remained under copyright.

GPL devs skirted this issue by not distributing the .wads at all. So you'd download a version that wouldn't run standalone, but since you had already installed the Official Doom client, you could point it at Doom's data directory and use the official, proprietary .wads.

A first-person-shooter is so far from Bitburner's reality that it hardly bears considering "what is considered artwork, what is considered characters." But, nonetheless, the proprietary license only covers those components. I intend to err far, far on the side of caution and rename every faction, augment, rewrite every .lit, and recreate the ASCII art wherever it's used. That's how Doom went GPL originally. Somebody fired up Gimp and redrew the sprites; fired up audacity and recomposed the music. There's nuances to it, but the thirty-some-odd Doom source ports and their dev blogs actually give a fairly good play-by-play of what's covered and what's not.

Of course, none of this was ever challenged in court, so a judge might tell me I'm completely wrong. But iD's lawyers didn't like their chances, and Bitburner is already older than Doom was when the first ports started. I have trouble believing a for-profit company with the most popular game of its time let a three-year-old IP slip away due to negligence.

Anyway, along the way, I'll patch a chunk of the 200-some-odd issues. But I'm not putting in that kind of effort for a non-free product. Why would anyone?

**Comment by phyzical** [comment]
>But I'm not putting in that kind of effort for a non-free product. Why would anyone?

noone asked you to and to be frank i would not want you to personally after the last few days, idk maybe plenty of would because we care about the core idea of the game? 

please seek help

**Comment by trhr** [comment]
> noone asked you to and to be frank i would not want you to personally after the last few days, idk maybe plenty of would because we care about the core idea of the game?

Hi Jack, unfortunately, since you're not on the contributors list at the time of my fork, your input will be filed and reviewed later.

**Comment by trhr** [comment]
![image](https://user-images.githubusercontent.com/5786272/155267554-7196bac8-4139-4ae2-b84e-fbf623405e20.png)

**Comment by TechnologyClassroom** [comment]
@trhr Your readme says bitburner is now free which is incorrect.  The Commons Clause is nonfree by FSF and OSI standards.

**Comment by Tanimodori** [comment]
Commons Clause is not an FOSS license as it forbids selling the copies. Why not go Apache 2?
