### ISSUE TITLE
Feature Request: Prevent purely negative impact by accepting Stanek's gift

### ISSUE THREAD

**Issue by kriber82** [danielyxie/bitburner#3018]
Problem: I was stuck with a harmful Stanek's Gift in BN8 (see below for details).
Solution ideas:
* Present grid size (or a reasonable hint) before accepting the Gift.
* Disable Stanek's Gift in BN8 (in case it is capped to 2x2 there for balance reasons, didn't look into the code)
* Allow removal of Stanek's Gift as long it never provided any bonuses

Detailed explanation of the Situation I ran into:
I am currently playing BN8.2 with SF11.1 unlocked.
In BN8.1, I forgot to acquire Stanek's gift and was hoping for one less aug-install round with its hacking bonus.
After accepting Stanek's gift, I realized that it's only 2x2 in size. This size only accommodates hacknet cost bonus, which is completely useless in BN8.
As I did not want to be stuck with its -10%, I went back to an older save and replayed the end of BN8.1. Would have loved to prevent this waste of time ;-)

**Comment by phyzical** [comment]
i agree with suggestion making it more obvious "maybe you should think harder about this before blah" or "you must bit flume to revert this" 

but i don't know i agree with being allowed to change the gifts, i think being forced to reboot the node is reasonable (just my opinion)

**Comment by kriber82** [comment]
I would be OK with having to restart the bitnode. But to me, it seems hard or non-obvious to do.

But even with knowing about ns.softReset() my googling before reloading my older save did not lead me anywhere near bit flume.
Additionally, I just now did a quick googling of "bit flume" and a short search in the bitburner repo did not reveal a clear path to a "quick" bitnode reset. Would think if I dug in for half an hour I would trace a way through the source to actually reset. Is resetting a bitnode intended to be hard?

**Comment by phyzical** [comment]
(dont mean to sound rude :D ) have you really never bit flumed yet? `run b1t_flum3.exe` it should have been provided after the first BN completion, if its missing is it possible you rm'ed it?

i dont see any references to it in docs so it was probably hidden due to spoilers, what i does is just perform a reset and you can choose a new bitnode to play in. (so in your case just pick 8.1 again :) )

**Comment by kriber82** [comment]
`run b1t_flum3.exe` would have been exactly what I had been looking for. Thanks for mentioning it ;-)

In most cases getting Stanek's Gift will be one of the first things players do in a BN.
In that scenario bit flume would help. Maybe mentioning it in the vicinity of Stanek's Gift might help.
In the rare case of acquiring Stanek's Gift after some time in a BN, some sort of size preview or undo-option might be more helpful.

For the problem I was facing (not recognizing it was there although I was searching for it) it might have been helpful to (strongly) hint at it at some point (i.e. in an achievement or in a notification like the one after taking the red pill).

**Comment by phyzical** [comment]
yeah. maybe it was something that was made more obvious after you started playing? (what version did you start in?)

i swear i just knew it existed after my first BN completion, maybe it was in a text dialog you closed?

**Comment by phyzical** [comment]
checked on discord and some think there is a message on your first completion, but maybe we can add a message from jump3r each time you enter a bitnode after completion of BN1.1 to say "i have added you SOME_RANDOM_LORE flume at your heart content"

**Comment by phyzical** [comment]
Ah thats right, after BN1 its just a program you can create, i assume you just automated this proccess and simply never used b1t_flum3.exe

maybe the correct suggestion is something to engourge users to b1t_flum3.exe atleast once, similar to a "After BN1" tutorial?

**Comment by kriber82** [comment]
"After BN1 tutorial" sounds like a great solution, if it is not too much work.
I would bet there are other topics that would find a home there, too.

**Comment by hydroflame** [comment]
Stanek should not be available in 8
