### ISSUE TITLE
Achievements are unclear whether 1Q stands for Quadrillion or Quintillion

### ISSUE THREAD

**Issue by BrianLDev** [danielyxie/bitburner#3019]
Just needs a simple clarification so players know that lowercase q == quadrillion and uppercase Q == quintillion.

![image](https://user-images.githubusercontent.com/16980550/155241327-5e8ad27e-13f7-44b0-a5ed-4599c79e9d49.png)

**Comment by BrianLDev** [comment]
Note: I've already submitted a PR that fixes this one

**Comment by phyzical** [comment]
mind adding `fixes #3019` tot he pr desc

**Comment by BrianLDev** [comment]
@phyzical FYI this is an issue.  The related PR already has `fixes #3019` in the description :)

**Comment by phyzical** [comment]
sorry you text has `fixes issue BLAH` it needs to be `fixes BLAH` for github to auto magic

**Comment by BrianLDev** [comment]
@phyzical gotcha, all set now.

**Comment by phyzical** [comment]
👍 as an fyi for future you can tell github know whats up by seeing this 
![image](https://user-images.githubusercontent.com/5182053/155503349-bdd8aa10-9c58-401e-a2d9-2f43026b1fb3.png)
