### ISSUE TITLE
Missable Achievement: "That's the new limit"

### ISSUE THREAD

**Issue by BrianLDev** [danielyxie/bitburner#3022]
If a player beats BN9 (Hacktocracy) before getting all the hacknet node related achievements, then they become impossible to get when you have Hashnet servers instead of the original Hacknet nodes.

Other bitburner devs told me that the intention is to not have any missable achievements in this game, so it would be good to fix this so it's no longer missable.

![image](https://user-images.githubusercontent.com/16980550/155267181-35c0a4b2-36d7-4256-9d51-4e3d1da8bb1d.png)
![image](https://user-images.githubusercontent.com/16980550/155267652-97219b12-bc88-457c-94f9-dcd2bc5148cf.png)

**Comment by BrianLDev** [comment]
Note: I've already submitted a PR that fixes this one

**Comment by phyzical** [comment]
mind adding `fixes #3022` to the pr description :)

**Comment by BrianLDev** [comment]
@phyzical FYI this is an issue.  The related PR already has `fixes #3022` in the description :)

**Comment by TheRealMaxion** [comment]
I don't think this is an issue when the hacknet server version of the achievement also grants the hacknet node version.
![image](https://user-images.githubusercontent.com/13872642/155912234-9c3a2391-f5a9-4d15-a3a1-9f6004bddf24.png)

**Comment by BrianLDev** [comment]
@TheRealMaxion Ah good catch.  I'll close the issue & related PR.

The `MAX_HACKNET_SERVER` Achievement is **much** harder to reach and it might be a good idea to reduce the maxCores or something.  But that's separate from this issue/PR so I'll consider this one closed.
