### ISSUE TITLE
Typescript accepted types for "answer" parameter of attempt() seems to be incorrect

### ISSUE THREAD

**Issue by BlackxSnow** [danielyxie/bitburner#3026]
https://github.com/danielyxie/bitburner/blob/c5462eb6f4eaa304eaac7369ed72a1561db9215e/src/ScriptEditor/NetscriptDefinitions.d.ts#L2938

According to the source [here](https://github.com/danielyxie/bitburner/blob/c5462eb6f4eaa304eaac7369ed72a1561db9215e/src/NetscriptFunctions/CodingContract.ts#L28) the function is fully capable of parsing 2D arrays, yet the typescript definitions forbid this.

This is prompted by the Merge Overlapping Intervals contract which one would expect takes a 2D array answer which is impossible within typescript.

**Comment by BlackxSnow** [comment]
An update: after using @ts-ignore to compile through the type error, the contracts completed successfully in game confirming that this is in fact an issue.

**Comment by phyzical** [comment]
incase i am miss interpreting what your asking doesn't `string[]` mean it accepts an array of strings? 
isnt 2d array? `string[][]`

**Comment by BlackxSnow** [comment]
> incase i am miss interpreting what your asking doesn't `string[]` mean it accepts an array of strings? isnt 2d array? `string[][]`
> 
> ah i think i get you AFAIK the "any" is due to how the auto docs are generated

string[] != string[][].

`    const sd2 = [["a","b"], ["c", "d"]];

    ns.codingcontract.attempt(sd2, contractFile, hostName);
`
Fails to compile.

[[1,2],[3,4]] is also an invalid typescript parameter, despite running completely run when used in JS.
