### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name') (at "Resleeves")

### ISSUE THREAD

**Issue by jonathan-dilorenzo** [danielyxie/bitburner#3029]
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'name')
* Page: Resleeves
* Version: v1.4.0 (a3c599e6)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
Attached, because otherwise it is too long.
[RECOVERY_BITBURNER_1645583736.txt](https://github.com/danielyxie/bitburner/files/8129288/RECOVERY_BITBURNER_1645583736.txt)

**Comment by jonathan-dilorenzo** [comment]
I went to re-sleeve at New Tokyo and got a crash.

**Comment by phyzical** [comment]
( i think ive seen an issue/pr related to locations not being reset)

**Comment by TheRealMaxion** [comment]
Is this due to how the city view doesn't change if a script makes you travel while you have the city open?

**Comment by jonathan-dilorenzo** [comment]
I don't have a script that makes me travel, so I suspect not.

**Comment by phyzical** [comment]
from memory ive seen this raised already (have a look in the bugs list) but it was related to resleeve not resetting the location then trying to go to say a gym that was in sector-12 but your sleeve was still in "New Tokyo" i could be wrong. less about the fact you dont automatically travel more about the sleeve properties themselves, next time it happens try to travel to sector-12 maybe? though i could be wrong/ remember what i saw wrong

**Comment by borisflagell** [comment]
Re-Sleeving has completly scrapped and replaced by grafting. Issue can be closed.
