### ISSUE TITLE
browser version unresponsive

### ISSUE THREAD

**Issue by bridgeofdivide** [danielyxie/bitburner#3030]
browser: brave
version:1.35.103
desc: game started crashing suddenly, page loads but i can't interact with it

**Comment by phyzical** [comment]
@bridgeofdivide https://danielyxie.github.io/bitburner/ you mean about this page?

could you try an incoginto window also which browser?

**Comment by bridgeofdivide** [comment]
>@bridgeofdivide https://danielyxie.github.io/bitburner/ you mean about this page?
yes

> could you try an incoginto window also which browser?
it works in icognito
browser is brave, chromium based
https://brave.com/

**Comment by phyzical** [comment]
thanks for that, it may relate to something with your game file being incompatible, could you please add that to the description?

**Comment by phyzical** [comment]
ah but you proably cant export it can you..

**Comment by bridgeofdivide** [comment]
exactly

**Comment by bridgeofdivide** [comment]
can't import a new one either

**Comment by phyzical** [comment]
if you inspect the page is there anything useful in the dev console?

**Comment by phyzical** [comment]
you can also try `https://danielyxie.github.io/bitburner/?noScripts` to see if that helps

**Comment by bridgeofdivide** [comment]
can't inspect element either, i think the page crashes at some point during load, interface loads (html) then i get page unresponsive prompt.

> you can also try https://danielyxie.github.io/bitburner/?noScripts to see if that helps
yes that fixed it

**Comment by bridgeofdivide** [comment]
can't inspect element either, i think the page crashes at some point during load, interface loads (html) then i get page unresponsive prompt.

> you can also try https://danielyxie.github.io/bitburner/?noScripts to see if that helps
yes that fixed it

**Comment by phyzical** [comment]
coolies, it must just be a bad script or too many scripts trying to reload, should work going forward 👍 feel free to close

**Comment by bridgeofdivide** [comment]
thanks for the help.
this was after starting bn-8, i had just started it and don't leaving any scripts running, just in case it comes up again
