### ISSUE TITLE
Toasts: use const objects (enums) instead of magic strings

### ISSUE THREAD

**Issue by BrianLDev** [danielyxie/bitburner#3032]
This came up in a broader discussion on the Discord dev channel about moving away from "magic strings" in general.

To start, hydroflame recommended converting Toasts, and then later we can look into enums for Gang names, crimes, universities, courses, etc.

![image](https://user-images.githubusercontent.com/16980550/155597789-5eaa6c5c-bdc2-4893-98c1-a970d50c2f50.png)

**Comment by waffleattack** [comment]
Could I have an example for what the magic strings are in toasts?

**Comment by BrianLDev** [comment]
@waffleattack since hydroflame was the source of this request, they're the best one to ask for more details.

But if I had to guess, I'd say that the toast variants should be converted from magic strings into const objects/enums.  Screenshot below:
![image](https://user-images.githubusercontent.com/16980550/156038579-c6b49cc1-44b3-40d0-b8d7-a7c037a51776.png)

**Comment by waffleattack** [comment]
ah so instead of inputting 
```js
ns.toast("Alert!", "warning", 10000)
```

you would instead be able to do
```js
ns.toast("Alert!", TOASTS.WARNING, 10000)
```
if I understand it correctly?

**Comment by BrianLDev** [comment]
@waffleattack Yup, that's exactly how I'd do it.  But you might want to check with hydroflame to see if they had anything else in mind.

**Comment by phyzical** [comment]
nah thats correct 👍

**Comment by hydroflame** [comment]
Yeah it's not that easy
How do you feed `TOASTS` to the scripts?

**Comment by waffleattack** [comment]
could we do it similar to ns.args? so instead of using `TOASTS.WARNING` you would use `ns.TOASTS.WARNING`?

**Comment by hydroflame** [comment]
https://github.com/danielyxie/bitburner/blob/dev/src/ScriptEditor/NetscriptDefinitions.d.ts#L6426

If someone can uncomment this line and make it compile ...
