### ISSUE TITLE
Regex's exec function uses 1.3GB of RAM, as it seems to be interpreted as `ns.exec`.

### ISSUE THREAD

**Issue by shadow7412** [danielyxie/bitburner#3048]
- [ ] Save file
- N/A, as highly reproducible.
- [X] Minimal scripts to reproduce the issue
```
/** @param {NS} ns **/
export async function main(ns) {
	ns.tprint(/test/.exec(ns.args[0]))
}
```
- [X] Steps to reproduce
Create  a file which contains the script above, or any other script that uses exec.
Run `mem scriptname.js` on the terminal, and note that exec has been incorrectly 'allocated' ram usage.
- [X] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
- 1.4.0 (49de4a28) on Steam

**Comment by shadow7412** [comment]
Note - this is fairly easy to workaround (such as by using `["exec"]` instead of `.exec`, but that's ugly.

**Comment by hydroflame** [comment]
Yeah nearly impossible to actually solve rn
