### ISSUE TITLE
corporation.setAutoJobAssignment to set zero workers to a job will instead set one worker to that job

### ISSUE THREAD

**Issue by bmartin1234** [danielyxie/bitburner#3059]
v1.4.0 (49de4a28)

To reproduce:
Have a corporation, with an office that has some unassigned workers
Call corporation.setAutoJobAssignment to set a job to zero workers, where that job already has zero workers assigned.
result: one worker will be assigned to that job.

To fix the bug:
src/Corporation/OfficeSpace.ts
line 191: replace <= with <
should be: if(jobCount < amount) { ...
line 198L replace >= with >
should be: if(jobCount > amount) { ...

The bug happens because setEmployeeToJob reassigns employees even when the correct number has already been assigned

**Comment by phyzical** [comment]
there is pr fixing this already :)
