### ISSUE TITLE
Overzealous dynamic ram calculation causes false flags:

### ISSUE THREAD

**Issue by thePalindrome** [danielyxie/bitburner#306]
Consider the following script: 

```
server = args[0];
brutessh(server);
ftpcrack(server);
relaysmtp(server);

if (fileExists("HTTPWorm.exe")) {
    httpworm(server);
}

if (fileExists("SQLInject.exe")) {
    sqlinject(server);
}


if (nuke(server)) {
    spawn('hack.script', getServerRequiredHackingLevel(server), server);
}
```

Saving it, then running it on `omega-net` (with the first 4 port openers) causes the `spawn` invocation to exceed the dynamic ram calculation. This is frustrating, since I've gone through every bit of it to reset the static usage, but to no avail.

**Comment by hydroflame** [comment]
How much static does it display for you ?

**Comment by thePalindrome** [comment]
I'm being shown 4.05 Gig on this script.

**Comment by hydroflame** [comment]
I can confirm, I'll investigate

**Comment by hydroflame** [comment]
@thePalindrome The developer is away for a few days, until then i have temporarely disabled the dynamic ram calculation, you can play a fork here that's exactly like the original
https://hydroflame.github.io/bitburner-fix/
Simply export your game from danielyxie, import in mine, wait a few days until we fix things around, export from mine, import in danielyxie

**Comment by thePalindrome** [comment]
Don't worry about it, just wanting to report things, same as ethan ;p

**Comment by hydroflame** [comment]
Should be fixed

**Comment by thePalindrome** [comment]
Can confirm, issue is no longer present, thanks!
