### ISSUE TITLE
Bug: Implementing a class with a `get` method causes Memory to be 2 GB higher

### ISSUE THREAD

**Issue by wesleycoder** [danielyxie/bitburner#3062]
I have implemented a simple json database using NS.read and NS.write inspired by the npm package [jsondb](https://www.npmjs.com/package/jsondb).
You can see my implementation [here](https://github.com/wesleycoder/bit-scripts/blob/main/src/jsondb.ts).

However since I've been using it I've noticed every script that uses it consumes 2 GB extra RAM than it should.
Then I've run `mem jsondb.js` to investigate:
```sh
[home ~/]> mem jsondb.js
This script requires 1.70GB of RAM to run for 1 thread(s)
  1.60GB | baseCost (misc)
100.00MB | fileExists (fn)
```

This seems totally ok.
However running mem on [a script using](https://github.com/wesleycoder/bit-scripts/blob/main/src/nukeall.ts) the `jsondb` bundled (I'm using [parcel](https://parceljs.org/) to bundle my `.ts` files) gives me that I'm calling `stanek.get`:
```sh
[home ~/]> mem nukeall.js
This script requires 7.95GB of RAM to run for 1 thread(s)
  2.00GB | getServer (fn)
  2.00GB | stanek.get (fn)   <--- This was strange
  1.60GB | baseCost (misc)
  1.30GB | exec (fn)
600.00MB | scp (fn)
200.00MB | scan (fn)
100.00MB | fileExists (fn)
100.00MB | getScriptRam (fn)
 50.00MB | nuke (fn)
```
And checking that [script source `.ts`](https://github.com/wesleycoder/bit-scripts/blob/main/src/nukeall.ts) we can see that I'm not using any `stanek` functions.

While inspecting the generated `.js` file we can see a hint on what can be happening since the call to my database `.get` function is similar to the `stanek.get` signature.
```ts
async function tryNuke(hostname: string) {
  const server = await $db.get(hostname);
  const commands = executables
    .filter(({ file }) => $ns.fileExists(file, 'home'))
    .map(({ cmdName }) => $ns[cmdName]);
  // ...
}
```
Generated `.js` corresponding part:
```js
async function $f67ee846f62d5e2d$var$tryNuke(hostname) {
    const server = await $f67ee846f62d5e2d$var$$db.get(hostname); // here we can see what can be confusing the `mem` logic
    const commands = $b69bf64a8801d8fc$export$423395798b97df86.filter(({ file: file  })=>$f67ee846f62d5e2d$var$$ns.fileExists(file, 'home')
    // ...
}
```
[edit]: this didn't work see comment below.
~For now I'm renaming my database `.get` to `.pick` so I'm not affected for 2 GB extra on all scripts that uses a DB.~

My questions are:
- can the mapping of `stanek.get` be improved to not report these false positives?
- if not could it be included in the `mem` command documentation the way upon which `mem` calculates the consumed memory (so less people spends a week thinking that there is a bug in their code 😿 )

Be free to check my scripts repo for more source files.
*There's no readme yet but I'm writing one, along with pushing more of my environment setup to help reproduce my current scenario.*

Checklist:
- [x] Save file [bitburnerSave_1646228544_BN1x1.json.zip](https://github.com/danielyxie/bitburner/files/8177920/bitburnerSave_1646228544_BN1x1.json.zip)
- [x] Minimal [scripts to reproduce the issue](https://github.com/wesleycoder/bit-scripts)
- [x] Steps to reproduce
- [x] Version of the game => `Bitburner v1.4.0 (49de4a28)`

**Comment by wesleycoder** [comment]
Renaming the `.get` prop didn't work and crashed the script with this:
```sh
RUNTIME ERROR
nukeall.js@home
Args: ["--resetOnInit"]

Dynamic RAM usage calculated to be greater than initial RAM usage on fn: exec.
This is probably because you somehow circumvented the static RAM calculation.

Threads: 1
Dynamic RAM Usage: 6.15GB
Static RAM Usage: 5.95GB

One of these could be the reason:
* Using eval() to get a reference to a ns function
  const myScan = eval('ns.scan');

* Using map access to do the same
  const myScan = ns['scan'];

Sorry :(
```

**Comment by TheMas3212** [comment]
underlying issue is tracked in #2529

**Comment by wesleycoder** [comment]
Closing in favor of keeping the discussion in #2529
