### ISSUE TITLE
Feature: Server security level suppression

### ISSUE THREAD

**Issue by GhostCrab** [danielyxie/bitburner#3063]
### **Issue:**
One of the primary road-blocks to a continuously executing HWGW algorithm is that it is near-impossible to start hack/grow/weaken operations on a server at the same time as other hack/grow/weaken operations are finishing on that server since the server's security level is bouncing up and down constantly depending on the phase of the HWGW batch.
A proposed solution is an alternative to the weaken mechanic where instead of actively reducing the security level of a server, there is a kind of "shield" that a player could generate that mitigates or even eliminates security increases to servers when hack or grow operations are executed. This mechanic would not eliminate the need for weaken operations, but instead would work in tandem to provide flexibility in how a player attacks a server. The mechanic would also be twice as expensive in RAM cost and effectively take twice as long to build up to provide the same security mitigation as an equivalent number of weaken threads.

I call this mechanic "Suppression".

### **Suppression:**

Suppression is a per-server statistic that ranges from 0 - 1.5 (0% to 150%) where zero is no suppression and anything over 100% is a full block of any security increases on a server due to hack or grow operations.

A player can increase the suppression stat for a server with a call to the async function suppress(). The suppression statistic increases at a constant rate regardless of the numbrer of active threads allocated to suppressing a server. The goal is to mimic the weaken timing such that it would take "weaken time" * 2 to raise the statistic from 0 to 1. The knock-on effect of this is that suppression is more effective on already weakened servers since the statistic will rise faster when the server's security is lower.

When an operation is made on a server that would normally cause a security increase where suppression is > 0, the following formula is applied:
	suppressed security increase = normal security increase * (1 - Math.min(suppression, 1))

After the suppressed security increase is calculated, suppression for the server is reduced based on the number of active threads calling suppress on the server. More threads mean a smaller reduction in the suppression statistic. If there are no active supress threads on an attacked server, the suppression statistic automatically falls to 0 regardless of it's previous value. Active suppression threads will try to mirror the effectiveness of the same number of weaken threads (but suppression threads are twice as expensive in RAM cost, for balancing). For an example of how effective active suppression threads are, first consider an example (assuming 1 core attack servers and BitNodeMultipliers.ServerWeakenRate = 1):

server.security = 10
server is grown with 500 threads that fortifies security by 2 (to 12)
server is weakend with 40 threads that reduces security back to 10

Baseline would be to require 1 suppress thread to counter a security increas of 0.05 (before factoring in core bonuses and bitnode multipliers).
The desired effect in our example would be if there are 40 suppress threads, the reduction of the suppression statstic woud be 0.5.
This means if suppression was 1.5 before the grow, it would be 1.0 after.

============================================================
**Rough Draft Code Changes:**

```
/* Server.ts */
fortify(amt: number): void {
    this.hackDifficulty += amt * (1 - Math.min(this.suppression, 1));
    this.capDifficulty();

    // reduce suppression
    if (this.suppression > 0) {
    	const suppressionFactor = getSuppressionFactor(this);
    	if (suppressionFactor <= 0) {
    		this.suppression = 0;
    	} else {
    		this.suppression -= (amt / suppressionFactor) / 2;
    		this.suppression = Math.max(this.suppression, 0);
    	}
    }
}

/* Server.ts */
suppress(amt: number): void {
	this.suppress += amt;
	this.suppress = Math.min(this.suppress, 1.5);
}

/* ServerHelpers.ts */
export function processSingleServerSuppression(server: Server, p: IPlayer, dT: number): number {
	if (** check if there are any active suppress calls on this server **) {
		const weakenTime = calculateWeakenTime(server, p);

		server.suppress((dT / weakenTime) / 2);
	}
}

/* ServerHelpers.ts */
export function getSuppressionFactor(server: Server, p?: IPlayer): number {
	// collect number of active suppress threads, suppress threads from servers with 
	// cores > 1 are more effective, so they will count as more than 1
	const effectiveThreads = ****;

	// 0.05 = 0.05 * 1 * 1
	return CONSTANTS.ServerWeakenAmount * effectiveThreads * BitNodeMultipliers.ServerWeakenRate;
}
```

============================================================

Here is a more complex example involving batching:

If weakenTime is 25000 ms, suppression increase per 1000ms is ((1000 / 25000) / 2) => 0.02/s

Suppose a hack operation takes 200 hack threads and 150 grow threads to counter the hack
200 hack => 0.002 * 200 = 0.4 (8 weaken threads)
150 grow => 0.004 * 150 = 0.6 (12 weaken threads)
 => fortify(1.0)

Suppose we run this hack/grow sequence to complete every 1 seconds, how many suppress threads would we need to have active to keep suppress even?
We will need to calculate how many suppress threads to keep suppression decrease equal to suppression increase (0.02/s)
every 1 seconds fortify(1.0) 
0.02 = (1 / factor) / 2
0.04 = 1 / factor
factor = 25
0.05 * threads = 25
threads = 500 
It would take 500 suppress threads to keep up with this hack/grow every 1 second where suppression increase is 0.02/s
Since suppress threads are 2x expensive, ram-wise this is equivalent to 1000 weaken threads.
The break-even point in batches if we could have used 20 weaken threads per batch instead of constantly running suppress threads is 1000 / 20 => 50 cycles.
This means anything less than 50 normal HWGW batches finishing at 1 batch/s, it is more cost-effective ram-wise to run normal HWGW batches. The optimization is actually more complex than that, though, since suppression potentially allows for continuous hack/grow execution as long as security stays level so you would have to factor in the long-term profit over time of a sustainable suppress/hack/grow process vs a cyclical batching HWGW process.

run the sequence every .5 seconds
every 1 seconds fortify(2.0)
0.02 = (2 / factor) / 2
0.04 = 2 / factor
factor = 2 / 0.04 = 50
0.05 * threads = 50
threads = 1000

run the sequence every 25 seconds (same as weaken time)
every 1 seconds fortify(0.04)
0.02 = (.04 / factor) / 2
0.04 = .04 / factor
factor = 1
0.05 * threads = 1
threads = 20
This means if you ran suppress with same number of weaken threads you would have needed and only ran the hack/grow batch as often as weaken time, you would keep up with suppression and security would never grow. The downside is that you would have waited weakenTime * 2 to get suppress to 1.0 and you are using twice as much ram as if you had just run weaken directly.

Test 500 suppress threads and instead of fortify(1.0) every second, its calling fortify(0.4) and then fortify(0.6) back-to-back. Make sure the result is the same.
suppression factor for 500 threads => 500 * .05 => 25
decrease for fortify(0.4) => (0.4 / 25) / 2 = 0.008
decrease for fortify(0.6) => (0.6 / 25) / 2 = 0.012
total = 0.008 + 0.012 = 0.02 (same)

============================================================

```
  /**
   * Suppress security level increases on a server.
   * @remarks
   * RAM cost: 1.9 GB
   *
   * Use your hacking skills to suppress security increases on a server due to hack or grow operations.
   * The functions effect will act continuously in the background as long as the function is running.
   * 
   * A server's suppression statistic grows at a constant rate regardless of how many suppression threads
   * are targeting it. The number of suppress threads targeting a server only affects the magnitude
   * of the suppression statistic's drop when a hack or grow operation targets the server. More suppress
   * threads mean a smaller drop in the suppression statistic, potentially making it easier to keep the
   * suppression statistic above 100% when a server is under constant attack.
   *
   * By default, this command never returns, but an optional parameter can be provided to have it return
   * after some number of milliseconds.
   *
   * Like hack, grow, and weaken, `suppress` can be called on any server, regardless of
   * where the script is running. This command requires root access to the target server, but
   * there is no required hacking level to run the command.
   *
   * ```
   * @param host - Hostname of the target server to suppress.
   * @param operatingTime - Optional parameter to set how many milliseconds suppress should run.
   *    If no operatingTime is provided, suppress runs indefinitely (or until the process is killed).
   * @returns The current suppression level of the target server.
   */
  suppress(host: string, operatingTime?: number): Promise<number>;
```

**Comment by GhostCrab** [comment]
I started implementing this for fun, WIP is here:
https://github.com/danielyxie/bitburner/compare/dev...GhostCrab:suppression

**Comment by GhostCrab** [comment]
@hydroflame any reason for the closure? I have a fully working implementation if you wanted to review it. I understand if you don’t think it fits in the game, just wondering if it was something specific.

**Comment by Ornedan** [comment]
I'm guessing it's that dealing with timings is meant to be part of the challenge of making an optimised HWGW setup.

**Comment by GhostCrab** [comment]
Timing an optimized HG suppressed setup requires a very similar algorithm to HWGW, you just don’t have to factor in the weaken threads, and instead have to do even more complex calculations to figure out how often you can run HG cycles while keeping suppression topped off based on available server RAM. I can see how at first glance this mechanic would supersede writing an efficient HWGW algorithm, but it’s actually more complex and requires more RAM so a good HWGW algorithm would still be necessary in the early stage of a node while you build up resources.

**Comment by GhostCrab** [comment]
Also, just to be clear, I’m totally not upset about this being closed. I understand new mechanics have a higher bar to be accepted. I was just looking for some feedback.

**Comment by phyzical** [comment]
its just a big change, that would affect the existing players. do appreciate the idea submission though.

**Comment by GhostCrab** [comment]
Thanks for the feedback. The extend of the change is a new function along the lines of hack, grow, weaken or share, a couple utility functions similar to hackAnalyze, and 1 new server stat. There would be 0 impact to existing players who don’t engage with the mechanic since when suppression of a server is 0, they behave exactly as before.
