### ISSUE TITLE
My HackTemplate always fails with Error

### ISSUE THREAD

**Issue by vincenthehna** [danielyxie/bitburner#3065]
Cant find reason for Error: _nuke: Not enough ports opened to use NUKE.exe virus._
Scripts were running fine, but when I wanted to run my script to automatically buy private servers (runs fine), it failed to run the hack script on them. When I wanted to restart the hack script on all servers, it then failed on all of them with the given error. Ports are opened and root access is given, stated by the scan-analyze and analyze command in terminal. 

# include (where relevant)

- [ x] Save file
- [ x] Minimal scripts to reproduce the issue
- [ x] Steps to reproduce
- [ x] Version of the game: Bitburner v1.4.0 (a3c599e6)

**hackTemplate.js**

/** @param {NS} ns **/
export async function main(ns) {
    
    function Uniq(a) {
        var seen = {};
        return a.filter(function(server) {
            if(seen.hasOwnProperty(server) == true){
            return false;
            }else {
            return seen[server] = true;
            }
        });
    }

    function NoHomeServer (a) {
        return a.filter(function(server) {
            if (server == "home" || ns.getPurchasedServers().includes(server)) {
            return false;
            }else{
                return true;
            }
        });
    }

    function FindTargets (serverarr) {
        var scannedServers = serverarr;
        var updatedScannedServers = [].concat.apply([], scannedServers.map(x => ns.scan(x)));
        //ns.print("updScServers: "+updatedScannedServers);
        var mergeScannedServers = scannedServers.concat(updatedScannedServers);
        //ns.print("mgdScServers: "+mergeScannedServers);
        var uniqFilteredServers = Uniq(mergeScannedServers);
        //ns.print("uniqFServers: "+uniqFilteredServers);
        var oneInstanceTargetlist = NoHomeServer(uniqFilteredServers); 
        ns.print("oneInstTL: "+oneInstanceTargetlist);
        return oneInstanceTargetlist;
    }
    
    function ServerMoney (serv) {
        return ns.getServerMoneyAvailable(serv);
        }

    function FindTarget(homeserver){ 
        var targetlist = FindTargets(FindTargets(FindTargets(FindTargets(FindTargets(FindTargets(FindTargets(homeserver)))))));
        //ns.print("targetlist: "+targetlist);
        var securityFilteredServers = targetlist.filter(x=>ns.getServerRequiredHackingLevel(x) <= ns.getHackingLevel() && ns.getServerMaxMoney(x) != 0);
        //ns.print("secFiltered: "+securityFilteredServers);
        var targetListMoney = securityFilteredServers.map(x=>ServerMoney(x));
        var highestMoneyCount = Math.max(...targetListMoney);
        ns.print("highestMney: "+highestMoneyCount);
        var targetindex = targetListMoney.indexOf(highestMoneyCount);
        return target = securityFilteredServers[targetindex];    
    }    
    
    while(true) {
        //ns.disableLog(ServerMoney());
        // var target = undefined;
        var target = FindTarget(["home"]);
        ns.print("target: "+target);
        
        var moneyThresh = ns.getServerMaxMoney(target) * 0.75;
        //var maxMoney = getServerMaxMoney(target);
        var securityThresh = ns.getServerMinSecurityLevel(target) + 5;

        if (ns.fileExists("BruteSSH.exe", "home")) {
            ns.brutessh(target);
        }

        if (ns.fileExists("FTPcrack.exe", "home")) {
            ns.ftpcrack(target);
        }

        if (ns.fileExists("SQLInject.exe", "home")) {
            ns.sqlinject(target);
        }

        if (ns.fileExists("HTTPWorm.exe", "home")) {
            ns.httpworm(target);
        }

        if (ns.fileExists("relaySMTP.exe", "home")) {
            ns.relaysmtp(target);
        }

        if (ns.hasRootAccess(target) == false) {
            ns.nuke(target);
        }
        
        while(true) {
            if (ns.getServerSecurityLevel(target) > securityThresh) {
                await ns.weaken(target);
            } else if (ns.getServerMoneyAvailable(target) < moneyThresh) {
                await ns.grow(target);
            } else {
                await ns.hack(target);
                break;
            }
        }
    }
}

[bitburnerSave_1646403190_BN1x0.txt](https://github.com/danielyxie/bitburner/files/8186468/bitburnerSave_1646403190_BN1x0.txt)

**Comment by GhostCrab** [comment]
Before I answer your question - This issue database is for issues/suggestions for the game itself. It is not a forum to ask developers to debug your scripts. In the future, posts questions like this to the discord or sub-reddit and see if someone can help you there. If someone says what you're looking at is actually a bug with the game, you can go ahead and post it here.

I ran hackTemplate.js on your save and just as the error says, you're trying to nuke a server that you dont have enough ports open on (specifically, you're trying to nuke zb-institute which needs 5 ports open, but you only have 4). Add checks to your code to detect the number of open ports on a server before attempting to nuke it.

Please close this issue and continue the discussion in another forum if you have additional questions.

**Comment by vincenthehna** [comment]
OK I am a newbie I wasnt aware of Reddit/Discord, I just came to the end of my competence, I dont get why it doesnt work on the <5 port servers that have root access and it worked just fine before I started the privateserver-buy script. Thanks for the help though
