### ISSUE TITLE
expr terminal command returns incorrect value for remainder/modulo operator (%)

### ISSUE THREAD

**Issue by ChrissiQ** [danielyxie/bitburner#3077]
`expr 121 % 2` returns `1212` instead of `1`.

<img width="249" alt="Screen Shot 2022-03-06 at 11 40 06 AM" src="https://user-images.githubusercontent.com/1127719/156937349-64d0baf7-037f-452b-903a-7df77f9c2dfb.png">

**Comment by mbrannen** [comment]
The regex sanitization didn't allow that operator.  I created a PR with a fix, hopefully it's accepted.
