### ISSUE TITLE
[Netscript 1.x] Logical OR inconsistently evaluates both sides of the expression when the LHS is non-binary

### ISSUE THREAD

**Issue by sgiandomenico** [danielyxie/bitburner#308]
```
function foo() { tprint('FOO'); return false; }

tprint(true || foo());  // true -- OK.
tprint(2 || foo());     // FOO \n 2 -- expecting 2 (without FOO).
tprint(1 || foo());     // true -- expecting 1.
```

There are two issues in the above:

1.  The function foo() is unnecessarily / incorrectly evaluated in the expression `2 || foo()` (the value of the expression as a whole is still correct).
1.  The value `1` is converted to the boolean `true` when used in the OR expression.  (I suppose the 'correctness' of this is debatable, but for consistency it seems to me like it should be returning `1`.  So far I have yet to run into a situation where this actually caused me any trouble, but it was an unexpected result that I discovered while trying to debug the first issue.)

Tested in v0.38.1 on both Chrome and Firefox.

**Comment by hydroflame** [comment]
FYI this isn't "correct or incorrect", it's called a compiler optimisation and netscript 1 doesn't have it.

**Comment by sgiandomenico** [comment]
This is more than mere optimization, since if the RHS has side effects, this behavior functionally changes the execution the program.  I will agree that 'correctness' in this case is a matter of the intended semantics of the language; however, as suggested in the aforedescribed code snippet, the behavior is not even consistent, since the RHS may or may not be evaluated even when the LHS is decidedly true-ish.

**Comment by hydroflame** [comment]
https://en.wikipedia.org/wiki/Short-circuit_evaluation
Some language have it, some language don't, I agree netscript 1.0 should have it but it's not a trivial feature to implement

**Comment by sgiandomenico** [comment]
This features is already largely implemented.  Looking at the source NetscriptEvaluator.js, I see
```
function evalBinary(exp, workerScript){
    return evaluate(exp.left, workerScript).then(function(expLeft) {
        //Short circuiting
        if (expLeft == true && exp.operator === "||") {
            return Promise.resolve(true);
        }
        if (expLeft == false && exp.operator === "&&") {
            return Promise.resolve(false);
        }
   [...]
}
```

I think making the short-circuit evaluation consistent might be as simple as replacing the expression 'expLeft == [true/false]' with simply 'expLeft'.

**Comment by danielyxie** [comment]
Made more consistent in v0.39.0

Let me know if there's still any issues

```
if (expLeft && exp.operator === "||") {
    return Promise.resolve(expLeft);
}
if (!expLeft && exp.operator === "&&") {
    return Promise.resolve(expLeft);
}
```

**Comment by sgiandomenico** [comment]
Works for me!
