### ISSUE TITLE
Consistent handling and formatting of numbers

### ISSUE THREAD

**Issue by Nezrahm** [danielyxie/bitburner#3080]
The formatting of numbers differs in various places. Just take a look at the "money earned" view under Stats.

![image](https://user-images.githubusercontent.com/8653358/157016622-1ae3cd78-766f-47d6-996c-1e281376892f.png)

The standard ns.nFormat caps out at "t".

The formatting should be the same everywhere (and support larger values), like in most of the corporation stuff. One issue there though seems to be that you can't input in the same format. For example, under factions can you choose to donate "1t" but that doesn't work for the corp inputs.

One suggestion regarding this from HeinousTugboat was to take inspiration from [Tyrope's lib](https://github.com/tyrope/bitburner/blob/master/lib/format.js])

Bitburner v1.4.0

**Comment by hydroflame** [comment]
For whoever taking this card.

The default library we use only handles kmbt. We added code on top of it to handle more letters on top.

Beyond a certain number we default to scientific notation and thats ok. 

For this card to be considered fixed, negative numbers need to be handled like positive numbers.
