### ISSUE TITLE
rm -r should confirm that you want to delete a directory and then do it.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#3090]

**Comment by Master-Guy** [comment]
Do you want this to be a yes/no prompt in the UI, or a textual yes/no question in the terminal?
The first is easy to implement, the latter might be very non-trivial

**Comment by Undeemiss** [comment]
bump. I can do this if given clear direction (I was planning to write a script to do this for my personal save, but can just write it as a feature instead if you want)
