### ISSUE TITLE
Sometimes hover tooltip does not disappear after mouse leave

### ISSUE THREAD

**Issue by ChrissiQ** [danielyxie/bitburner#3094]
I think any save can reproduce this. Experienced this behaviour using all of the web/steam/electron versions, on both Windows and Mac OS.

Verison: Bitburner v1.5.0

It always happens when the "Hire Employee" button becomes disabled due to max employees.  I think it happens elsewhere too.  Issue resolves when the current view is replaced (eg. tab switch).

Including video showing issue on corp city view when hiring employees.  Sorry it's a little phrenetic but it's basically showing that when hiring employees, once the max is hit and the button is disabled, the tooltip stays behind and won't disappear until the view is replaced by switching city tabs.

https://user-images.githubusercontent.com/1127719/157184925-efd828d0-099c-4ba9-9591-7c77ca2f6786.mp4

**Comment by ChrissiQ** [comment]
User Noaphiel on discord pointed out:

> got another one, actually not a real bug, but a QoL feature, that's missing from the previous version:
> when you hover over Sell Shares in company (and it's on cooldown), it doesn't display the time left until you can sell shares again. It was a feature in v1.4, that is missing in v1.5

I think something changed about buttons such that they can no longer support a tooltip when the button is disabled, but I'm not really sure since I haven't checked.  That's my suspicion though from this behaviour.

**Comment by ChrissiQ** [comment]
More wisdom from Discord: user Nezrahm says:

> disabled html elements don't receive any mouse events, which is perhaps the issue here?

I think they are spot on.  I believe the interface changed to use disabled buttons instead of allowing an open modal where no action can be taken.  Which is why the bug is now rearing its head.

**Comment by MartinFournier** [comment]
> I think something changed about buttons such that they can no longer support a tooltip when the button is disabled, but I'm not really sure since I haven't checked. That's my suspicion though from this behaviour.
> 
> Or maybe it's because that button didn't used to become disabled - maybe this is actually a more longstanding bug?

Material UI's <Tooltip> component will warn in the console of dev builds if it receives a component with disabled pointer events as a children. If it's the case, you can usually just wrap the button in a span. It will sometime look wrong when using a ButtonGroup though.

```js
<Tooltip title='abc'>
  <span><Button disabled>Stuff</Button></span>
</Tooltip>
```

**Comment by phyzical** [comment]
i gave it a try
```
 <ButtonWithTooltip title={<Typography>Automatically hires an employee and gives him/her a random name</Typography>} disabled={props.office.atCapacity()} onClick={autohireEmployeeButtonOnClick}>
            Hire Employee
          </ButtonWithTooltip>
          
          
          interface IButtonWithTooltipProps {
  title: string | React.ReactElement;
  disabled: boolean;
  onClick: any;
  children: any;
}

const ButtonWithTooltip = ({ title, disabled, onClick, children }: IButtonWithTooltipProps): React.ReactElement => (
  <Tooltip title={title}>
    <Button disabled={disabled} component={disabled ? "div" : Button} onClick={disabled ? undefined : onClick} > {children} </Button>
  </Tooltip>
);
```

sadly the issue still occured the one difference to the SO was ` component={disabled ? "div" : Button}` providing undefined wouldnt compile

**Comment by hydroflame** [comment]
fixed
