### ISSUE TITLE
Bug: Bypass static and dynamic RAM analysis of ns.hacknet

### ISSUE THREAD

**Issue by dcrego** [danielyxie/bitburner#3103]
- [ ] Save file
- [x] Minimal scripts to reproduce the issue
```
ns.tprint(ns["hacknet"].getNodeStats(0))
```
- [x] Steps to reproduce
  1. Create a script `test.js` with the code above.
  2. Check `mem test.js`: no RAM for ns.hacknet. It should be 4GB.
  3. Run `run test.js` to see that it works.
- [x] Version of the game
Bitburner v1.5.0 (bc952147)

**Comment by hydroflame** [comment]
not a bug
