### ISSUE TITLE
readport fails on Steam edition v1.5.0

### ISSUE THREAD

**Issue by himonline33** [danielyxie/bitburner#3105]
Trying to use readPort on Steamedition v1.5.0 fails but works in browser(Chrome)

save is fresh

![image](https://user-images.githubusercontent.com/7318536/157543729-4760f6b8-e369-4b9c-8e11-96977004cd59.png)

/** @param {NS} ns **/
export async function main(ns) {
	await ns.writePort(1, "Hello world");
	await ns.tprint(ns.readPort(1));
}

**Comment by phyzical** [comment]
hmm, just tried the latest dev (but this is the browser also) ill try the steam version localy later today 

![image](https://user-images.githubusercontent.com/5182053/157544650-72702cae-2bb7-49cf-b90f-2f83fc76b1f8.png)
