### ISSUE TITLE
Blurred text on Steam version

### ISSUE THREAD

**Issue by blueglyph** [danielyxie/bitburner#3106]
**Description:**

The Steam version shows blurred text after a while, it seems to happen once the tutorial is opened on a browser, or when the user switches to another window.

- When clicking on some part of the window, or when scrolling / changing page and so on, the text becomes clear again. Sometimes it's only partial, and it quickly becomes blurred again.
- It doesn't seem to be linked to not being in "fullscreen" mode, but since it's not an actual fullscreen mode and the game doesn't start with this mode anyway, it makes any test impossible to confirm that. If the "blurred" issue appears, toggling to "fullscreen" doesn't solve the problem.
- It is not linked to the game advancement, I get this with a fresh game or an ongoing game.

The two first screenshots below show the difference blurred / normal. Note that I had to restart the game to get the "normal" screenshot because once the problem of blurred text appears, it is not possible to get a clear screenshot anymore.

**How to reproduce:**

- Start the game from Steam
- Open the tutorial, for example on "Getting Started"
=> opens the tutorial in a browser
=> the text may already appeared blurred, see the 3rd screenshot. This happens at once, it's not progressive, all characters get blurred.

- Switch back to the game
=> the text is blurred
- Move the mouse over the text, or change the page
=> the text may be clear again for a while, at least on a part of the window. When it happens, it's again the whole or a part of the screen that gets blurred all at once. Sometimes it's slightly blurred, sometimes it's unreadable.

This makes playing the Steam version of the game very inconvenient, and almost impossible after a while.

**Version**: 1.5.0 (bc952147)

**Screenshots:**
1st: blurred text (this is extreme and not always so blurred when the game window is in focus)
![Clipboard01](https://user-images.githubusercontent.com/31706195/157701890-fb11a1e4-d8a7-49d8-b707-2064a49eeb4c.jpg)

2nd: normal, before the issue starts
![Clipboard02](https://user-images.githubusercontent.com/31706195/157701909-c54a0523-6553-47e7-9697-94120da11d63.jpg)

3rd: see "how to reproduce", browser in front, game in background with text getting blurred
![Clipboard03](https://user-images.githubusercontent.com/31706195/157704815-75b25d2c-5007-4521-8c61-dc0db5a72829.jpg)

**Other information:**

Screen resolution: 1920x1080
Chrome version: latest as of today (Version 99.0.4844.51 (Official Build) (64-bit)), default browser
Edge version: latest as of today (Version 99.0.1150.36 (Official build) (64-bit))
OS: Windows 10 Home 64-bits, updated
GPU: RTX 3070, NVIDIA drivers 497.09

I don't have any particular issue with the (default) Chrome browser, the rendering is fine. Same with Edge which is still installed (but I have no idea what is used with the Steam version of the game, so this may be irrelevant).

Steam has no rendering issue either, nor the games I play on that platform.

**Comment by blueglyph** [comment]
I'm not sure I can compare versions though:

- the Steam version shows: "1.5.0 bc95214"
- unfortunately the tag is missing for that version
- revision bc952147fd2b1d5238cfd05ff4a4e12bc4815937 seems to be v1.5.0 from the commentary, except the displayed version (from main.bundle.js) shows "1.4.0"
- revision 192a037dfa375813ac39f0ed17df99383d70c86b is the first of the branch 'master' to change the version to 1.5.0 bc952147, so I suppose it's the one that corresponds to the Steam "1.5.0".

**Comment by phyzical** [comment]
so is the issue that when its in the background its blurred and you click back and its fine? or clicking off the game blurs it and it never fixes again?

**Comment by blueglyph** [comment]
Once it gets blurred, it's never really fixed, even if I don't switch task anymore.
If there's a way to fix it, I haven't found it yet.

**Comment by phyzical** [comment]
do you happen to use more than 1 monitor? ive seen weird things happen with monitors that "Try too hard"

the weird part is its not doing anything special, maybes its an electron specific bug?

```
<Link
          color="primary"
          target="_blank"
          href="https://bitburner.readthedocs.io/en/latest/guidesandtips/gettingstartedguideforbeginnerprogrammers.html"
        >
        ```

**Comment by phyzical** [comment]
also what resolution and dpi are you using?

**Comment by blueglyph** [comment]
No, only 1 monitor.

I'm not sure what you mean by electron (I assume it's what plays the role of browser in the Steam version) or the code you've pasted.

I was just wondering if that was the fact I didn't keep the game window maximized, but I deleted the config.json and tried again, it still happens.

The game just updated to a new revision of 1.5.0, but the same problem is still there. And I checked the integrity of the local files too, just to make sure, it's not that.

It's not happening every time, but it seems to happen almost every time I open the tutorial from the game. If not immediately, after a little while or after switching windows back & forth a few times.

**Comment by blueglyph** [comment]
Resolution is 1920x1080 as said before, and it's a 24" monitor. I'm using it in landscape, scale is 100%.

Nothing fancy, really.

**Comment by blueglyph** [comment]
I would even say that only clicking on Tutorial is enough, no need to click on any of the links to open a browser from the game.
After that, switching tasks makes the problem appear.

**Comment by phyzical** [comment]
i cant seem to replicate but looking at the screenshots again  it does seem like some sort of accessibility feature maybe

![image](https://user-images.githubusercontent.com/5182053/157997294-7db98091-c896-4164-a011-7f6b270087f9.png)

like how the terminal and sidebar text is blurred but the responses of the terminal commands are clear

**Comment by phyzical** [comment]
i did also find these

 https://github.com/mui/material-ui/issues/5809
 https://stackoverflow.com/questions/32034574/font-looks-blurry-after-translate-in-chrome

but looking in the code we only have a few references to translates (so unless a dependency is responsible for it) the fix mabye just be to adjust the translates to add a minor offset instead of fully relying on %.

the problem is i cant seem to replicate the issue so hard one to try and fix

**Comment by MartinFournier** [comment]
For what it's worth, in the screenshot, even the rendering of the menu is blurred (file, etc), which is handled by electron itself so we probably have no control over that.

@blueglyph You might want to check this if you have an Nvidia GPU, someone seems to have had a similar problem with a possible fix in the nvidia control panel
https://github.com/microsoft/vscode/issues/51789#issuecomment-416868789

**Comment by phyzical** [comment]
yeah i had a thought that hardware acceleration may be at play here

**Comment by blueglyph** [comment]
Thanks @MartinFournier, that seems to solve the problem, I could not see any blurred text!

And it's good to know too. Now I see what proton is, and indeed Atom is using it.

It's probably worth signaling the problem to them.

**Comment by phyzical** [comment]
closable :)
