### ISSUE TITLE
`print` is also a browser function that brings up the print dialogs

### ISSUE THREAD

**Issue by jaguilar** [danielyxie/bitburner#311]
We should probably put a "print" into the namespace of NS-JS modules that just throws an exception. Otherwise you end up getting an uninterruptible loop of print dialogs that is a bit surprising and hard to reason about.

**Comment by kopelli** [comment]
Yeah, this is a bit of a bug in that you can still access the global scope (anything attached to `window`) without actually prefixing it with `window` and incurring the RAM cost.

**Comment by jaguilar** [comment]
Of course. I'm just saying that with print especially, it might be good to write an alias into the user's script to prevent them DOSing themselves.

**Comment by danielyxie** [comment]
Done in v.41.0. Unfortunately this means people can't define their own `print()` functions since those will get automatically overriden.
