### ISSUE TITLE
Script Editor loses fidelity with > 8 scripts (1800x1200 screen res)

### ISSUE THREAD

**Issue by Penumbra69** [danielyxie/bitburner#3121]
Issue: 
When the script editor is opened with more than 8 files (I'm on a Mac using 1800x1200 screen res), the CSS seems to shrink the title and leave a blank box next to it, making it nearly impossible to read the title if you have more than 8 scripts open.

Here's a screenshot with 8 open:
![image](https://user-images.githubusercontent.com/17106044/157974224-b82b8371-6398-4823-b7e3-0e8726804695.png)

And here's a screenshot of 10 scripts open:
![image](https://user-images.githubusercontent.com/17106044/157974293-2e48b378-2229-4c64-9f77-d83df5785546.png)

And for fun (also to show it continues) - here's 12 scripts open:
![image](https://user-images.githubusercontent.com/17106044/157975041-69030546-d24f-4dc3-928b-5c90f36f1840.png)

Note: I haven't changed the font or font size in the theme, but I did adjust the line height to 1.25 (which shouldn't matter, but I want to be sure all details are captured).

Expected behavior:
 - A scrolling list of open files in the editor
 
Actual Behavior:
 - An over-shrinking of the title 

Version of the game:
- Bitburner v1.5.0 (bc952147)
- Using "Brave" browser - [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)](https://brave.com/latest/)

Steps to reproduce:
Open scripts in the editor until you fill the editor's natural head space (took 8 for me), and then open a few more.

**Comment by InDieTasten** [comment]
I can reproduce the infidelity, though it expresses itself somewhat differently:
![image](https://user-images.githubusercontent.com/7047377/158028938-02ae60bc-365e-4b65-9494-04f2222f2b41.png)

(Same version, but Edge Browser: Version 99.0.1150.36 (Official build) (64-bit))

Ideally the tabs would have some min-width and the tab display would allow horizontal scrolling like VS Code is doing it.

**Comment by phyzical** [comment]
we recently removed the min-width for something else 😆  @nickofolas what do you think should be just add it back?

**Comment by nickofolas** [comment]
sounds fine, just need to make sure the issue that it was removed for is fixed along with adding it back haha

can't test anything right now but i imagine just giving a 100% width to the inner tab content (part with the filename) might fix it?
