### ISSUE TITLE
Feature: bladeburner.inBladeburner() like gang.inGang()

### ISSUE THREAD

**Issue by Cabu** [danielyxie/bitburner#3122]
Could we have a function like gang.inGang() but for bladeburner? 

The actual way for me of doing something similar is to catch the error "Must have joined bladeburner" when accessing any method of the bladeburner class. Method I don't find very clean... 
Or I am very bad at reading the API and there is already something for that purpose :/

**Comment by phyzical** [comment]
had a quick look the api uses    `const bladeburner = player.bladeburner;` but can confirm this currently isn't exposed like it is for Gang. its probably just an oversight ill make a pr and if its be design we can just close it
