### ISSUE TITLE
Feature request: Green on black documentation is hard to read / straining

### ISSUE THREAD

**Issue by blueglyph** [danielyxie/bitburner#3126]
**Feature request**

Provide another theme for the documentation.

The current version is green on black, which is very hard to read and straining for the eyes.
The recommendation for long texts is a dark colour on light colour, however if the desire is to use a light-on-dark theme for the "hacker" atmosphere, something closer to "one dark" would be already less straining than the current one.

**Version**

Version 1.5.0 b265d7ba

![doc](https://user-images.githubusercontent.com/31706195/158015118-da781695-317c-4373-abff-8a091b86bf3b.jpg)

**Workaround**

Downloading the PDF version of the documentation.

Perhaps there are other CSS files if that's based on a doc framework and there aren't too many customizations, but I couldn't find it so far.

**Comment by hydroflame** [comment]
I'm colorblind so I'm ill equipped to handle this situation.

I made the changes personally to make the documentation match the default theme of the game but that was a bad idea because a11y is far more important. 

Whoever fixes this. Probably just remove the css files for rst. I'm sure the default theme is better.

**Comment by Undeemiss** [comment]
Personally, I've always thought it was really cool-looking. Perhaps making it something toggleable would be a good middle-ground?

**Comment by blueglyph** [comment]
> Personally, I've always thought it was really cool-looking. Perhaps making it something toggleable would be a good middle-ground?

Sure, that's how I saw it. Obviously many people like the current theme, so it would be an additional one.
