### ISSUE TITLE
Semi-colon separated list of nano commands only opens last command in Script Editor

### ISSUE THREAD

**Issue by InDieTasten** [danielyxie/bitburner#3130]
## Steps to reproduce
Run the following command in the terminal:

```
nano file1.js; nano file2.js;
```

## Expected behavior
Script Editor opens with both file1.js and file2.js.

## Actual
Observe, that only file2.js will be opened in the script editor.

## Details
Version of the game, e.g. Bitburner v1.5.0 (bb433d46)

**Comment by phyzical** [comment]
as a workaround i think 

`nano file1.js && nano file2.js;` would work

**Comment by hydroflame** [comment]
Unfortunately it'd be very difficult to implement &&
