### ISSUE TITLE
Bugreport

### ISSUE THREAD

**Issue by IC333** [danielyxie/bitburner#3135]
Hey found a bug :)
Requirements:
x Sleeves 
x -1 Factions
Steps to reproduce:
1. Set all sleeves to "Working for Faction" but dont click "set to task"
2. Then click "set to task" 
3. And if u run out of Factions the game will crash

Version v1.5.0 b265d7ba
[RECOVERY_BITBURNER_1647190052.txt](https://github.com/danielyxie/bitburner/files/8240212/RECOVERY_BITBURNER_1647190052.txt)

**Comment by phyzical** [comment]
hey @IC333 thanks for rasing i think this one miight be fixed in the dev branch already, mind trying the beta version (if in steam?) backup your save just incase :)
