### ISSUE TITLE
Hacking world_daemon doesn't kill running scripts

### ISSUE THREAD

**Issue by GingerAvalanche** [danielyxie/bitburner#3136]
- Steps to reproduce
  - Run the amount of scripts and/or get the amount of hacknet nodes/upgrades needed to start slowing your game down
  - Hack world_daemon
- Version: Bitburner v1.5.0

The error log text will come up very slowly. I'm making an assumption, here, that the scripts/hacknet nodes still running in the background are the cause. Depending on how many you have, it can take quite a while: I managed to get tired of waiting, look up the Github, and write up this entire issue (~15 minutes?) and my game still hasn't printed the bitnode ascii art.

Whatever the case, thematically the bitnode has been destroyed so everything on it should be halted at that point, in-universe.

**Comment by phyzical** [comment]
happen to have a save file right before killing the daemon for reproduction?

**Comment by GingerAvalanche** [comment]
Not at the moment, but I can get one by tomorrow, probably. Stay tuned

**Comment by GingerAvalanche** [comment]
[bitburnerSave_1647241176_BN9x1_breakstuff.zip](https://github.com/danielyxie/bitburner/files/8242386/bitburnerSave_1647241176_BN9x1_breakstuff.zip)

Here's the save. Steps to reproduce:
 - `run do_crimes.js`
 - `run purchase/crackers.js`
 - `run startup_hacks.js` (click through the three popups)
 - `run crack_servers.js`
 - Wait for a few seconds for crack_servers.js to crack world_daemon

I got the save up to 1000 NeuroFlux just to make the problem *really* obvious. The text should take somewhere in the area of a couple minutes just to start printing the bitnode map.

The main sources of slowdown in these scripts come from
1. `do_crimes.js` trading hashes for money millions of times every 4 seconds (which could probably be solved by a parameter allowing the player to specify how many to buy, instead of repeatedly calling the function, though this probably only matters because of 1000 NFG - in normal play, I've never gotten hashes fast enough for this to get *too* bad)
2. `hackcycle.js` (run by `startup_hacks.js`) running once for each hackable server and spawning a hack/grow/weaken process every 251ms. Again, exacerbated by 1000 NFG, but given that it's sequential hacks, and not batches, there are probably people out there with algorithms spawning 4x that many processes, so it might be a wash.

**Comment by hydroflame** [comment]
triggering the bitverse should kill all runnign scripts and call player.stopAction

**Comment by phyzical** [comment]
i had a scan we do kill all scripts, but i couldnt see anything around stopping the player action. only the terminal action

**Comment by hydroflame** [comment]
Ok so killing all scripts would make the implementation of destroyWorldDaemon a nightmare. So we're just not going to. If you're lagging then kill some scripts :)
