### ISSUE TITLE
TypeError: (destructured parameter) is undefined (at "ScriptEditor")

### ISSUE THREAD

**Issue by RaresEra** [danielyxie/bitburner#3142]
### How did this happen?

I made about forty scripts and forget to close the windows in the script editor.

- [ ] Save file
- [ 40ish] Minimal scripts to reproduce the issue
- [ 2] Steps to reproduce

### Environment

* Error: TypeError: (destructured parameter) is undefined
* Page: ScriptEditor
* Version: v1.5.0 (b265d7ba)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
* Features: lang=en-US cookiesEnabled=true doNotTrack=unspecified indexedDb=true
* Source: https://danielyxie.github.io/bitburner/main.bundle.js

**Comment by phyzical** [comment]
@RaresEra any chance of a save file? and the last file you opened before the error?
