### ISSUE TITLE
Add functions to buy WSE Account and TIX API Access

### ISSUE THREAD

**Issue by ToasterUwU** [danielyxie/bitburner#3143]
There are functions to buy the two Stockmarket things from Four Sigma.
[ns.stock.purchase4SMarketData](https://github.com/danielyxie/bitburner/blob/27a54217eb69c8d69c81ee523855b8265c513932/src/NetscriptFunctions/StockMarket.ts#L313) and [ns.stock.purchase4SMarketDataTixApi](https://github.com/danielyxie/bitburner/blob/27a54217eb69c8d69c81ee523855b8265c513932/src/NetscriptFunctions/StockMarket.ts#L332), but there are no functions for all the other things. 
Meaning that if I need it for my fully automated setup, I need to manually buy it, which for obvious reasons is not optimal or right.

I would add this myself since it is fairly simple, but I'm a Python dev (and other languages), with no experience in TS, so I wouldn't write the optimal code someone else more experienced can provide.

**Comment by phyzical** [comment]
@ToasterUwU have a crack :) youll learn about the "gross" js world :P and we can help suggest what we think might be more correct

**Comment by ToasterUwU** [comment]
> @ToasterUwU have a crack :) youll learn about the "gross" js world :P and we can help suggest what we think might be more correct

No thanks. I already have a high-level interpreted language in my arsenal. I rather focus my time on learning other languages like rust.

I don't think JS or TS are "gross" or anything. I just already know a language with the same properties. And since I don't plan on becoming a web-dev, I won't need JS.

**Comment by phyzical** [comment]
fair enough :) quick followup any chance you can list the functions you were after

**Comment by incubusnb** [comment]
I'm working on this right now, Hopefully I'll have a PR by tonight.
