### ISSUE TITLE
ns.asleep function missing from RamCosts

### ISSUE THREAD

**Issue by cjwprostar** [danielyxie/bitburner#3149]
The 'asleep' function is missing from RamCosts in src/Netscript/RamCostGenerator.ts and throws a warning in the console. Not really an issue but certainly annoying getting 5 warnings a second while trying to debug.

RamCostGenerator.ts:416 Unexpected type (undefined) for value [asleep]

Bitburner v1.5.0 (3aabbb7a)

**Comment by phyzical** [comment]
haha isnt it free, thats kinda funny
