### ISSUE TITLE
Different Multiplier for servercost in BN-5

### ISSUE THREAD

**Issue by RefRec97** [danielyxie/bitburner#3172]
The Description for Bitnode 5 reads as follows:
In this BitNode:

The base security level of servers is doubled
The starting money on servers is halved, but the maximum money remains the same
Most methods of earning money now give significantly less
Infiltration gives 50% more reputation and money
Corporations have 50% lower valuations and are therefore less profitable
Augmentations are more expensive
Hacking experience gain rates are reduced

It does not include an increased cost to bought servers.
In bitnode 1 the formula was 55000 * ram = server cost.
But in bitnode 5 it is roughly 136.857 * ram = server cost.

In my case 2048GB cost 112m in bn1 but 280.284m in BN5.

Not sure if im missing something and if this is just missing from the doc or a bug. After clarification i could create a pullrequest.

**Comment by hydroflame** [comment]
Well most bitnode don't list all their parameters, so I'll open another card.

**Comment by RefRec97** [comment]
okay sure, thank you for the info!
