### ISSUE TITLE
Bulk Purchase errors when not affordable, but code can't see price

### ISSUE THREAD

**Issue by TheRealMaxion** [danielyxie/bitburner#3173]
[Bulk Purchase](https://github.com/danielyxie/bitburner/blob/fc963bb583f31c053a26074f05e29dc1ad5de905/src/Corporation/Actions.ts#L265)
How is a player's code supposed to avoid triggering the error that is thrown when the corporation can't afford a bulk purchase, if the code can't see what the price is?
There seems to be no limit to how much the price can change, so a reasonable hardcoded estimate will eventually become wrong.
And calculating the price of a material that is not used for production appears to be very impractical if at all possible for player code currently.

**Comment by TheRealMaxion** [comment]
A possible solution could be, if the corporation can not afford the bulk purchase, then instead of erroring, the purchase amount can be limited to the amount that is affordable.

**Comment by phyzical** [comment]
cant the user use `getMaterial` and get the cost that way?

**Comment by TheRealMaxion** [comment]
> 

At least according to the docs, that does not include that information.
![image](https://user-images.githubusercontent.com/13872642/159144430-66f018b0-c82e-4c07-adb8-87dc75e1c410.png)

**Comment by phyzical** [comment]
ah sorry your right, doesn't expose it. should be an easy fix 👍
