### ISSUE TITLE
There is no netscript function to limit corporation production

### ISSUE THREAD

**Issue by TheRealMaxion** [danielyxie/bitburner#3174]
https://github.com/danielyxie/bitburner/blob/fc963bb583f31c053a26074f05e29dc1ad5de905/src/Corporation/Actions.ts#L479

There is currently no netscript function to set the production limit of corporation products (despite there being a ui function for doing this manually), which becomes an issue when there is not enough space in the warehouse to support the full production of the city's products, and not enough funds to sufficiently expand the warehouse. This may just be a late game problem, but still.

Is this intentionally not available to scripts because it could enable price inflation to get more extreme than it already does?

**Comment by phyzical** [comment]
@pigalot was this left out on purpose do you know?

**Comment by pigalot** [comment]
No I expect we just missed it as I don't know anyone that was working with me on it that uses limits.
