### ISSUE TITLE
Producing too many materials lowers product production to 0

### ISSUE THREAD

**Issue by TheRealMaxion** [danielyxie/bitburner#3180]
https://github.com/danielyxie/bitburner/blob/77cb7dd775b0d738bd1c945cdcf4b1e2836301e8/src/Corporation/Industry.ts#L449

With apparently too high production multiplier, because materials are processed before products, the produced products may fill the entire warehouse, causing there to be 0 production of products. This has only been observed to occur in the Real Estate industry, especially with production multiplier over 100k.
This causes the profits of the division to be much lower than they should be.
Since there is currently no way to artificially limit production of materials like there is for products, the only way currently to prevent this from happening is to lower the amount of production boosting materials in the warehouse until material production is low enough to not take up all the available space.

If possible, determining the produced amount of materials and products should be done together, both so that the production equation becomes factual as shown, with equal amounts produced between materials and each product (when not set to limit production), and most importantly so that material production can not drown out all product production.
Ideally this would also let there be equal production amounts (when limiting production is not set) between the products of the industry instead of the current first come first serve basis where the oldest products are made first, and newer ones only made if there is space left over.

**Comment by phyzical** [comment]
would having a way to limit production for non products solve this issue maybe?

**Comment by TheRealMaxion** [comment]
> would having a way to limit material production solve this issue maybe?

That could work. Currently netscript has no way to limit the production of neither products nor materials. And manual can only limit products.

**Comment by phyzical** [comment]
alright we will go ahead and add this :) 
@TheRealMaxion did you want to have a crack? 
would need somewhere on the ui to enter this per product and material, 
api function to match ui functionailty 
then check this in appropriate places to limit buys per tick (export would be doing something similar in terms of "limiting" for reference)

**Comment by phyzical** [comment]
fell free to fix https://github.com/danielyxie/bitburner/issues/3173 while your there too

**Comment by TheRealMaxion** [comment]
If someone else would like to do it, feel free to do so.
