### ISSUE TITLE
Purchases in Megabyte Burner 2000 do not remove money from the player

### ISSUE THREAD

**Issue by simplyzalp** [danielyxie/bitburner#3182]
While playing Megabyte Burner 2000, purchasing items does not subtract the cost from the player's balance. I've confirmed this for buying the TOR router, a 1GB server, a hacknet node, hacknet upgrades, and traveling. (The player **is** correctly blocked from making a purchase if they don't have enough cash to "pay" for it.)

Steps to reproduce:
1. Start a game of MB2k at the arcade.
2. In MB2k, buy a hacknet node for $1000. (Once the player's balance is high enough, other items can be purchased with the same effect.)
Expected behavior: The player has a new hacknet node and zero cash.
Actual behavior: The player has a new nethack node and still has $1000 cash.

Version 1.5.0

Save file probably not relevant, but attached below.

[bitburnerSave_1647664266_BN3x0.txt](https://github.com/danielyxie/bitburner/files/8308593/bitburnerSave_1647664266_BN3x0.txt)

**Comment by simplyzalp** [comment]
Taking a quick look now (it's 1am)...

It looks like this is related to the definition for **PlayerObject.prototype.loseMoney** at [bundle.js:617](https://github.com/bitburner-official/bitburner-legacy/blob/master/dist/bundle.js):

```
PlayerObject.prototype.loseMoney = function(money) {
    money = 0;
    if (isNaN(money)) {
        console.log("ERR: NaN passed into Player.loseMoney()"); return;
    }
    this.money = this.money.minus(money);
}
```

For some reason `money` (the cost of the purchase` is set to 0 before taking any action, so 0 cash is always lost by the player on purchase. It seems that removing that line would solve the issue.

**Comment by hydroflame** [comment]
intended
