### ISSUE TITLE
Tutorial should be clearer on ns1 vs ns2

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#3188]
The first screen of the game should show a piece of code in ns1 and in ns2.

It should explain that new developpers should use ns1 and experienced dev use ns2.

"If you understand what's going on on the left side click X" or whatever.

The tutorial should adjust based on that choice.

**Comment by nanogyth** [comment]
n00dles.script
```js
while(true) {
  hack('n00dles');
}
```

n00dles.js
```js
/** @param {NS} ns */
export async function main(ns) {
  while (true) {
    await ns.hack('n00dles');
  }
}
```

The ns2 looks much more complicated.
Maybe a suggestion that ns2 is faster and closer to modern javascript??

**Comment by phyzical** [comment]
https://bitburner.readthedocs.io/en/latest/netscript/netscriptlearntoprogram.html#netscript-1-0-vs-netscript-2-0 is it covered already

**Comment by nanogyth** [comment]
Well, "covered" is pretty far from it being the first screen of the game.

I am fine with the tutorial being in ns1 as a softer, closer to psuedo-code ns2.
But ideally everyone would be using ns2 after the tutorial.
