### ISSUE TITLE
Small town achievement (Corp 3000 employees) calculation is incorrect

### ISSUE THREAD

**Issue by BrianLDev** [danielyxie/bitburner#3194]
The achievement says `Have a division with 3000 employees`, but the calculation doesn't sum up all the employees in the division, it just looks at one individual city.  I found out because I have 3,240 employees in a division (540 employees in each city: 540*6 = 3,240) but the achievement wasn't popping.

Should be a pretty easy fix, just sum the employee count for all cities within a division.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/16980550/159139889-3f78d0f6-edad-40e4-8bed-85bbb6e91603.png">

**Comment by phyzical** [comment]
i wonder if the description is wrong for this one? "small town" probably shouldn't be spanning  multiple cities right?

**Comment by BrianLDev** [comment]
@phyzical It could go either way.  A former boss I worked for used to brag about "providing jobs and livelihoods for an entire town worth of people" and all the employees were spread across the US.

Timing-wise, I'd argue that it works best when you use the division subtotal, since that puts the achievement in a similar cost/difficulty to the other Corp achievements.  But making it 3,000 in only 1 city would be 5-6x worse.

**Comment by BrianLDev** [comment]
Plus, everyone works remote these days anyways 😂

**Comment by Ornedan** [comment]
Getting to 3000 in one city is more expensive than 3000 total across all cities. So the fix should be to change achievement text to say "Have a division with 3000 employees in one city." to make it accurate, rather than making the achievement easier to match current inexact description.
