### ISSUE TITLE
Add cheap function to check whether a corporation is founded or not

### ISSUE THREAD

**Issue by smmalis37** [danielyxie/bitburner#3203]
It'd be nice to have a cheap (in terms of RAM cost) function that just returns a bool for whether or not a corp has been founded. This could be useful, for example, to determine whether to spend hacknet hashes on corporation funds or something else. Currently simply accessing the `corporation` property requires 1TB of ram, making this a prohibitively expensive thing to check for if no other information is needed.

**Comment by phyzical** [comment]
check out `getPlayer` ;) https://github.com/danielyxie/bitburner/blob/dev/dist/bitburner.d.ts#L4834

**Comment by smmalis37** [comment]
Hah! That'd work, thanks!.
