### ISSUE TITLE
Gang territory gets stuck around 99.84% despite rival gangs having 0.00% territory

### ISSUE THREAD

**Issue by PSEUDOSTAGE** [danielyxie/bitburner#3206]
Gangs appear to be getting stuck just shy of capturing 100% territory despite rival gangs having no territory to capture.

Steps:
- Create gang and level them up for success
- Turn on Territory Warfare
- Wait until all other gangs have 0.00% territory

Noticed in Version: Bitburner v1.5.0 (06b2ec89)

Updated to Version: Bitburner v1.5.0 (cbeb6d13) and problem persists.

![bitgangs2](https://user-images.githubusercontent.com/61438810/159180175-5a29c69c-54b3-4787-be1c-06d673e009bf.PNG)

**Comment by Arronax06** [comment]
The rounding issue seems to be located in `Gang/Gang.ts` line 228-245:
`if (AllGangs[thisGang].territory > 0.999)  AllGangs[thisGang].territory = 1;`
          ...
          `if (AllGangs[thisGang].territory < 0.001) AllGangs[thisGang].territory = 0;`
          ...
         ` if (AllGangs[otherGang].territory < 0.001) AllGangs[otherGang].territory = 0;`
          ...
         ` if (AllGangs[otherGang].territory > 0.999) AllGangs[otherGang].territory = 1;`

**Comment by hydroflame** [comment]
I'm going to close and re-open an issue explaining the larger problem and the fix.
