### ISSUE TITLE
ns.workForFaction for "Blade Industries" fails with bizarre message (Bug source seems to be found already)

### ISSUE THREAD

**Issue by ToasterUwU** [danielyxie/bitburner#3207]
When I use `ns.workForFaction('Blade Industries', 'Hacking Contracts', true)` i get a notice in the log of the script like this: `workForFaction: Faction 'Blade Industries' do not need help with hacking contracts.`

This doesn't make much sense since I can use the button on the faction page to do it manually just fine and also it should be possible since that's the best way to get the reputation needed to buy the augmentations.

@Arronax06 on Discord suggested that there is a bug since `"Blade is not in the list of faction available for work in the Singularity class"` and `"to go further, they put bladeburner in the list instead of blade industry"`. They also said  `"I checked the other factions, they all seem to be correct except those 2"`.
For my answers and the full conversation click [here](https://discordapp.com/channels/415207508303544321/415207923506216971/955223417420935198).

I hope that info helps.

PS: I play on the currently newest version of the steam release. (`Bitburner v1.5.0 (cbeb6d13)`)

**Comment by Arronax06** [comment]
To sum up, in `NetscriptFunctions/Singularity.ts` the variables `hackAvailable`, `fdWkAvailable` and `scWkAvailable` at line 1037-1094 are created with `FactionNames.Bladeburners` instead of `FactionNames.BladeIndustries`
