### ISSUE TITLE
Gang territory needs to do it's math in integer land.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#3212]
Sub zero fractions are very imprecise.

Gangs need to do their territory warfare in integer land.

Take note of this special number `9007199254740988`, call it X

This is the highest number below MAX_SAFE_INTEGER that  mod 7 === 0.

This means every single integer between 0 and this is represented exactly, addition and substraction works without an itch.

So this issue is fixed in multiple steps.

First we need a save file migration.

In the save file migration we multiply all territory by that number, this will move the territories from [0, 1] to [0, X].
Next make sure there's no leftover, add the territory of everyone and adjust the players territory by whatever amount is needed in order for the total territory to equal X.

Finally all the code needs to be multiplied by X and ROUNDED when exchanging territory so that the total territory split among everyone is always equal this.

**Comment by Arronax06** [comment]
Just a note concerning the previous issue #3206 : the main issue was that in a normal playthrough, 0.001 is rounded to 0 for 6 gangs, but 0.999 is rounded to 1 for only 1 gang, so there is between 0 and 0.6% of the territory that is lost and not allocated to anyone, so when everyone else is at 0, you end up with territory anywhere between 99.40% and 99.89% or 100% only if you're lucky and get rounded up from 99.9%.

**Comment by smmalis37** [comment]
Dup of #1914?

**Comment by phyzical** [comment]
yep but this is the one that explains how it needs to be solved

**Comment by alainbryden** [comment]
Brb, opening a PR that adds an 8th gang faction.

**Comment by stalefishies** [comment]
This is _vastly_ overcomplicating things - there is more than enough precision in [0, 1] for gang territory. To stop the total drifting away from 1, then whenever the gang territories change, just add up the territory fractions and divide each territory by the total. You'll get 7 numbers that will always add to 1 to within a normal floating-point error, rather than having an error that grows over time.
