### ISSUE TITLE
Bladeburner console keymap error

### ISSUE THREAD

**Issue by quantenmechaniker-b3rnd** [danielyxie/bitburner#3215]
- [X] Save file
[bitburnerSave_1647853741_BN4x1.txt](https://github.com/danielyxie/bitburner/files/8314193/bitburnerSave_1647853741_BN4x1.txt)
- [X] Steps to reproduce
- [X] Version of the game: Bitburner v1.5.0 (0171fc23) (Steam)

Steps to repro:
1. go to Bladeburner console
2. try to type 'automate dis'
=> the final 's' will be interpreted as a "Arrow Up" (recall last command). 
Also, regular "Arrow Up/Down" don't work on Bladeburner console either

**Comment by dowinter** [comment]
Ok here is my theory:
Before, the keyCode which was checked was "38", which is indeed the letter "s". But then, it got changed to keymapping via key, not keycode:
https://github.com/danielyxie/bitburner/commit/9dd933eceecfd261723df6529124ad291245e3c5#diff-805e99128ba7654d5b738d4669557d4c1ae452d47059669db369a698370b2001R92

However, the code 38 was never correct to begin with, it should have been 83. I don't know why the problem didn't occur before, but fix should be simply checking for `KEY.DOWNARROW`, not S.
