### ISSUE TITLE
[Feature Request] Make it possible to launch programs on other computers.

### ISSUE THREAD

**Issue by sebbes333** [danielyxie/bitburner#3231]
I have found a thing that I think is currently impossible to do in this game, I want it to be possible.

I have a Server & Home.
I have a "seeker" script running at Server, and it Should also be responsible of breaking down all defenses below my level, but to do this it needs to check if the eg. `BruteSSH.exe` scripts exists (on Home), that CAN be done. 
BUT I can NOT find any way to execute those .exe files from the server.

I'm also not allowed to move (`scp()`) those scripts onto the server.
i was exploring the idea of making some kind of tiny script that could somehow relay the needed execution-information to Home and run some small "launcher" program at home, 

Something like this (but it is really obnoxiously annoying & unnecessarily complicated):
*1 From the "Seeker" when it finds a suitable target, write a text file with the target information.
*2 Execute a `scp(file, 'home')` on that file.
*3 at Home, have some kind of file checker running in a constant loop (waste of CPU & RAM) that checks for that file with a specific name.
*4 open that file & read the content (NO, I don't think this is possible, I don't think you can open a text file from inside a script?).
*5 Use that information to launch the requested programs at the requested target.

**What I REALLY want is a function like:**
(running at Server)
**`exec2('my.script','home', 1', 'args[]')`**
* `'my.script'` = name of script to be executed (optionally an array with multiple scripts?)
* `'home'` = What server to launch this program on.
* `1` = nr of threads.
* `args[]` = array of arguments (optionally: array of arrays with arguments, when launching multiple scripts: [ [arg1], [arg2] ] )

Another solution would be to make it possible to copy (`scp()`) those .exe files.

Yet another solusion would be some kind of message system between the servers, so instead of having to go through all that nonsense of sending files back & forth, it would just be possible to send a message to a specific server, like:
(runing at server)
`message('home', "run 'script_1.script' ", args[]);`
Or something like that.

**Comment by phyzical** [comment]
just use `ns.blah(target)` is that what your after? i.e `ns.brutessh(target);`

**Comment by sebbes333** [comment]
`ns` does not exist in `.script` files.

**Comment by phyzical** [comment]
i would highly suggest switching over to ns2
