### ISSUE TITLE
SF9 rewards not applying

### ISSUE THREAD

**Issue by smmalis37** [danielyxie/bitburner#3233]
Just cleared BN 9 for the first time, SF9 does show up on my augmentations page, but I'm starting all new runs still with 32gb of ram and no free hacknet server.

- Bitburner 1.5 (aabb764d)
[bitburnerSave.txt](https://github.com/danielyxie/bitburner/files/8326285/bitburnerSave.txt)

**Comment by smmalis37** [comment]
I do have the ability to purchase hacknet servers instead of nodes, so at least that part is unlocking correctly.

**Comment by SagePtr** [comment]
You need to complete DN9 two times for 128GB ram and three times for free Hacknet server.
