### ISSUE TITLE
Corportation Number Error

### ISSUE THREAD

**Issue by dtoms0224** [danielyxie/bitburner#3243]
# DELETE THIS AFTER READING

# include (where relevant)

- [x] Save file

[bitburnerSave_1648063735_BN3x2.zip](https://github.com/danielyxie/bitburner/files/8336575/bitburnerSave_1648063735_BN3x2.zip)

- [ ] Minimal scripts to reproduce the issue
- [x] Steps to [reproduce](url)
1. Go To Corp
2. Go to Softworks
3. Get Error
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by phyzical** [comment]
closable due to lack of info
