### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name') (at "Work")

### ISSUE THREAD

**Issue by Benjamin-Berry** [danielyxie/bitburner#3254]
### How did this happen?

I'm running a script to work for faction rep and purchase augments (see attached). While AFK the game crashes. Its happened 4 times so far. No usage stack trace to debug.

Get invited to the factions listed in the script. 
Run the script.

Please fill this information with details if relevant.

- [ y] Save file
- [ y] Minimal scripts to reproduce the issue
- [ y] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'name')
* Page: Work
* Version: v1.5.0 (bc952147)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Sav
[Bug.zip](https://github.com/danielyxie/bitburner/files/8354009/Bug.zip)
e
```
See attached
```

**Comment by phyzical** [comment]
i believe this may be fixed in dev already

**Comment by Benjamin-Berry** [comment]
I think I found the issue. The script installed augments but I was still working for the faction.

**Comment by Benjamin-Berry** [comment]
<img width="712" alt="Screen Shot 2022-03-26 at 1 43 28 PM" src="https://user-images.githubusercontent.com/4303648/160251317-31dfc27f-1bc6-4991-8d20-ab9c7ff1df41.png">
Console error messages

**Comment by phyzical** [comment]
yeah can confirm this should be fixed in dev, it throws an "sorry screen" instead of the recovery screen
