### ISSUE TITLE
App ID in Electron should be set to BitBurner name

### ISSUE THREAD

**Issue by DavidGrinberg** [danielyxie/bitburner#3258]
If you create an ES6 notification in a script, e.g. `new Notification("test!", {body: "foobar"}` then the resulting notification popup will look like:

![image](https://user-images.githubusercontent.com/13791262/160298597-2de751b6-bc6f-4664-9fa3-18d5601274b6.png)
(run on Windows 11 in the Steam app)

![image](https://user-images.githubusercontent.com/13791262/160311272-67a17e5a-a72d-4b64-99ea-67732eff53a5.png)
(Windows 10, steam app. Bitburner icon was manually added)

The app name on the notification is `electron.app.bitburner`, which is ugly. It should read just `Bitburner`

This can probably be done by applying [this fix](https://github.com/nativefier/nativefier/issues/869) to [this file](https://github.com/danielyxie/bitburner/blob/dev/electron/main.js)

**Comment by phyzical** [comment]
we should probaly add the bitburner icon too
