### ISSUE TITLE
[Feature Request] Additional gang territory mechanic

### ISSUE THREAD

**Issue by mrnetops** [danielyxie/bitburner#3259]
Gate gang augmentation access behind territory

* Gang automatically gets access to the augmentations normally available to that criminal faction (not gang!)
* All other augmentations have %territory chance of being available, determined individually.
* Unavailable augmentations are reevaluated every whole 10% of faction (20%, 30%, etc)
* for gangs with a city requirement, grant a bonus +5/10% chance to augmentations from the associated city factions and corporate factions hosted from those cities.

Ideally, this
* Makes fighting for territory much less optional
* Potentially makes gang selection more interesting
* Makes a small hop from initial augmentation rolls at start (14.286%) to 20% before requiring 10% every time

**Comment by TheRealMaxion** [comment]
Would this mean that you lose access to them at random if losing territory below such thresholds?
If implementing this, should ensure all are guaranteed available at territory over 99%.

**Comment by mrnetops** [comment]
Well, the 1.6.0 update with augment grafting threw this suggestion for a loop ;)

I actually wouldn't reroll on loss simply because you would also need to reroll on re-gain and I could see folks bounding up and down on territory till they get an augment they like.

Pre 1.6.0 gangs got access to (almost) all augments out of the gate, so this was more to make it feel like those were earned rather then bulk unlocked.

**Comment by TheRealMaxion** [comment]
Ah, for some reason I thought this was just about which augments were available for the gang members.
This makes more sense now, but indeed, changes by recent updates, especially the one that gives the gang some random ones as well, have thrown this suggestion for a bit of a loop, hehe.
