### ISSUE TITLE
Deprecated functions in docs

### ISSUE THREAD

**Issue by incubusnb** [danielyxie/bitburner#3262]
Deprecated NS functions should be more obviously shown as Deprecated, moved to a section specifically for Deprecated Functions or removed entirely from the Full Documentation page. A way to do this would be to prepend them with a [d] or something on the list of Functions as it would just make it easier to see what functions are available and still supported at a glance.

**Comment by phyzical** [comment]
@incubusnb was there any functions in particular that you noticed shouldn't be in the documentation?

**Comment by incubusnb** [comment]
@phyzical Off the top of my head, there were 3 singularity functions that I was thinking about when I opened this issue. I haven't gone through the rest of the documentation to see what else is obsolete.

[getStats()](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.getstats.md)
[getCharacterInformation()](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.getcharacterinformation.md)
[getAugmentationCost()](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.getaugmentationcost.md)

**Comment by phyzical** [comment]
so the docs are auto generated from memory and we do have 
![image](https://user-images.githubusercontent.com/5182053/165930491-ef9c4a06-b573-4414-857d-f27ad35c0109.png)
it marked as deprecated in the namespace so possible this deprecation doesnt make its way into the autogenerated docs?

**Comment by Undeemiss** [comment]
Appears to have been resolved, if it was an issue to begin with.
![image](https://user-images.githubusercontent.com/55594961/167497257-7197d83e-af3c-4371-a15a-8a2c393d415e.png)
