### ISSUE TITLE
move sing functions to their own API.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#3274]
- [x] Make a namespace called `singularity` that has all the current singularity functions. The current sing function and new sing functions should point to the same thing so as to avoid double fixing bugs.
- [ ] Update the doc so that that change is reflected in the markdown. The old sing functions should no longer appear. At that point they will not appear in Monaco either.
- [ ] Pick a date that's the final cutoff. Ideally like 6+ months from now.
- [ ] When that date comes, remove the functions from the top level API.

**Comment by Martin-Pitt** [comment]
You could also do something similar like library or browser API deprecations, where if the function is called in the old place, you log out a one-time warning about that. Either wrapping the function or using a proxy. It's a friendly way to warn devs about deprecations in userland.
