### ISSUE TITLE
CotMG has NF

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#3296]

**Comment by TheRealMaxion** [comment]
Bladeburners does too.

**Comment by TheRealMaxion** [comment]
CotMG and Bladeburners still have NF by the way

**Comment by phyzical** [comment]
![image](https://user-images.githubusercontent.com/5182053/167392037-0346c196-154a-4540-a77f-c6633375be25.png)
![image](https://user-images.githubusercontent.com/5182053/167392148-c53ddf05-7a82-45e5-a453-2e9e2198f8bf.png)
maybe its fixed in dev?

**Comment by TheRealMaxion** [comment]
Fixed now at least.
