### ISSUE TITLE
icarus.msg should be displayed once only

### ISSUE THREAD

**Issue by RobLeachman** [danielyxie/bitburner#3311]
I see an option to "Suppress story messages" but like to see these when available. What I don't like is seeing icarus.msg over and over. For me right now it is displayed every few minutes on BN2 and 3.

Would be lovely if this message worked the same as the others. Really, after BN1 is there any reason to every display it?

In any case it would be better to not nag the player about this goal. Thanks!

**Comment by phyzical** [comment]
yeah ive had this thought, its just the code isnt setup to track what has been displayed before and what hasnt over multiple BNs

tldr consider adding a new option `display only new messages`

**Comment by RobLeachman** [comment]
thanks :) 

I think this one could be closed by checking if the .msg file exists before sending over and displaying a new copy? I probably don't understand what is happening but it seems like

1) event criteria met for the message
2) copy .msg file to the player's file system, overwriting as required
3) display the message

A small tweak to #2?

**Comment by DJ-Laser** [comment]
It should have 4 options: all, once ever, once per bitnode,once per installation(augmentations), and none. per installation would stop spamming icarus.msg, per BN would stop getting messages you've already read in that bitnode (faction tests, jump3r, etc..), and once ever would never show you the same message twice, and none would not show and all would show you every meggage. This would replace the supress story message option and be called something like repeated message display setting

**Comment by TheRealMaxion** [comment]
Name for the option could be:
Story message display frequency

**Comment by phyzical** [comment]
and to implement all possible modals content would need some sort of identifier to uniquely track what has been shown. 

This list would need to be saved against the user save `shownStoryMessages`

Then based on what time of setting each part of code would need appropriate setting checks to determine if the array needs clearing
