### ISSUE TITLE
corporation.expandCity() resets Office values if expansion already exists

### ISSUE THREAD

**Issue by MatelDS** [danielyxie/bitburner#3312]
The function corporation.expandCity() resets the office of a divison expansion in a city, when it is called and the expansion already exists.

The amount of workers is set back to zero and the maximum worker amount is set back to 3. Warehouse and other stuff remains untouched.

Steps to reproduce:
-> Divison office in city is upgraded to 6/6 workers
-> run function like "corporation.expandCity(divName, city)"
-> Office of divison in city is 0/3 workers

Version: v1.6.0 (a0361c9a)

![image](https://user-images.githubusercontent.com/36420116/161105589-c3f1a81f-c2d0-4fb7-aaa8-a1d5485cb999.png)
![image](https://user-images.githubusercontent.com/36420116/161105691-99d1c8ad-cdb6-4a77-96d9-9447e36933fc.png)

**Comment by phyzical** [comment]
im going to do some corp fixes over the weekend ill look into this while at it
