### ISSUE TITLE
fl1ght.exe vanished

### ISSUE THREAD

**Issue by AnJoy34** [danielyxie/bitburner#3316]
i recently installed all the augmentations that were given by Daedalus, however, soon after, i received a file called "icarus.msg", and fl1ght.exe disappeared, only i had to install the augmentations, so i had to do it all over again, but i still didn't have fl1ght.exe anymore. once i reached its goals again, i still got a request to join Daedalus. I think it's simply a bug, could you guys fix it?

Version 1.6.1

**Comment by phyzical** [comment]
@AnJoy34 do you happen to have any scripts that delete the files in your directory

**Comment by Hedrauta** [comment]
🤔 you can remove .exe-files? ...... 
👀 oh dang.... you can 🤔 
maybe fail the rm-command if you want to delete files, that shouldn't be removed 👀

**Comment by vladtepesch** [comment]
its a hacking game. you are root on your device. if you want you to shoot yourself in the food, you should allowed to do so 🤣
