### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cost') (at "Grafting")

### ISSUE THREAD

**Issue by sb17joker** [danielyxie/bitburner#3317]
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'cost')
* Page: Grafting
* Version: v1.6.0 (4b8791e3)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by phyzical** [comment]
cc @nickofolas

**Comment by nickofolas** [comment]
I'm assuming you have all Augmentations, and it looks like you're on a slightly outdated version of the game.

Update to the latest version, and the issue should be fixed.
