### ISSUE TITLE
April fools gag freezes game on Win11/Chrome100

### ISSUE THREAD

**Issue by jaysen-fullbay** [danielyxie/bitburner#3323]
When loading the game on Windows 11 using Chrome 99 or 100, the rick roll does not animate and the page lags out to the point where Chrome asks if you want to wait or kill the page. The modal cannot be closed making the game completely unplayable.

I have checked for Chrome updates as well as disabled all extensions, still freezes.

![Screenshot 2022-04-01 112242](https://user-images.githubusercontent.com/95240010/161312079-c2b0f98a-011b-45f8-a6b8-5ea24c9d60de.png)
![Screenshot 2022-04-01 112201](https://user-images.githubusercontent.com/95240010/161312090-49ad04f7-574d-4fd0-8204-f8206c17c6ce.png)

**Comment by phyzical** [comment]
@jaysen-fullbay sorry to hear that it exploded ;( it will stop after the 1st.

**Comment by hydroflame** [comment]
hmm

**Comment by Andres-M-Rios** [comment]
Ack! Sorry about that. Can't debug all the OS/Browser combinations for everything. April Fools explosion? Guessing it's not an issue anymore on April 2.
