### ISSUE TITLE
Hacking gangs should do territory warfare with hacking.

### ISSUE THREAD

**Issue by DJ-Laser** [danielyxie/bitburner#3324]
Ngl im kinda salty about this. I made a **_HACKING_** gang so I wouldn't have to worry about clashing, so when I lost all my territory on accident and it cut my production massively (~50m/sec to ~1m/sec) I was kinda mad. Now I'm trying to train all my members of a _**HACKING**_ gang in **_COMBAT_**, so I can get territory to be able to make enough money to actually get enough neuroflux to get 15k skill and beat the BN, but it is so slow -_-

This is my 2nd BN so I only have gangs to work with, so I am stuck and it is kinda demoralizing to me to have all my hard work lost and I might need to flume and reset. Pls fix this.

Steps:
1. Make a HACKING gang
2. lvl them up a lot
3. Accidentally lose all your territory
4. Observe massive money/rep production decrease

Version: Bitburner v1.6.1 (d9499077)
Save:
[bitburnerSave_1648836646_BN2x0.txt](https://github.com/danielyxie/bitburner/files/8400070/bitburnerSave_1648836646_BN2x0.txt)

**Comment by phyzical** [comment]
what do you mean by "accidentally lost territory"? i would just flume and do it again if you messed up

**Comment by hydroflame** [comment]
That won't fix this users issue but we'll make hacking gangs participate in territory warfare with their hacking skills.
