### ISSUE TITLE
gang wanted level reduction displayed wrong

### ISSUE THREAD

**Issue by RobLeachman** [danielyxie/bitburner#3328]
Here's a softball...

The gang UI says <Wanted Level: 8.32183k (-11.50557 / sec)>
Actually it drops by a much larger value

Hydroflame agreed it's a bug, said "vigi jus reduces by a percentage but that's not displayed"

**Comment by hydroflame** [comment]
Yeah so vigilante justice reduces wanted by a percentage but this information is not fed in the UI.

**Comment by hydroflame** [comment]
I think it's a dupe
