### ISSUE TITLE
Cannot bulk purchase

### ISSUE THREAD

**Issue by c-goldschmidt** [danielyxie/bitburner#3334]
I always get the message "Error: You do not have enough warehouse size to fit this purchase"

If i'd have to guess, then i'd guess it's because this: https://github.com/danielyxie/bitburner/blob/dev/src/Corporation/Actions.ts#L261
should be `amt * matSize > maxAmount` instead of `amt * matSize <= maxAmount`.

**Comment by vladtepesch** [comment]
can this be fixed fast (maybe independently of the merge of such a large PR)
