### ISSUE TITLE
[proposal] add infiltrate (company) method

### ISSUE THREAD

**Issue by Vic1970** [danielyxie/bitburner#3340]
I have been playing a little while, have some source files etc, and the only activity I cannot find automation for is infiltrating a company.

I understand the manual nature of the task, but the singularity API has (close to) every activity apart from infiltration.  

Options: 

* add to singularity API with static or dynamic chance of success.
* add to sleeves API with static or dynamic chance of success.
* require one or both source files to use?
* possibility to send multiple sleeves on the same infiltration to improve success probability or reward
* allow the use of an ns.share() type function on home and on other hosts (botnet) to improve probability or reward

Thanks for a great game.

**Comment by phyzical** [comment]
@Vic1970 hey good news its coming

> add to singularity API with static or dynamic chance of success.

there will be stats of things like difficulty and rewward, i dont think you can fully automate infils (without dom maniup right)?

> add to sleeves API with static or dynamic chance of success.

wait can you infiltrate with sleeves? i dont think you can right?

> require one or both source files to use?

atm will not require any SF

> possibility to send multiple sleeves on the same infiltration to improve success probability or reward

again can you infil with sleeves atm?

> allow the use of an ns.share() type function on home and on other hosts (botnet) to improve probability or reward

interesting idea we could consider after the first wave of infil updates

cc @hydroflame

**Comment by TheRealMaxion** [comment]
@phyzical 
Sleeves can not infiltrate currently.
One of their ideas for automation of it is that sleeves could do it.

**Comment by Vic1970** [comment]
Thanks for your consideration @phyzical @hydroflame   
Love the game.
