### ISSUE TITLE
singularity.commitCrime() should return Promise<boolean>

### ISSUE THREAD

**Issue by jacktose** [danielyxie/bitburner#3344]
[Singularity.commitCrime()] returns `number: The number of milliseconds it takes to attempt the specified crime.` That seems like a kludgy version of a promise, so could it just be made to return `Promise<boolean>: True if the data crime was successful, false if it failed.`?

[Singularity.commitCrime()]: https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.commitcrime.md

**Comment by Hedrauta** [comment]
🤔 but then you can't grab the time for making a pause, and you have to await the whole thing....
🤔 🤔 🤔 🤔 
would save 1 step in the crime-loop
usually you do:
```js
let sleeptime = ns.commitCrime("Homicide") // which will return 3000 ms crime-time
await ns.sleep(sleeptime) // wait for the crime to be finished, result will get printed into log
```

the sleep would just be removed on a promise-function <.<

**Comment by jacktose** [comment]
Just an idea. That's how `tryWritePort()`, `scp()`, `wget()` work and it seems more elegant. What's the advantage of this synchronous style? You're able to do other things while you wait for the crime, I guess?

**Comment by hydroflame** [comment]
API breaking, so no
