### ISSUE TITLE
Bug: calling installAugs() while focused on a task gives an error screen

### ISSUE THREAD

**Issue by DavidGrinberg** [danielyxie/bitburner#3348]
**Steps to reproduce:**

1. Start some work (e.g. hacking contract) and don't focus on it
2. Run this script:
```
export async function main(ns) {
  await ns.sleep(10_000)
  ns.installAugmentations()
}
```
3. Focus on the work
4. Wait ~20 seconds for augs to be installed and game to reset

**Expected result:** You should be taken to a fresh terminal screen

**Actual result:** You get to a page like this: 
![image](https://user-images.githubusercontent.com/13791262/161470199-a2e1dabd-f3a8-4cd9-851a-655d323565eb.png)

v1.6.3 (6c8a46d3)

**Comment by DavidGrinberg** [comment]
I think this can be fixed by just adding

```
if (player.isWorking) {
        if (player.focus) {
          player.stopFocusing();
          Router.toTerminal();
        }
}
```

Between these lines https://github.com/danielyxie/bitburner/blob/ce944bfccbb7190d366e3cbabdb065f206384d8e/src/NetscriptFunctions/Singularity.ts#L234-L235

**Comment by phyzical** [comment]
hmm we could send users to the terminal instead, this is just a bandaid to avoid the recovery screen tbh.
only issue is this sometimes occurred in other instances, when they have two scripts that fight each other.

Looking deeper i think there should be logic to stop working somewhere in prestigeAugmentation, it seems to handle a bunch fo reset realted stuff but i see nothing about resetting the users current "work"

**Comment by phyzical** [comment]
ah actually ii guess it doesnt matter that much its not reset as it proably lives on the faction somewhere.

But yeah i actually cant seem to find a line that sends the user anywhere during an augmentation install maybe thats all we should do, that would solve these issues in so many places
