### ISSUE TITLE
[Feature request] `ns.backdoor("server_id")`

### ISSUE THREAD

**Issue by sebbes333** [danielyxie/bitburner#3353]
Hi
I would like a function just like `ns.nuke("server_id")`
but for installing backdoors, like: `ns.backdoor("server_id")`

It gets annoying to manually re-backdoor all the servers after several restarts (argument-installs).

I have already made a script that bounces around & both cracks & nukes every server I can, I also want that script to backdoor those servers too.
My goal is to make a script that can as far as possible handle ALL aspects of this game, from backdoors to stock trades etc... then there can't be things that is impossible to do with code.

BitBurner Version: 1.6.3 (6c8a46d3)

**Comment by boris-stepanov** [comment]
!!! Spoiler alert !!!

This one [exists](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.installbackdoor.md) already. You need to progress further.

**Comment by sebbes333** [comment]
Ok, thanks.
(this "issue" can be closed/removed)

**Comment by waffleattack** [comment]
there's a way to do it without using the built in function btw.... you can have scripts that input to terminal, with dom manipulation

**Comment by Andres-M-Rios** [comment]
# This Issue can be closed!
