### ISSUE TITLE
[Feature Request] Make corporation material export take precedence over selling the same

### ISSUE THREAD

**Issue by perpterds** [danielyxie/bitburner#3360]
It seems (to me at least) implicit that if one has a material set to export, the intention of the player would always be to export first, and sell any remaining material (if any were to remain), including if both were set to max. As far as I'm concerned, this could be either an outright change, or an option. If it were an option, it would be preferable to be a toggle within the box of each material, so that one could easily toggle from multiple cities reasonably quickly.

**Comment by phyzical** [comment]
issue with exporting is most people dont bother, its just not that profitable

**Comment by perpterds** [comment]
Perhaps, perhaps not, but that doesn't negate the possibility of it working more effectively for the folks that do

**Comment by Vic1970** [comment]
it would be great to see corps tweaked in this way.  As @phyzical  has said, it's not really worth it at the moment, but the veChain upgrade seems ideal as an information conduit for showing the delta between selling all materials and supplying input materials from your own factories, also to collate total production and total requirement across businesses and cities.  A bigger delta between sell price and buy price would push players down this route - perhaps the TA-I research would then allow you to reduce the spread between sell and buy price.  Also different costs of exporting within a city or between cities.
