### ISSUE TITLE
while(await ns.sleep(1)) no longer evaluates to true

### ISSUE THREAD

**Issue by Waladil** [danielyxie/bitburner#3361]
Bitburner v1.6.3 (6c8a46d3)

This change occurred somewhere between 1.6.1 and 1.6.3. Virtually all of my scripts use the architecture while(await ns.sleep(1)) (or other number) as a form of while(true) loop that doesn't have any risk of locking up the game. I've looked through recently merged PRs and don't see anything that overtly indicates this was an intentional change, but I couldn't locate the PR that made the change. 

Was this intentional? If so, why? It's broken nearly every script I've ever written and while it's not too difficult to fix each script individually (just moving the sleep statement down a line and putting a true into the while loop), I've got several dozen scripts that would need that treatment.

**Comment by Hedrauta** [comment]
🤔 it always returns a void?

look here:
https://github.com/danielyxie/bitburner/blob/acfd164927112368bcce467778bcbe643533158b/src/ScriptEditor/NetscriptDefinitions.d.ts#L4645

**Comment by Waladil** [comment]
While that file has been changed a good bit, that particular line hasn't changed recently, since some time before it was evaluating to true.

**Comment by Hedrauta** [comment]
🤔 not in the last 7 months I had played

**Comment by Hedrauta** [comment]
But nonetheless; 
Why should you assign a boolean to a function, which just "sleeps"
.... because you may fail at typing an integer number inside?

**Comment by Waladil** [comment]
I mean, if we're going to be condescending to each other, why would you use two lines of code when one line of code works just as well? Until something changed, it was shorter, more parsimonious, and more resistant to errors. Those are qualities of good code. And I've asked other people who reported that their code was *recently*, not over seven months ago, broken by this change (albeit they didn't use this as heavily as I do, so it wasn't such a big deal). So I'm not sure why you're spreading misinformation that doesn't speak to my questions or the actual code of the issue.

**Comment by Hedrauta** [comment]
i'll look deeper into some histories.... but it's just strange 🤔 maybe it was changed, just forgotten to change that in the NetScriptDefinition 🤔 will report later 😉

**Comment by Hedrauta** [comment]
👆 found something, that may reach your interest 🤔 i'm sorry... you're right, it was changed 😉 
aa0425a2 ("unknown-ify half the basic API.", 2022-03-29)

**Comment by Waladil** [comment]
Thank you for pointing me to that! The code there is a little over my head, but it does look like things got changed from returning return Promise.resolve(true); to return Promise.resolve(); and I guess that lack of true changes how it's evaluated. The question then is whether it could be changed back in a way that doesn't ruin other improvements.

**Comment by hydroflame** [comment]
Fixing in 5m

**Comment by hydroflame** [comment]
Sorry I didn't know. The documentation say it returns promise void so I didn't expect anyone to rely on this bug.

But hey, that's life.
