### ISSUE TITLE
Sleeves page causes the recovery mode, Cannot read properties of undefined.

### ISSUE THREAD

**Issue by FuttoFin** [danielyxie/bitburner#3362]
# Sleeves page causes the recovery mode.

### Minimal scripts to reproduce the issue

sleeveTasks.js 

### Steps to reproduce

You just have to run sleeveTask.js

Game seem to run fine after, but when you go to Sleeves page the recovery mode kicks in.

I managed to solve the problem by running the sleeveGang.js script, which changes the sleeves tasks, so my guess is that 
their current task is what is causing the problem.

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.6.3 (6c8a46d3)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.0.0 Chrome/93.0.4577.82 Electron/14.0.2 Safari/537.36
* Features: lang=fi cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
[Save.txt](https://github.com/danielyxie/bitburner/files/8417871/Save.txt)

**Comment by FuttoFin** [comment]
Seems like this problem was also previosly posted here:

https://github.com/danielyxie/bitburner/issues/3347

After testing it seems i had the same problem where the Sleeves page causes recovery mode if a sleeve is assigned to work for a gang faction. I modified the script to check if the faction is a gang faction.

**Comment by phyzical** [comment]
@FuttoFin mind closing this? a pr should have been merged to resolve it on dev on the next version pursh
