### ISSUE TITLE
unreproducable `ns.gang.getAscensionResult(...) is undefined` 

### ISSUE THREAD

**Issue by vladtepesch** [danielyxie/bitburner#3364]
I sometime get an errormessage that `ns.gang.getAscensionResult` is undefined  on starting my gang managing script.
A few minutes later it does work again (without changing anything).
It never stops working once it was startet.

start the script without arguments.

version is 1.6.3 6c8a46d3
browser: Firefox 98.0.2 (64-Bit)

not sure if it helps but I attached the save file

[bitburnerSave_1649186801_BN10x2.json.txt](https://github.com/danielyxie/bitburner/files/8421336/bitburnerSave_1649186801_BN10x2.json.txt)

This is the error message
```
RUNTIME ERROR
gangmanager.js@home

ns.gang.getAscensionResult(...) is undefined
stack:
main@gangmanager.js:39:23
executeJSScript@https://danielyxie.github.io/bitburner/main.bundle.js:19:94028
```

**Comment by joshwills** [comment]
Without getting too into the weeds, I think this might be a bug in your specific script, not the ns.gang.getAscensionResult() function - if the gang member in question cannot be ascended, that function will return null (or rather undefined: https://github.com/danielyxie/bitburner/blob/master/markdown/bitburner.gang.getascensionresult.md ), but from what I can tell your code just assumes it will succeed, and then you try to reference the ".hack" property of it:


```
for (let name of ns.gang.getMemberNames())
{
		let st = ns.gang.getMemberInformation(name);
		let ascSt = ns.gang.getAscensionResult(name).hack;

		ns.tprint(name, " hack_asc_mult ", st.hack_asc_mult, "  ascSt ", ascSt);
	}
```

For reference, here's some code from my own gangAscend.js script that skips checking a gang member if they cannot be ascended:

```
			if (ns.gang.getAscensionResult(member) == null){
				continue;
			}
```

You do a similar thing later on in the script (only run a section if ns.gang.getAscensionResult(name) returned something), so I think you just missed putting that check in the initial setup area:

```
		for (let name of ns.gang.getMemberNames())
{
//			ns.tprint(name, JSON.stringify(ns.gang.getAscensionResult(name), null, 2));
			//let st = ns.gang.getMemberInformation(name);
			let asS = ns.gang.getAscensionResult(name);
			if(asS)

```

Separately, I like your gang member naming scheme - I just use "jim[0:11]", but I also don't have a script that recruits members yet...I might steal your names for the added flavor X)

**Comment by vladtepesch** [comment]
> I think this might be a bug in your specific script, not the ns.gang.getAscensionResult() function - if the gang member in question cannot be ascended, that function will return null (or rather undefined: https://github.com/danielyxie/bitburner/blob/master/markdown/bitburner.gang.getascensionresult.md ), but from what I can tell your code just assumes it will succeed, and then you try to reference the ".hack" property of it:
🤦‍♂️ This makes sense - i totally misinterpreted the error message.

the 
> initial setup area  

is just a left over from the initial tests - so even more annoying that the lazyness of removing this just bite me.


> Separately, I like your gang member naming scheme
the names are also just copied from a random list from the www.
A second thought I had was to use a list of the commit names from this repo
