### ISSUE TITLE
Sleeve UI not updating for gym stat when assigned via script

### ISSUE THREAD

**Issue by BrianLDev** [danielyxie/bitburner#3366]
When assigning a sleeve to workout at the gym via script like this:
`ns.sleeve.setToGymWorkout(2, c.GymName.powerhouse, 'def');`
... the UI always shows "Train Strength" even though a different stat is being trained.  

See screenshot below where Defense Exp is increasing but the UI shows "Train Strength".
![image](https://user-images.githubusercontent.com/16980550/162034497-bb85237c-e7a6-40e4-a9d2-313a1ea1305c.png)

**Comment by borisflagell** [comment]
Bug reproduced.
