### ISSUE TITLE
SCPing of NS2 scripts does not take into account changes in the script.

### ISSUE THREAD

**Issue by JaceySanders** [danielyxie/bitburner#337]
If you have a script copy a file to another server, then change the file on the source server, and run the copying script again, it does not copy the updated version until you close and restart your browser.

A note from BigD "Its because a NetscriptJS's "module" gets updated when you save the script, so if you scp a file it doesn't actually save it".

**Comment by danielyxie** [comment]
Shouold be fixed in v0.39.1, let me know if otherwise
