### ISSUE TITLE
Servers that trigger faction invitations (CSEC) on backdoor will deliver messages even if faction is joined.

### ISSUE THREAD

**Issue by rrosales** [danielyxie/bitburner#3370]
You receive the pop-up/modal in addition to the csec-test.msg even if you have already joined the faction. This may also apply to other factions that invite you via backdoor'ing a server.  Please close issue if this is not relevant.

Scripts:
- No scripts necessary

Reproduction:
- Starting BN1 or any bitnode where you can make fast enough progress.
- Nuke/Backdoor CSEC as quickly as possible.
- Join CSEC faction
- If done fast enough, at a later time, the pop up message that delivers csec-test.msg will pop up anyways.

Version
- 1.6.3 (724c0669)

**Comment by phyzical** [comment]
tbh does it really matter? 

in any event i think this issue  https://github.com/danielyxie/bitburner/issues/3311 covers this which suggest options to toggle "only show new messages"
