### ISSUE TITLE
delete server isn't working

### ISSUE THREAD

**Issue by Tailzin** [danielyxie/bitburner#3377]
![image](https://user-images.githubusercontent.com/69316017/162334363-141141ce-e7be-4260-b806-ee498dda6597.png)
![image](https://user-images.githubusercontent.com/69316017/162334393-6fd20ede-4a9d-4b4f-a2ce-80580337cf8e.png)
![image](https://user-images.githubusercontent.com/69316017/162334417-a8c31f84-e866-4363-9641-0eb0d9b0a1bc.png)
all i did was try to make a script that deletes purchased servers, it's relevant cuz i want to upgrade my servers

**Comment by hydroflame** [comment]
Send save file

**Comment by Tailzin** [comment]
https://drive.google.com/file/d/1bZklMngl34zYTYFUoYCIf9YA7X_nWx2e/view?usp=sharing

**Comment by borisflagell** [comment]
Weird issue. Still reproducable with his save in 1.7.0

In his save, getPurchasedServers() returns an array of IP Adress in place of the hostname.
