### ISSUE TITLE
[Feature request] function, replace last row in log, instead of adding a new row.

### ISSUE THREAD

**Issue by sebbes333** [danielyxie/bitburner#3382]
A print function that replaces the last row (or X rows) on the log (instead of adding a new row).
This would allow us to create loading animations, or update a countdown, without spamming the entire log with useless information.

eg. countdown:
new function: 
60 --> 59 --> 58 --> 57 --> 56 --> 55 ....   (ignore the --> it symbolizes the number getting replaced/overwritten in the new output)

current function:
60
59
58
57
56
55
... 
^^^---- Unnecessarily much more space used.

(Maybe this can be done to the terminal too?)

**Comment by phyzical** [comment]
hmmm cool idea in theory, but i feel like it wouldnt go well in practice. well maybe?

maybe just a simple bool to logging functions which is `replaceLastLog?: false`.

**Comment by MartinFournier** [comment]
You can already kind of handle this yourself in scripts. 
You can keep the information you want to log in memory, use ns.clear() and ns.print() in a loop on each iteration.

**Comment by sebbes333** [comment]
> You can already kind of handle this yourself in scripts.
> You can keep the information you want to log in memory, use ns.clear() and ns.print() in a loop on each iteration.

Not exactly what I meant. ( also, it's: ns.clearLog() not ns.clear() ).
I still want to keep the "history" of what has already been printed.

I have now found this function: getScriptLogs() where I can get the logs to a variable array & modify it, then loop with getScriptLogs(), ns.clear() & ns.print() again, but it would be nice to have built in by default as a function.
