### ISSUE TITLE
getting recovery mode : TypeError: Cannot read properties of undefined (reading 'getInfo') (at "Sleeves")

### ISSUE THREAD

**Issue by wchevalier** [danielyxie/bitburner#3393]
Steam : 
   Bitburner v1.6.3 (a2dddb0e)

Steps to reproduce
   start bit node  
   get Slum Snakes faction 
   set sleeve to work slum snake faction 
   commit 14 hours  homicide to get low enough karma
   manage slum snakes as a gang 
   going to sleeve screen now crashes the game. 

[RECOVERY_BITBURNER_1649641256.json.txt](https://github.com/danielyxie/bitburner/files/8460520/RECOVERY_BITBURNER_1649641256.json.txt)

**Comment by Seancheey** [comment]
I also crashed around 3 times with this error message. The frequency is pretty low though (~2-3 days per occurrence).
