### ISSUE TITLE
Can donate to Bladeburners faction via API (but should be disabled)

### ISSUE THREAD

**Issue by alainbryden** [danielyxie/bitburner#3395]
You can currently donate to Bladeburners via API, but not via UI.
![image](https://user-images.githubusercontent.com/2285037/162757675-a1101e71-a194-48ca-b1bc-df78cc0525f2.png)

Note that you should not be able to donate to any of the following factions for reputation, either in the UI or the API:
- Bladeburners
- Church of the Machine God
- Any gang faction once gangs are active.

I've confirmed that this is enforced for the player's current gang faction, but have not checked on other gangs or church:
![image](https://user-images.githubusercontent.com/2285037/162757969-f3f58c59-5d36-4a24-ae06-6d65774732e9.png)

**Comment by TheMas3212** [comment]
investigating
