### ISSUE TITLE
Hamming code contracts seem to expect invalid hamming codes

### ISSUE THREAD

**Issue by c-goldschmidt** [danielyxie/bitburner#3402]
So i'm using the hamming-code library here: https://github.com/georgelviv/hamming-code to encode/decode hamming codes for the contract.

That doesn't work.

Since the algorithm is not very variable, i'd say that using this library should work just fine.

cc @Hedrauta

**Comment by Hedrauta** [comment]
Well.... That library doesnt usr the overall parity... I did wrote that specific one into the notes

**Comment by Hedrauta** [comment]
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/X8jsijhllIA/0.jpg)](https://youtu.be/X8jsijhllIA?t=838) 

started the vid at specific timestamp, which explains that first index bit... that repo isn't using that specific index

**Comment by Hedrauta** [comment]
last comment for now: 
you CAN use that repo, "**but**" you have to add an extra parity-bit at the start for the whole encoded string 😉

**Comment by c-goldschmidt** [comment]
No, because it seems to be wrong in more ways (either the lib or the contract):

```
const input = 42;
const encoded = lib.hammingEncode(input.toString(2));
const encoded2 = HammingEncode(input);
console.log(asBinary, input);
console.log(encoded, encoded2);
```

=>
```
1010010110     // lib
10011010110  // contract code
```

**Comment by Hedrauta** [comment]
![image](https://user-images.githubusercontent.com/20142298/162940786-a793061b-e937-4bba-944f-ce8a15b624bb.png)

Seems valid for me ? .... 

try to code your own solver..... that lib seems kind of broken

**Comment by Hedrauta** [comment]
but i will inspect that repo a bit further.... weird lib 😕

**Comment by c-goldschmidt** [comment]
yea, i also dont't tend to trust it, it's the first thing that showed up on google ;)
this contract is however quite a lot harder than the others, as it requires pretty specific knowledge...not exactly something one comes across often 😄

**Comment by Hedrauta** [comment]
Was in my projects for 2 months...  and took me actually 2 weeks to program solvers.... 


and yes… that lib is broken.... it's getting weird values 


![image](https://user-images.githubusercontent.com/20142298/162943161-e6e1d9e5-398b-4ada-b73d-87b8c4b7927b.png)
![gif](https://media.giphy.com/media/521JLj0YGzz6AEWsZ5/giphy.gif)

**Comment by Hedrauta** [comment]
But to be exact... I found that lib too earlier... 
But for better understanding of the whole encode/decode, i wanted to  write my own encode/check+decode and I'm kind of happy right now 😆

**Comment by c-goldschmidt** [comment]
so much for cutting corners there...gotta build my own solver then...just wish i had a better way to verify the results, do you know one?

this one delivers completely different values:
=> https://www.ecs.umass.edu/ece/koren/FaultTolerantSystems/simulator/Hamming/HammingCodes.html

this one aswell:
=> http://www.mathaddict.net/hamming.htm (....seems to be the same anyways)

these seem to have fixed data lengths, wich doesn't work here:
=> https://www.toolmenow.com/34/Hamming(7,4)-Code-Calculator
=> https://www.toolmenow.com/73/Hamming(15,11)-Code-Calculator

...and i also don't trust the contract code...because i have seen it, lol

**Comment by Hedrauta** [comment]
my encode-solver is working in multiple steps
> first: get the value, change it into a binary string and then create an array out of that characters of the string
>then, adding the parity-bits ( without the index 0 one ) as character "x" in between ( pre-build )
>now it's just doing hamming-rule following math of the paritybits
- get the index of "x", add +1 and define this one as "stepsize"
- cut 2*stepsize and that cut will be cut in half again, to get the corresponding bits for the parity  ( that's the while-loop )
- remove first bit of the cutting, which is the parity, sum up the 1s, do remainder 2, and save the answer as paritybit of index "x" 
> Last step is getting the whole "mathed" string, sum up 1s, do remainders 2, and add that answer in front of the string as the overall-paritybit

idk what's wrong with these encoders.... will try to watch into it

**Comment by c-goldschmidt** [comment]
This _sounds_ like pretty much exactly what is described here: http://www.mathaddict.net/hamming.htm (see lower left description text). i'll have an actual go at it after work 😉

**Comment by c-goldschmidt** [comment]
chunked, yes that indeed needs a multiple of 4 bits.

**Comment by Hedrauta** [comment]
oh.... 7/4. ... dang ... PIBCAK me

**Comment by Hedrauta** [comment]
oh... yes... but they are still wrong.... they just added the parity at the end... not inside as rule'd

**Comment by c-goldschmidt** [comment]
Okay, i got my own encoder, produces the same result as the contract. maybe slightly more readable than the code from the contract.

SPOILER AHEAD 😄 

```
function hammingEncode(input) {
    const bits = input.toString(2).split('').map(i => parseInt(i, 2));
    const newArray = _prepareParityArray(bits);

    for (let i=1; i < newArray.length; i *= 2) {
        let idx = 0;
        let offset = i;
        let checksum = 0;

        while (offset + idx < newArray.length) {
            if ((offset + idx) !== i) {  // skip the parity bit itself, it isn't known yet
                checksum += newArray[offset + idx];
            }

            idx++;
            if (idx == i) {
                // skip i bits
                idx = 0;
                offset += i*2;
            }
        }
        newArray[i] = checksum % 2
    }

    const checksum = newArray.reduce((prev, curr, idx) => idx === 0 ? 0 : prev + curr, 0);
    newArray[0] = checksum % 2;
    return newArray.join('');
}

function _prepareParityArray(bits) {
    const newArray = ['']; // bit 0 is the main parity bit and will be filled later
    let target = 0;
    let pow = 0;
    for (let i=0; i<bits.length; i++) {
        const bit = bits[i];

        if (target === 0) {
            // skip for main parity
            target++;
        }

        while (Math.pow(2, pow) == target) {
            // skip for parity bit
            newArray[target] = '';
            pow++;
            target++;
        }
        
        // insert data bit at new position
        newArray[target] = bit;
        target++;
    }
    return newArray;
}
```

**Comment by c-goldschmidt** [comment]
i'm still not convinced that this contract is very good, as it is hard to verify (because there seem to be lots of different implementations and the contract expects a specific one) and i'm also not sure if BB should promote youtube channels (altough i follow that one anyways, as most of us do, i guess)

**Comment by Hedrauta** [comment]
🤔 maybe get the parity from back to front working... so it will be possible to do it all at once
uurgh... will rework the encode-solver in the next time...

![gif](https://media.giphy.com/media/1k5ja4kxAVhlseNz9x/giphy.gif)

I'm not exactly promoting, just suggesting a specific video, which explains it perfectly.... most videos on yt are doing it the right way.... getting a solver from Google is just..... not the best idea 🤣

**Comment by Nytelife26** [comment]
@c-goldschmidt is right, and your attitude is somewhat concerning @Hedrauta. Your lack of ability to see from other people's perspectives and accept criticism will not benefit the project.

**Comment by wullxz** [comment]
I've tried to implement a solution myself but have failed to get a valid result ingame until now.
My own tests with the examples from the video actually work.

Does someone have an example from the game? (data, fixed data, converted number)
I'd like to verify before I burn all the tried I have remaining on my Hamming contracts.

**Comment by c-goldschmidt** [comment]
@wullxz i didn't yet do the decode part, but you can try to validate your results against the contract code [here](https://github.com/danielyxie/bitburner/blob/1b7abbffaf3458f7a33930891fcf7fe281d7ef98/src/utils/HammingCodeTools.ts#L48) ....good luck
