### ISSUE TITLE
corporation.getProduct() should also accept 'cityName' as a parameter

### ISSUE THREAD

**Issue by fknietzsch** [danielyxie/bitburner#3408]
Running Bitburner v1.6.3 (fc9e7244) --> Steam version
But I guess the issue should appear on all versions as far as I can understand the documentation.

### **Description of problem:**
When managing a corporation manually I can set the sell amount and sell price of my created products. This is possible to do so individually for the warehouse of each town. I can activate the toggle button to apply the values for all cities, But I can also set it for each city individually.

When using netscript to manage the corporation I can also use _corporation.sellProduct()_ to set all the required parameters. This function also allows me to state whether the parameters should be applied to all cities. I can also choose to apply the parameters only to one city, which I can pass in as one of the parameters. So far so good.

As soon as I try to write a script that is required to retrieve the set value for the sell price in a specific town, I cannot find any function that returns the appropriate value. Let's say I need this to write an algorithm which fine tunes the sell prices of products in each town individually. I can only get the quantities of each city with the "cityData" attribute. But the set sell prices remains hidden on the API as far as I can see. I would have to save it in a variable to keep track of the price value. But this causes annoying behaviour on script startup as the script doesn't know any old values by then. I could only use the value from the attribute "sCost", but which city does it belong to if the values were set to be different for all cities beforehand?

### **Proposal**
Please also include "cityName" as a paramter for _corporation.getProduct()_. This would allow to retrieve the values for a product for a specific city.

**Comment by hydroflame** [comment]
So as much as this seems weird. This information is available via getProduct.

Products aren't different object per city, the poorly named `sllman` field has the information you want.
