### ISSUE TITLE
bad performance of Market-TA.II

### ISSUE THREAD

**Issue by vladtepesch** [danielyxie/bitburner#3410]
Market-TA.II sometimes does a terrible job

for example in this screenshot:
It sets the sell price to 3.3m despite the marketprice is 5.5m. the whole production will be sold if manually set this price.
Even more strange is that the AI dialog allready suggests a much better Price.

![grafik](https://user-images.githubusercontent.com/1601159/163054076-22665c70-f6ee-46e0-b322-c0f931753a6e.png)

Sometimes its is the other way around (i especially could observe this with the Agriculture output materials) that the market AI 2 sets the price to high so that the materials fill up the storage.

Another issue seems to be that, even if MAX is specified (not PROD) the market AI does not regulate the price in a way that existing stockpile gets sold.

Version 1.6.3 fc9e7244

save:
[bitburnerSave_1649796778_BN9x1.json.txt](https://github.com/danielyxie/bitburner/files/8476491/bitburnerSave_1649796778_BN9x1.json.txt)

**Comment by Draco18s** [comment]
Can confirm.
![image](https://user-images.githubusercontent.com/1750680/194180795-487534d4-2925-4214-9b6e-5c28b0482021.png)
![image](https://user-images.githubusercontent.com/1750680/194180985-ea7a8d83-4820-4ccf-a7be-b4367743f7dd.png)
