### ISSUE TITLE
Hamming code contract sample is incorrect

### ISSUE THREAD

**Issue by JLat** [danielyxie/bitburner#3419]
Doing hamming code contract and the sample data in the description given is incorrect

![hamming](https://user-images.githubusercontent.com/5460185/163080937-00a262bc-7e9d-415d-8af4-91b710b69f09.png)

Encoded value of  0b10101 is '1001101011' not '1111101011' as stated in the question

**Comment by phyzical** [comment]
this has been fixed, closable
