### ISSUE TITLE
SyntaxError: unexpected token: numeric literal (at "Corporation")

### ISSUE THREAD

**Issue by reneraab** [danielyxie/bitburner#3426]
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce:
 
I tried to sell a product (tobacco) for 1.5MP (instead of 1.5*MP) and quickly pressed Enter. The game immediately crashed. Soft resetting works at first, but the game immediately crashes again when opening the Tobacco Production screen.

### Environment

* Error: SyntaxError: unexpected token: numeric literal
* Page: Corporation
* Version: v1.6.3 (dca1ceaf)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0
* Features: lang=en-US cookiesEnabled=true doNotTrack=1 indexedDb=true
* Source: https://danielyxie.github.io/bitburner/main.bundle.js

### Save
[RECOVERY_BITBURNER_1649841648.txt](https://github.com/danielyxie/bitburner/files/8480113/RECOVERY_BITBURNER_1649841648.txt)

**Comment by phyzical** [comment]
known bug, really need to get around to fixing it properly
