### ISSUE TITLE
[Feature Request] Grafting API function to return graftable augmentation names.

### ISSUE THREAD

**Issue by alainbryden** [danielyxie/bitburner#3427]
Users in #endgame-9-10-13 observed that the list of augmentations available for grafting is not super-straightforward to obtain.

Since existing grafting API functions ( https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.grafting.md ) all require an `AugName` to be passed in, and no existing API functions can provide the full list of possible `AugName` values (most notably "nickofolas Congruity Implant"), there should probably be a dedicated function for this.

**Comment by nickofolas** [comment]
Definitely a fair request. I'll implement this
