### ISSUE TITLE
A bug that blacks out the screen

### ISSUE THREAD

**Issue by TataOwO** [danielyxie/bitburner#3435]
It looks like this in the video
https://youtu.be/HOwu5jew_KQ

Save file: [bitburnerSave_1649871082_BN7x0.zip](https://github.com/danielyxie/bitburner/files/8483518/bitburnerSave_1649871082_BN7x0.zip)

Steps to reproduce:
- Apply to a job
- Apply to another job
- Quit the job you secondly applied to
- Press Alt + J

Version:
Bitburner v1.6.4 (fbb99c17)

**Comment by Undeemiss** [comment]
I tried to test this, but Alt + J is doing nothing at all for me. Not sure what's up with that.

**Comment by Snarling** [comment]
I was able to reproduce, but only if I work at the first company for some amount of time before applying to the second company.

https://user-images.githubusercontent.com/84951833/163892947-992a4fb0-c8fd-4ba7-8915-7e9b15d6c64e.mp4
