### ISSUE TITLE
Improve Vim emulation in in-game editor

### ISSUE THREAD

**Issue by Hoekstraa** [danielyxie/bitburner#3439]
A QoL improvement to the Monaco editor to provide a more complete emulation of Vim keybindings/movements.
First thoughts are to have a look at VSCode's Vim emulation package, to possibly backport features or integrate the package.

**Comment by Snarling** [comment]
Right now we're using the monaco-vim package, is there a better option available? Seems like any significant improvements we could make should be contributed to monaco-vim, not directly to bitburner. Is there a specific missing feature that makes more sense to implement here?

**Comment by Hoekstraa** [comment]
Agreed. There's two features that skirt the boundaries in my head, one being :x and one being `=` (reindent/beautify in Vim).

### :x

`:x` in Vim is in essence `:w` and `:q` together.
It'd be nice if this were implemented on our side to save and swap to the terminal at once.
It's quite easy to add from a technical perspective, for example at [line 210 @ src/ScriptEditor/ui/ScriptEditorRoot.tsx](https://github.com/danielyxie/bitburner/blob/dev/src/ScriptEditor/ui/ScriptEditorRoot.tsx#L210)

### =

I haven't dug into the code enough to know whether beautifying in Bitburner is a feature of monaco, or a separate package being applied to the buffer, but when using the [demo](https://editor.bitwiser.in/) it appears to not be included in the editor itself, which makes me assume it is something unique to Bitburner.
In that case, we might want to link the beautifier to `=` ourselves.

Downside however is that Vim allows to beautify sections of code with `=`, not just the complete file. 
Thus there'd have to be enough ties into the editor to support the beautifying of dynamic blocs within the filebuffer.

### Other

There were some more improvements I had in mind, like linking the unnamed yank/paste buffer to clipboard. That however, can probably be implemented upstream.
