### ISSUE TITLE
Corp loses employees in city when script crashes

### ISSUE THREAD

**Issue by JefStat** [danielyxie/bitburner#3448]
Version 1.6.3 web

running my corp script crashed because Plants was misspelled. Each time the script crashed my Agriculture division in Sector-12 would lose it's employees.

```
export async function main(ns) {
    ns.corporation.sellMaterial('Agriculture', 'Sectpr-12', 'Plant;, 'MAX', 'MP');
}
```
[bitburnerSave_1649911196_BN3x1.zip](https://github.com/danielyxie/bitburner/files/8486281/bitburnerSave_1649911196_BN3x1.zip)

**Comment by TheMas3212** [comment]
i cant seem to reproduce this, does this still happen for you in the latest version?
