### ISSUE TITLE
getting property ns.gang.getMemberInformation().hack has a RAM cost of 100MB

### ISSUE THREAD

**Issue by klepu** [danielyxie/bitburner#3452]
Nothing severe, but I noticed that calling the hack property of gang.getMemberInformation() costs 100MB of RAM, obviously this happens because the "hack" keyword is interpreted as ns.hack().

edit: Same for ns.gang.getEquipmentStats().hack

Game version 1.6.4 fbb99c17

**Comment by hydroflame** [comment]
duplicate
