### ISSUE TITLE
Singularity would benefit from having getFactionWorkTypes()

### ISSUE THREAD

**Issue by PSEUDOSTAGE** [danielyxie/bitburner#3467]
One of the parameters for the existing Singularity method [workForFaction()](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.singularity.workforfaction.md) is a string for workType however there is not currently a Singularity method to get the available workTypes for a faction.

Having a method like getFactionWorkTypes(faction) which could return an array of the available workTypes as strings (i.e. "hacking", "field", "security") would be very useful.

**Comment by Hoekstraa** [comment]
This can already be achieved with `FactionInfos[FactionName].offer*Work (boolean)`,
however that isn't very clean.
Results should be part of an Enum (e.g. workTypes)
