### ISSUE TITLE
None effect in augmentation "ECorp HVMind Implant"

### ISSUE THREAD

**Issue by maciekkrysz** [danielyxie/bitburner#3481]
None effects in augmentation

![obraz](https://user-images.githubusercontent.com/63737298/163686233-a96d185b-8d1f-4784-96ca-c7fec64e5b15.png)

I've found that augmentation in source:
https://github.com/danielyxie/bitburner/blob/0fda1ecabf6de1f672c949997a38235ec817c618/src/Augmentation/AugmentationCreator.tsx#L1146

- [ ] Save file:  x
- [ ] Minimal scripts to reproduce the issue: 0
- [ ] Steps to reproduce: none
- [ ] Version of the game: Bitburner v1.6.4 (fbb99c17)

**Comment by maciekkrysz** [comment]
Dont think about extension of this file, github doesnt support files without extension 


https://user-images.githubusercontent.com/63737298/163686476-342b2174-db94-40c1-9867-c52dcdfee776.mp4

**Comment by maciekkrysz** [comment]
Save file

[save.txt](https://github.com/danielyxie/bitburner/files/8500423/save.txt)

**Comment by phyzical** [comment]
it does say "they do not real what it does"

**Comment by maciekkrysz** [comment]
@phyzical could anybody delete this issue? i cant do this and i dont want that in my contribution activity in my profile

**Comment by phyzical** [comment]
you cant delete issues i dont think. i wouldnt worry about it nothing wrong with raising an issue
