### ISSUE TITLE
[Bug] You cannot purchase 4s market data via singularity before TIX API access

### ISSUE THREAD

**Issue by DavidGrinberg** [danielyxie/bitburner#3489]
https://github.com/danielyxie/bitburner/blob/3bccfb1de672cd6e9a65155051ed9c07f37981bc/src/NetscriptFunctions/StockMarket.ts#L359-L361

I'm presuming this is unintentional as you can purchase 4s market data via UI before getting TIX API access.

**Comment by phyzical** [comment]
yeah was probably an oversight when i implemented it
