### ISSUE TITLE
Vim editor substitute command hangs when replacement string contains search string

### ISSUE THREAD

**Issue by Dumonu** [danielyxie/bitburner#3491]
## Reproduce Steps:
1. Open a script in vim mode: `vim foo.js`
2. Run a global substitute command where the search string is a substring of the replacement string: `:%s/main/foomain/g`
## Expected:
`export async function main(ns)` becomes `export async function foomain(ns)`
## Observed:
Bitburner game hangs.

Observed in v1.6.4 (fbb99c17).
## Notes:
- This is a very common action to take when renaming a symbol.
- Likely caused by finding the search string in the replaced text and replacing it again - incorrect implementation of the `g` flag.

**Comment by Dumonu** [comment]
A couple other notes:
- The bug is not observed in nano mode when Ctrl+F > replace all is used.
- Running with the `c` flag shows that it is indeed finding the replaced text.

**Comment by Dumonu** [comment]
Here's an interesting observation. I did a little digging into the code. It looks like the vim mode is handled by including the monaco-vim package. The bug successfully reproduces in the monoco playground at https://editor.bitwiser.in/ linked from https://github.com/brijeshb42/monaco-vim.

**Comment by Snarling** [comment]
Yeah I think most issues with vim need to be addressed in the monaco-vim project, not in bitburner directly. Or if there's a better alternative to monaco-vim we could consider moving to that.

**Comment by Dumonu** [comment]
That makes sense to me. I didn't discover that bitburner uses monaco-vim
until after I initially filed the issue.

For what it's worth, bitburner's vim emulation works really well for me, so
unless something significantly better is found, I'd stick with monaco-vim.
