### ISSUE TITLE
[Bug] Inconsistency: deleting a folder on any other server than home has different folder deletion behaviour than home

### ISSUE THREAD

**Issue by Hoekstraa** [danielyxie/bitburner#3492]
## Description
When deleting the last file in a folder, while currently being located within the folder, the player is 'cut off' from other folders, unable to use relative pathing to return to the base folder ( ~/ ).

Above behaviour is prevalent in all servers but home, which handles the scenario as one might expect, allowing the player to use `cd ..` for example to return to a folder that is in existence.

## Version
Tested on 1.6.4 (fbb99c17)

## Reproduction
Home (showing no error)
![behaviour on home](https://user-images.githubusercontent.com/19653491/163794719-77108362-4d93-4d57-bb57-2c48ddfe3b81.png)
Other server (showing error)
![behaviour on faction server](https://user-images.githubusercontent.com/19653491/163794722-2bd4efd7-cccd-414a-ab8d-481799705dc4.png)

**Comment by Snarling** [comment]
It's not something weird about home vs. other servers, it's just that the game doesn't let you move into a folder that's empty. Here it is also happening on home, with the destination directory of .. being an empty directory
![image](https://user-images.githubusercontent.com/84951833/164247441-876672d2-240b-4cac-a2fe-03aa24a3d744.png)

Working on a PR to address.

**Comment by Hoekstraa** [comment]
You're right. This was discussed in the Discord server and from my point of view the different behaviour made me consider it an inconsistency between servers (making it a bug), since in my examples the directory to `cd` to exists in both scenarios.

I considered adding the case you presented as well, however wasn't sure if that was something that could be resolved.
Seems you found a way, good!
