### ISSUE TITLE
Int Info

### ISSUE THREAD

**Issue by apdjz** [danielyxie/bitburner#3506]
Would love to have information on int works and how much of an increase. Currently as far as I know this is the most info: Higher Intelligence levels will boost your production for many actions in the game.

**Comment by Snarling** [comment]
When intelligence was added, this info was purposely hidden from the player. I'm not sure if we want to expose that info now, but if you're curious you can always search the source code for references to intelligence. The big ones off the top of my head are crime chance, hacking chance, bladeburner success chance.

**Comment by apdjz** [comment]
Fair enough
