### ISSUE TITLE
Misleading ns.nFormat() magnitude letter

### ISSUE THREAD

**Issue by bimsherwood** [danielyxie/bitburner#3509]
Hello,

My currently installed version is 1.6.4 (00628A8C) on Windows installed via Steam.

I have noticed that `ns.nFormat()` sometimes emits a confusing combination of a rounded-up mantissa with the magnitude letter for the unrounded number.

For example:

`1,000,000,000 - 1` formatted with `"0.00 a"` becomes `"1.00 m"`.

The reproduction is as follows:

```
/** @param {NS} ns */
export async function main(ns) {
    ns.tprint(ns.nFormat(1000*1000*1000 - 1, "0.00 a"));
}
```

I noticed I get the same result on the web console on the Numeral.js website. It seems like a massive pain to fix, as Numeral.js looks abandoned.

(Please excuse me if I make a faux-pas, this is the first issue I've posted.)

**Comment by Snarling** [comment]
Unfortunately if it's a problem with base numeraljs it will probably be difficult to fix directly in bitburner.

Searching for up to date numeral alternatives, I found numbro which was forked from numeral and is actively maintained and also available via npm. `numbro(1000*1000*1000 - 1).format("0.00 a")` outputs the expected 1.00 b. So switching over to numbro or another alternative would be a way we can address this bug.
