### ISSUE TITLE
can't join fulcrum tech

### ISSUE THREAD

**Issue by HoaxParagon** [danielyxie/bitburner#3526]
on version 1.6.4, I've hacked and backdoored the fulcrum secret tech assets server then got over the 250k requirement for them but they aren't inviting me and I think it's because I hacked the server first.

**Comment by rderfler** [comment]
Have you tried backdooring the server again?

**Comment by HoaxParagon** [comment]
> Have you tried backdooring the server again?

I tried backdooring Fulcrum Technologies server again but no invite came my way.

**Comment by hydroflame** [comment]
That is not the correct server.
