### ISSUE TITLE
ns.gang.getBonusTime() wrong return value (or wrong documentation)

### ISSUE THREAD

**Issue by vladtepesch** [danielyxie/bitburner#3527]
doc of `ns.gang.getBonusTime()` states that the time is returned in milliseconds.
It seems that the value is returned in seconds instead. 
So one of the two is wrong.

Bitburner v1.6.4 (00628a8c)

**Comment by phyzical** [comment]
based on this one https://github.com/danielyxie/bitburner/pull/3053 id say it should be in ms not seconds
