### ISSUE TITLE
Negative Corp Funds?

### ISSUE THREAD

**Issue by apdjz** [danielyxie/bitburner#3536]
I personally find the ability to go into the negatives slightly odd without any detriment. Perhaps a bank loan with interest or the possible bankruptcy would make sense? Although I don't know how it would affect the gameplay.

**Comment by Undeemiss** [comment]
It's an intentional choice, with game mechanics to support it. It's not like there's no penalty for being in the red, either; your employees will start losing energy and such.

**Comment by apdjz** [comment]
Yeah, it was mistakingly spending all of my money and having to buy materials. Also didn't help not knowing what I was doing.
