### ISSUE TITLE
Unable to purchase upgraded augmentation

### ISSUE THREAD

**Issue by RobLeachman** [danielyxie/bitburner#3538]
The attached game is in an invalid state. Bought Bionic Legs and want to buy the Graphene upgrade, but no. Observe this worked fine for the Spine.
[no graphene bionic leg joy.zip](https://github.com/danielyxie/bitburner/files/8536427/no.graphene.bionic.leg.joy.zip)

Faction > Slum Snakes > Augs > no joy

**Comment by Snarling** [comment]
Could not reproduce. On your save you don't have enough money for the graphene bionic legs, but once I gave myself enough money I was able to purchase them.

**Comment by RobLeachman** [comment]
I'm an idiot, please delete.
