### ISSUE TITLE
v1.6.4 (00628a8c) save-file corruption

### ISSUE THREAD

**Issue by FreifunkerEZ** [danielyxie/bitburner#3554]
Bitburner v1.6.4 (00628a8c)

[RECOVERY_BITBURNER_1650790131.zip](https://github.com/danielyxie/bitburner/files/8549369/RECOVERY_BITBURNER_1650790131.zip)

# Hallow!
My game did not load, and it told me to upload this file. No idea if I did anything to break this. I was in the middle of bitnode-4 and you can probably read that from the recovery file.

thanks for the fun game!
Cheers,
chris :)

**Comment by Snarling** [comment]
Did you do anything odd right before the recovery screen came up?

**Comment by FreifunkerEZ** [comment]
Hi Snarling! Thanks for answering.

Nah, I usually save the game manually, then press BACK on the browser, say "ya, leave" to go back to the matrix screen. Then I put the computer into sleep for the night. (I do that because I feel like hibernating with the game open causes "funny") Next day I start the computer, click the big Bitburner-logo, the spinner comes and boom: dead.

Haven't done anything I thought was strange before that.
I got an older save-export, from before it blew up, if that helps.

**Comment by FreifunkerEZ** [comment]
Oh, maybe it matters, that I use the web-version? https://danielyxie.github.io/bitburner/

**Comment by hydroflame** [comment]
So did I.

**Comment by hydroflame** [comment]
I'm gonna close for now because I can't reproduce. But if it happens again I'll investigate. I take corruption more seriously than any other bug.

**Comment by FreifunkerEZ** [comment]
Nah, It still happens. Does the console help?
[RECOVERY_BITBURNER_1650978160.zip](https://github.com/danielyxie/bitburner/files/8563617/RECOVERY_BITBURNER_1650978160.zip)

```
LoadingScreen.tsx:64 Error: Router called before initialization
    at Object.Ct (GameRoot.tsx:115:9)
    at b (MessageHelpers.ts:60:14)
    at Object.checkCounters (engine.tsx:214:7)

    at Object.updateGame (engine.tsx:142:12)
    at Object.start (engine.tsx:459:14)
    at Object.load (engine.tsx:404:14)
    at LoadingScreen.tsx:53:20
    at async LoadingScreen.tsx:49:5
(anonymous) @ LoadingScreen.tsx:64
AllServers.ts:96 Hostname of the server thats being added: ecorp
y @ AllServers.ts:96
AllServers.ts:97 The server that already has this IP is: ecorp
y @ AllServers.ts:97
AllServers.ts:98 Uncaught (in promise) Error: Error: Trying to add a server with an existing IP
    at y (AllServers.ts:98:11)
    at b (AllServers.ts:171:5)
    at Object.load (engine.tsx:435:7)
    at LoadingScreen.tsx:65:18
    at async LoadingScreen.tsx:49:5
```
