### ISSUE TITLE
Abrupt crash while setting task for sleeve

### ISSUE THREAD

**Issue by jacobs2k** [danielyxie/bitburner#3556]
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by nickofolas** [comment]
did you by any chance create a gang with the faction your sleeve was working for before the crash occurred?

**Comment by jacobs2k** [comment]
It is possible. I'm far enough down the road now that I've forgotten some
of what I've done.

It wasn't a big issue, and a quick restart resolved the issue. I just used
the bug reporter in case it was of any use to developers.

It is wonderfully unique game.

Many thanks

**Comment by nickofolas** [comment]
alright, thanks for responding! i've got a PR lined up that hopefully addresses your issue, so fingers crossed.
