### ISSUE TITLE
Request: easier Sleeve Task interface

### ISSUE THREAD

**Issue by vladtepesch** [danielyxie/bitburner#3566]
Restoring a sleeves task currently is tedious and thanks to https://github.com/danielyxie/bitburner/issues/2884 impossible for some tasks.

May be an function could be added that takes a `SleeveTask` object.

then the following workflow would be possible

```
let oldTask = ns.sleeve.getTask(someId);
// set to some other tasks
ns.sleeve.setTask(someId, oldTask);
```

**Comment by borisflagell** [comment]
#2884 will be fixed by PR #3631.

Concerning a SetTask function. The current consensus is that it would go against the game philosophy. It's up to the player to write something to make the process less tedious.
