### ISSUE TITLE
Augmentation issue: The Blade's Simulacrum

### ISSUE THREAD

**Issue by Tigenzero** [danielyxie/bitburner#3579]
Version: Bitburner v1.6.4 (00628a8c)

The Blade's Simulacrum allows for Bladburner functions to run at the same time as faction/company functions. However, two unexpected events occur.
1. After buying the augmentation, the effect is in play without needing to install it.
2. Any time a Bladeburner function is executed, the previous faction/company function is canceled. This would normally be expected but I can simply restart the faction/company function and it will run simultaneously with the Bladeburner function.

Save file included.

[bitburnerSave_1651148148_BN3x1.zip](https://github.com/danielyxie/bitburner/files/8582607/bitburnerSave_1651148148_BN3x1.zip)

**Comment by Undeemiss** [comment]
This was fixed by #3639, and can thus be closed. I did not notice it when creating #3639 because there were two reports for the same bug.
