### ISSUE TITLE
Game progression is terrible.

### ISSUE THREAD

**Issue by RedStoner** [danielyxie/bitburner#3580]
I have completed bit node 1 three times now as suggested by the wiki, and have moved on to artificial intelligence. In BN1 progression was slow but an ok pace. Now that I have moved on to artificial intelligence, i feel the game is not progressing in any way shape or form. I have tried other nodes as well, and all the "Decreased Income Significantly" nodes seem absolutly impossible. I have been on artificial intelligence now for 5 days. I have let the game run idle 98% of that. With very efficient batching of hacking and a fully completed contract solver. It is near impossible to earn the amount of money needed to even buy one augment now for bitrunners let alone all of them. In 24 hours of play, i have earned less than 15 billion. Most idle games will pickup in progression speed as you play, This game seems to be the exact opposite. I was enjoying this game until i tried moving on to ANY other bitnode. The node states infiltrations earn 50% more money, yet infiltration are probably the most annoying thing about this game, with 0 scripting means.  The wiki classifies this as the "Fast" Route...... HA. That must be an inside joke or some really outdated information.
![image](https://user-images.githubusercontent.com/1278466/165825449-c2f78b48-72ff-4406-9f6f-c30258728450.png)

  I am quite curious as to how many people on average will cheese the system time to compensate for the weeks of idle time it takes to beat some of these nodes. As it seems the point of this node is to increase your intelligence to work through it, yet the only way i have seen it move is by creating programs. Which is yet another broken mechanic. It seems even with a hacking level of 1500, writing the simple programs can take hours. In a run where money is incredibly difficult, it would be nice if the create programs at least scaled in any way with your skill level. The only logical solution for this bitnode i can come up with to beat it is to cheese the system time, or let the game idle for weeks. If this is the intention..... Shame.

- [ ] Version v1.6.4

**Comment by RedStoner** [comment]
Just dug through source code... Just wow...
        ScriptHackMoney: 0.15,
        HacknetNodeMoney: 0.2,
        CrimeMoney: 0.5,
The three main methods of making money nerfed to high heaven.

        AugmentationMoneyCost: 2,
Augmentations doubled in cost.. This is just a major Decrease. That augement multiplier essentially cuts any profit in half again. thus you get about 7% income. I really feel this is just way too much.

**Comment by dleblond312** [comment]
You might want to look at the singularity node. With access to Source-File 4, you can destroy these easy/medium bitnodes in 1-2 days tops (I did SF5 in 1d3h). Even in SF4, you should be earning billions/s after 12 hours.

If you want some inspiration, my scripts are uploaded to my GitHub profile.

**Comment by phyzical** [comment]
ah yeah those docs are probably a tad old, i think the biggest issue here is that it suggests moving straight to bn5 after 1
