### ISSUE TITLE
Bladeburner.getActionRepGain() docs mismatch functionality

### ISSUE THREAD

**Issue by smmalis37** [danielyxie/bitburner#3582]
https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.bladeburner.getactionrepgain.md specifies that the `level` argument is supposed to be optional, although It doesn't specify what the result will be in the case that this argument is omitted. However the current implementation requires a level value to be passed in, and will throw an exception if one is not.

**Comment by phyzical** [comment]
hmm source wise it should be optional, and will default to the current actions level if nothing is provided,

what is the exception that is thrown?

**Comment by smmalis37** [comment]
Taking a quick glance, I believe the exceptions that I'm seeing are all coming from the [helper.number call](https://github.com/danielyxie/bitburner/blob/371de216ea4bb07f83baa142f00f1acf5b4d3520/src/NetscriptFunctions/Bladeburner.ts#L162), as I believe it doesn't let null/NaN through to hit the later if.
