### ISSUE TITLE
API Request: Bladeburner.getNextBlackOpName

### ISSUE THREAD

**Issue by smmalis37** [danielyxie/bitburner#3583]
Currently the only way to get information about the available Black Ops is to start by calling `Bladeburner.getBlackOpNames()`. However most of the time users will not care about black ops that are already completed, or that can not yet be attempted. Really only the currently available Black Op is the one that matters. It'd be nice to have a function that returns a single name of just the black op that's relevant at that point in time.

**Comment by LeviPesin** [comment]
Yeah, that'd be nice. Currently the following function can be used instead:

```
function getNextBlackOp(ns) {
	for (let op of ns.bladeburner.getBlackOpNames()) {
		if (ns.bladeburner.getActionCountRemaining('Black Operation', op) > 0)
			return op;
	}
}
```
