### ISSUE TITLE
Ability to specify <x,y> coordinates as optional parameters to ns.tail()

### ISSUE THREAD

**Issue by dleblond312** [danielyxie/bitburner#3585]
It would help a lot with augment installs if various log output screens could be opened at various locations instead of stacked on each other in the middle of the screen.

**Comment by JohnnyQuazar** [comment]
Great idea! I thought I opened a similar issue but apparently not, will ride your coattails :)

We also need (NEED) a way to declare width and height.

**Comment by MatiasCardullo** [comment]
Yes please

**Comment by OriginalRobotWizard** [comment]
@hydroflame To answer the question: Optional parameters.

BUT: I highly suggest to change this into 2 new functions, because it's much more versatile:
- moveTail(x, y)
- resizeTail(w, h)

The cherry on the cake would be 
- closeTail()

**Comment by OriginalRobotWizard** [comment]
Right, tail has the possibility to just open any log, not just the one of the own script. Interesting, but I never used it that way, so I did not know.

Anyway, then the 3 new functions can solve the needs?

**Comment by vladtepesch** [comment]
maybe `tail` could return a handle that has some member functions like `move`, `close`, `resize`, `clear`
This would have the advantage to not clutter the ns-namespace.
