### ISSUE TITLE
BitNode requirement mismatch between game and documentation

### ISSUE THREAD

**Issue by dleblond312** [danielyxie/bitburner#3589]
I'm currently in BitNode 6 (according to the stats page):
![image](https://user-images.githubusercontent.com/906357/166127481-cc89ebfa-c084-4d41-b7e2-65f2906fc520.png)

When I access the bladeburner APIs (any function I've tested so far), I get a script failure indicating I need SF-7 or to be in BitNode 7. I believe think this is a game bug:
![image](https://user-images.githubusercontent.com/906357/166127506-9fc8526c-bf5c-4a5d-ad42-149909922c99.png)

ns.getPlayer().bitNodeN returns a value of 6

[BitNode7-Bug.zip](https://github.com/danielyxie/bitburner/files/8598100/BitNode7-Bug.zip)

**Comment by dowinter** [comment]
This is intended, no? Bitnode 6 gives unlocks Bladeburners, Bitnode 7 unlock Bladerburner API access.
