### ISSUE TITLE
Sidebar shortcuts don't work on some MacOS keyboard layouts

### ISSUE THREAD

**Issue by Guddler** [danielyxie/bitburner#3592]
I don't believe save files and scripts are really of much use here

If you are on a Mac (tested) pressing the alt (Option) key and pressing some other key will quite likely not give the keycode you expect to see. For example, pressing ALT-S on a British English Mac keyboard will actually type `ß` not `s`. This in turn means that the condition:

`if (event.key === KEY.S && event.altKey)`

in src/Sidebar/ui/SidebarRoot.tsx will not be met and the shortcut will get ignored.

I tested this on v1.6.4 of the game natively from Steam on macOS and also in a browser both on an Apple Silicon machine and also an older Intel machine so I don't believe this has anything to do with the OS itself. Also the same keyboard works with v1.6.4 on Windows so it appears to be an entirely layout based issue.

Discussing the issue on Discord it would appear that using `event.code` rather than `event.key` might be the solution but I don't really have a JS dev environment ready to go to test this and provide a PR.

**Comment by Hoekstraa** [comment]
I'm picking this one up.

Same issue appears within `terminalInput.tsx`
@HeinousTugboat wrote a little tester that shows we can use event.code to get the key input more directly (s instead of an eszett, even when that is what would be typed).
