### ISSUE TITLE
Autocomplete/argument parsing does not work correctly with quoted arguments/escaped spaces

### ISSUE THREAD

**Issue by RevanProdigalKnight** [danielyxie/bitburner#3596]
Game version: `Bitburner v1.6.4 (00628a8c)`

This is really 2 issues, autocomplete not working properly on quoted options and terminal argument parsing not properly handling escaped spaces.

When trying to include autocomplete for single arguments which contain spaces by wrapping them in quotation marks (single or double), the autocomplete breaks and doesn't suggest anything.

```js
// autocomplete-cities.js
export function autocomplete(data, args) {
  return ['Sector-12', 'Aevum', 'Volhaven', 'Chongqing', '"New Tokyo"', 'Ishima'];
}

export async function main(ns) {
  ns.tprintf('City: %s', ns.args[0]);
}
```

```sh
# in the terminal
$ run autocomplete-cities.js S\t # Autocomplete works, fills in with Sector-12. Same for other single-word cities
$ run autocomplete-cities.js N\t # No autocomplete occurs, no popup shows
$ run autocomplete-cities.js "N\t # same as above
```

Returning arguments with spaces that are *not* wrapped in quotations does provide autocomplete options but the autocomplete does not auto-wrap them in quotes

```js
// autocomplete-cities-2.js
export function autocomplete(data, args) {
  return ['Sector-12', 'Aevum', 'Volhaven', 'Chongqing', 'New Tokyo', 'Ishima'];
}

export async function main(ns) {
  ns.tprintf('City: %s', ns.args[0]);
}
```

```sh
# in the terminal
$ run autocomplete-cities-2.js N\t # autofill provides `New Tokyo` (without quotes)
Running script with 1 thread(s), pid 1 and args: ["New", "Tokyo"]
City: New
```

Autocomplete works if spaces are escaped with `\\`, but then still ends up being 2 separate arguments when run:

```js
// autocomplete-cities-3.js
export function autocomplete(data, args) {
  return ['Sector-12', 'Aevum', 'Volhaven', 'Chongqing', 'New\\ Tokyo', 'Ishima'];
}

export async function main(ns) {
  ns.tprintf('City: %s', ns.args[0]);
}
```

```sh
# in the terminal
$ run autocomplete-cities-3.js N\t # autofill provides `New\ Tokyo` (without quotes)
Running script with 1 thread(s), pid 1 and args: ["New\\", "Tokyo"]
City: New
```

I'm not sure what the best solution to this would be. Right now I'm getting around the problem by replacing spaces with underscores and then swapping it back in the main function, but it would be nice if the autocomplete could automatically quote or escape spaces in results which contain spaces.

Regardless of what's done with the autocomplete code the terminal really should be fixed to work with escaped spaces properly.

**Comment by phyzical** [comment]
@RevanProdigalKnight 
so i had a long look through how all this works wild beast :D

anyway based on my scans of the source it looks like your first attempt should have worked, (havnt tried yet)

but i think your `"N` attempt may have been auto escaped? i.e
![image](https://user-images.githubusercontent.com/5182053/166441816-baa3cd90-3f1e-47d2-ae3e-34beee15795b.png)

so could you try `\"N` alternatively it looks like `"'"` plays nicer so if the former works, a workaround could be to use `'` in the autocomplete data for now and use `'N` for the script

sadly there is not a better way to handle this as argv will just explode on the space so youll either have to do what your already doing or using the above (if it does work)

**Comment by RevanProdigalKnight** [comment]
> but i think your `"N` attempt may have been auto escaped? i.e
> ![image](https://user-images.githubusercontent.com/5182053/166441816-baa3cd90-3f1e-47d2-ae3e-34beee15795b.png)
> 
> so could you try `\"N` alternatively it looks like `"'"` plays nicer so if the former works, a workaround could be to use `'` in the autocomplete data for now and use `'N` for the script

Escaping the quote in the terminal doesn't seem to work either.

> sadly there is not a better way to handle this as argv will just explode on the space so youll either have to do what your already doing or using the above (if it does work)

Ah, I thought the argument parsing code may have been custom. Something I only just thought of now which would be pretty simple to do is loop over the parsed arguments before passing them to the script and join any arguments ending with \ together with the next, e.g.:

```js
var args = ["arg1", "arg2\\", "arg3\\", "arg4", "arg5", "arg6\\", "arg7"];

for (let i = args.length - 1; i >= 0; i--) {
  if (args[i].endsWith('\\')) {
    args.splice(i, 2, args[i].concat(' ', args[i + 1]))
  }
}
```

![image](https://user-images.githubusercontent.com/5728037/166461691-f4da25b4-11c6-40e4-a756-86089e186a8d.png)

**Comment by phyzical** [comment]
if your curious i think the nitty gritty starts around here (i think) https://github.com/danielyxie/bitburner/blob/dev/src/Terminal/determineAllPossibilitiesForTabCompletion.ts#L293

**Comment by RevanProdigalKnight** [comment]
Okay so after digging through the code a bit more (after creating #3606, that is) it looks like the code which actually inserts text into the terminal input when hitting tab is here https://github.com/danielyxie/bitburner/blob/f6e689eeadb2ed17ec2434c759e9df09ad0e6ad3/src/Terminal/tabCompletion.ts#L44

As far as I can figure, automatically wrapping multi-word arguments in quotes would break the current command parsing and make autocomplete not work past the first time.

If my PR is accepted and merged, I'm pretty sure it wouldn't break outright, but in order to autocomplete properly on multiple matches the user would have to move the cursor back into the quotations and continue typing (e.g.: `run script.js multi\t` -> `run script.js "multi word"`, but if there are multiple autocomplete results starting with "multi word" then the user would have to move the cursor left into the quotes and continue typing to get true autocomplete behavior). Escaping spaces with backslashes would alleviate that issue and behave more like a standard Unix terminal, but do not work with current command parsing.

Thoughts?
