### ISSUE TITLE
Nerf Bladeburners

### ISSUE THREAD

**Issue by LeviPesin** [danielyxie/bitburner#3600]
I think that currently Bladeburners are too OP...

Yesterday I managed to complete BN6.2 in 4 days 6 hours with:
1) playing it in mostly passive way (not completely passive because I did not start BN7 yet, so I was programming automation, levelling up skills, and completing BlackOPs manually),
2) not spending any money except a small amount in the start to obtain required 100 combat skills,
3) **not purchasing or installing any augmentations** and with no interaction with any faction,
4) levelling up only 5 Bladeburner skills (Blade's Intuition, Digital Observer, Overclock, Reaper, Evasive System),
5) and this was just the second time I ever interact with the Bladeburners...

I think this was too easy.

~I think that in BN8 the Bladeburners will become even more OP, because the BN8 is meant to extremely harder money obtaining, while the Bladeburners allow to break the node without earning any money.~

**Comment by phyzical** [comment]
so while i agree with you. there are people that complain 1 week is too long :D we cant win.

but you cant actually use bladeburner in BN 8 

```
export function canAccessBladeburner(this: IPlayer): boolean {
  if (this.bitNodeN === 8) {
    return false;
  }

  return this.bitNodeN === 6 || this.bitNodeN === 7 || this.sourceFileLvl(6) > 0 || this.sourceFileLvl(7) > 0;
}
```

**Comment by LeviPesin** [comment]
> but you cant actually use bladeburner in BN 8

I did not know that, thank you! That is good!
