### ISSUE TITLE
The function destroyW0r1dD43m0n is not defined on ns.singularity at runtime

### ISSUE THREAD

**Issue by dleblond312** [danielyxie/bitburner#3602]
I'm playing steam version 1.6.4, the function ns.singularity.destroyW0r1dD43m0n does not exist (I have access to singularity API).

Here's a screenshot of ns.singularity in the debugger:
![image](https://user-images.githubusercontent.com/906357/166479046-61048e08-f5be-47d7-bea1-329c4cacfd3b.png)
![image](https://user-images.githubusercontent.com/906357/166480304-a41e1863-c144-4900-9725-bec24e3f4ca3.png)

The function is still part of the Netscript typings file and it looks to be part of Singularity, but can't be accessed at runtime.
https://github.com/danielyxie/bitburner/search?q=destroyW0r1dD43m0n

Could this be a recent regression?

**Comment by nickofolas** [comment]
this function is in dev, and will not be available on steam until the next update

**Comment by hydroflame** [comment]
oof, I didn't think about the problem of the documentation being out of date with the code :\
