### ISSUE TITLE
Purchased servers ending in "-1" Does not increment properly.

### ISSUE THREAD

**Issue by matte0802** [danielyxie/bitburner#3603]
For example. 
PurchasedSevers("MyServer-0",128)
PurchasedSevers("MyServer-0",128)

This will output servers with the names `MyServer-0` and `MyServer-0-0`. But I expected the second server to be named `MyServer-1`

**Comment by millennIumAMbiguity** [comment]
This fix was suggested in #2166

**Comment by phyzical** [comment]
doesnt this function expect a name and then it appends numbers to that?

i.e
`PurchasedSevers("blah",128)` which results in blah-0, blah-1, blah-2 ect

**Comment by Hoekstraa** [comment]
It does.

This is essentially just a patch that makes it so when you instead do `PurchaseServer("server-0",x)` it reuses that `-0` instead of appending another `-0`,`-1`, etc, preventing a duplicate (resulting in `server-6` instead of `server-0-5` for example)

**Comment by millennIumAMbiguity** [comment]
The current code to decide the names:
```ts
  if (GetServer(hostname) != null) {
    hostname = `${hostname}-0`;

    for (let i = 0; i < 200; ++i) {
      hostname = hostname.replace(/-[0-9]+$/, `-${i}`);
      if (GetServer(hostname) == null) {
        break;
      }
    }
  }
```
meaning that it will always append a number to the name if it already exists. example:
```ts
PurchasedSevers("foo",128)      //foo
PurchasedSevers("foo",128)      //foo-0
PurchasedSevers("bar-0",128)    //bar-0
PurchasedSevers("bar-0",128)    //bar-0-0
PurchasedSevers("bar-9000",128) //bar-9000
```
with #2166, the names would be `foo`, `foo-0`, `bar-0`,  `bar-1`, and `bar-9000`

**Comment by borisflagell** [comment]
I'll cast my vote to the "no" urn.
Mainly because that kind of change is potentially breaking. 
Also the added-value is highly subjective. Some may say that you had wrong expectation.
