### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getInfo') (at "Sleeves")

### ISSUE THREAD

**Issue by JefStat** [danielyxie/bitburner#3604]
### How did this happen?

Please fill this information with details if relevant.

- [x] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.6.4 (00628a8c)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=1 indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
``
[RECOVERY_BITBURNER_1651598894.txt](https://github.com/danielyxie/bitburner/files/8612457/RECOVERY_BITBURNER_1651598894.txt)
`

**Comment by nickofolas** [comment]
should be fixed in dev

**Comment by phyzical** [comment]
there was one more potential reference i found, but pr is up for it 👍
