### ISSUE TITLE
Stats box overflows after adding intelligence

### ISSUE THREAD

**Issue by twilde** [danielyxie/bitburner#361]
After getting the intelligence stat from BN5 the stats box in the upper right is slightly overflowed on my 15" MacBook Pro running Chrome (Version 67.0.3396.99 (Official Build) (64-bit)) on OS X. Screenshot attached.

<img width="422" alt="screen shot 2018-07-19 at 4 32 41 pm" src="https://user-images.githubusercontent.com/1042669/42968526-8372aa5a-8b71-11e8-8fa3-6994d82cc1b3.png">

**Comment by hydroflame** [comment]
@danielyxie We can close this.
