### ISSUE TITLE
Type error when setting sleeve task

### ISSUE THREAD

**Issue by tjones35** [danielyxie/bitburner#3629]
### How did this happen?

Set sleeve 7 to security work for ECorp 

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.6.4 (00628a8c)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save

[RECOVERY_BITBURNER_1651967653.zip](https://github.com/danielyxie/bitburner/files/8646117/RECOVERY_BITBURNER_1651967653.zip)

**Comment by nickofolas** [comment]
This should be fixed in the next update, which you can test out on the Steam development branch if you'd like
