### ISSUE TITLE
Suggestion: Make the corporation API cost 0 ram in the Corporatocracy BitNode

### ISSUE THREAD

**Issue by dleblond312** [danielyxie/bitburner#3630]
This game rocks, I've sunk huge hours and it always comes back offering more. Every BitNode offers something new and exciting. The first time I noticed myself discouraged with continuing was in the Corporatocracy node (my 5th node type). The issue that caused discouragement was because I hit a wall of progression waiting for my wealth to accumulate to where I could start using the ns.corporation APIs by purchasing home ram over 1TB.

I know that manual manipulation via the UI could get me there faster - but that's the real shame, I try and interact with the UI purely to learn mechanics. The moment I have an understanding I want to exclusively work in scripts for all aspects of the game (and the game really really excels at letting me do this - except for this spot).

There is a similar issue in BitNode 6 + 7 where the API to code against BitNode 6's mechanic is in 7...which I don't like... However, it can be worked around. This one is really punishing if you don't manually setup a corp. It adds something like 72 hours per BitNode reset if you do not use the manual interface.

The huge ram requirement for corps makes sense to me, just not in context of the Corporatocracy BitNode since this is supposed to be an "easy" rated node, either set to 0 or set to a lower number like 32 or 64.

**Comment by borisflagell** [comment]
Ol' discord user have told me it's a historical design choice :

Apparently, a dev took "ram cost dodging" as an offense and came up with 1To ram cost for the whole corporation namespace as a countermeasure. Which was maybe a bit too much, indeed :D
