### ISSUE TITLE
Hacknet Multipliers not working

### ISSUE THREAD

**Issue by rojekabc** [danielyxie/bitburner#3635]
Hi,

BitBurner v1.3.4

I use some Augmentations.

In stats I may see:
```
Hacknet Node production | 108.29%
Hacknet Node purchase cost | 92.35%
Hacknet Node RAM upgrade cost | 92.35%
Hacknet Node Core purchase cost | 92.35%
Hacknet Node level upgrade cost | 92.35%
```
But, when I'm buying new hacknet nodes / levels / RAM / Core - the price is still same as before Augmentations.

**Comment by Undeemiss** [comment]
This isn't very specific. Also, _1.3.4_? It's been a long time since then. Was that a typo?

**Comment by rojekabc** [comment]
Sorry. Version 1.6.4 (00628a8c). Yes, it was a typo.
I've used the script with formulas package to calculate those values with player hacknet multiplier and there're different than those from visual view of hacknet (visual view keeps the value before augmentations).

**Comment by borisflagell** [comment]
`ns.hacknet.getLevelUpgradeCost(i, 1) * ns.getHacknetMultipliers().levelCost`
Yes, it is !
Most netscript function return "modded" value.  Multipliers are usually accounted for.
