### ISSUE TITLE
Reseting milestones after augmentation installed

### ISSUE THREAD

**Issue by rojekabc** [danielyxie/bitburner#3636]
BitBurner v1.3.4

After augmentations are installed all the milestones have been reset.
I understand, than I don't have previous milestone steps now, but milestones have been done..... It's funny

**Comment by phyzical** [comment]
yeah milestones are more of a guide, not so much like achievements rather a reminder to the player what to do next.

@nickofolas we wanted to avoid having to save this as a state on purpose right? just asking incase we wanted to consider an option in settings to persist milestones

**Comment by nickofolas** [comment]
i dont remember the reason exactly but yeah we want to keep them stateless

**Comment by rojekabc** [comment]
Ok. If this is a feature and not a bug - close this.

**Comment by phyzical** [comment]
@rojekabc fyi you have the ability to close issues you create :)

**Comment by hydroflame** [comment]
Hold up
Where are you playing on 1.3.4?

**Comment by rojekabc** [comment]
type 1.6.4
