### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getInfo') (at "Sleeves")

### ISSUE THREAD

**Issue by Hellsau** [danielyxie/bitburner#3643]
### How did this happen?

Repeatable crash with multiple sleeves set to "Work for Faction" and have their faction target forcibly switched due to its existing target becoming actively worked by another sleeve, and having no such available faction targets remaining.

Replicating the crash requires: more than one sleeve, more sleeves than factions able to be used for the Work for Faction sleeve function, and at least one such faction. 

No scripts required.

Steps to replicate crash:

1) Open Sleeve window
2) Set all Sleeves to "Work for Faction" without pressing Set Task. This should automatically fill in the chosen faction for all sleeves to the first option in the faction list.
3) Click "Set Task" for the first sleeve. That sleeve will start working for the faction. All other sleeves should shift to the next faction in the list.
4) Continue to click "Set Task" on sleeves that are not currently working for a faction until you work as many sleeves as you have factions. The crash should occur immediately as the game attempts to shift the extra sleeves to the next faction in the list, which is now emptied of factions.
 
Recommendation: if the game logic would set a sleeve to show an undefined target, dump the sleeve back to the idle state shown as "------" in the action list.

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.6.4 (00628a8c)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
``
[RECOVERY_BITBURNER_1652150414.zip](https://github.com/danielyxie/bitburner/files/8657068/RECOVERY_BITBURNER_1652150414.zip)
`

**Comment by phyzical** [comment]
@nickofolas youve fixed this one in dev right?

**Comment by nickofolas** [comment]
presumably? i haven't tested with this use case, but a glance at what was changed seems to indicate that it would be fixed?
