### ISSUE TITLE
Undeletable file

### ISSUE THREAD

**Issue by PaintedGauthier** [danielyxie/bitburner#3645]
- Bitburner v1.6.4 (00628a8c)

Basically create a double //name.js file

- related script 
var list = ['/helpers/hack.js','/helpers/weaken.js','/helpers/grow.js'];
await ns.scp(list, host)
for (var m = 0; m < list .length; ++m) {
	file = list [m];
	if (file.startsWith('/helpers/') && ns.fileExists(file, host))
		ns.mv(host, file, file.replace('/helpers',''));
}

What happens is the files end up on the host (yes the go away eventually on bn destruction)
When you ls you only see
/
when you
nano / [then tab]
you see
//hack.js //weaken.js //grow.js

Was not able to duplicate with terminal commands only ns.mv

But you can never delete them

**Comment by phyzical** [comment]
thanks for the report,

if i was to guess we enforce the folder on rm but not on mv so a folder of "//" which probably turns into a multi directory when removing, there is a feature for rm recursively not yet done, which might actually allow for deletion.

by really we should lock down the file and folder sanitisation

**Comment by PaintedGauthier** [comment]
I will say that i can no longer create un-deletable files, so this is fixed. 
However the following line instead of prefixing the filename with / , will just move the file to never be seen again
ns.mv('home', '/Temp/foobar.txt', '/foobar.txt')
 v1.7.0 (837cceba)

This issue is solved though
