### ISSUE TITLE
Valid folder names are not valid in game

### ISSUE THREAD

**Issue by Dane-Horn** [danielyxie/bitburner#3651]
Version 1.6.4
Run `nano testv1.0/test.js` in the in-game terminal: 
![image](https://user-images.githubusercontent.com/20649301/168400417-f9827e24-fc4c-472d-821e-a59d935b4b56.png)
Same folder name is valid in VS Code, for example:
![image](https://user-images.githubusercontent.com/20649301/168400671-b0e08d0d-abc9-4815-a0df-935f35943b48.png)

Additionally, the regex used to validate directory names is out of sync with the comments above it:
```ts
export function isValidDirectoryName(name: string): boolean {
  // Allows alphanumerics, hyphens, underscores, and percentage signs.
  // Name can begin with a single period, but otherwise cannot have any
  const regex = /^.?[a-zA-Z0-9_-]+$/;

  // match() returns null if no match is found
  return name.match(regex) != null;
}
```
Suggestion to adjust this regex to match more flexible folder names that are still legal and won't interfere with the directory system.

**Comment by Dane-Horn** [comment]
Willing to work on this issue myself. Just want to get consensus on what a sensible regex would include and what, if any, gotchas there might be in this regard.

**Comment by phyzical** [comment]
why not, but the reason its probably doing this is there is probably logic around the place expecting if it contains a single period then it must be a file, but id assume those should be easily fixed (if it even ends up being a problem) with enforcing this logic on the last item of an explode of "/" instead

**Comment by Dane-Horn** [comment]
That was my concern and proposed solution too. I'll take a look at this over the course of the day
