### ISSUE TITLE
SLEEVE: ns.sleeve.travel won't check the player's balance. Allowing negative balance.

### ISSUE THREAD

**Issue by borisflagell** [danielyxie/bitburner#3656]
![image](https://user-images.githubusercontent.com/104104269/168477761-b3b9f037-d6b0-489a-a883-f59a108344d1.png)

**Comment by Undeemiss** [comment]
Is this actually a bug? I was under the impression it was a choice.

**Comment by hydroflame** [comment]
Not a bug
