### ISSUE TITLE
Bug on new servers after soft reset

### ISSUE THREAD

**Issue by GuSamadhi** [danielyxie/bitburner#3658]
- Some sort of bug while copying a script to some servers (CSEC and FoodnStuff for example). When I move a file to the servers, I receive the message "file overwriten". When I type "ls" on the server, I receive blank info. When trying to run, sometimes it says there's no such file. When I try to kill the script, I receive There's no such file.
v1.6.4 (00628a8c)

[bitburnerSave_1652645611_BN1x1.txt](https://github.com/danielyxie/bitburner/files/8695923/bitburnerSave_1652645611_BN1x1.txt)

**Comment by borisflagell** [comment]
Could not reproduce.
