### ISSUE TITLE
ns.growthanalyzesecurity()

### ISSUE THREAD

**Issue by copsi1** [danielyxie/bitburner#3663]
Hello,
i use Bitburner 1.6.4.

in NS.growthAnalyzeSecurity() method the discription of parameter "hostname": is limit to hack the maximum? in my test i think it is grow to maximum. becouse if a server lost 200k money and i test to grow with double the money, the result of growthanalyzesecurity ist very low.
sry for my bad english.

![grafik](https://user-images.githubusercontent.com/104488252/168662797-32066526-aa64-40eb-9000-b2e61757e1d4.png)

**Comment by N1cc3** [comment]
`NS.growthAnalyzeSecurity()` seems to be broken and always return 0.

**Comment by cmetz** [comment]
I think that's the correct behavior, as it is a optional parameter, but the documentation is wrong here, its the same like in hackAnalyzeSecurity and should may say something like this:
```
@param hostname — - Hostname of the target server.
The number of threads is limited to the number needed to grow the
servers to a maximum amount of money.
```
Just do not use the optional hostname parameter and you should be fine, as far as i know the security increases are the same on all servers. In my scripts it's working without the hostname parameter.
