### ISSUE TITLE
Server interface moneyAvailabe and maxMoney return null

### ISSUE THREAD

**Issue by SadBoiLlama** [danielyxie/bitburner#3668]
trying to make a database of the different servers to hack by calling getServer() and then getting what i needed from that
printed out the values to check and where there should have been numbers for money there was null

**Comment by Snarling** [comment]
The fields are called `moneyAvailable` and `moneyMax`. I'm not able to reproduce your issue, can you provide the script that is giving you the issue? I think this is an issue with your script.

**Comment by SadBoiLlama** [comment]
Run it with test.js
The actual issue is in the db.js
It should print out the values each time it tries to get the data for that server using moneyAvailable and moneyMax vs the get functions

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by phyzical** [comment]
@SadBoiLlama you will need to include your scripts for us to see what they do

**Comment by SadBoiLlama** [comment]
oh sorry im new to this
[files.zip](https://github.com/danielyxie/bitburner/files/8740411/files.zip)

**Comment by phyzical** [comment]
is it just this maybe? `moneyAvailabe` should be `moneyAvailable`
