### ISSUE TITLE
Error: ActiveFragment should not be null (at "StaneksGift")

### ISSUE THREAD

**Issue by EinHuhu** [danielyxie/bitburner#3669]
### How did this happen?

calling ns.stanek.clearGift() while in "Stanek's Gift" view

Steps to reproduce:
start the test script and switch to the "Stanek's Gift" view

Test script:
/** @param {NS} ns */
export async function main(ns) {
    
    ns.clearLog()
    ns.tail()
    await ns.sleep(2000)

    ns.print("Clearing gift")
    await ns.sleep(1000);
    ns.stanek.clearGift()
}

### Environment

* Error: Error: ActiveFragment should not be null
* Page: StaneksGift
* Version: v1.6.4 (00628a8c)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

**Comment by borisflagell** [comment]
Still bugged in 1.7.0
