### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getInfo') (at "Sleeves")

### ISSUE THREAD

**Issue by MSivonen** [danielyxie/bitburner#3670]
### How did this happen?

Please fill this information with details if relevant.

- [x ] Save file
- [x ] Minimal scripts to reproduce the issue
- [ x] Steps to reproduce

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getInfo')
* Page: Sleeves
* Version: v1.6.4 (00628a8c)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=fi cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a
[RECOVERY_BITBURNER_1652875587.zip](https://github.com/danielyxie/bitburner/files/8716549/RECOVERY_BITBURNER_1652875587.zip)

Run /bn4/startSin.js (which also runs thugGang.js and ver6.js, leave them running)
Go to sleeves page and it will sometimes crash.

**Comment by nickofolas** [comment]
this should be fixed in dev
