### ISSUE TITLE
Bladeburner message popup

### ISSUE THREAD

**Issue by ElRectalo** [danielyxie/bitburner#3685]
![assassination](https://user-images.githubusercontent.com/105966137/169640932-dd6168ab-b3a0-4877-a406-822de8d80e97.png)

[bitburnerSave_1653117909_BN13x2.zip](https://github.com/danielyxie/bitburner/files/8747162/bitburnerSave_1653117909_BN13x2.zip)

-Latest steam version
-message pops up on bladeburner BlackOps completion. 
Everything else seems to be working properly. Nothing crushes, blackops finishes correctly and lets me do next one.

**Comment by borisflagell** [comment]
Reproducible. 
Error thrown by Bladeburner.processAction() line 1686.

**Comment by TheMandalorian42** [comment]
Thanks, was JUST about to post this.  Literally just reached the stage where I could do my first Black Ops and this popped up :( Hopefully patched soon

**Comment by MatiasCardullo** [comment]
It was happening to me too, the game and the bladeburner actions don't crash but that alert comes out every now and then
