### ISSUE TITLE
version 1.7 infinite loop detection false positives

### ISSUE THREAD

**Issue by vladtepesch** [danielyxie/bitburner#3686]
in the new version (1.7.0. b71418b0) some of my more complex scripts get interrupted sporadically by the infinite loop detection heuristics.
There is definitevly none
the threshold of 1000 seems to be quite low. may be it should be configurable

e.g. just iterating over all servers or all stocksymbols and calling a few function for each object reaches this limit quite fast

**Comment by hydroflame** [comment]
It is toggleable in the options

**Comment by vladtepesch** [comment]
> It is toggleable in the options

yes but the threshold is at a limit that makes it nearly unusable
