### ISSUE TITLE
Bitburner.exe does not stop on exit

### ISSUE THREAD

**Issue by bd5872** [danielyxie/bitburner#3687]
Version: Bitburner v1.7.0 (b71418b0) (Steam)

This seems to be a new thing that has appeared since the most recent update.

After exiting, the executable doesn't actually stop, and needs to be killed via task manager (else Steam complains that it's already running when attempting to re-launch several hours later).

**Comment by borisflagell** [comment]
Could not reproduce. May be specific to some steam/Windows setup ?

**Comment by bd5872** [comment]
Might be, and frustratingly it's stopped doing it now, did it consistently three times, and now it's stopped.

So probably easiest to close.
