### ISSUE TITLE
Augmentations at 1 with no augmentations installed

### ISSUE THREAD

**Issue by D3thSh0t** [danielyxie/bitburner#3688]
Recently started playing Bitburner, after a recent patch my augmentations installed have increased to 1 even though I have yet to install any augmentations.

# include (where relevant)

- [bitburnerSave_1653138182_BN1x1.zip](https://github.com/danielyxie/bitburner/files/8747687/bitburnerSave_1653138182_BN1x1.zip)
  Save file
- [ None] Minimal scripts to reproduce the issue
- [open the game] Steps to reproduce
- [Bitburner v1.7.0 (b71418b0)] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by nickofolas** [comment]
looks like this was the result of a save file migration that fixed a bug with Augmentations during dev. tl;dr, you technically have a neuroflux governor, but it's at level 0 and thus providing no benefits.
