### ISSUE TITLE
Hamming code encoding contract's binary representation is not specified

### ISSUE THREAD

**Issue by gnoailles** [danielyxie/bitburner#3689]
The hamming code encoding contract is using the positive binary representation of the given value which adds a leading 1 compared to the two's complement representation.
```
(8587465242).toString(2)
'111111111110110100101001000011010'
(8587465242 >>> 0).toString(2)
'11111111110110100101001000011010'
```
(see this: [https://stackoverflow.com/questions/16155592/negative-numbers-to-binary-string-in-javascript](https://stackoverflow.com/questions/16155592/negative-numbers-to-binary-string-in-javascript))

I would argue that the 2's complement is the more widely used one and should be preferred but whatever representation is used, it should be specified in the contract because this makes it practically impossible to find why your result is wrong without going in and checking the actual implementation of the contract.

cc @Hedrauta

**Comment by stalefishies** [comment]
The second bitstring is just flat-out incorrect. Javascript outputs it because it truncates the value to a 32-bit unsigned integer (and this has nothing to do with twos complement). Nothing in the contract suggests anything about truncation, so it's correct as-written as I read it.

**Comment by Hedrauta** [comment]
Ye... I'm sorry 😔... There are a few different ways to get it encode and I don't have any time atm 😒

Working hard and exhausted after getting home 😑

 I'm trying to get a New version with a specified rule running, but can't find any good time for it 😭

I had sent a PR for temporary deactivate the hamming contracts, but it seems like it was ignored 🤔
Have a day free on Tuesday so I'll try for it then 😉
________________________________

**Comment by gnoailles** [comment]
> The second bitstring is just flat-out incorrect. Javascript outputs it because it truncates the value to a 32-bit unsigned integer (and this has nothing to do with twos complement). Nothing in the contract suggests anything about truncation, so it's correct as-written as I read it.

Oh right, you're correct. 🤦 Completely missed that it was higher than a 32bit max value, this seems fine.
