### ISSUE TITLE
#3624 does not count asleep()?

### ISSUE THREAD

**Issue by mycroftjr** [danielyxie/bitburner#3696]
Bitburner v1.7.0 (b71418b0)
```
export async function main(ns) {
    while (true) {
        for (let i = 0; i < 990; i++) {
            ns.hacknet.getPurchaseNodeCost();
        }
        await ns.asleep(1000);
    }
}
```
in case that doesn't replicate, the error was originally observed with https://github.com/mycroftjr/BitburnerAutoFarm/commit/63d7f328b0c9a7320ed9726cee3ea6b68b9d120f, Hacknet Manager ON. As you can see, the ns.asleep() was not detected as mitigating an infinite loop.

Granted, I don't understand what the "does not block with concurrent calls" part of the description of ns.asleep() means, but it seemed to prevent infinite loops just fine before #3624.

**Comment by phyzical** [comment]
i think its by design that asleep does not count cc @hydroflame

**Comment by hydroflame** [comment]
It is intentional but idk if it SHOULD be.

**Comment by fdellwing** [comment]
This change broke like 99% of my scripts, using asleep everywhere without a problem. Need to disable the function for me until this is changed.

**Comment by phyzical** [comment]
you can disable in the options

**Comment by hydroflame** [comment]
You're wrongly using asleep everywhere probably.
