### ISSUE TITLE
script log line wrap does not work correctly

### ISSUE THREAD

**Issue by vladtepesch** [danielyxie/bitburner#3699]
since the latest update (v1.7.0 b71418b0) the line wrap in the tail-windows is broken.

reproduce:
put a long line into log: (eg `---------------------------------------------------------------------------------------------------------------------` )

it gets not wrapped, if the window is smaller than the log.
In the last versions, lines like this got wrapped even if there were no word boundaries.

**Comment by nickofolas** [comment]
I don't seem to be able to reproduce this?

![bitburner_uCQAxwrym2](https://user-images.githubusercontent.com/60761231/169673523-77a23ea3-658d-4f68-a5d7-e242cc215aaa.gif)

**Comment by vladtepesch** [comment]
strange:
![GIF 22 05 2022 10-22-25](https://user-images.githubusercontent.com/1601159/169685631-2710ff55-b0ce-4a5a-91a6-ed34ae167853.gif)

```
/** @param {NS} ns */
export async function main(ns) {
	ns.disableLog("ALL");
	ns.print("----------------------------------------------------------------")
	ns.print("----------------------------------------------------------------G")
	ns.print("----------------------------V-W---------------------------------------------")

	while(true){
		await ns.sleep(1000);
	}

}
```

**Comment by nickofolas** [comment]
ah it repro-s in firefox

alright, i can get a fix in, sorry about that!
