### ISSUE TITLE
有中文版本吗？什么时候出中文版本？

### ISSUE THREAD

**Issue by CFX1234567890** [danielyxie/bitburner#3704]
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？
有中文版本吗？
什么时候出中文版本？

**Comment by borisflagell** [comment]
Translate by : Is there a Chinese version? When will the Chinese version be released?

**Comment by phyzical** [comment]
lol surly once would have been enough :/
