### ISSUE TITLE
Duplicate sleeve not benefiting from Bladeburner bonus time during Bladeburner activities.

### ISSUE THREAD

**Issue by Vic1970** [danielyxie/bitburner#3709]
Bitburner V1.7.0
Sleeve bladeburner activities do not benefit from bonus time. 

I have bonus time in Bladeburners.  My player activities are speeded up at about 5:1 as per normal behaviour during bonus time.  A duplicate sleeve is also doing bladeburner activities, but is not speeded up.

Intentional balance decision or error?

**Comment by hydroflame** [comment]
... I have no clue tbh ... but will think on it.
