### ISSUE TITLE
Contracts may spawn in unreachable servers

### ISSUE THREAD

**Issue by xRalic** [danielyxie/bitburner#3711]
# Issue

Calls to generateRandomContract() occasionally generate no contract.

## Traceback and replication

On the process of implementing a fix for a different issue, I ran the following code on ``Engine.ts`` under ``load()``:

```js
      const numCyclesOffline = 3000 * 200; // Math.floor(timeOffline / CONSTANTS._idleSpeed);

      // Generate coding contracts
      let numContracts = 0;
      if (numCyclesOffline < 3000 * 100) {
        // if we have less than 100 rolls, just roll them exactly.
        for (let i = 0; i < numCyclesOffline / 3000; i++) {
          if (Math.random() < 0.25) numContracts++;
        }
      } else {
        // just average it.
        numContracts = (numCyclesOffline / 3000) * 0.25;
      }
      console.log(`cycles = ${numCyclesOffline} contracts = ${numContracts}`);
      for (let i = 0; i < numContracts; i++) {
        generateRandomContract();
      }
```
When the code runs, ``numContracts`` always evaluates to 50, so 50 contracts should be generated. I ran this code three times (by refreshing the window): the first time it produced 50, and the following two times it produced 49 and 49, for a grand total of **not 150**.

On a hunch, I deleted **the save**, then I closed the node server, hardcoded ``numContracts = 500``, and reopened the node server. Refreshed the page to trigger the load event. Then this madness happened:

![image](https://user-images.githubusercontent.com/87785383/169724303-11c406da-ad0f-4176-aaa8-8413b5ef1079.png)

**I deleted the contracts** and I refreshed the page to trigger a second load:

![image](https://user-images.githubusercontent.com/87785383/169725409-e17494ae-a549-4619-99a9-0620bcd09b04.png)

Repeated the process several times: 491, 489, 495, _occasionally_ 500.

## Fix

???

## Related Issues
#2709 - Generate contracts while offline

## Scripts used
<details>
<summary> findContracts.js </summary>

```js
/** @param {NS} ns */
function getServerList(ns) {
	const servers = ns.scan("home");
	
	for (const server of servers) {
		const children = ns.scan(server);
		for (const child of children) {
			if (!servers.includes(child)) {
				servers.push(child);
			}
		} 
	}
	return servers;
}

export async function main(ns) {
	const servers = getServerList(ns);
	let contracts = 0;
	for (const server of servers) {
		const files = ns.ls(server);
		for (const file of files) {
			if (file.includes(".cct")) {
				++contracts;
			}
		}
	}
	ns.tprint(`found a total of ${contracts} contracts`);
}
```
</details>

<details>
<summary>deleteContracts.js</summary>

For deleting contracts, code is same as above, but:

```js
		for (const file of files) {
			if (file.includes(".cct")) {
				if (ns.rm(file, server))++contracts;
			}
		}
```

</details>

**Comment by phyzical** [comment]
One user had a good suggestion are you also checking `darkweb and/or w0rld_daem0n in your search` not sure if they can even get contracts but couldnt hurt.

maybe also include the script that is finding the contracts

**Comment by xRalic** [comment]
> maybe also include the script that is finding the contracts

It's at the bottom of the first message in the post, in a dropdown.

> One user had a good suggestion are you also checking darkweb and/or w0rld_daem0n in your search not sure if they can even get contracts but couldnt hurt.

This is a great point. I've started a new save, and my script now includes both ``darkweb`` and ``w0r1d_d43m0n``:

## Results 
Results: Fresh save

![image](https://user-images.githubusercontent.com/87785383/170027724-30d187c2-4d4d-4740-a46e-d5569359a42a.png)

After loading the save for the first time (``numContracts = 500``):

![image](https://user-images.githubusercontent.com/87785383/170028191-bdde6a05-5578-4094-a59a-e3b210d8d4ab.png)

After loading the save two times: 

![image](https://user-images.githubusercontent.com/87785383/170028327-662fa7bf-5e2f-4639-bd3a-a58af271d1f3.png)

After loading the save three times, however:
![image](https://user-images.githubusercontent.com/87785383/170028435-2a70a61d-f559-4866-bf91-e95d4e4a6d5d.png)

The amount seems to have hit a hard limit. I've tried refreshing or reopening the window several times, it will always net 1000 as a result. Weird.

I decided to restart the node server and try again: Same result.

## Conclusions:

1) I have apparently hit a hard limit on how many contracts can exist on the game at the same time, whereas none is specified in the code (for what I know.)

2) ``darkweb`` generates contracts. I don't think this is by design, since ``darkweb`` was recently disconnected from the network at the beginning of the game to fix a bug.

## Fix 

1) what??????

2) To stop this and future changes to the network to produce contracts on places where they shouldn't be, check if the server is connected to the network before adding a contract to it. This should be fairly straightforward.

**Comment by phyzical** [comment]
hmmmmm i think contracts being added to servers you are not connected to is actually valid imo. 

think of it as "the deeper you go, the more contracts you can solve". otherwise contracts might aswell just spawn in home 😆 

now as for them spawning in the darkweb im not sure tbh
