### ISSUE TITLE
Failed to get BlackOperation Object

### ISSUE THREAD

**Issue by micha5973** [danielyxie/bitburner#3713]
I got the following error message:

> Caught an exception: Exception caught in Bladeburner.process(): Error: Failed to get BlackOperation Object for:
> 
> Filename: UNKNOWN FILE NAME
> 
> Line Number: UNKNOWN LINE NUMBER
> 
> This is a bug, please report to game developer with this message as well as details about how to reproduce the bug.
> 
> If you want to be safe, I suggest refreshing the game WITHOUT saving so that your save doesn't get corrupted

It happened in Bitnode nr. 7. I had the bladeburner script running which can be found [here:](https://github.com/alainbryden/bitburner-scripts/blob/main/bladeburner.js). The script decided to run Operation Typhoon and when that operation finished, the given error message appeared. As far as it seems, the game runs as expected without any problems. Operation Zero appeared as the next BlackOp and Operation Typhoon is marked as completed. The attached save was made shortly afterwards.

[bitburnerSave_1653285017_BN7x1.zip](https://github.com/danielyxie/bitburner/files/8751845/bitburnerSave_1653285017_BN7x1.zip)
.

**Comment by nickofolas** [comment]
update your game from steam
