### ISSUE TITLE
Too many calls to tprint hang the game

### ISSUE THREAD

**Issue by alexanderabramov** [danielyxie/bitburner#3717]
#### Suggestion
It would be useful to by default throttle calls to tprint / tprintf to levels that the game itself can handle without freezing / hanging.
Or to provide an API to enable such throttling.
Or to make these functions awaitable.

#### Context
I've accidentally logged too many debug/warning lines to the in-game terminal (tprint / tprintf), which lead to it becoming unresponsive and eventually the restart popup appearing. It was just 1 line per misbehaving worker, but there were in excess of 1000 workers running.

I've fixed this by adding throttling to my script along the lines of:
```
const terminalState = {};

export async function main(ns) {
  while (true) {
    terminalState.budget = 5; 
    for (many workers) {
      if (something is wrong) {
        tprintf(ns, 'this is bad');
      }
    }
    await ns.sleep(1000);
  }
}

function tprintf(ns, format, ...values) {
  if (terminalState.budget < 0) {
    return;
  }
  if (terminalState.budget === 0) {
    ns.tprint('WARN throttling terminal');
    terminalState.budget = -1;
  }
  if (terminalState.budget !== undefined) {
    terminalState.budget -= 1;
  }
  ns.tprintf(format, ...values);
}
```

Steps to reproduce:
- call ns.tprint more than 1000 times
- observe unresponsiveness

```
/** repro.js */
export async function main(ns) {
	const lines = 10000;
	for (var i = 0; i < lines; i++) {
		ns.tprint(i);
	}
}
```

Version: Bitburner v1.7.0 (837cceba) (Steam)

**Comment by phyzical** [comment]
i think if you also added a sleep of say 1 ms int he for loop you might find it helps

**Comment by alexanderabramov** [comment]
> i think if you also added a sleep of say 1 ms in the for loop you might find it helps

I beg to differ.

If one adds a 1ms sleep in a sync loop with let's say 2000 iterations, it will now take at a minimum 2 seconds to execute instead of a few ms, regardless of how many times tprint is used. Additionally, ns.sleep is async, and indiscriminately using thousands of async calls in sync code will just make it much slower.

From my understanding, the slow down is purely caused by the calls to ns.tprint/tprintf, not by the other code in the loop. When I short-circuit tprint calls as shown in the ticket, the slowdown seems to disappear.
Although it's difficult to be completely sure without profiling and I don't know how to profile the Steam client.

If you run the repro, you can see a stark difference between 1000 tprints and 10000 tprints. I'd guess the slowdown only starts once tprint needs to push old terminal history out of the buffer. Perhaps some string manipulation can be optimized there.

**Comment by phyzical** [comment]
@alexanderabramov if your up for it, you can try profiling via the web based app to confirm your suspicious.

(not saying theres nothing wrong with the underlying function of tprint, was more of a "workaround" to avoid the freeze/lockup itself)

**Comment by hydroflame** [comment]
OP is right but that's just the technology we use. I don't think this can be fixed.
