### ISSUE TITLE
[Feature Request] A Function to Get an Exported Save File String

### ISSUE THREAD

**Issue by jojotastic777** [danielyxie/bitburner#3718]
Being able to get a save string, like what is written to a file when using the "Export Game" button on the Options screen, or the "Backup Save" button on the Augmentations screen, would allow for automated save backups when paired with an external http server.

**Comment by phyzical** [comment]
seems reasonable but
is this a request for a new web server api function to get save file as string?
or a ns function that returns this string?

if the latter we could make the existing ns function take in an optional param which is say format.

could take zip/json/string as the output expectation and have it default to zip to preserve existing functionality

**Comment by jojotastic777** [comment]
My thought was an ns function. Honestly, I hadn't even *thought* of making it a api feature, personally.
