### ISSUE TITLE
UI (minor): Inconsistent colors of reputation gains on Install Augmentations screen

### ISSUE THREAD

**Issue by alexanderabramov** [danielyxie/bitburner#3719]
Reputation gains are green, not white, so they blend in and are easy to miss.
![image](https://user-images.githubusercontent.com/96938/169834566-2e71620d-6a22-4614-b2c2-b0cbba173995.png)
Stats screen:
![image](https://user-images.githubusercontent.com/96938/169834789-ddad0245-329d-4f85-9845-75fa57e421c6.png)

Version of the game: Bitburner v1.7.0 (837cceba)

**Comment by phyzical** [comment]
cc @nickofolas

**Comment by nickofolas** [comment]
will take care of
