### ISSUE TITLE
BlackOps finish error

### ISSUE THREAD

**Issue by PaintedGauthier** [danielyxie/bitburner#3726]
- [ ] Save file - json file attached as .txt

- [ ] scripts i had running ( /simple.stock.js /trickle.js /heavy.js /bladeburner/run.js
  i think none need to be running though

- [ ] Version of the game,  v1.7.0 (b71418b0)

- [ ] Steps to reproduce
 - sleeve probably set as it is in the save, or blade burner diplomacy.
 - run a black ops mission (the save should have red-dragon, which duplicated the error as i tried it)
 - wait for the black ops to finish (succeed ive gotten the problem, i havent failed yet)
 
3 times on a black ops finish, i got the error at the bottom of this report 
Red-dragon mission finishes, but does not report to the bladeburner output. 
instead the error pops up

My scripts abuse the document[stuff here] pretty hard, but i dont think that could be the cause of the issue.
If it is , shame on me (and this is total user error). However the first few black ops went fine, i think it has something to to with this last update.

Caught an exception: Exception caught in Bladeburner.process(): Error: Failed to get BlackOperation Object for:
Filename: UNKNOWN FILE NAME
Line Number: UNKNOWN LINE NUMBER
This is a bug, please report to game developer with this message as well as details about how to reproduce the bug.
If you want to be safe, I suggest refreshing the game WITHOUT saving so that your save doesn't get corrupted

[bitburnerSave_1653330343_BN10x1.json.txt](https://github.com/danielyxie/bitburner/files/8757244/bitburnerSave_1653330343_BN10x1.json.txt)

**Comment by xRalic** [comment]
I reckon this issue was fixed by #3710, 9a2c743. 
Try updating to the newest version, should be v1.7.0 ``837cceba```.

**Comment by PaintedGauthier** [comment]
Yes, updating totally solved that. Didnt realize you released so fast. Sorry for wasting your time on solved issues.
