### ISSUE TITLE
Calling non-async functions in Array.prototype.map() triggers an infinite loop runtime error

### ISSUE THREAD

**Issue by Infinite-Trial** [danielyxie/bitburner#3727]
Version: Bitburner v1.7.0 (837cceba)

Since the newest update its no longer possible to use some functions inside Array.prototype.map() without causing a run time error.

The issue only occurs if the array has more then 1000 elements.
It can be reproduced with:
```
let x = new Array(5000).fill(0)
x = x.map(_ => ns.singularity.getOwnedAugmentations())
```

Its not limited to singularity functions since it also triggers with:
ns.gang.getBonusTime() and
ns.sleeve.getInformation(0)

Some functions like the following seem fine so not all are affected.
ns.isLogEnabled("sleep") and
ns.formulas.reputation.calculateFavorToRep(0)

Example error:
> RUNTIME ERROR
> temp.js@home (PID - 94)
> 
> Infinite loop without sleep detected. 1000 ns functions were called without sleep. This will cause your UI to hang.
> stack:
> Error: Infinite loop without sleep detected. 1000 ns functions were called without sleep. This will cause your UI to hang.
> at value (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:406962)
> at Object.getOwnedAugmentations (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:1:307868)
> at home/temp.js:13:32
> at Array.map ()
> at Module.main (home/temp.js:13:8)
> at executeJSScript (file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Bitburner/resources/app/dist/main.bundle.js:19:101217)

**Comment by vladtepesch** [comment]
same problem like here: https://github.com/danielyxie/bitburner/issues/3686
threshold 1000 is way to small.
should be 100000 or so - as a safety net a small gui freeze may acceptabe but atm this feature is not usable without much hassle on writing simple scripts that just do a single thing without loop - there it does not matter if they run 1s or 2s.

for example sorting some list with an ns-function within the compare-function.

**Comment by hydroflame** [comment]
What's the piece of code?

**Comment by vladtepesch** [comment]
> What's the piece of code?
> 
> 100k calls would be the same as just letting the game crash completely.

what?
I guess the limit is more in the range of 10-100m. and a small hang seems acceptable to prevent a complete crash but otherwise no interference with normal scripts.
maybe increment the counter different amounts, depending on the computational cost of the called ns-functions.

on the other hand, this only captures loops that involve ns-functions. pure logic algorithms (eg for contract solving) still has a huge potential for (virtually) endless loops

some measurements with different subsequent ns-function calls:

```
/** @param {NS} ns **/
export async function main(ns) {
  ns.disableLog("ALL");
  let n = 10;
  let sum = 0; // not know if required because if or how optimization is done
  ns.tail();
  while(true){

    let sT = Date.now();
    for(let i=0; i< n; ++i){
      let t = ns.growthAnalyze('ecorp',n, 2) ;
      sum += t;
    }
    let d = Date.now()-sT;
    ns.print("Duration n=",n, ": ", Math.round(d/1000), 's');
    if(d > 5*1000){
      break;
    }
    n = n*10;
    await ns.sleep(100);
  }
  ns.print(sum);
}
```

```
Duration n=10: 0s
Duration n=100: 0s
Duration n=1000: 0s
Duration n=10000: 0s
Duration n=100000: 0s
Duration n=1000000: 0s
Duration n=10000000: 2s
Duration n=100000000: 26s
```
tested with FF and edge
