### ISSUE TITLE
[Bug / Feature]: Sleeve augmentation costs are not affected by bitnode multipliers.

### ISSUE THREAD

**Issue by Vic1970** [danielyxie/bitburner#3734]
Bitburner 1.7.0 (837cceba)
I am in Bitnode 10, where augs are 500% cost.  

When I look at (for example) Brachiblades in the Syndicate aug screen, they cost 450 million.

When I look at Brachiblades as listed in the augmentation section of a duplicate sleeve, they are being offered for $90 million.

This difference applies to all of the augmentations I have access to.

It appears that the Bitnode multiplier for augmentation cost is not being applied to sleeve augmentation.
Likely a simple fix - if I find the right bit of code I'll link a pull request, but otherwise over to wiser heads.

**Comment by phyzical** [comment]
i believe this is valid as sleeves only use the Aug base cost for price (though i may be confusing the bitnode multiplier with the augmentation queue multiplier to cost)

**Comment by borisflagell** [comment]
I've always assumed it to be by design. Like with grafting.

**Comment by Vic1970** [comment]
@phyzical I think you might be mixing the two.  The docs state that sleeve aug cost multipliers (for already having bought augs) are separate from player aug cost multipliers and this appears to be working as intended.

 I am referring to the characteristics of different bitnodes that apply multipliers to attributes, experience, (almost everything else) and also augmentation cost and rep requirement.  I just changed bitnodes, but I will post screenshots once sleeve shock reaches 0.

**Comment by Vic1970** [comment]
@phyzical here you go: 
Sleeve aug cost (none bought yet)
![image](https://user-images.githubusercontent.com/12029663/170197994-9cbaad87-c4be-4f42-b3d8-3fa64f8285f2.png)

Player aug cost (none bought yet)
![image](https://user-images.githubusercontent.com/12029663/170198105-dbd459c3-ffe6-4580-ac29-4de25b8e3840.png)

Bitnode multipliers showing the 500% aug cost multiplier that is being applied to player augs but not sleeve augs.
![image](https://user-images.githubusercontent.com/12029663/170198533-e8bf5c6d-995f-42e4-a830-34a1984a30bf.png)

**Comment by Vic1970** [comment]
> I've always assumed it to be by design. Like with grafting.



> I've always assumed it to be by design. Like with grafting.

Sorry Boris, I don't know anything about grafting yet.  Is the cost different/do bitnode multipliers not apply to augs acquired by grafting?

**Comment by phyzical** [comment]
@Vic1970 yepp the multipliers should apply as you expect, just the augmentation cost is not applied.

https://github.com/phyzical/bitburner/blob/dev/src/PersonObjects/Sleeve/ui/SleeveAugmentationsModal.tsx#L55

i double checked to before the last set of changes around aug costs also and seemed to always use "baseCost" and never applied the BN multiplier for costs to sleeves

https://github.com/phyzical/bitburner/blame/c3a3994658c227568ea5283a8a4e39ab924e0fd1/src/PersonObjects/Sleeve/ui/SleeveAugmentationsModal.tsx#L69

**Comment by borisflagell** [comment]
> > I've always assumed it to be by design. Like with grafting.
> 
> Sorry @borisflagell, I don't know anything about grafting yet. Is the cost different/do bitnode multipliers not apply to augs acquired by grafting?

Yep, Grafting has its own x3 multiplier. Independent from the Bitnode multiplier.
Incidently, grafting is part of the same bitnode as sleeve. So, it should be available to you already . Go to vitalife in New Tokyo :-)
