### ISSUE TITLE
[Bug] Floating Point math rounding errors all over since 1.7.0 update

### ISSUE THREAD

**Issue by deuspayne** [danielyxie/bitburner#3735]
> [home ~/]> expr 26.6 + 66.7 + 6.7
> 100.00000000000001

Seems to be a lot of Floating Point errors lately. Show up a lot with odd numbers, but now it's showing up all the time even with relatively simple floats.

Occurs in: Bitburner v1.7.0 (837cceba)

**Comment by hydroflame** [comment]
That's what float do. Nothing changed.

**Comment by deuspayne** [comment]
Are you sure nothing changed? My scripts never used to fail trying to add up 3 numbers to equal 100. And now they fail all the time.
I see it all over the place too. Adding up the memory used always used to give nice round numbers, now they all list as "130974.50000000007 GB". Prior to 1.7 release, it seemed like there was some normalizing of the weirdness in javascript float imprecision that is now gone.
