### ISSUE TITLE
UI: Overview conflicts with Augmentation purchase and other dialogs

### ISSUE THREAD

**Issue by alexanderabramov** [danielyxie/bitburner#3736]
When purchasing augmentations, one would want to both read their description and see remaining money.

But expanded Overview partially overlaps the purchase dialog and augmentation description even when the window is maximized to e.g. 2560x1380. Which forces the user to repeatedly minimize/maximize the overview.

![image](https://user-images.githubusercontent.com/96938/170010883-2e2d8443-2f7c-4aa0-869c-3aee7a9b61c9.png)

Perhaps there is a design solution here to make all popup dialogs (also faction join, story messages etc) respect the overview once more than X horizontal screen space is available?

Bitburner v1.7.0 (837cceba) (Steam)

**Comment by hydroflame** [comment]
It's also draggable. You could just move it at the bottom for a second.
