### ISSUE TITLE
(Beta) Type errors less helpful now

### ISSUE THREAD

**Issue by typicalTYLER** [danielyxie/bitburner#375]
In v0.39.1, running this program:
`[].length()`
gives you this error:
![image](https://user-images.githubusercontent.com/6762150/43099667-7eb92aa6-8e88-11e8-81e7-c30f5ec3aeea.png)
While not extremely helpful, it at least gives a line number.

But in v0.40.0, running the same program gives you this error:
![image](https://user-images.githubusercontent.com/6762150/43099565-310f65e0-8e88-11e8-9987-29669d695c82.png)
Which baffled me for a while when I got this error in a long program, cause it has no line number, after forgetting that javascript array length is an attribute and not a function.

**Comment by danielyxie** [comment]
Nothing I can do about the text in the type error, but line numbers were added (for most errors) in v0.40.0
