### ISSUE TITLE
[Documentation] Additional Duplicate Sleeve documentation is inconsistent

### ISSUE THREAD

**Issue by Vic1970** [danielyxie/bitburner#3750]
As at 25 May 2022, [bitburner/sleeves.rst](https://github.com/danielyxie/bitburner/blob/master/doc/source/advancedgameplay/sleeves.rst)  discusses the methods of gaining [additional duplicate sleeves](https://github.com/danielyxie/bitburner/blob/master/doc/source/advancedgameplay/sleeves.rst#obtaining-duplicate-sleeves) and of [increasing sleeve memory](https://github.com/danielyxie/bitburner/blob/master/doc/source/advancedgameplay/sleeves.rst#memory).  The paragraph on memory refers back to the duplicate sleeve paragraph:

 **"Just like the ability to purchase additional sleeves, this is only available in BitNodes-10 and above, and is only available after defeating BitNode-10 at least once."**

This is different information from the additional sleeve paragraph, which states (typo as per the original - suggests a previous edit?)

**Purchase Duplicate Sleeves from [:ref:`the faction The Covenant <gameplay_factions>`](https://github.com/danielyxie/bitburner/blob/master/doc/source/advancedgameplay/sleeves.rst#id3). This is only available in BitNodes-10. Sleeves purchased this way are permanent**

I have not yet purchased sleeves or memory from the covenant, having just destroyed BN10 for the first time.  Depending on which part of the documentation is correct, I can: 

- either only buy memory and sleeves in BN10 **OR** I can buy memory and sleeves in any BN numbered 10 or above.
- either only buy memory and sleeves after beating BN10 at least once **OR** I can buy memory and sleeves in BN10 before beating it for the first time.
- Alternatively I can buy sleeves under one set of conditions and memory under another?  

I'm happy to submit a PR to update the doco if someone can tell me which of the alternatives is correct.

**Comment by borisflagell** [comment]
You can only buy memory and sleeves in BN10, regardless of having beat it already or not. 

In all other Bitnode, the "Purchase sleeve" button is hidden.
