### ISSUE TITLE
Unable to connect directly from one purchased server to another, despite being unable to backdoor own servers

### ISSUE THREAD

**Issue by futureneur0** [danielyxie/bitburner#3751]
In the terminal, when trying to connect from one purchased server to another, you must connect to home in between. If you cannot backdoor purchased servers, you should be able to connect to them from servers other than your home (as if they had a backdoor) without the middle step of connecting to home. 

Unsure if this is new. Version 8159dad5

**Comment by phyzical** [comment]
im pretty sure this is possible, just to confirm are you sure you were not trying to connect to a server that was out of reach of the current connected server?

**Comment by futureneur0** [comment]
I was trying to connect from one purchased server to another to killall (still don't have Source-file 4 so I had to do it manually), but when I was in "pserv-0" and tried to "connect pserv-1", I got the "Cannot directly connect to pserv-1. Make sure the server is backdoored or adjacent to your current Server". Then I connected to home, then connected to pserv-1 without a problem. 

![image](https://user-images.githubusercontent.com/106228557/170301238-e0469206-a8ee-4985-a61a-1cbb171ec9d1.png)

**Comment by phyzical** [comment]
hmm the private servers should proably be on the same network but its possible code wise atm they are like so

home--> ps-1
home --> ps-2

you should be able to confirm by doing scan on each one to see what they can see 

now if this is the case and is correct not 100% sure

**Comment by futureneur0** [comment]
I feel like an easy solution to this is to set backdoor to true on purchased servers automatically. Then it acts like a server that is backdoored and you can still keep the code that prevents a manual backdoor.

**Comment by phyzical** [comment]
good thought 👍
