### ISSUE TITLE
Coding contract "Proper 2-Coloring of a Graph" does not accept empty array as solution, insists on a literal string "[]"

### ISSUE THREAD

**Issue by holgero** [danielyxie/bitburner#3755]
When my contract solver returned an empty array as solution for a 2-colorung contract that didn't have a proper coloring, it failed. (My
debug output showed, that it supplied as solution the empty array.)

I then checked that there indeed was no solution (graphs contained [2,7], [2,5] and [5,7]), the answer was correct.

Then I tried it in the UI, entering nothing in the solution field (this usually also denotes the "empty" solution in other contracts), this didn't work, too. Finally I entered in the UI the string "[]" and the answer was accepted.

My expectation was that the empty array as a solution from a script should be accepted as correct answer.

Unfortunately I don't have a save file with that contract alive.

- [x] Version of the game, e.g. Bitburner v1.7.0 (837cceba)

**Comment by ealmen** [comment]
I just had this issue as well, and this is not fixed. Or am I missing something here?

From the contract: "If it is impossible to construct a 2-coloring of the given graph, instead submit an empty array."

But the contract doesn't accept a an empty array ([]) via API. It accepts two strings ("" and "[]"), but that isn't what the contracts says you should submit

Either change the code so an empty array is accepted, or change the wording in the contract, right?

**Comment by phyzical** [comment]
@ealmen just to confirm are you still having the issue in dev or the current steam/web version?

**Comment by ealmen** [comment]
Ah, sorry. It's in the stable web version. v2.0.2 (3067703c), running in chrome.

**Comment by phyzical** [comment]
i think there was a fix for this that has been merged into dev, if the next version doesnt fix this feel free to post here to let us know

**Comment by ealmen** [comment]
Will do!
Sorry, I thought the commit above had reached stable. New to the game and new to GitHub...
