### ISSUE TITLE
Can't read or write .script files

### ISSUE THREAD

**Issue by typicalTYLER** [danielyxie/bitburner#376]
This is less of an issue, and probably more of a feature request, but I was attempting to write a script that would modify another script and then run it (as a RAM optimization).

But after writing the whole set of scripts, I was saddened to realize the read() and write() functions only work for text files, which makes this impossible.

Would it be possible to allow the user to read and write .script files?

**Comment by Alxandr** [comment]
And JS files. I just wrote a script to sync my script files from github, and I ended up with a bunch of `.js.txt` files. I really need this functionality.

**Comment by danielyxie** [comment]
Added in v0.40.4. Let me know if there are any issues with it
