### ISSUE TITLE
After installing augments, I can still 'buy' from darkweb even if I haven't purchased tor from a vendor.

### ISSUE THREAD

**Issue by hometoast** [danielyxie/bitburner#3770]
I just started BN1x2, and after installing augmentations, I can immediately issue `buy -l` and `buy BruteSSH.exe` , etc .

This is a fresh start and I've only redpilled once from BN1.

version: Bitburner v1.7.0 (8159dad5)
save: 
[bitburnerSave_1653587593_BN1x2.zip](https://github.com/danielyxie/bitburner/files/8781064/bitburnerSave_1653587593_BN1x2.zip)

**Comment by phyzical** [comment]
this has been resolved in dev. will work as expected next release 👍
