### ISSUE TITLE
New Sleeves+Bladeburner  does not support multiple Bladeburner contracts, but UI does

### ISSUE THREAD

**Issue by alainbryden** [danielyxie/bitburner#3773]
While it's possible to assign up to 3 sleeves up to 3 different contracts in the UI, the API only lets you assign one:
![image](https://user-images.githubusercontent.com/2285037/170610347-cfd3eda5-baec-4250-a7e7-b9e72b6de270.png)

The error thrown is:
> Sleeve 1 cannot take of contracts because Sleeve 0 is already performing that action.

(which has a typo in it by the way: "take of contracts" instead of "take on contracts")

**Comment by borisflagell** [comment]
Known issue. Fixed by #3739
