### ISSUE TITLE
destroyW0r1dD43m0n gives no achievments

### ISSUE THREAD

**Issue by Markus-D-M** [danielyxie/bitburner#3777]
Version: v1.7.0 (8159dad5)
When finishing a node via destroyW0r1dD43m0n, it gives no achivments.
Steps to reproduce: 
- Open attached savegame
- run /destroyWorld.js -> no achievement :(

- Open attached savegame
- hack w0rld_d43mon -> get bn3+ achievement :)

Maybe the destroyWorld.js script is deactivated by a return statement - so remove it first.

[bitburnerSave_1653660061_BN3x4.zip](https://github.com/danielyxie/bitburner/files/8787277/bitburnerSave_1653660061_BN3x4.zip)

**Comment by phyzical** [comment]
@Markus-D-M did you happen to provide "next node param"?

if so its due to how achievements are rewarded on the BN screen and we might need to add some more logic

**Comment by Markus-D-M** [comment]
yes, I provide next node and callback script. I know that achievements are calculated in the bitverse, but this is not the expected behaviour for a player :)

**Comment by phyzical** [comment]
yepp thanks for confirming 👍
