### ISSUE TITLE
(Beta) sprintf named arguments not working

### ISSUE THREAD

**Issue by typicalTYLER** [danielyxie/bitburner#378]
This code works in live v0.39.1

`tprint(sprintf("hackmult = %(money)3.4f;\r\n", getHackingMultipliers()));`

but in the beta v0.40 the same code throws this error:
![image](https://user-images.githubusercontent.com/6762150/43102213-15be0e6a-8e90-11e8-8bae-ea9b5ecac8a8.png)

I also tried adding a layer of indirection but still get the same error:
```
autohack_multipliers = {
    money: getHackingMultipliers().money,
};

tprint(sprintf("hackmult = %(money)3.4f;\r\n", autohack_multipliers));
```

Although the second script doesn't work in live, and I get this error:

`Unrecognized token: ObjectExpression. This is currently unsupported in Netscript (Line 1)`

**Comment by danielyxie** [comment]
Should be fixed in v0.40.0. If not, reopen
