### ISSUE TITLE
(Beta) NaN manual hack time

### ISSUE THREAD

**Issue by typicalTYLER** [danielyxie/bitburner#379]
Tried to hack CSEC but the hack time is NaN, not sure why this could've been so just dumping info about my game.

![image](https://user-images.githubusercontent.com/6762150/43103135-c6b769e4-8e92-11e8-8dba-b7014c8cf0e2.png)
![image](https://user-images.githubusercontent.com/6762150/43103224-0446aaea-8e93-11e8-81d5-dde88f1bbac1.png)

Looks like my script I had running on the CSEC server got stuck in an infinte NaN hack loop:
![image](https://user-images.githubusercontent.com/6762150/43103334-549424f0-8e93-11e8-9840-f6bec6c4ba60.png)

Script hack of NaN time takes 0 seconds to run, but manually it doesn't run at all. I imagine you'll just have to add some NaN safety checking somewhere though.

**Comment by typicalTYLER** [comment]
Also happening on avmnite-o2h, but not neo-net. Maybe it has something to do with them being the servers you have to manually hack once?

**Comment by hydroflame** [comment]
Can you upload your save file ? It's impossible to know without.

**Comment by typicalTYLER** [comment]
After importing the save, refresh the page and manually hack avmnite-02h until it fails once or twice, then it'll get stuck on NaN manual hacks:
![image](https://user-images.githubusercontent.com/6762150/43148498-0be4e968-8f2b-11e8-822f-64884c932325.png)

[NaN Manual Hack Save.zip](https://github.com/danielyxie/bitburner/files/2224265/NaN.Manual.Hack.Save.zip)

I also found that if I don't refresh after importing a game, the terminal doesn't even show up, even though some of my other running scripts will tprint after a while, I still can't type. Should I file a separate issue for this?
![image](https://user-images.githubusercontent.com/6762150/43148590-39fcf610-8f2b-11e8-9499-821bec19b99f.png)

**Comment by danielyxie** [comment]
This is a bug in both beta and the game

These servers have no money, which at one point can lead to a `0/0` operation (aka NaN).

Should be fixed in beta, although you'd have to do a reset through installing Augs or Soft Reset so that the server's data gets reset to normal.

**Comment by danielyxie** [comment]
Should be fixed in v0.40.0. If not, reopen
