### ISSUE TITLE
defcomm and iron-gym share an ip address

### ISSUE THREAD

**Issue by SolarVampire** [danielyxie/bitburner#3803]
EDIT: I've since learned that ips change on reset. But that would mean that during a reset the game is assigning two different servers the same ip address. Must have been a slim chance, but it happened, can happen.

![image](https://user-images.githubusercontent.com/103239537/171108388-334fd515-5d09-45bb-b179-e177078e3ec5.png)

Bitburner v1.7.0 (00adc2ff)
- [ ] I don't upload save files.
- [x] Script: 
```
/** @param {NS} ns */
export async function main(ns) {
	const irongym = ns.getServer("iron-gym");
	const ip = ns.getServer("61.7.8.3");
	const defcomm = ns.getServer("defcomm");
	console.log(irongym);
	console.log(ip);
	console.log(defcomm);
	ns.tprint(irongym);
	ns.tprint(ip);
	ns.tprint(defcomm);
}
```
- [x] Run this script and you will see that the ips conflict. I can't share the entire framework that discovered the bug, but this script will at least show you the results.
- [x] Bitburner v1.7.0 (00adc2ff)

**Comment by SolarVampire** [comment]
Well, I guess that means the bug is that the game can assign one ip address to two different servers, in general.

**Comment by deuspayne** [comment]
I actually believe another open issue (#3765) is related to this.

`Uncaught (in promise) Error: Error: Trying to add a server with an existing IP`

seems to be an error related to importing a save file where servers with duplicate IP addresses fail.

**Comment by SolarVampire** [comment]
Interesting. That's beyond my scope, I'm relatively new. I'll keep my eyes open for things related to that topic as well now though. If a fix isn't found we might be given a button in settings that reassigns all of the IPs? For debugging at the very least. It would surely break something else in the game. For the time being I'll just stick to host names for my world. If I had to guess that my problem specifically stems from the reassignment algorithm. 
I have a large number of backups to debug with if my situation turns into their situation. :salute:
I wonder if this happens on brand new accounts ever? Are the IPs statically assigned for a new game? If not, are both the new game initialization and the augment reset algorithms the same?

**Comment by crimsonhawk47** [comment]
> 

I'm inclined to think the issue you linked is not related to this one. The game seems perfectly fine launching when `createRandomIp` returns the same IP address. 

I've opened a PR to fix this bug
