### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'playerReputation') (at "Work")

### ISSUE THREAD

**Issue by ridilculous** [danielyxie/bitburner#3809]
Bitburner v1.7.0 (00adc2ff)

Don't really know how and exactly when the error was caused. It showed when the script "workMegacorps.js" got executed.

[RECOVERY_BITBURNER_1654116025.zip](https://github.com/danielyxie/bitburner/files/8818695/RECOVERY_BITBURNER_1654116025.zip)
.

I could work around by editing the corrupt save game and disabling the company work there.
Afterwards, i was able to reproduce the problem once with "workMegacorps.js" (but i guess some other running scripts are required for reproduction); the working company was empty or undefined.
But now trying the same again i cannot reproduce it anymore; tried to run each script separately together with "workMegacorps.js" but there's always a valid company name.

**Comment by Herzfinsternis** [comment]
[https://github.com/danielyxie/bitburner/issues/3830](3830)
> Steps to reproduce:
> 
> 1. Create brand new game
> 2. Apply for a job inside any company, (joe's guns will do)
> 3. Click "Work"
> 4. Click "Do something else simultaneously"
> 5. Quit your job while it's running in the background

**Comment by ridilculous** [comment]
Fix savegame:

`base64 --decode RECOVERY_BITBURNER_...json > RECOVERY_BITBURNER_..fixed.txt.json`

Open for editing, replace `\"isWorking\":true` with `\"isWorking\":false` and save.

`base64 RECOVERY_BITBURNER_..fixed.txt.json > RECOVERY_BITBURNER_...json`
