### ISSUE TITLE
TypeError: String.fromCharCode is not a function (at "ScriptEditor")

### ISSUE THREAD

**Issue by bobillian** [danielyxie/bitburner#3817]
### How did this happen?

I was creating a script to build a multidimensional array, and simply testing a single dimensional array function.

- [ ] Save file
- [var servers = ns.scan(ns.args[0])
- const serverlist = [servers]
- ns.tprint(servs.findIndex(String = "n00dles" ] Minimal scripts to reproduce the issue
- [ Just run the script.] Steps to reproduce

### Environment

* Error: TypeError: String.fromCharCode is not a function
* Page: ScriptEditor
* Version: v1.7.0 (00adc2ff)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

[bitburner recovery file.zip](https://github.com/danielyxie/bitburner/files/8835820/bitburner.recovery.file.zip)

### Save
```
Copy your save here if possible
Could not find my save file. but here is the recovery file. [bitburner recovery file.zip](https://github.com/danielyxie/bitburner/files/8835820/bitburner.recovery.file.zip)

**Comment by stalefishies** [comment]
`String = "n00dles"` sets the internal String javascript object to `"n00dles"`, which will cause all String methods to break.

You probably want something like `servs.findIndex((str) => str === "n00dles")`

**Comment by bobillian** [comment]
> `String = "n00dles"` sets the internal String javascript object to `"n00dles"`, which will cause all String methods to break.
> 
> You probably want something like `servs.findIndex((str) => str === "n00dles")`
That was definitely my issue, thanks!
