### ISSUE TITLE
window.open allows executing files on the system

### ISSUE THREAD

**Issue by DaXcess** [danielyxie/bitburner#3822]
## Tested versions: 
* Bitburner v1.7.0 (00adc2ff) (Windows)

## Description
The window.open JavaScript function call can be used within scripts to launch external programs on the user's system.
The dynamic RAM check also gets bypassed by using `eval` instead of using `window` natively, reducing RAM cost by 32GB

## Steps to reproduce
Create a new script file with nano
```
nano exec.js
```

Enter the following code:
```js
export async function main() {
    eval("window.open(\"cc:=C:\\\\Windows\\\\System32\\\\calc.exe\");");
}
```

Execute the script:
```
run exec.js
```

An instance of calculator will open up
![image](https://user-images.githubusercontent.com/46288749/172071324-b64d3b0c-7c24-4bd7-964c-c649d59e2b05.png)

## Video
https://streamable.com/e225a7

## Temporary Workaround
Write a script (or use the debug console) that no-ops the window.open function like so:
```js
window.open = () => {}
```

**Comment by Daniel-Barbera** [comment]
Thanks for taking the time to file the issue!

AFAIK, using ``eval`` to bypass the RAM cost of things like document is ""expected"" from the player [(there even is an achievement for doing a similar thing).](https://github.com/danielyxie/bitburner/blob/c21644397d5ab7e3e8a23fe2f47e7c5438661b86/src/NetscriptFunctions/Extra.ts#L25) In fact, if you look at the UI and HTML Injection channels in the official discord server, you'll see plenty of code that does exactly that.

About allowing executing external files, being a single player game, it could be considered a positive (for example, although impractical, imagine a button that opens an external IDE from inside the game).

I don't believe there's any security concerns as long as the player isn't using external code that they do not understand - at which point it's no longer the developer's responsibility. Although there's something to be said about a meaningful amount of people who are learning to code with BB, who play by using other people's scripts.

I'd love to see the others' input about this. It's an interesting issue.

**Comment by Herzfinsternis** [comment]
Bypassing RAM cost is part of the game. This is known and perhaps even intended.

The window.open-bug does not apply to the browser version of the game. Must be specific to the steam version.

**Comment by DaXcess** [comment]
> Bypassing RAM cost is part of the game. This is known and perhaps even intended.
> 
> The window.open-bug does not apply to the browser version of the game. Must be specific to the steam version.

Got it. I guess I was thrown off by an earlier popup when I tried to bypass RAM cost using ns["getServer"] which triggered a popup about a static/dynamic RAM cost mismatch (and thereby preventing the script to run).

It is indeed true that this only works on the steam (or native) version of the game. To be specific it is caused by https://github.com/danielyxie/bitburner/blob/dev/electron/gameWindow.js#L101, where the URL is opened in explorer, and because "cc:=C:\Windows\System32\calc.exe" is seen as a valid URL, it will cause it to open the supplied program.

While I agree with Daniel that this can only be caused by a user manually inputting the code that triggers this, I also agree that users new to programming might blatantly copy and paste code without knowing how it works.

Luckily it is not possible (at least AFAIK) to supply command line args using this technique.

Maybe it's an idea to check the `URL.protocol` and only allow `http:`, `https:` and `file:` protocols?

**Comment by phyzical** [comment]
yeah but how far do we take users from punching themselves 😆 they have to learn eventually

**Comment by Herzfinsternis** [comment]
> yeah but how far do we take users from punching themselves 😆 they have to learn eventually, another life lesson int he world of software (which is what i look at this game as) never blindly copy pasta, check the ingredients first

Do you check every savegame users have uploaded here? Probably not. So you might want to reconsider your attitude. Though - partly - I am with you.

**Comment by phyzical** [comment]
fair call 😆

**Comment by alainbryden** [comment]
@DaXcess Do you have any sources on this "cc:" URI scheme? I've hunted around but can't find information on it anywhere. It's not on Wikipedia's list of schemes: https://en.wikipedia.org/wiki/List_of_URI_schemes

**Comment by alainbryden** [comment]
After an [extensive chat on Discord](https://discord.com/channels/415207508303544321/928919860891750410/1014212772411736136), I'm proposing we patch this vulnerability using the advice at the end of this article:
https://benjamin-altpeter.de/shell-openexternal-dangers/

> # Defending against these attacks
>
> This post has hopefully shown that blocklisting certain protocols or similar approaches are not sufficient to defend against shell.openExternal() attacks. The only viable solution is a strict allowlist that only permits the protocols (or even particular URLs) that are actually intended to be opened.
>
> As I have said earlier, most apps really only want to open websites in the browser or maybe compose messages in the user’s email program. For these use-cases, only http(s): and mailto: need to be allowlisted:
>
 ```js
const { shell } = require('electron');

function openInBrowser(url) {
  if (!['https:', 'http:'].includes(new URL(url).protocol)) return;

  shell.openExternal(url);
}

function openInEmailSoftware(mailto_url) {
  if (new URL(mailto_url).protocol !== 'mailto:') return;

  shell.openExternal(mailto_url);
}
```

**Comment by DaXcess** [comment]
> ```js
> const { shell } = require('electron');
> 
> function openInBrowser(url) {
>  if (!['https:', 'http:'].includes(new URL(url).protocol)) return;
> 
>  shell.openExternal(url);
> }
> ```

Yes this would indeed fix the issue. I tried it on a local development test back when I discovered this. There was however still a way to run explorer with (if I remember correctly) something like `https://cc:=`, but this will always open the explorer window without arguments and is not harmful in any way AFAIK.

**Comment by phyzical** [comment]
we could also add a blacklist to start including such cases 
```
const { shell } = require('electron');

function openInBrowser(url) {
 if ["c:=","someOtherRandomViolation"].some(violation => url.includes(violation)) return
 if (!['https:', 'http:'].includes(new URL(url).protocol)) return;

 shell.openExternal(url);
}
```

**Comment by DaXcess** [comment]
> we could also add a blacklist to start including such cases
> 
> ```
> const { shell } = require('electron');
> 
> function openInBrowser(url) {
>  if ["c:=","someOtherRandomViolation"].some(violation => url.includes(violation)) return
>  if (!['https:', 'http:'].includes(new URL(url).protocol)) return;
> 
>  shell.openExternal(url);
> }
> ```

That would most likely result in false positives. Also the bug triggers on any protocol that the OS does not recognize, as long as it is at least 2 characters long (e.g. "this:=" or "aaaaaaa:=" also work).
Filtering the protocol so it's only allowed on `https`, `http` and `file` should be enough.
