### ISSUE TITLE
Megabyte burner 2000 does not start

### ISSUE THREAD

**Issue by Herzfinsternis** [danielyxie/bitburner#3825]
When I click the button labled "Megabyte burner 2000" I see a joystick and four buttons made of ASCII-art and above the load spinner and text. However, it does not seem to really load anything!?

Bitburner v1.7.0 (b60f3da8)
Google Chrome 102.0.5005.63

**Comment by Herzfinsternis** [comment]
I opened the Chrome DevTools and tried again. Threw an exception.

    Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
        at loadGame (https://bitburner-official.github.io/bitburner-legacy/dist/bundle.js:91297:17)
        at Object.load (https://bitburner-official.github.io/bitburner-legacy/dist/bundle.js:4890:86)
        at window.onload (https://bitburner-official.github.io/bitburner-legacy/dist/bundle.js:5429:12)

Hope that helps.

**Comment by Herzfinsternis** [comment]
It showed up in Edge after importing a savegame someone else uploaded here. I guess, I will have to do some more testing to provide more information.

**Comment by Snarling** [comment]
Does the game load if you just go directly to https://bitburner-official.github.io/bitburner-legacy/ in another tab?

**Comment by Herzfinsternis** [comment]
> Does the game load if you just go directly to https://bitburner-official.github.io/bitburner-legacy/ in another tab?

Yes, it does.

**Comment by Snarling** [comment]
Based on the error message you're getting, your browser is not allowing the iframe (where it's loading the old-game) to access localstorage. I would say it might be a weird security setting you have enabled, but it looks like you've reproduced this issue on both Chrome and Edge so I'm not sure how likely that is. Or were you saying it works fine in Edge, and only doesn't show in Chrome?

**Comment by Snarling** [comment]
Based on https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni
It looks like the issue might be Chrome's Settings > Privacy > Content settings -> "Block sites from setting any data"

**Comment by Herzfinsternis** [comment]
Works fine now! :-)
Thank you!
