### ISSUE TITLE
Purchasing too many Reduce Minimum Security for a server results in most server information being unusable (NaN for ns.getGrowTime, -1 for getServerSecurityLevel etc...)

### ISSUE THREAD

**Issue by wchevalier** [danielyxie/bitburner#3828]
Steps to reproduce : 
load save (dont need any scripts running)
augment
max out hacknet nodes 
buy 194  Reduce Minimum Security for ecorp 
run ServerProfiler.exe ecorp

here is the before and after the purchase:
![image](https://user-images.githubusercontent.com/97134273/172582030-dd2bc189-2d4a-4970-8210-de176f9c153c.png)

- [Bitburner v1.7.0 (00adc2ff)

(Steam)  ] Version of the game, e.g. Bitburner v1.7.0 (00adc2ff)

[bitburnerSave_1654679982_BN12x7.zip](https://github.com/danielyxie/bitburner/files/8860217/bitburnerSave_1654679982_BN12x7.zip)

**Comment by phyzical** [comment]
are you sure you dont have any scripts running that are also hacking? and just so happen to cap out the security level as NAN mean its hit infinity, doesnt really have much todo with the current security level, rather once your at the max you will see NAN 

based on the code it will never allow the minimum  to get below 1 anyway

```
    // Server security cannot go below 1
    this.minDifficulty = Math.max(1, this.minDifficulty);

**Comment by wchevalier** [comment]
That's the thing the server couldn't have hit inf, I had reduced the security level of the server below 0. I also found it actually doesn't even need the Reduce Minimum Security purchases after a couple more augs just hacking level would produce the same issue, keep in mind this is after hacking level gets above 7e12.  I totally get this is an edge case, I was just working on some of my scripts long after I should have completed the node when all of a sudden I was getting thousands of errors and I was introduced to the number that isn't.

**Comment by wchevalier** [comment]
That's the thing the server couldn't have hit inf, I had reduced the security level of the server below 0. I also found it actually doesn't even need the Reduce Minimum Security purchases after a couple more augs just hacking level would produce the same issue, keep in mind this is after hacking level gets above 7e12.  I totally get this is an edge case, I was just working on some of my scripts long after I should have completed the node when all of a sudden I was getting thousands of errors and I was introduced to the number that isn't.

**Comment by Herzfinsternis** [comment]
> are you sure you dont have any scripts running that are also hacking? and just so happen to cap out the security level as NAN mean its hit infinity, doesnt really have much todo with the current security level, rather once your at the max you will see NAN
> 
> based on the code it will never allow the minimum to get below 1 anyway
> 
> ```
>     // Server security cannot go below 1
>     this.minDifficulty = Math.max(1, this.minDifficulty);
>    
> ```

`Math.max()` would return `NaN` if `this.minDifficulty` was `NaN`. Could this happen when you import a savegame?

Perhaps the easiest solution would be to cap the hacking level. 7e12 lets Nero feel like being a noob.

**Comment by wchevalier** [comment]
When I first stumbled upon the bug I had hundreds if not thousands of apps running/hacking/weakening, buying max money for n00dles and ecorp server using Hashes, as well as stanek charges, corp scripts, gang scripts etc... The save that is attached is pretty much what i was running

I just loaded it up in Chrome and after a few minutes checked ecorp and saw it was sitting at 1 security, running weaken on the command line will pushed it over the edge and it will start showing NaN and you will also lose your command line prompt unless you refresh. 
I then clicked the kill all scripts and refreshed. I added a couple print statements to the monitor.js  app I use for server monitoring as well as starting up stats.js and server-list.js (none of which does anything but displaying data ). The below screenshot shows an untouched megacorp with 148 security and the results from running ns.getServerSecurityLevel('megacorp') and ns.getServerMinSecurityLevel('megacorp') next to it is the same thing for ecorp
below that is the the server-list.js . ns.getServerSecurityLevel('ecorp'); returns null and ns.getServerMinSecurityLevel('ecorp'); returns 1. 

![image](https://user-images.githubusercontent.com/97134273/172728180-90d29114-2421-4453-abb4-ef089f7c6f37.png)

There is nothing that can be done for ecorp at this point without augmenting, weakens do nothing but lock you out of the command line (the command does finish it just doesnt let you type anything after that). 

If you want me to upload the save from the screenshot i can do that but it is only a few minutes of idling past what was already posted and what i described above. 

I don't think capping the hacking level will solve the issue since there is more than one way to get your security values into the twilight zone of numbers that aren't.

BTW it isn't hard to get insane hacking levels if you don't backdoor the w0r1d_d43m0n and just keep going.

**Comment by Snarling** [comment]
I still don't think this is an issue with the hashnet reduce min security upgrade. Min security on ecorp is still 1 in your screenshot. It's current security level that has lowered to <1 (somehow), the hashnet purchase doesn't reduce actual security.

The actual issue is whatever is allowing the current security level to drop below the minimum security level. Weakening should not be able to "push it over the edge" because the edge is actually supposed to be a wall.

**Comment by Snarling** [comment]
I could not reproduce the issue on the save you provided using the steps you provided. I ensured that no scripts were running prior to the test by running with noScripts and then reloading the page, then installed augs and performed the rest of the steps you provided.

![image](https://user-images.githubusercontent.com/84951833/174105525-cfa0ffeb-2c84-4e52-a7f2-2e8429bb9385.png)
