### ISSUE TITLE
Bitburner Bug, negative amount of money

### ISSUE THREAD

**Issue by jtam2204** [danielyxie/bitburner#3835]
<img width="960" alt="2022-06-10" src="https://user-images.githubusercontent.com/107278022/173141700-f9168d85-55e4-4899-9dd7-bca8bad0e7bf.png">

first-time augmentation, then start over.(still normal)
went to the Roth uni and took the Algorithms course($960/sec), (earning around $300/sec at the time with around $50k), 
so I thought the course would end itself if I have not enough money, but it still continued and now I have $-500k

 v1.6.3

**Comment by RadicalZephyr** [comment]
this is well known, and is probably by design. See this [pull request for a discussion of it](https://github.com/danielyxie/bitburner/pull/2949)
