### ISSUE TITLE
Have difficult to grow a server.

### ISSUE THREAD

**Issue by Neutron3529** [danielyxie/bitburner#3839]
# DELETE THIS AFTER READING

My game hangs for several times after I decided to use seperate threads rather than run script once with a large thread count.

think about a question: how much would grow after a 100 thread grow function and a grow percentage about 3%?
the game shows a (1+0.03*100)=4x grow with a single script with thread=100, but if we create 100 script with thread=1, the growth could be (1+0.03)^100 = 19.21 x.

The game encourage us to made thousands of scripts running together, but the game could hang after 10000 scripts running at once.
Actually I'm using await ns.sleep(1) to avoid the possible stuck, but it does not help avoid the hang.

It might be better to change the calculation of the grow function. otherwise you couldn't stop someone create thousands of scripts running together.

Version: All(I'm using Bitburner v1.7.0, but actually all version have the same issue)

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by stalefishies** [comment]
No, that's not how the grow mechanic works. If you use multiple threads, the effect increases multiplicatively in the number of threads, just as if you had separate scripts. But also, multiple scripts is *less* efficient since each one increases the security level, making all subsequent scripts less efficient.

**Comment by Herzfinsternis** [comment]
Sorry for beeing late...

running test with 1 threads
grow: Executing on 'sigma-cosmetics' in 10.963 seconds (t=1).
grow: Available money on 'sigma-cosmetics' grown by 0.012626%. Gained 9.147 hacking exp (t=1).

running test with 5 threads
grow: Executing on 'sigma-cosmetics' in 10.963 seconds (t=5).
grow: Available money on 'sigma-cosmetics' grown by 0.063145%. Gained 45.736 hacking exp (t=5).

running test with 20 threads
grow: Executing on 'sigma-cosmetics' in 10.963 seconds (t=20).
grow: Available money on 'sigma-cosmetics' grown by 0.252820%. Gained 182.944 hacking exp (t=20).

1.00012626^1  => 100.012626%    => grown by 0.012626%
1.00012626^5  => 100.063145944% => grown by 0.063146%
1.00012626^20 => 100.25282312%  => grown by 0.252823%

Run the following script with at least 20 threads to verfiy.

    /** @param {NS} ns */
    export async function main(ns) {
        const target = "sigma-cosmetics";

        async function fullyWeaken() {
            while (ns.getServerMinSecurityLevel(target) < ns.getServerSecurityLevel(target)) {
                await ns.weaken(target);
            }
        }

        async function hackEmpty() {
            while (ns.getServerMoneyAvailable > 0) {
                await ns.hack(target);
                await fullyWeaken();
            }
        }

        async function grow1() {
            while (ns.getServerMoneyAvailable == 0) {
                await ns.grow(target, { "threads": 1 });
            }
            await fullyWeaken();
        }

        async function testGrow(numThreads) {
            //prepare target
            await hackEmpty();
            await grow1();
            //test
            ns.print("running test with " + numThreads + " threads");
            await ns.grow(target, { "threads": numThreads }); //run 'grow' with 'numThreads' threads - script needs to be run with at least 'numThreads' threads for this to acually work
        }

        ns.tail();
        await testGrow(1);
        await testGrow(5);
        await testGrow(20);
    }
