### ISSUE TITLE
Reset corporation exports

### ISSUE THREAD

**Issue by IB-Tool** [danielyxie/bitburner#3842]
There should be a way to automatically (script, button) delete exports even if the exact values are unknown. 

I have a bug in my script that has created tons of exports that I now have to delete manually because I can't get the data or delete them otherwise.

**Comment by Mughur** [comment]
There is a way to automatically delete exports.
```js
export async function main(ns) {
	for (let div of ns.corporation.getCorporation().divisions){
		for (let city of div.cities){
			for (let material of ns.corporation.getMaterialNames()){
				for (let e of ns.corporation.getMaterial(div.name,city,material).exp){
					ns.corporation.cancelExportMaterial(div.name,city,e.div,e.loc,material,e.amt);
				}
			}
		}
	}
}
```
for example would cancel every single export that is currently set
