### ISSUE TITLE
Nitpick: incorrect message when createProgram is interrupted

### ISSUE THREAD

**Issue by nimelennar** [danielyxie/bitburner#3846]
I have a script which automatically tries to buy various port openers; it creates them if the hacking level is high enough, but it also checks every thirty seconds to see if there is enough money to buy the program outright. If not, it runs createProgram() again.

The game is reporting that SQLInject has completed successfully if createProgram is interrupted, even if the creation has not completed successfully.

My logs look like this:

    createProgram: Began creating program: 'sqlinject.exe'
    sleep: Sleeping for 30000 milliseconds
    purchaseProgram: Not enough money to purchase 'SQLInject.exe'. Need $250.000m
    createProgram: You've finished creating SQLInject.exe! The new program can be found on your home computer.
    createProgram: Began creating program: 'sqlinject.exe'
    sleep: Sleeping for 30000 milliseconds
    purchaseProgram: Not enough money to purchase 'SQLInject.exe'. Need $250.000m
    createProgram: You've finished creating SQLInject.exe! The new program can be found on your home computer.
    createProgram: Began creating program: 'sqlinject.exe'
    sleep: Sleeping for 30000 milliseconds
    purchaseProgram: Not enough money to purchase 'SQLInject.exe'. Need $250.000m
    createProgram: You've finished creating SQLInject.exe! The new program can be found on your home computer.
    createProgram: Began creating program: 'sqlinject.exe'

**Comment by ilkecan** [comment]
What is the version of the game that you are playing? e.g. "v1.7.0 (00adc2ff)"

**Comment by nimelennar** [comment]
Sorry; I meant to include that but must have forgotten.

Yes, it's Bitburner v1.7.0 (00adc2ff), via Steam.
