### ISSUE TITLE
Recovery mode activated didn't mention details

### ISSUE THREAD

**Issue by StrategicVirus** [danielyxie/bitburner#3850]
- [ ] Save file
[RECOVERY_BITBURNER_1655485030.txt](https://github.com/danielyxie/bitburner/files/8929443/RECOVERY_BITBURNER_1655485030.txt)
you may want to change the .txt to a .json if you want/need to use the file
- [ ] Minimal scripts to reproduce the issue
autobuy.ns
master.js
(other files will run from the master.js script)
- [ ] Steps to reproduce
idk I was playing the game one second then the next it came up with a black screen, trying to reopen it said recovery mode activated and there was a error with my game file then 2 mins later it came up with a black screen again
- [ ] Version of the game
1.7.0

**Comment by StrategicVirus** [comment]
Ok looking back at the issue i went back onto bitburner and did soft reset and worked just fine. Possibly that was caused by too many scripts running and my actual computer couldn't handle it?

**Comment by Snarling** [comment]
Tried running the scripts you mentioned (autobuy and then master) with the debugging window open. Execution paused with the following error: 
![image](https://user-images.githubusercontent.com/84951833/174480746-bacf85a1-67f1-420c-ba2f-eb6a5d070779.png)

And chrome was using over 3GB of ram.

So yeah it seems like whatever you're doing is very memory inefficient and is causing the browser to crash.
