### ISSUE TITLE
ctrl+c does not clear terminal input

### ISSUE THREAD

**Issue by ofsaleem** [danielyxie/bitburner#3854]
- [ ] Steps to reproduce: have "enable bash hotkeys" set (or not set, doesnt matter) in options -> misc, try to use `ctrl+c` to clear terminal input. it does nothing, regardless of either hotkey option (disable hotkeys or enable bash hotkeys) setting.
- [ ] Version of the game: Bitburner v1.7.0 (00adc2ff)

its mentioned [in the docs](https://bitburner.readthedocs.io/en/latest/shortcuts.html#terminal-bash-shortcuts) to `nano .fconf` to enable the hotkeys, but that behavior is no longer supported. and i can't figure out how to allow ctrl+c to override the global hotkey since the disable hotkeys toggle doesnt allow it

**Comment by Snarling** [comment]
It looks like this is not one of the extra bash hotkeys that is in the game.
https://github.com/danielyxie/bitburner/blob/f6e689eeadb2ed17ec2434c759e9df09ad0e6ad3/src/Terminal/ui/TerminalInput.tsx#L319
