### ISSUE TITLE
Bug while infiltrating VitaLife

### ISSUE THREAD

**Issue by WiseMack** [danielyxie/bitburner#3863]
### Environment

* Error: Error: Trying to do infiltration on invalid location.
* Page: Infiltration
* Version: v1.7.0 (00adc2ff)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=es-419 cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
[RECOVERY_BITBURNER_1656124055.zip](https://github.com/danielyxie/bitburner/files/8983734/RECOVERY_BITBURNER_1656124055.zip)

### Script
https://pastebin.com/7DuFYDpJ

###Target
VitaLife

**Comment by WiseMack** [comment]
Two possible causes
- If a script attempts to change location while infiltrating.
- If a script tries to soft reset while infiltrating.

Not sure which.

###
Using 
https://github.com/alainbryden/bitburner-scripts

**Comment by Saynt-Garmo** [comment]
Not necessarily an issue, as Infiltrations are not intended to be automated by traditional means from within the game. This sort of feat falls a little outside the normal automation methods meant for within the game.
