### ISSUE TITLE
TypeError: t is undefined (at "Work")

### ISSUE THREAD

**Issue by Trolenol** [danielyxie/bitburner#3865]
### How did this happen?
To do this bug:
1. You have to be in a job (ingame).
2. Then work.
3. Press "Do something else simultaneously".
4. Quit the job (ingame)
5. Press the Focus button.

This will result in Recovery mode with this bug, or would i say, a TypeError.

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [X] Steps to reproduce

### Environment

* Error: TypeError: t is undefined
* Page: Work
* Version: v1.7.0 (b60f3da8)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
* Features: lang=en cookiesEnabled=true doNotTrack=unspecified indexedDb=true
* Source: https://danielyxie.github.io/bitburner/dist/main.bundle.js

### Explanation
What it might be, is that the t variable is stored in shifts. And if you aren't in a shift let alone not being in a job (ingame), so it doesn't have access to the t variable, therefore causing a fatal error, which is only fatal if you don't have a save file before the triggered bug.

I found this out, on my own, while I was trying to find a job that has a lot per second, I forgot to press the "Stop working" button, and quitted out of the job (ingame), so I tried to see if it would still work even if i quitted it, it didn't.

**Comment by ilkecan** [comment]
I can reproduce this but only for full-time jobs. Quitting a part-time job as described will also finish the job.

**Comment by Snarling** [comment]
This was fixed by #3847 and can be closed.
