### ISSUE TITLE
Having servers hack each other in a circle hangs game

### ISSUE THREAD

**Issue by pludi** [danielyxie/bitburner#3868]
-    Version: Bitburner v1.7.0 (b60f3da8)
-   Steps to reproduce
    1. Load the attached save file (used script should be included)
    2. `n00dles` is already working against `foodnstuff`, which is attacking `sigma-cosmetics`, which in turn attacks `joesguns`
    3. Connect to `joesguns`
    4. `run hack-und-back.js n00dles`, completing the circle
    5. Script hangs tab
    
    Tried with Firefox

- Relevant save file (gzip'd to allow upload): [bitburnerSave_1656333863_BN1x1.json.gz](https://github.com/danielyxie/bitburner/files/8992097/bitburnerSave_1656333863_BN1x1.json.gz)
- Script used:
    ```javascript
	/** @param {NS} ns */
	export async function main(ns) {
		var server = ns.args[0];
		var hack = true;
		while (true) {
			var pct_money = ns.getServerMoneyAvailable(server) / ns.getServerMaxMoney(server);
			if (pct_money < 0.25 || !hack) {
				ns.print("*** Server: " + server + " at " + pct_money + " capacity");
				await ns.grow(server);
				hack = false;
			} else if (pct_money > 0.75) {
				hack = true;
			} else {
				await ns.hack(server);
			}
		}
	}
    ```

**Comment by Snarling** [comment]
The reason has nothing to do with "hacking in a circle" (it doesn't matter what server you run a hacking script from). The issue is that your while loop has a path (pct_money > 0.75) that is a non-correcting infinite loop with no await.
