### ISSUE TITLE
Tutorial instantly confusing

### ISSUE THREAD

**Issue by ChristopherDrum** [danielyxie/bitburner#3869]
- Bitburner v1.7.0 (b60f3da8)
![Screen Shot 2022-06-28 at 7 12 41](https://user-images.githubusercontent.com/320377/176044566-d37436f8-e7ee-467e-991e-332ac5cf7a8f.png)
 
You can see in the tutorial, after running `scan-analyze` that we are told `we can see that the nOOdles server is only one node away`. But the output for n00dles shows no such information. Or is that what `hacking skill` is supposed to be? 🤷 Either some information is missing or the tutorial needs to be reworded to explain the terminology better.

**Comment by ilkecan** [comment]
![image](https://user-images.githubusercontent.com/40234257/176319042-46609d42-b5b5-4b7b-bdaa-e8910a8b51df.png)
Note that "zer0" and "max-hardware" are indented further than "n00dles" and "foodnstuff" in this example. This Indentation reflects the distance to the current server. So the first two server are adjacent to the current server while the last two is adjacent to "foodnstuff" and has a distance of 2 to the current server.

This is somewhat similar to the output of `tree` command in Unix.

**Comment by Sheltraks** [comment]
There is a couple of confusing/unknown stuff in the tutorial for non-coders.
E.g. The "ls" command is an already shortened alias for "list"
Everything obviously is developed with rudimentary coding-knowledge in mind.

**Comment by OneOfMany07** [comment]
My issue is the tutorial covering the text I'm supposed to read when the window is half the width of my screen (might differ for full screen).  I knew I had to minimize the tutorial and scroll up/down sometimes.  Adding a way to limit output initially might be useful.  Like only show 1 server from the command using "head" after piping into it (don't know if that's supported here, but it's a *nix way to do this).  Or make the initial area simpler, and make all servers appear after you "escape" it.

**Comment by OneOfMany07** [comment]
Just found the issue.  The spot is...

"Hacking is the core mechanic of the game and is necessary for progressing. However, you don't want to be hacking manually the entire time. You can automate your hacking by writing scripts!

To create a new script or edit an existing one, you can use

[home ~/]> nano

Scripts must end with the .js extension. Let's make a script now by entering

[n00dles ~/]> nano n00dles.js

after the hack command finishes running (Sidenote: Pressing ctrl + c will end a command like hack early)"

Note how the first command is on home, but second is on n00dles?  At the terminal I'm not allowed to create a blank script with "nano", nor connect to n00dles first before creating my script.

**Comment by OneOfMany07** [comment]
And following the directions to run this on my "home" machine gives an error...

"RUNTIME ERROR
n00dles.js@home (PID - 1)

Identifier 'main' has already been declared (4:23) (sorry we can't be more helpful)"


    With the tutorial saying...


"Your script is now running! It will continuously run in the background and will automatically stop if the code ever completes (the n00dles.js will never complete because it runs an infinite loop).

These scripts can passively earn you income and hacking experience. Your scripts will also earn money and experience while you are offline, although at a slightly slower rate.

Let's check out some statistics for our running scripts by clicking"
