### ISSUE TITLE
purchased server limit

### ISSUE THREAD

**Issue by Granaat** [danielyxie/bitburner#3870]
When deleting a purchased server, doesn't it subtract 1 from the total bought servers?

getPurchasedServerLimit returns 25, I have no purchased servers left but bought & deleted some several times.
Now when I try to buy a server the app crashes for no reason while it functioned correctly before.

reproduce:
call this function several times on some hostnames.

```
export const replaceServer = (hostname, ns) => {
	ns.killall(hostname)
	const success = ns.deleteServer(hostname)

	if (success) return ns.purchaseServer(hostname, 64)
	return ''
}
```

**Comment by ilkecan** [comment]
> When deleting a purchased server, doesn't it subtract 1 from the total bought servers?

There isn't a separate counter for the number of servers that you have. It is calculated from the array that keeps the servers by taking its length:
https://github.com/danielyxie/bitburner/blob/6f017bf4f60cbe264556456c69450d7a160856fd/src/NetscriptFunctions.ts#L1794

I cannot reproduce any problems by calling `replaceServer` multiple times like you said.
