### ISSUE TITLE
Corporation export/import not working

### ISSUE THREAD

**Issue by exi** [danielyxie/bitburner#3876]
Exporting plants from agriculture seems to work. At least they are listed as "exported".

However, the receiving end of the shipment does not list anything as "imported".
The resources seem to disappear.

- [X] Steps to reproduce
Add an export for plants to some agriculture warehouse.
Check that the expected import for plants does not show up at (in my case) the chemical warehouse.

- [X] Version of the game
v1.7.0 (b60f3da8)

**Comment by Bobsson** [comment]
I can confirm that this is still broken on v2.0.2 (`3067703c`)
