### ISSUE TITLE
Corporations - "Drones - Transport" not working without "Smart Storage"

### ISSUE THREAD

**Issue by EricCodesStuff** [danielyxie/bitburner#3880]
Warehouse storage does not seem to receive the 1.5x from Drones - Transport until Smart Storage has at least 1 level.

- Steps to reproduce
1. Start Corporation
2. Expand Industry
3. Expand Cities/Warehouses (Had all cities, 300 storage Sector-12)
4. Research Drones, Drones - Transport

Tried restarting Bitburner with no change.

- Version: 1.7.0 (00adc2ff)

**Comment by Mughur** [comment]
You were half-right. researching Drones - Transport does not increase the storage size until _after anything else_ increases it, be it storage or smart storage upgrade. Upgrading the size by other means activates the research's effect
