### ISSUE TITLE
change * indicator on edited files

### ISSUE THREAD

**Issue by Sheltraks** [danielyxie/bitburner#3882]
For any .txt file:
- has a *-changed mark on at opening (without any changes yet)
- if saved, * does not vanish
- if closed, game always asks if .txt shall be saved (also when without any changes)

For .js file:
- has a * mark on it at opening (no changes yet)
- if saved, * stays
- if change is made and change is removed to inital state, * vanishes

Still valid for:
Bitburner v1.7.0 (b60f3da8)
in FF 102.0

**Comment by Snarling** [comment]
This is fixed on dev and can be closed
