### ISSUE TITLE
formulas.hacking.growPercent does not accurately predict the growth amount

### ISSUE THREAD

**Issue by BennieVE** [danielyxie/bitburner#3885]
Neither the `growPercent` nor `growthAnalyze` correctly predicted the amount by which the server money would grow.

- [x] Save file 
  [backup_2022-07-03.txt](https://github.com/danielyxie/bitburner/files/9035374/backup_2022-07-03.txt)
- [x] Version of the game: Steam - Bitburner v1.7.0 (00adc2ff)

![all](https://user-images.githubusercontent.com/84269545/177056682-64e61bda-46a9-4675-8321-5e2c42eaa4fd.png)

Growing omega-net with the given amount of growth threads should have increased the money on the server by ~100%, but as seen from the grow.js logs, it only increased by ~96%.

Additional notes:
* I don't have any augmentations installed
* I'm on BitNode 12

**Comment by Snarling** [comment]
I see you are running other processes on the same server. Was the server's security level when your grow process completed the same as the security level when you made the calculation? If security is higher when your grow completes, you will grow by a smaller amount.

**Comment by BennieVE** [comment]
Ah, I think I understand where my mistake came in.

I'm running a hack-grow-weaken script, so after the hack finished, the security was higher than when the formula was executed, causing a decline in the expected growth. 

I should rework it into a hack-weaken-grow-weaken script to have a more predictable outcome.

Thanks for the help.
