### ISSUE TITLE
Faction Invitation Not Extended if hacking from script

### ISSUE THREAD

**Issue by therealmichaelberna** [danielyxie/bitburner#3887]
Bitburner v1.7.0

I've created a script that automatically hacks the run4theh111z server. I looked at the logs and my script hacked it a few times, but I never received the invitation to join. I only received an invitation after manually connecting and hacking it.

**Comment by therealmichaelberna** [comment]
[bitburnerSave_1656959205_BN1x1.zip](https://github.com/danielyxie/bitburner/files/9041501/bitburnerSave_1656959205_BN1x1.zip)

**Comment by aheinzm** [comment]
Which faction are you expecting to unlock by hacking **run4theh111z**?

**Comment by Snarling** [comment]
Not an issue. In order to unlock hacking faction invites, you need to _manually hack_ their server, or backdoor it (backdooring via script is not available right away).
