### ISSUE TITLE
Displayed Favor not matching after backup save bonus

### ISSUE THREAD

**Issue by EinzigeMeister** [danielyxie/bitburner#3890]
After performing backup save, Favor doesn't display properly on either the Factions page or the Augments/Details page on several factions. I believe the faction I was working for displays properly (ECorp), however all others show 1 less favor on the Augments/Details pages.

- [ ] Save file
[bitburnerSave_1656976777_BN13x2.txt](https://github.com/danielyxie/bitburner/files/9042319/bitburnerSave_1656976777_BN13x2.txt)

- [ ] Minimal scripts to reproduce the issue: None required

-Steps to reproduce: import save file, go to Factions, view the Augments/details page on any faction besides ECorp.

![cap2](https://user-images.githubusercontent.com/106645041/177224985-67b560d5-9ddb-4831-a6e4-68aad5caa5f2.PNG)
![cap1](https://user-images.githubusercontent.com/106645041/177224986-7f654a4c-9891-4c39-b095-37eef7451ce5.PNG)
![cap3](https://user-images.githubusercontent.com/106645041/177224987-13c21f8b-c359-4ee6-90c9-342ce4d08b32.PNG)

-Bitburner v1.7.0 (00adc2ff)

**Comment by EinzigeMeister** [comment]
After installing augments, Church of the Machine God still shows different favors

**Comment by RyanHx** [comment]
Also just ran into this issue. 

- [ ] Save file
[bitburnerSave_1658080527_BN1x1.txt](https://github.com/danielyxie/bitburner/files/9128261/bitburnerSave_1658080527_BN1x1.txt)

The Black Hand shows 150 favor in the Factions screen, but in their 'Details' it shows 149 favor and I'm unable to make donations. It actually gave me the achievement for unlocking donations, despite not being able to currently.

Bitburner v1.7.0 (cfcdc254)
