### ISSUE TITLE
invalid hostname undefined

### ISSUE THREAD

**Issue by arch-user-france1** [danielyxie/bitburner#3896]
![image](https://user-images.githubusercontent.com/72965843/178150052-7d868aba-bc54-4be8-a758-ac7d6d38a8f4.png)
This script always dies:
![image](https://user-images.githubusercontent.com/72965843/178150090-24f3987b-e1b8-4121-8ce0-2389418d78df.png)
Why is that happening?
Here's the code:
```
while(true){
availableHosts=""
availableHosts=scan()
for (i = 0; i <= availableHosts.length; i++) {
	hack=true
	currentHost=(String(availableHosts[i]))
	try {
		if (currentHost == undefined){hack=false}
		else if (hasRootAccess(currentHost)){hack=false}
		else if (currentHost == getHostname()) {hack=false}
		else if (getServerNumPortsRequired(currentHost)>3){hack=false}
		else if (getServerRequiredHackingLevel>getHackingLevel){hack=false}
		if (hack){
			ftpcrack(currentHost)
			brutessh(currentHost)
			relaysmtp(currentHost)
			nuke(currentHost)
			if (hasRootAccess){tprint(getHostname()," hacked: ", currentHost)}else{tprint("Failed to hack: ", currentHost)}
		}
	}
	catch(err) {print(err)}
}
sleep(10000)
}
```

The` if currentHost == undefined `does not help :(

**Comment by Granaat** [comment]
```for (i = 0; i <= availableHosts.length; i++) ``` 
should be
```for (i = 0; i **<** availableHosts.length; i++) {```

It could also be null, so better write ```if (!currentHost)```

**Comment by arch-user-france1** [comment]
> `for (i = 0; i <= availableHosts.length; i++) ` should be `for (i = 0; i < availableHosts.length; i++) {`
> 
> It could also be null, so better write `if (!currentHost)`

I used to check if currentHost == null...
