### ISSUE TITLE
Elements out of viewport 

### ISSUE THREAD

**Issue by Appa-lw** [danielyxie/bitburner#3898]
Hey Guys, 

when i open Bitburner only in half-window size some of the content gets out of the viewport of the browser. There is no scrollbar so i have to mark the text in the window and drag to the side so that the viewport shifts to the right (or left).

![image](https://user-images.githubusercontent.com/69350876/178226516-3d1796fd-f2d7-4941-a576-fc2998094198.png)

- Bitburner v1.7.0 (b5927847)
- Browser: Brave Version 1.40.113  Chromium: 103.0.5060.114 (Offizieller Build)  (64-Bit)

**Comment by kotenok2000** [comment]
You can also use wheel click to scroll sideways.
