### ISSUE TITLE
[Feature Request] Add ability to clear terminal

### ISSUE THREAD

**Issue by dflor003** [danielyxie/bitburner#3902]
It would be awesome if we had the ability to clear the terminal programmatically (note, I do mean _terminal_, not a script's _log_ which can already be done via `ns.ClearLog()`). 

I'm writing some scripts for things like node management where I'd like to be able to do run add a `--watch` to my CLI command and then all of a sudden have it live-refresh a view every, say 1 second or so. Maybe one of the following?

```js
ns.tClear(); // Lines up with some of the existing terminal apis
ns.clearTerminal(); // No ambiguity
```

I've been able to work around this by following the example in the docs for [injecting html[(https://bitburner.readthedocs.io/en/latest/netscript/advancedfunctions/inject_html.html) but its quite a hacky approach to the problem (does work pretty well though). It'd also be cool if there was some built in functionality off `ns` to intercept key combinations like `Ctrl/Cmd + C` and use that as the signal to stop the script.

```ts
// scripts/helpers/run-terminal-command.ts
const ID = 'terminal-input';

export function runTerminalCommand(command: string) {
  const terminalInput = document.getElementById(ID) as HTMLInputElement;
  if (!terminalInput) {
    return false;
  }

  terminalInput.value = command;
  const handler = Object.keys(terminalInput)[1];
  terminalInput[handler].onChange({ target: { value: command } });
  terminalInput[handler].onKeyDown({
    key: 'Enter',
    preventDefault: () => null,
  });

  return true;
}

// scripts/helpers/watch.ts
import { runTerminalCommand } from 'scripts/helpers/run-terminal-command';
import { NS } from 'types';

export async function watchScript(
  ns: NS,
  func: () => void | Promise<void>,
  interval: number = 1000,
) {
  let finished = false;
  function captureCtrlC(evt: KeyboardEvent) {
    if (evt.ctrlKey && evt.code === 'KeyC') {
      finished = true;
    }
  }
  document.addEventListener('keyup', captureCtrlC);
  ns.atExit(() => document.removeEventListener('keyup', captureCtrlC));
  while (!finished) {
    if (runTerminalCommand('cls')) {
      await func();
      ns.tprintf(' ');
      ns.tprintf('Press Ctrl + C to stop...');
    }
    await ns.sleep(interval);
  }
  document.removeEventListener('keyup', captureCtrlC);
  ns.tprintf(`Exited watch`);
}
```

**Comment by Snarling** [comment]
From a design perspective, the issue here is that while one script owns its entire script log, it doesn't own the entire terminal, so I'm not sure it makes sense to add terminal-clearing as a native function.

It's also very unlikely that custom shortcut key handling will be added in a native way. Advanced functionality like that can still be achieved through player use of js like you've shown above.

**Comment by dflor003** [comment]
Oh! Perfect! I completely missed that. Thank you for that! Works like a charm 😄

![image](https://user-images.githubusercontent.com/103017/179266578-d16206e6-0c5c-40e8-a4ba-555d22bc450e.png)
