### ISSUE TITLE
[BUG] More space between text lines in tail logs after recent update

### ISSUE THREAD

**Issue by TheRealMaxion** [danielyxie/bitburner#3905]
After the most recent update on steam, the tail logs suddenly have a lot more space between lines of text.

![image](https://user-images.githubusercontent.com/13872642/179089958-6cec454b-c1aa-47eb-a88a-856d30762ca8.png)

Version: Bitburner v1.7.0 (686ca3e3)

**Comment by xPoP** [comment]
Can confirm, I have this too. Super annoying bug, haha.

**Comment by xPoP** [comment]
Looks like there's been another update fixing it 👍🏻

**Comment by TheRealMaxion** [comment]
Indeed, this has been fixed. 👍
