### ISSUE TITLE
"Invalid donate amount entered!" when you can't donate

### ISSUE THREAD

**Issue by pawl** [danielyxie/bitburner#3916]
I'm on Bitburner v1.7.0, and viewing the details of any faction will show "Invalid donate amount entered!" when you didn't enter an amount and haven't unlocked donations yet because you don't have enough favor. I think it would be an improvement to hide the "Invalid donate amount entered!" text when you haven't unlocked donations yet.

Screenshot:
![Screenshot from 2022-07-17 18-07-11](https://user-images.githubusercontent.com/992533/179428463-fd126c56-3ff4-4027-9afd-4a5935e66412.png)

It looks like this is the relevant code: https://github.com/danielyxie/bitburner/blob/6f017bf4f60cbe264556456c69450d7a160856fd/src/Faction/ui/DonateOption.tsx#L64

**Comment by hydroflame** [comment]
Thanks, fixed
