### ISSUE TITLE
Not getting any skill point from BN6.2

### ISSUE THREAD

**Issue by BBloke** [danielyxie/bitburner#3918]
Game Version: v1.7.0 cfcdc254

I've hacked BN6.1 and started BN6.2.  I have 4300+ rank dut I've noticed from this figure I haven't received any skill points.  My current rank is 4339.

I'm using automate and have my earnt skill points spent where I want them.

I have saved and closed the game and steam and restarted and I'm still not getting the any skill points.

Exported game attached
[bitburnerSave_1658256457_BN6x2.json.zip](https://github.com/danielyxie/bitburner/files/9143902/bitburnerSave_1658256457_BN6x2.json.zip)
!

**Comment by hydroflame** [comment]
Right so what happened is you don't get skill point every time you gain rank. You gain skill point when you exceed your maximum rank this BN. In your case you just lost a bit of rank and have to catch up.
