### ISSUE TITLE
mem function apparently doesn't use treeshaking

### ISSUE THREAD

**Issue by Granaat** [danielyxie/bitburner#3919]
I have a utils.js file which contains several functions.
Importing 1 function of this file results in calculation all used functions in the imported file instead of just the function used.
Even more, if that imported function isn't even used, all ram of the imported file still is taking into account.

Expected result would be the memory usage uses treeshaking so only the used functions count to the ram result.

**Comment by phyzical** [comment]
are you doing an `import * as blah from  blah.js` then `blah.thing()` or `import {thing} from blah.js`

from memory the latter should work as expected.

if not mind adding same of how your exporting and importing your functions

**Comment by Granaat** [comment]
```
import { Time } from 'global/utils'

/** @param {NS} ns */
export async function main(ns) {
	const hostname = ns.args[0]
	const threads = ns.args[1]
}
```
for example. should result in 1.6 GB (base) as 'Time' isn't used.
but results in 
```
This script requires 1.85GB of RAM to run for 1 thread(s)
1.60GB | baseCost (misc)
100.00MB | getScriptRam (fn)
100.00MB | getServerMoneyAvailable (fn)
 50.00MB | getServerMaxRam (fn)
```

Furthermore, getScriptRam, getServerMoneyAvailable & getServerMaxRam  aren't used in Time.
They are used in another function in 'global/utils'.

**Comment by phyzical** [comment]
hmm looking at the code we do have tests for this maybe something else is going on with your code?

the first test is a case that imports 1 function and only incurs the cost of the one imported, the second is an example where importing both incurs the cost of both

```
 it("Importing a single function from a library that exports multiple", async function () {
      const libCode = `
        export async function doHack(ns) { return await ns.hack("joesguns"); }
        export async function doGrow(ns) { return await ns.grow("joesguns"); }
      `;
      const lib = new Script(Player, "libTest.js", libCode, []);

      const code = `
        import { doHack } from "libTest";
        export async function main(ns) {
          await doHack(ns);
        }
      `;
      const calculated = (await calculateRamUsage(Player, code, [lib])).cost;
      expectCost(calculated, HackCost);
    });

    it("Importing all functions from a library that exports multiple", async function () {
      const libCode = `
        export async function doHack(ns) { return await ns.hack("joesguns"); }
        export async function doGrow(ns) { return await ns.grow("joesguns"); }
      `;
      const lib = new Script(Player, "libTest.js", libCode, []);

      const code = `
        import * as test from "libTest";
        export async function main(ns) {
          await test.doHack(ns);
        }
      `;
      const calculated = (await calculateRamUsage(Player, code, [lib])).cost;
      expectCost(calculated, HackCost + GrowCost);
    });
    ```

**Comment by phyzical** [comment]
hmm

mind humoring me and trying  incase something weird goes on with anonymous function declarations
`export const calcThreads = (ns, server, files) => {` to `export function calcThreads(ns, server, files) {`

if not another thing to try would be to comment out all the class stuff and just try importing another random function, i wonder if the initialization of the class `export const Time = new TimeClass()`  causes the whole file to count as being run to export it?

**Comment by Granaat** [comment]
- Importing another function which doesn't include a class gives the same result
- Commenting out the classes gives the same result
- `export function` instead of `export const` gives the same result

**Comment by phyzical** [comment]
thanks for trying, we will have to wait for other to weigh in i guess

**Comment by Granaat** [comment]
@hydroflame is a bug that is already fixed? Or am I missing something?
