### ISSUE TITLE
ns.infiltration.getInfiltration() leaks internal reference

### ISSUE THREAD

**Issue by TheMas3212** [danielyxie/bitburner#3920]
the object returned by getInfiltration contains a reference to the internal location object for the target location
this can be used to modify the stats of that location (for example, lowering the difficulty to 0)

```
/** @param {NS} ns **/
export async function main(ns) {
    const x = ns.infiltration.getInfiltration("MegaCorp");
    x.location.infiltrationData.startingSecurityLevel = 0
}
```

v1.7.0 (cfcdc254)

**Comment by hydroflame** [comment]
Thanks, solved
