### ISSUE TITLE
Wanted Level Penalty

### ISSUE THREAD

**Issue by Granaat** [danielyxie/bitburner#3922]
The `Wanted Level Penalty` on the gang view always displays a negative percentage. Making you think this is a positive thing. 
Instead it appears to be the invert (100 + displayed percentage).
So -0.07% should be 99.93% ?

**Comment by Saynt-Garmo** [comment]
So -0.07% should be 99.93% ?  Yes, UI displays information one way, the function returns it another. 

Wanted Penalty is a ration of respect/wanted.  Just because you dropped wanted level by a significant amount, you may not have had the respect to offset the penalty correctly.

**Comment by hydroflame** [comment]
dup
