### ISSUE TITLE
Training at a gym apparently gives you a credit line?

### ISSUE THREAD

**Issue by Granaat** [danielyxie/bitburner#3926]
When training in a gym and your money reaches $0. It still goes down infinitely.
I don't know if this is the purpose or not.

**Comment by phyzical** [comment]
at the moment this is by design, there was a pr to change this. but was closed due to a recent rework of the "work" system. 

But will probably be changed in the future.

**Comment by Granaat** [comment]
Makes it real easy in the beginning to commit crime :)
