### ISSUE TITLE
Sleeve augs not visible in UI after 2.0.0 upgrade

### ISSUE THREAD

**Issue by nekoyoubi** [danielyxie/bitburner#3928]
- [✔️] Save file
  - [bitburnerSave_1658515855_BN10x3.zip](https://github.com/danielyxie/bitburner/files/9170090/bitburnerSave_1658515855_BN10x3.zip)
- [❌] Minimal scripts to reproduce the issue
- [🤷] Steps to reproduce
  - have 8 sleeves (7+1; BN 10.3) that are done with shock recovery
  - have a gang with 8m+ rep, and various other tiny factions with at least enough rep for some augs
  - decide upgrading to the dev branch would be a good idea in the middle of a bitnode (lol)
  - look at your shiny, new, shock-free 0th sleeve's augs available to install
  - recoil in horror as there is no list of augs *\*gasp\**
  - check all the rest of the sleeves and see the same thing
- [✔️] Version of the game
  - Bitburner v2.0.0 (c37d7845)  /  dev branch via Steam

**Comment by nekoyoubi** [comment]
Just as an update, installing augs didn't jump start the sleeves' ability to purchase augs of their own.

**Comment by Snarling** [comment]
> have 8 sleeves (7+1; BN 10.3) that are almost done with shock recovery

Pretty sure they need to be at 0 shock in order to install augs.

**Comment by nekoyoubi** [comment]
Sorry, I should have been more succinct; that was just my lead into the issue. I will update for clarity. They had since been done with shock recovery (all were at 0 shock and 100 sync). I had others in Discord confirm that it was actually a reproducible issue, and not just something silly that I was doing wrong. For now, the issue can be gotten around by programmatically purchasing augs, but the UI does not show them under any circumstances.
