### ISSUE TITLE
Grow() documentation incorrect

### ISSUE THREAD

**Issue by Granaat** [danielyxie/bitburner#3929]
The examples on the grow() doc state:
```
// NS1:
var currentMoney = getServerMoneyAvailable("foodnstuff");
currentMoney = currentMoney * (1 + grow("foodnstuff"));

// NS2:
let currentMoney = ns.getServerMoneyAvailable("foodnstuff");
currentMoney *= (1 + await ns.grow("foodnstuff"));
```

This is incorrect as the grow() function returns 1.000xxx.
So the multiplier is returned, not the precentage, making the examples:

```
// NS1:
var currentMoney = getServerMoneyAvailable("foodnstuff");
currentMoney = currentMoney * grow("foodnstuff");

// NS2:
let currentMoney = ns.getServerMoneyAvailable("foodnstuff");
currentMoney *= await ns.grow("foodnstuff");
```

**Comment by Saynt-Garmo** [comment]
Grow adds a flat +$1 dollar per thread before calculating to account for growing from an empty server.

**Comment by Granaat** [comment]
This is not concerning an empty server.
Also, the 1 is also not 1$, it's used as 100%.
Hence this is correct
```
Returns:
Promise<number>
The number by which the money on the server was multiplied for the growth.
```

But the examples ain't

**Comment by Saynt-Garmo** [comment]
My apologies, I misunderstood, Feel free to ignore my comment then.
