### ISSUE TITLE
batches slowing app down considerably + possibly leaking memory

### ISSUE THREAD

**Issue by Granaat** [danielyxie/bitburner#3934]
When running hacking with batches, I spawn atm 23831 batches which consist of 3 scripts. (so +/- 71500 scripts / server)
The startup is very slow. (even with some sleeps in-between each server spawn.)
Once they all started, the app works smoothly again, but over time, ram accumulates & crashes the app.

1. I suppose it's not meant to run this many scripts? If not there is no use in buying high ram servers then I suppose?
2. Letting the app run while idle results in crashing the app. (mostly rendering engine crashing)
3. restarting bitburner mostly results in the "debug mode" when "Kill all scripts" is not selected. When debugging I noticed all scripts run double also (I believe it can't kill all scripts fast enough en reboots alle old & new versions, using twice the memory, resulting in a more frequent boot crash)

**Comment by phyzical** [comment]
use threads instead of batches. i.e instead of spawning 15 of the same script spawn 1 with 15 threads

**Comment by Granaat** [comment]
Normally I would, as threads are multipliers instead of new workers, but I need to offset the batches so that they cascade. Threads can't be offset as far as I know?

This is a batch of 4 groups, below the fat line is the repetition of the batch.
But each batch need to be offset by 200 ms to the right so that they end differently.
![image](https://user-images.githubusercontent.com/30253437/181188724-fadf96f0-c2e1-499c-8cea-cd4f82ddfb33.png)

If the threadId would be available inside a script, it would be possible, but I guess it isn't?
