### ISSUE TITLE
passing Player object to formulas.hacking functions throws error 'player should be Player'

### ISSUE THREAD

**Issue by RedeyeRaskol** [danielyxie/bitburner#3937]
Bitburner v2.0.0 2b4a1bb7

browser: Brave v1.41.100
OS: Windows 10

reproduce:
create and run script:
```
/** @param {NS} ns */
export async function main(ns) {
    const s = ns.getServer("foodnstuff");
    const p = ns.getPlayer();
    const hackTime= ns.formulas.hacking.hackTime(s, p); // throws runtime error: "formulas.hacking.hackTime: player should be a Player."
    ns.tprint(hackTime);
}

```
possible cause:

https://github.com/danielyxie/bitburner/blob/2b4a1bb7db0eca13e606d078c3c5c7bbbf6fef32/src/NetscriptFunctions.ts#L586

fakeplayer object in player function does not reflect the properties defined in NetscriptDefinitions.d.ts. The following properties are no longer present in player object when calling ns.getPlayer():
hacking
max_hp
strength
defense
dexterity
agility
charisma
intelligence
hacking_exp
strength_exp
defense_exp
dexterity_exp
agility_exp
charisma_exp

also the new skills property is missing from fakePlayer.

This causes if ```(!roughlyIs(fakePlayer, p)) throw makeRuntimeErrorMsg(funcName, `player should be a Player.`);```  (on line 624) to throw when passing in a valid (new) player object.

**Comment by hydroflame** [comment]
Fixed
