### ISSUE TITLE
Bitburner runs but I cannot open the program window

### ISSUE THREAD

**Issue by Aeria87** [danielyxie/bitburner#3939]
After 3000 odd hours of enjoying the game I have encountered a situation that means I cannot play it anymore. 
Yesterday 29/07/2022 after having the program open in the morning, something has happened and I cannot actually open or see the window any more. 
The program logo comes up when open on the start bar, I can hover over it and it has the small program window comes up but when I click on it, nothing happens. 
I have verified the file integrity multiple times, deleted and reinstalled it multiple times, I have troubleshot through task manager and windows. I have updated windows and restarted the computer multiple times and even turned it off multiple times. All of these have not fixed the issue 

My version is v1.7.0(cfcdc254) 

the savefile wont upload "D:\Program Files (x86)\Steam\steamapps\common\Bitburner\savefiles\bitburnerSave_1659066310_BN10x1.json"

**Comment by hydroflame** [comment]
zip your save file and upload it

**Comment by Aeria87** [comment]
[bitburnerSave_1659066310_BN10x1.zip](https://github.com/danielyxie/bitburner/files/9225768/bitburnerSave_1659066310_BN10x1.zip)

**Comment by oddiz** [comment]
I was able to run your save file on [browser Bitburner](https://danielyxie.github.io/bitburner/) using private window on Chrome. (Felt like entering Matrix with all those toasts queued up, was pretty cool 😁)

One unlikely cause I have in mind; if you use multi monitor rarely a window bugs out and go out of view. When game opens without window select it from task bar and press `WIN + arrow keys` to different directions, see if window pop backs into view.

Assuming save file you send is the latest (if not I'd suggest waiting hydroflame's response just in case), I'd try going to `Steam > Library > Bitburner > Properties > General` disable steam cloud, delete game, check for any left over files at the Bitburner directory and reinstall.

For last drop of hopium,  `Steam > Library > Bitburner > Properties > Betas` and select development branch.

**Comment by Aeria87** [comment]
Thanks oddiz for your help. Yes I like the Matrixy feel but [alainbryden](https://github.com/alainbryden) is responsible for that with their excellent scripts that help me a shiny noob coder to feel like I understand way more than I do.

Yes I have a multi monitor set up and your idea of a rare bug from that makes sense for what I am seeing. I will try your fix suggestions. So far no luck but I'll keep trying because I do really like the game, even if I am a noob coder.

**Comment by phyzical** [comment]
you could try importing your save on steam version if thats an option
