### ISSUE TITLE
Folder "/" created by script - cannot be removed anymore

### ISSUE THREAD

**Issue by bachlauf** [danielyxie/bitburner#3940]
I'm not sure, which script command exactly produces this issue. Possibly;
`ns.write("/dir/file")`
or
`ns.scp("/dir/file", "home")`
or
`ns.mv(...)`
or anything similar.

Finally, I got a directory in my root directory with the name "/" and files in this directory. I can see that there are files within this directory by pressing the tab key e.g. after "rm /" in the terminal. But I cannot delete this file / these files, because the "rm" command does not find the file. Autocompletion does not find this file, even when it is listed in the autocompletion window.

So I need a possibility to remove the files in this magic "/" folder or the folder completely with all content (without removing all my files in the root directory). Also there should not be any possibilty to create such a file in this directory.

Version of the game, Bitburner v1.7.0 (cfcdc254)
![grafik](https://user-images.githubusercontent.com/22352423/181915985-00295f91-0179-4355-a9e8-f7defc70d133.png)

**Comment by phyzical** [comment]
all i can say is i cannot replicate this in version 2.0 of the game
```
/** @param {NS} ns */
export async function main(ns) {
	ns.write("/dir/file.js")
	ns.write("/dir/file2.js")
	ns.write("/dir/file4.js")
	ns.scp("/dir/file4.js", "home")
	ns.mv("home","/dir/file.js", "/dir/file3.js")
}
```
![image](https://user-images.githubusercontent.com/5182053/182105361-aaf8873b-a4cb-483f-ad61-8d31218046e1.png)

**Comment by Snarling** [comment]
It's due to your file named `//next.js` which I'm not sure how you created. I'm not able to make a file with that name.

**Comment by bachlauf** [comment]
In my experiments I tried to create a script for each server - so at first I have created a folder for each server (or later: copy / scp). Possibly the server with the name "." has caused this problem anyhow?!?!?
... I will report the result of my experiments in the next days

**Comment by hydroflame** [comment]
I think wget can cause this.
