### ISSUE TITLE
Mouse Drifting When clicked in game

### ISSUE THREAD

**Issue by argon1820** [danielyxie/bitburner#3944]
When I am clicked into the game my mouse constantly drifts to the top left corner of the screen. Once I click/tab out of the game the mouse stops drifting. This happens every time I launch the game.

**Comment by oddiz** [comment]
Never happened to me, but those kind of problems usually happens to me if I forgot my rudder pedal plugged in. If you have any controllers or pedals connected try plugging them off and kill their software running in background.

Can't think of any other reason how an electron app can take control of your mouse.

**Comment by phyzical** [comment]
This shouldnt be possible via JS (what electron runs) is this the browser version or steam version? if steam what OS?
