### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (at "Location")

### ISSUE THREAD

**Issue by task58** [danielyxie/bitburner#3952]
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Location
* Version: v1.7.0 (cfcdc254)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
* Features: lang=ja-JP cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by task58** [comment]
This occurred when I tried to purchase a TOR router at NetLink Technologies in Aevum.
However, when I loaded the RECOVERY data and performed the same operation, I was able to purchase the router without any problems.
I have not been able to reproduce this at this time.

**Comment by Snarling** [comment]
Do you do any document manipulation stuff? Is there anything outside of the norm that you had been doing prior to the error?

**Comment by task58** [comment]
No, I did not.
