### ISSUE TITLE
Prompt choices issue enters me in recovery mode.

### ISSUE THREAD

**Issue by GamerTronky** [danielyxie/bitburner#3957]
How to reproduce:
var serv = prompt('Prompt.',
	{type:'select',choices:ls})
- [1.7.0] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
 [Prompt issue bitburner](https://vimeo.com/736637187/599936990d)

**Comment by Snarling** [comment]
The reason it's erroring is that you're sending a function `ls` as the choices, which is supposed to be an array.
This is still a bug because it shouldn't kick you out to recovery mode, it should just give you an error.
