### ISSUE TITLE
ns.exec documentation lookup shows regex args instead of Netscript

### ISSUE THREAD

**Issue by michalmonday** [danielyxie/bitburner#3959]
![image](https://user-images.githubusercontent.com/16074078/183267207-ccfb6c51-926c-463a-bae7-25eb52358efe.png)

Game version is v1.7.0 (cfcdc254)

**Comment by Snarling** [comment]
It's because you removed or moved the jsdoc entry that defined what type `ns` is.

![image](https://user-images.githubusercontent.com/84951833/183268429-3518ba8a-4b7d-44c6-9bbe-fd2e2f35b2d9.png)

That line needs to be directly above any function that takes ns as a parameter.
