### ISSUE TITLE
Cannot delete contract files with special characters in filename

### ISSUE THREAD

**Issue by DrCuriosity** [danielyxie/bitburner#3979]
When attempting to delete a contract I'd resigned to the "too hard basket" the `rm` command failed, saying the file did not exist.

Output:
```
[zeus-med ~/]> ls
contract-45485-Bachman&Associates.cct 
[zeus-med ~/]> rm contract-45485-Bachman&Associates.cct
No such file exists
```

- **Version**: v1.7.0
- **To reproduce**: find a contract file containing a name like "Joe'sGuns" or "Bachman&Associates" and attempt to delete it with `rm`

I think this is happening because the apostrophe and ampersand characters are failing `isValidFilename` validation in the Terminal/DirectoryHelpers, where the regex only "Allows alphanumerics, hyphens, underscores, and percentage signs".

I'm of two minds about this could be fixed.
1. Expanding the regex with `\'\&` symbols could work, but there could be a side-effect of validating some strings that shouldn't be considered valid, in some part of the system I don't yet understand.
2. Altering the way contract filenames are generated to avoid or remove the invalid characters, e.g. "JoesGuns", "BachmanAssociates" or "BachmanAndAssociates", so that they pass validation. Might be more effort, but a more stable change (at least for filenames generated in future versions of the game).

**Comment by Snarling** [comment]
Yeah it looks like you're right about it being the &. It's eventually reaching this filename check and failing to match this regex:

https://github.com/danielyxie/bitburner/blob/ba5b0be7f4753a5be6a7f1a98164dd9d7911a6df/src/Terminal/DirectoryHelpers.ts#L38-L45

**Comment by DrCuriosity** [comment]
Have run into a new problem after the latest update, possibly related: I now can't directly run a file with an apostrophe in it without wrapping it in quotes.

```
[vitalife ~/]> run contract-134876-Joe'sGuns.cct 
No such contract
[vitalife ~/]> run "contract-134876-Joe'sGuns.cct"
Contract FAILED - 9 tries remaining
```
