### ISSUE TITLE
Runtime error when running script containing ns.purchaseTor() function

### ISSUE THREAD

**Issue by ActuallyHappy** [danielyxie/bitburner#3988]
Save file:
[bitburnerSave_1655912169_BN1x1.zip](https://github.com/danielyxie/bitburner/files/9367468/bitburnerSave_1655912169_BN1x1.zip)

Bitburner v2.0.1 (69934257)

Steps to reproduce: Run any script containing the singularity function ns.purchaseTor()

Doing this returns this runtime error ![Skjermbilde 2022-08-18 054211](https://user-images.githubusercontent.com/109360914/185288380-f0efbc00-6e58-4e78-8798-dae9f35b183c.png)

Script: 
`/** @param {NS} ns */
export async function main(ns) {
	ns.tail()
	ns.clearLog()

	const cost = 200000
	let money = ns.getServerMoneyAvailable('home')
	let purchased = ns.purchaseTor()
	let focus = !ns.getOwnedAugmentations().includes('Neuroreceptor Management Implant')

	while (!purchased) {
		money = ns.getServerMoneyAvailable('home')
		if (money > cost) {
			purchased = ns.purchaseTor()
		}
		else {
			if (ns.isBusy()) {
				await ns.sleep(1000)
			}
			else {
				await ns.commitCrime('Rob Store', focus)
			}
		}
	}
	ns.closeTail()
	ns.exit()
}`

**Comment by Snarling** [comment]
Read the 2.0 migration guide, singularity functions are now under ns.singularity.functionName

**Comment by ActuallyHappy** [comment]
Close because end user didn't read the documentation (that's a new one, right?)
