### ISSUE TITLE
Lost Int stat after 2.0

### ISSUE THREAD

**Issue by Magistrazh** [danielyxie/bitburner#3989]
I am in bitnode 5.1
Before 2.0 I got ~60 INT, lost it after update and cannot get anymore.
- [https://disk.yandex.ru/d/sjpC7a7zceMSBA] Save file before 2.0
- [https://disk.yandex.ru/d/hpaVJvVzguy9lQ] Save file after 2.0
- [ns.tprint(ns.getPlayer().skills);] Minimal scripts to reproduce the issue
- [ 2.0.1 ] Version of the game

**Comment by Herzfinsternis** [comment]
Did not happen to me. My player kept its Int. Only my sleeves lost all Int.

**Comment by avgrad** [comment]
I can confirm, my INT stat is also lost.

Apparently the save still contains the experience. The `skills` struct at to bottom shows INT level 0, the probably old `experience` and `experience_exp` property contain the "old" values. Furthermore the `exp` struct also contains the actual experience value.
A bugfix could potentially restore it without save trickery, dev menu or alike.

![image](https://user-images.githubusercontent.com/34600077/185422713-2e5bd77b-5e48-4482-8f7c-9ff5f117f1c5.png)
![image](https://user-images.githubusercontent.com/34600077/185423346-2668976f-0903-436c-b1a4-b8f4fb845ba4.png)

**Comment by avgrad** [comment]
While there is no automatic fix, this netscript can be used to restore the stat. (**no guarantees or warranty though, because I only tried it for my own game!**)

```js
// restoreIntelligence.js
/** @param {NS} ns **/
export async function main(ns) {
	const boxes = Array.from(document.querySelectorAll(".MuiBox-root"));
	const playerBox = boxes.find(boxHasPlayerProp);

	if (playerBox) {
		const props = getReactProps(playerBox);
		const player = props.player;
		const intLvlBefore = player.intelligence;
		player.skills.intelligence = intLvlBefore;
		ns.tprint(`Intelligence stat restored to ${player.skills.intelligence}`);
	}
}

function getReactProps(box) {
	return Object.entries(box).find(entry => entry[0].startsWith("__reactProps"))[1].children.props;
}

function boxHasPlayerProp(box) {
	try {
		return getReactProps(box).player ? true : false;
	}
	catch (ex) {
		return false;
	}
}
```

**Comment by hydroflame** [comment]
hopefully fixed
