### ISSUE TITLE
Sleeves nerfed to death

### ISSUE THREAD

**Issue by Herzfinsternis** [danielyxie/bitburner#3993]
Bitburner v2.0.1 (a8bef50e)

Sleeves are now earning much less experience. Workout at Powerhouse Gym with 84.395 shock gives only 1.115 experience per second. When the player does workout, the sleeves earn nothing. It is now much faster to commit crimes to gain experience. Heck, even working for factions gives them more exp. The changelog does not mention anything about this, so I guess, it is a bug.

**Comment by smeehrrr** [comment]
+1 on this one, this is pretty brutal.
