### ISSUE TITLE
TOR Browser not unlocking darkweb 

### ISSUE THREAD

**Issue by Sasoesegreto** [danielyxie/bitburner#3994]
Hi,
buying the TOR server does not unlock darkweb host, it is buyable (money goes down) but the option does not disappear after the click
Attached is the save file if you need it
Version: Bitburner v2.0.1 (a8bef50e)

Many thanks.

[bitburnerSave_1660838334_BN1x1.zip](https://github.com/danielyxie/bitburner/files/9375459/bitburnerSave_1660838334_BN1x1.zip)

**Comment by hydroflame** [comment]
After investigating is seems like the dark web server does not exists on your save file.

I installed some augs and that solved the problem. I understand this prevents you from buying programs this install but not the next. So I'm going to close this because it'll resolve itself soon.
