### ISSUE TITLE
Getting Root Access without necesary hacking level

### ISSUE THREAD

**Issue by wilkkylar** [danielyxie/bitburner#3995]
-  Bitburner v2.0.0

The issue i found is that you can connect to the  networks without high enough hacking level, but you still need to have had gotten access to programs that allow you to attack ports if you want to connect to iron-gym and likes of it.

I used the code js code that is demonstrated in getting started guide, and i made an autorun script that turns on programs that later hack the servers. (im not really sure if autorun is necesery for us to bypass the level requirement but i only tried hacking with it).

The bug after being used opens the Root Access for the program and the player, so the player can easly get an access  to particular network without level requirements only if he has the necessary programs

**Comment by hydroflame** [comment]
Not a bug
