### ISSUE TITLE
Sleeves broken on BN8 - v2.0.2 (3067703c)

### ISSUE THREAD

**Issue by fdellwing** [danielyxie/bitburner#4003]
Sleeves are currently able to generate money doing crimes on BN8 (this worked as intented before V2). Doing crimes myself does not give money.

![grafik](https://user-images.githubusercontent.com/22813377/185669297-d5333d92-ce86-481a-af67-9113ac2cf7c4.png)

**Comment by Mughur** [comment]
Fixed on 2.1
