### ISSUE TITLE
BruteSSH.exe Reacting wierldy to stopping/unfocusing.

### ISSUE THREAD

**Issue by Zorm** [danielyxie/bitburner#4004]
After taking a break from creating BruteSSH.exe, the create a program button will try to create BruteSSH.exe from scratch instead of continuing where you left off. If this one is stopped as well, the previously worked on BruteSSH.exe will reappear. If repeated once more, a new, empty BruteSSH.exe can be found and seems to be repeatable indefinitely.

Happened in 2.0.2

[bitburnerSave_1660927018_BN1x1.zip](https://github.com/danielyxie/bitburner/files/9384027/bitburnerSave_1660927018_BN1x1.zip)

**Comment by Zorm** [comment]
![bild](https://user-images.githubusercontent.com/946387/185681542-813f43ea-276d-40fd-94b1-1c520314ff84.png)
Also, apollogies for the save,just took the closest backup, hopefully this doesn't hinder testing speed to badly

**Comment by phyzical** [comment]
is there any other steps to repo, i tried a new save creating stop starting focus unfocus . starting a crime while creating unfocused, restarted the game while stopped all seemed to resume program creation correctly.

i also imoprted your save and you had a program 50% complete and that resumed also. so im guessing there must be some sort of set of instructions to cause such a bug  to occur

**Comment by Zorm** [comment]
Managed to reproduce, from the save prestige and get enough hacking skill to make a program, then start creating the program. Start doing something else simultaneously/unfocus, and you will notice that the current program worked on appears empty. Start working on the same program again, this should trigger the bug as mentioned above.

**Comment by DandyV3000** [comment]
https://github.com/danielyxie/bitburner/issues/4014#issuecomment-1242560227

had the same issue and I think I found the fix, I already posted it on another similar issue:
"hey letting you know that I was able to delete the copy,
ls to see file name at home
them rm [filename]
for me it was 'BruteSSH.exe-6.18%-INC'
hope this helps"

![Capture2](https://user-images.githubusercontent.com/113217646/189459405-a1a23e20-a394-4165-a264-88b66adb4718.PNG)
![Capture](https://user-images.githubusercontent.com/113217646/189459406-43c0f432-3e01-47c4-a71c-99fc14208399.PNG)
