### ISSUE TITLE
Faction work experience

### ISSUE THREAD

**Issue by rlmoser** [danielyxie/bitburner#4006]
In v2.0.2 after the work changes it looks like Faction work is giving 100 times the amount of experience as previously.  Compare old src/PersonObjects/Player/PlayerObjectGeneralMethods.tsx (startFaction*Work methods) prior to f7805c4a5 with src/Work/Formulas/Faction.tsx (the WorkStats objects).  Was there supposed to be a scaling multiplier in the calculateFactionExp function?

Faction Hacking work:
    old: 0.15 * player mult * BN mult (only Hacking)
    new: 15 * player mult * BN mult (only Hacking)

Faction Field work:
    old: 0.1* player mult * BN mult (Hack, Str, Def, Dex, Agi, Cha)
    new: 10 * player mult * BN mult (Hack, Str, Def, Dex, Agi, Cha)

Faction Security work:
    old: 0.05 * player mult * BN mult (Hack) & 0.15 * player mult * BN mult (Str, Def, Dex, Agi)
    new: 5 * player mult * BN mult (Hack) & 15 * player mult * BN mult (Str, Def, Dex, Agi)

In comparison, the most expensive gym gives 10 * player mult * BN mult for one of (Str, Def, Dex, Agi) and the most expensive Uni gives 16 * player mult * BN mult for one of (Hack, Cha)

**Comment by phyzical** [comment]
```
old: 0.1* player mult * BN mult (Hack, Str, Def, Dex, Agi, Cha)
new: 10 * player mult * BN mult (Hack, Str, Def, Dex, Agi, Cha)
```
that does look like were just missing a /by 100 (but maybe thats meant to happen in one of the multipliers now?)
