### ISSUE TITLE
currentWork is missing from the return value of ns.getPlayer

### ISSUE THREAD

**Issue by 1cekrim** [danielyxie/bitburner#4009]
It looks like the return value of ns.getPlayer() should include the 'currentWork' field, but it's missing in 2.0.2 (3067703)

https://github.com/danielyxie/bitburner/blob/07c7f0641a5dffb0c0139448201876ba6e001b63/src/utils/v2APIBreak.ts#L225

https://github.com/danielyxie/bitburner/blob/2abc5687e14dadcd1fb867e2945fff563b5a7cc5/src/NetscriptFunctions.ts#L1912-L1933

**Comment by fdellwing** [comment]
=> `ns.singularity.getCurrentWork()`
