### ISSUE TITLE
Error on atExit when script finishes

### ISSUE THREAD

**Issue by joshuademarco** [danielyxie/bitburner#4011]
## Description

When a script finishes executing and `ns.atExit(() => f)` is provided, following Error occurs:
`Error trying to call atExit for script test.js on home [object Object]`

However, it seems that this only occurs if ns is being used inside of `atExit()`.
Also, if the script is being terminated with `ns.exit()` before "finishing" the script, the error does not occur.

## Steps to reproduce

1. Set ns.atExit() and call a method from ns inside the passed function.
2. Don't terminate the script with ns.exit();

## Example
```javascript
/** @param {NS} ns */
export async function main(ns) {
    ns.atExit(() => ns.print('test'));
}
```

## Version
Bitburner v2.0.2 (3067703c)

I noticed this as my main script used to work until (i think) 2 versions ago.
It might also be that i'm just too stupid and not realizing something important. Please let me know if I handled something wrongly.

**Comment by Snarling** [comment]
Will be fixed by #3978
