### ISSUE TITLE
creating a program while owning at the same time 

### ISSUE THREAD

**Issue by MrPeanutbutterz** [danielyxie/bitburner#4014]
# DELETE THIS AFTER READING

# include (where relevant)

Regarding programs (.exe) 

At this moment the game shows that i'm creating burteSSH en FTPCrack while also owning the program 

BruteSSH.exe            BruteSSH.exe-99.89%-INC FTPCrack.exe            FTPCrack.exe-78.83%-INC 

- [ x] Save file
- [ x] Minimal scripts to reproduce the issue
- [ x] Steps to reproduce
- [ ] Version of the game, e.g. Bitburner v2.0.2 (3067703c)

**Comment by DandyV3000** [comment]
hey letting you know that I was able to delete the copy,
ls to see file name at home
them rm [filename]
for me it was 'BruteSSH.exe-6.18%-INC'
hope this helps
![Capture2](https://user-images.githubusercontent.com/113217646/189459267-d7d15bae-a80c-4b90-93da-cb1592ebc354.PNG)
![Capture](https://user-images.githubusercontent.com/113217646/189459269-bddb952f-d1bc-4c6d-a3e6-e2be611e7009.PNG)
