### ISSUE TITLE
Alerts stacking when stopping work in companies via script

### ISSUE THREAD

**Issue by ActuallyHappy** [danielyxie/bitburner#4016]
- [x] Save file [bitburnerSave_1655912169_BN1x1.zip](https://github.com/danielyxie/bitburner/files/9388766/bitburnerSave_1655912169_BN1x1.zip)
- [x] Minimal scripts to reproduce the issue: Any script that starts work for factions, and "restarts" work automatically by using ns.singularity.stopAction()
- [x] Steps to reproduce: Run abovementioned script
- [x] Version of the game: Bitburner v2.0.0 (3067703c)

When player uses a script to work for a faction, which loops every x seconds, an alert will pop up on the screen (similar to when you join factions from milestones). These stack, and cannot be disabled in settings like the milestones-alerts.

**Comment by Snarling** [comment]
Is there a reason you are stopping and restarting work instead of just continuing work?

**Comment by Snarling** [comment]
This should be fixed now on dev #4023
