### ISSUE TITLE
ns.singularity.workForCompany - focus parameter is reversed

### ISSUE THREAD

**Issue by Kelenius** [danielyxie/bitburner#4018]
Version - 2.0.2, 3067703c

Calling `ns.singularity.workForCompany(corp, false);` makes the player work and grabs the focus. `ns.singularity.workForCompany(corp, true);` starts the work without the focus. This is opposite to how other singularity work functions work, and contradicts the description.

**Comment by phyzical** [comment]
will be fixed by https://github.com/danielyxie/bitburner/pull/4000
