### ISSUE TITLE
Save game issue (was: Blank Screen after Running in Background)

### ISSUE THREAD

**Issue by Zacch** [danielyxie/bitburner#4021]
After upgrading to 2.0 (and still in 2.0.2 3067703c) I find that Bitburner often shows a blank screen when I come back after doing other things for an hour or two. I tried waiting, but the game never wakes up again. When I restart (or Reload), I get messages like "Offline for X hours", so it looks like the game really does freeze up.  I tried activating Debug, but that didn't help – after the next freeze the developer console was disconnected:

<img width="860" alt="Screenshot 2022-08-22 at 11 34 49" src="https://user-images.githubusercontent.com/1161900/185890352-1966bc72-3f77-427d-948c-4e2b2117e3c1.png">

I run on a MacBook Pro (with an Apple M1 Max processor and MacOS 12.5.1) using the Steam client. I've also noticed many short GUI pauses on v2, like the GC starts up every few minutes. Maybe that is connected.

I realize that this is a pretty vague bug report. I'll be happy to work on narrowing it down, but I don't really know where to start so any suggestions are welcome. I have cloned the repo but haven't got around to getting it running in my IDE yet – let me know if you want me to get my hands dirty.

Oh, and thanks for making such an awesome game!

**Comment by Granaat** [comment]
I've had the same problem multiple times also. Only with devtools open.
At first I thought it was when OS updates were installed or when Steam updated.

**Comment by Zacch** [comment]
@phyzical GC stands for "garbage collection". Sometimes old variable values like strings are left lying around in memory even though they aren't used anymore, so JavaScript has a process that runs now and then to get rid of this clutter. That turns out to be pretty complicated and time consuming (check [Mozilla's documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#garbage_collection) if you are interested) so that's why I suspected it to be the problem. But I'm pretty sure now that it's not.

The blank screen appears even if I don't have Debug/devtools enabled.

**Comment by Zacch** [comment]
I now believe this is a save related issue. I noticed that the game froze up for about five seconds exactly once per minute. When I opened devtools I could see that immediately after every freeze the message "send on channel push-game-saved" appeared on the console.

While I was digging through the bitburner source to find the origin of that message, the debugger suddenly paused automatically:
<img width="1769" alt="Screenshot 2022-08-24 at 21 55 51" src="https://user-images.githubusercontent.com/1161900/186517325-5f84b668-fc34-45d4-95df-eb7fe953ec5e.png">

So, it seems to me that

1. Auto-save is now blocking the GUI thread
2. There may be a memory issue when saving the game.

Bitburner uses 4 Gb of memory right now, and the helper uses 6 Gb. There's still plenty left on my machine, but maybe this is close to some limit.

<img width="852" alt="Screenshot 2022-08-24 at 22 38 54" src="https://user-images.githubusercontent.com/1161900/186519597-f3ad5283-9da0-49f0-918d-f8bcc9652e42.png">

Is this normal, or can I investigate further in some way?

**Comment by phyzical** [comment]
OOC how big is your save file at this time, as i know all the scripts source is included in the json of your save file. so i could see how this could be an issue with someone who has alot of scripts or a bunch of text files of logs or something.

(also 64gb mac jeeez im jealous)

**Comment by Zacch** [comment]
Aha, good point! My exported save files were 352 Mb each. I have about 3000 lines of scripts (91 files) in my repo, which shouldn't be that bad, but I had lots of old clutter lying around on the 'home' server. I did a bit of cleaning up and reduced the size of the saves with about 10 Mb – not a huge gain but there is probably more I can do here.

Another thing I did was reduce the auto saves to once every five minutes. I still get crashes but, predictably, they are much less common.

I'll have a look at my save files and see if I find any more old junk that I can get rid of!

**Comment by phyzical** [comment]
yeah that might explain whats causing it to break 😆 .

doesn't mean its an issue with your code though, we might need to consider if theres a better way to handle the save file in relation to users scripts/files though i cant think of anything off the top of my head tbh as we need to save the sources for cloud saves

**Comment by Zacch** [comment]
I solved it.
I found the **Diagnose Files** button on the settings page, and it was a big help! It seems I had a _huge_ (218 Mb) text file called **V2_0_0_API_BREAK.txt** on my home server:
<img width="824" alt="Screenshot 2022-08-28 at 08 45 18" src="https://user-images.githubusercontent.com/1161900/187061452-06611ecf-41d1-4b1d-876c-e9ead4e2bf7a.png">
 I don't know if the file got put there during the upgrade or if I managed to put it there myself somehow. At any rate, I deleted it and my save files are now down to just 4 Mb. Case closed.
