### ISSUE TITLE
Corporation Exporting is a waste of time

### ISSUE THREAD

**Issue by dlowe-net** [danielyxie/bitburner#403]
Unlocking the Export capability is not useful at all at present, and it should be great.

A corporation can buy a commodity at the Market Price (MP). Usually, though, due to quality and advertising adjustments, a corporation can sell a commodity at many times the MP. What this means that if I set up another industry, for every unit I export, I am saving MP while giving up n*MP. Since n > 2 most of the time, it almost never makes sense.

Ideally, the MP of a commodity should always be substantially more than the cost of its components, and  a corporation shouldn't be able to sell its goods for many times the MP. Perhaps the MP follows more closely the actions and pricing of the corporation?

**Comment by danielyxie** [comment]
Addressed (hopefully) in v0.42.0:

* The Market Price of an industry's produced materials are usually greater than the cost of components (the only time it won't be is if you get really unlucky with the way the market price changes)
* The sale price of a material can no longer be marked up as high without suffering a large decrease in the number of materials sold
