### ISSUE TITLE
"Find All Valid Math Expressions" has crazy long answer, must be a bug

### ISSUE THREAD

**Issue by ealmen** [danielyxie/bitburner#4033]
I got a "Find All Valid Math Expressions" contract with ["547960125941", 12] as input.
The answer is ~133 kB worth of text, pasted in that little answer box.
It accepted it, so it works, but game almost crashes and slows down a lot handling it.

This can't be right. Having an answer that big must be a bug and the contract gives you a way to long and complex problem, right?
I'm guessing the input is randomly generated, and a few inputs can really explode in length? And it doesn't check if the answer is a suitable length or not before giving you a random input.

Or am I misunderstanding something here, and it was just a lucky coincidence that it accepted my crazy answer?

My answer is too long to paste here. Full anser is attached: [crazy long answer.txt](https://github.com/danielyxie/bitburner/files/9416855/crazy.long.answer.txt)
It starts with:
["54796*0+12+5-9+4*1","54796*0+12-5+9-4*1","54796*0+1+25-9-4-1","54796*0+1+2+5+9-4-1","54796*0+1+2-5+9+4+1","54796*0+1-25+9*4*1","54796*0+1*25-9-4*1","54796*0+1*2+5+9-4*1","54796*0-1+25-9-4+1","54796*0-1+2+5+9-4+1","54796*0-1*25+9*4+1","54796*0*125+9+4-1","54796*0*12*5+9+4-1","54796*0*1+25-9-4*1","54796*0*1+2+5+9-4*1","54796*0*1-25+9*4+1","54796*0*1*25+9+4-1","54796*0*1*2*5+9+4-1","5479*6*0+12+5-9+4*1","5479*6*0+12-5+9-4*1","5479*6*0+1+25-9-4-1","5479*6*0+1+2+5+9-4-1","5479*6*0+1+2-5+9+4+1","5479*6*0+1-25+9*4*1","5479*6*0+1*25-9-4*1","5479*6*0+1*2+5+9-4*1","5479*6*0-1+25-9-4+1","5479*6*0-1+2+5+9-4+1","5479*6*0-1*25+9*4+1","5479*6*0*125+9+4-1","5479*6*0*12*5+9+4-1","5479*6*0*1+25-9-4*1","5479*6*0*1+2+5+9-4*1","5479*6*0*1-25+9*4+1","5479*6*0*1*25+9+4-1","5479*6*0*1*2*5+9+4-1","547+96*0-12*5*9+4+1","547+9+6*0-12*5*9-4*1","547+9-601+25-9+41","547+9-601+2+59-4*1","547+9-601+2+5+9+41","547+9-6*0-12*5*9-4*1","547+9*6*0-12*5*9+4+1","547-96*0-12*5*9+4+1","547-9-601+25+9+41","547-9-60+1+2-5*94+1","547-9*60+12+5-9-4+1","547-9*60+1+2*5-9+4-1","547-9*60+1-2*5+9+4+1"....

It was on version 2.0.2. Contract name was contract-897814.cct
Any other info I should provide here?

**Comment by quacksouls** [comment]
> I got a "Find All Valid Math Expressions" contract with ["547960125941", 12] as input. The answer is ~133 kB worth of text, pasted in that little answer box.

Problem data like `["547960125941", 12]` are normal when I was playing in versions before v2.0.2.  If you find that you are manually copying your answers to the solution box, you might want to consider using the Coding Contract API to automate the process.

> It accepted it, so it works, but game almost crashes and slows down a lot handling it.

I solved the above problem using an efficient implementation as well as a brute force solution.  When using the brute force implementation, it took a while to solve the problem with the given data.  However, my PC did not seem to be overloaded.  CPU usage was usually below 20% even when I have these open: Firefox browser with 3 tabs and the Steam client.  CPU is Intel Core i5-4690K @ 3.50GHz and 16GB RAM.  I was not playing the game in a browser.  You might want to review your implementation by consider using a sleep statement somewhere, i.e. `await ns.sleep(t)`, where `t` is a second or so.  Or consider using different data structures and/or reduce the memory usage of your implementation.

**Comment by phyzical** [comment]
pretty much this, most of these if not all are expected to be solved via the api

**Comment by ealmen** [comment]
Maybe this is just me, being new to the game, and getting stuck in the wrong mindset on how contracts work.
If no one else reacts to this I guess feel free to ignore me. But this sure didn't seem right to me, and that might be a hint to rework the contract a bit for an easier time for new players.

Considering you can get this contract before it is possible to answer it using the API (RAM limitations on home), I would argue that it is perhaps not a bug, but still inappropriate to give out contracts with this type of impractical to copy+paste answers.
And answering only via API shouldn't be required IMO. Scripting the finding and solving these should be done out of QOL, and should not be the only viable way to solve it.
I feel contracts should be somewhat on an equal difficulty level, compute-complexity level, and answer length level. And considering almost all contracts can be brute forced and have a relatively short answer, this one sticks out quite a bit in multiple ways.

At a minimum I think an extra note should be added, something like "NOTE: The answer can get very long, consider using the Coding Contract API to attempt this contract, rather than copy pasting in the answer.".

But I guess ignore me if I'm the only one reacting this way on that contract.

**Comment by phyzical** [comment]
your right, 

like we could say sorry this answer is too long please use api, but given the way it currently is its letting you solve it even though your screen hangs for a bit, which i think would be better than just not letting the user solve some contracts

we could like you say rework it to give easier contracts until you have the api but at the same time a user probably wants the hardest/newer ones as time goes idk

the whole premise of the coding contracts is to reflect things like advent of code, project Euler ect which you can solve maybe the first two by hand but the rest are impossible

**Comment by quacksouls** [comment]
> At a minimum I think an extra note should be added, something like "NOTE: The answer can get very long, consider using the Coding Contract API to attempt this contract, rather than copy pasting in the answer.".

Proposed update is at #4064.
