### ISSUE TITLE
Not all async functions are wrapped properly by NS1 interpreter.

### ISSUE THREAD

**Issue by Snarling** [danielyxie/bitburner#4037]
Discovered via reddit : https://www.reddit.com/r/Bitburner/comments/wx2bg6/n00b_trying_and_failing_bn13_scripting/
Player reported chargeFragment creating an unawaited promise error. Looks like stanek.chargeFragment just is not being wrapped by the NS1 async function handler.

https://github.com/danielyxie/bitburner/blob/ccbca5c38cd75ca4c89cc0c4ad42fe167187da13/src/NetscriptWorker.ts#L126-L127

stanek.chargeFragment is not the only discrepancy here, will need to fully match the list of promise-returning ns functions against the hardcoded list that is being fed to this ns1 async handler.

**Comment by Snarling** [comment]
This will be a bit more tricky to solve than I originally thought, right now the interpreter does not seem to be wrapping functions that aren't direct members of ns.

**Comment by Snarling** [comment]
Okay so right now, ns functions are wrapped 4 different ways:

1. For a hardcoded list of async functions that are direct members of ns, a custom async wrapper is used.
https://github.com/danielyxie/bitburner/blob/ccbca5c38cd75ca4c89cc0c4ad42fe167187da13/src/NetscriptWorker.ts#L126-L168

2. For a hardcoded list of functions that might use objects as their arguments, a custom wrapper is used to turn those objects into the interpreter's version.
https://github.com/danielyxie/bitburner/blob/ccbca5c38cd75ca4c89cc0c4ad42fe167187da13/src/NetscriptWorker.ts#L169-L193

3. For any other ns function that is a base member of ns, a different wrapper just return values to the pseudo versions used by the interpreter, if the returned value was an array or object.
https://github.com/danielyxie/bitburner/blob/ccbca5c38cd75ca4c89cc0c4ad42fe167187da13/src/NetscriptWorker.ts#L195-L207

4. For any deeper ns functions (not direct members of ns), the interpreter automatically wraps the function because e.g. the entire bladeburner layer is assigned using a single interpreter setProperty call.
https://github.com/danielyxie/bitburner/blob/ccbca5c38cd75ca4c89cc0c4ad42fe167187da13/src/NetscriptWorker.ts#L209-L212

Using the dev console, this is the text of the wrapper the interpreter automatically uses for those deeper ns functions, with nativeObj being the game function being wrapped. Looks like it handles return values and arguments whether they're objects/arrays or not.
```javascript
function () {
  return interpreter.nativeToPseudo(nativeObj.apply(
    interpreter,
    Array.prototype.slice.call(arguments).map(function (i) {
      return interpreter.pseudoToNative(i);
    })
  ));
}
```

I think the best way forward is to unify all of the wrapping methods under a single async wrapper, that will handle functions whether they return promises or not, and handle arguments or return values whether or not they are arrays or objects. This would remove the need for any hardcoded list of functions that apply to a specific wrapping method. Also instead of only iterating through the top layer of ns, recursively iterate through sub-levels too.

**Comment by phyzical** [comment]
in theory it sounds like a good idea, aslong as its not a monster 😆
