### ISSUE TITLE
ns.singularity.getCurrentWork() returns null when doing BladeBurner action without The Blade's Simulacrum

### ISSUE THREAD

**Issue by jwfxpr** [danielyxie/bitburner#4038]
- [x] Save file
- [x] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
- [x] Version of the game, Bitburner v2.0.2 (3067703c)

## Expected behaviour

Without _The Blade's Simulacrum_, Bladeburner actions use the player's work slot. Since this is the player's work, I expect `ns.singularity.getCurrentWork()` to return an object containing information about that work, similar to `ns.bladeburner.getCurrentAction()`. E.g.,

`{ type: "BLADEBURNER", actionName: "Training", actionType: "General" }`

With _The Blade's Simulacrum_, the player's work slot *is* empty while BB actions are being performed; in this case, I expect `ns.singularity.getCurrentWork()` to return `null`, as it usually would for an idle work slot.

## Actual behaviour

When performing a Bladeburner action without _The Blade's Simulacrum_, `ns.bladeburner.getCurrentAction()` returns `null`, despite the work slot being occupied by a Bladeburner action.

## Steps to reproduce

1. Ensure that _The Blade's Simulacrum_ augmentation is not currently installed in the player
2. Start any Bladeburner action
3. Call `ns.singularity.getCurrentAction()` and inspect the returned object

Or:

1. Import the attached save file ([bitburnerSave_1661415227_BN10x2.zip](https://github.com/danielyxie/bitburner/files/9422829/bitburnerSave_1661415227_BN10x2.zip)) and `run temp.js`:

```console
[home ~/]> run temp.js
Running script with 1 thread(s), pid 3934 and args: [].
temp.js: Is 'The Blade's Simulacrum' installed? false
temp.js: ns.singularity.getCurrentWork() returns: 'null'
temp.js: ns.bladeburner.getCurrentAction() returns: '{"type":"General","name":"Training"}'
[home ~/]> 
```

**Comment by hydroflame** [comment]
Not a bug, bladeburner actions are not work
