### ISSUE TITLE
Intelligence disappeared after updating to v2.0.2

### ISSUE THREAD

**Issue by hughperman** [danielyxie/bitburner#4045]
I was running old version (v1.7 I think?) in BitNode 5 with intelligence ~90. This was my first runthrough of Bitnode 5.

Then I reloaded, the game updated to v2.0.2, and the intelligence stat has disappeared. Base64 decode of the attached save shows it is set to 0.

[bitburnerSave_1661506267_BN5x1.json.zip](https://github.com/danielyxie/bitburner/files/9432046/bitburnerSave_1661506267_BN5x1.json.zip)

**Comment by hydroflame** [comment]
Just go to uni for 1s or gain int any other way and you'll get it back
