### ISSUE TITLE
[feature request] upload scripts

### ISSUE THREAD

**Issue by Herzfinsternis** [danielyxie/bitburner#4046]
Scripts can be downloaded, what about an upload option?

With the latest API changes in mind (see #4005 for example) it would be nice to have an option to upload scripts. So that one could download all scripts, apply changes with the help of an external editor and upload the updated scripts. Having the scripts on my hard drive lets me search and replace text in all scripts. Also, I sometimes import https://github.com/Snarling/bitburner-scripts/blob/main/BatchingReferenceSave.json to test my batching algorithm and an upload option would make it easier to get my scripts in there.

Would be nice to have...

**Comment by hydroflame** [comment]
Already exists
