### ISSUE TITLE
Persistent Toast Raises Error

### ISSUE THREAD

**Issue by zepalmer** [danielyxie/bitburner#4057]
Thank you for the delightful game that has entertained me for many hours now!  :)

In Bitburner v2.0.2, the `ns.toast` documentation indicates that the third parameter, `duration`, can be set to `null` in order to produce a persistent toast.  However, the program

```javascript
/** @param {NS} ns */
export async function main(ns) {
	ns.toast("toast", "error", null);
}
```

produces the error

```
RUNTIME ERROR
test5.js@home (PID - 63520)

toast: 'duration' should be a number.
```

This appears to be the case regardless of the toast string or toast type (e.g. `"error"`).

**Comment by phyzical** [comment]
should be resolved in dev https://github.com/danielyxie/bitburner/pull/4002
