### ISSUE TITLE
Wrong documentation of `ns.corporation.limitProductProduction`

### ISSUE THREAD

**Issue by BlobbyBob** [danielyxie/bitburner#4058]
The parameters cityName and productName of `limitProductProduction` do not match the parameter order in the documentation.

## [Netscript Function Definition](https://github.com/danielyxie/bitburner/blob/3ee55b291829854cd97cf7c929041ebcdeba6b0c/src/NetscriptFunctions/Corporation.ts#L535)
```ts
    limitProductProduction:
      (ctx: NetscriptContext) =>
      (_divisionName: unknown, _productName: unknown, _cityName: unknown, _qty: unknown): void => {
```

## [Documentation](https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.warehouseapi.limitproductproduction.md)

```ts
limitProductProduction(divisionName: string, cityName: string, productName: string, qty: number): void;
```

## Version

I've found the issue in the `dev` branch and in (through playing) in v2.0.2 (3067703c)

**Comment by BlobbyBob** [comment]
IMO this is a pretty unfortunate bug and fixing will either introduce breaking changes or an inconsistent API :see_no_evil:

**Comment by phyzical** [comment]
yeah imo avoid the breaking change and just fix the documentation

**Comment by hydroflame** [comment]
ehh, in cases like these fixing the code makes more sense.

Since BlobbyBob is the first to mention this we can assume this function sees very little use.

**Comment by BlobbyBob** [comment]
Personally, I would also prefer an API fix as it is much cleaner.  
Breaking backwards-compatibility is always very annoying, but as @hydroflame said: The bug has been there for a long time and everyone that tries to use this function stumbles upon it, so there must have only been very few people using that function.

Besides, fixing only the documentation would probably still cause issues for many people trying to use the Warehouse API as everyone would expect `limitProductProduction` and `limitMaterialProduction` to have the same argument order.
