### ISSUE TITLE
Add support to buy items from the darkweb via scripts

### ISSUE THREAD

**Issue by Draco18s** [danielyxie/bitburner#4066]
- [x] Version of the game, e.g. Bitburner v2.0.2

Kinda surprised this wasn't already part of the scripting API. I tried an `ns.exec('buy','darkweb',1,'relaySMTP.exe')` but that failed due to no script named `buy` on the server. Similarly `ns.buy('relaySMTP.exe')` is not a function.

**Comment by quacksouls** [comment]
I remember the functionality is locked behind the Singularity API.  You must destroy at least BitNode 4.1 to unlock this API.  The relevant function is `ns.singularity.purchaseProgram(programName)`.

**Comment by Draco18s** [comment]
Ahhh. Ok. Yeah, haven't gotten anywhere near that far in yet (I haven't even found any bitnodes, that I am aware of).
It wasn't anywhere in the documentation, even under spoilery things (and I still have no idea what methods the Formulas api actually grants access to...).

**Comment by phyzical** [comment]
@Draco18s from memory that's by design to avoid spoilers you'll get there ;)
