### ISSUE TITLE
Contracts with apostrophes can't be run

### ISSUE THREAD

**Issue by Draco18s** [danielyxie/bitburner#4067]
[home ~/]> connect hong-fang-tea
    Connected to hong-fang-tea
    [hong-fang-tea ~/]> ls
    brighter-than-the-sun.lit 
    contract-412281-Joe'sGuns.cct 
    [hong-fang-tea ~/]> run contract-412281-Joe'sGuns.cct 
    No such contract

Note that I used autocomplete to fill out the contract name.

There's another one on deltaone (`run getconnectionpathto.js deltaone` to get the connection chain, its long) that also does this.

- [x] Save file: [contracts-bug.zip](https://github.com/danielyxie/bitburner/files/9456873/contracts-bug.zip)
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v2.0.2

**Comment by Draco18s** [comment]
Update, the `'` needs to be escaped and then it can be run.
Either the autocomplete needs to autoescape or the game just shouldn't generate filenames with `'` and similar characters.

**Comment by quacksouls** [comment]
Autocompletion in the game is not as feature rich as say under the Bash environment of Linux/UNIX.  Anyway, the game already has one way to escape single quotation marks, i.e. use the double quotation marks to delimit whatever you want to consider as a string, so
`run "contract-412281-Joe'sGuns.cct"`.

**Comment by hydroflame** [comment]
Let's remove special characters from contract names when generating them. only like [a-zA-Z0-9]
