### ISSUE TITLE
growthAnalyzeSecurity returns wrong values

### ISSUE THREAD

**Issue by n-gist** [danielyxie/bitburner#4071]
v.2.0.2 (3067703c)

The code:

```
const grow1 = threads * ns.growthAnalyzeSecurity(1, server, 1);
const grow2 = ns.growthAnalyzeSecurity(threads, server, 1);
ns.tprint(`${server} ${threads}, ${grow1}/{$grow2}`);
```
Outputs:
`foodnprint 135, 0.54/0.092`

If I check the actual security increase by `ns.getServerSecurityLevel(server)` after grow, grow1 appears to be the correct one:
Security increases from 3 to 3.54 (hacking level about 500)

**Comment by n-gist** [comment]
It appears to be inconsistent. Now I get the same values for grow1 and grow2 even though the code hasn't changed.

**Comment by Snarling** [comment]
Intended behavior. The security increase from grow is capped by how many threads you need to max out the money on the targeted server. So if you only needed 20 threads to max out the server, but you try analyzing for 40 threads, you will only see the security increase from 20 threads.

You can run growthAnalyzeSecurity with no server input to prevent seeing this cap out effect:

```javascript
const grow1 = ns.growthAnalyzeSecurity(threads);
//or with cores taken into account,
const grow2 = ns.growthAnalyzeSecurity(threads, undefined, cores);
```

**Comment by n-gist** [comment]
Makes sense, thank you!
