### ISSUE TITLE
No way to iterate corporation products to use ns.corporation.discontinueProduct()?

### ISSUE THREAD

**Issue by Cle-O** [danielyxie/bitburner#4075]
There doesn't seem to be a proper way to handle corporation products (Drugs, Tobacco, ...) after they have been desgined.
Yes, there is division.products, but this only returns numbers. Example:

```
const divisionName = "Pharmaceutical";
const divisions = await ns.corporation.getCorporation().divisions;
const division = divisions.find((d) => d.name == divisionName);

for (const p in division.products) {
   ns.tprint("Found product: " + p);
}
```
Gives the output: 
```
autoCorp.js: Found product: 0
autoCorp.js: Found product: 1
autoCorp.js: Found product: 2
autoCorp.js: Found product: 3
autoCorp.js: Found product: 4
```

This is a problem since the API to discontinue a product expects a product NAME, not an index. 
I cant find any other documented way to query currently available products for a division.
Also, it would be nice to have a way to get the design cost for a product. 
A nice clean ns.corporation.getProducts(division) that returns Product[] would come in very handy...

**Comment by hydroflame** [comment]
for of, not for in
