### ISSUE TITLE
bitburner.ns.kill.md

### ISSUE THREAD

**Issue by RiscaYin** [danielyxie/bitburner#4076]
relevant: Bad Documentation

You asked many questions but since this is documentation I do not see how any of that is relevant.

Now I do see we have two documents for kill, and maybe this document should just be deleted.
Or the examples do not make any sense in this document.  Since none do a kill by pid, but the other document days script name or pid.

kill(script: number): boolean;
example in the document:
//The following will try to kill a script named foo.script on the current server that was ran with the arguments 1 and “foodnstuff”:
ns.kill("foo.script", getHostname(), 1, "foodnstuff");

This a) does not fit the kill(script: number): boolean at all, but using the example I got the detail I needed but I probably should have looked at the other page.  Still, this all seems off to me.

**Comment by OneOfMany07** [comment]
It might be worth a URL or two here.  Also the title isn't very descriptive if you don't already know the contents of the bug.

I'm pretty new, but so far...  the kill(...) entry is NS1 vs. ns.kill(...) is NS2.  They'll be similar, but I'm not sure if exactly the same.

And I've noticed issues with the documentation too.  If you feel up to it, you might try fixing it and offering a pull request.
