### ISSUE TITLE
log output windows are reset after infiltration missions

### ISSUE THREAD

**Issue by kitoma** [danielyxie/bitburner#4077]
[ ] Version of the game: Bitburner v2.0.2 (3067703c)
[ ] Steps to reproduce:
- run any script
- open its log output via "tail", move and resize the window to a convenient position
- open the infiltration UI via: city interface / select any corporate entity / infiltrate company
- observe the main UI is gone and replaced by the infiltration difficulty window
- close the window via "cancel" (or finish the mission - both works)
- now observe the position of your log output windows have reset
-> expected behavior: window positions do not reset

**Comment by jhollowe** [comment]
I experience the same.

**Comment by hydroflame** [comment]
dup
