### ISSUE TITLE
Corporation Selling keywords don't work with Math

### ISSUE THREAD

**Issue by beardyman** [danielyxie/bitburner#4097]
Version 2.0.2

I can't seem to get keywords for selling product quantities to work.  'PROD-50' as described in the help gives an "invalid" error.  I have similar issues for 'MAX-50'.  PROD and MAX seem to work fine on their own, however expressions using these values return an error and don't update the settings.

This does not seem to apply to the selling amount.  'MP+100' or 'MP-100' seems to work just fine.

**Comment by Mughur** [comment]
Can't reproduce in either 2.0.2 nor 2.1. In both versions `PROD`, `MAX`, `MAX-PROD` and `MAX/2+PROD/2+2` all works just fine.
