### ISSUE TITLE
Coding Contracts API does not list script as having incurred income

### ISSUE THREAD

**Issue by Draco18s** [danielyxie/bitburner#4098]
This will explain better:
![image](https://user-images.githubusercontent.com/1750680/189553020-437a4eef-7b70-43ae-8367-6f7844514147.png)

Stock trades denote value-earned as "production," but coding contracts do not (and probably should).

Save was made shortly after running the relevant script, however if you let the game run long enough to generate more contracts (or have a way of just injecting them) then run (from home) `findcontracts.js --submit` which will attempt to solve any coding contracts that  I have solutions for and submit the answers automatically (there's a minimum of 4 scripts involved for this: `findcontracts.js`, `contracts/autosolve.js`, `contracts/wrapper.js`, and then the actual solvers themselves; look at `autosolve` to see which contracts are handled, it's most, but not all, of them).

TBH not actually sure if the scripts are included in the savefile, and if not, where they're stored instead.

Essentially just need to solve a coding contract that awards money via script.

- [x] Save file [bitburnerSave_1662938219_BN1x1.zip](https://github.com/danielyxie/bitburner/files/9543706/bitburnerSave_1662938219_BN1x1.zip)
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v2.0.2

**Comment by quacksouls** [comment]
The script `findcontracts.js` finds Coding Contracts.  If one is found, it launches `contracts/autosolve.js` to solve any contracts found.  So `findcontracts.js` is not solving any contracts at all so it's not making money.  The real workhorse is `contracts/autosolve.js`, which solves contracts and generates money.  You might be looking at the wrong script to tell how much money it generates.  However, even if you let `contracts/autosolve.js` run in an infinite loop, looking for contracts to solve and solve them, the status viewer as shown in your image would show `contracts/autosolve.js` as generating zero income.  Indeed, you are pointing out a weird issue with how generated income is reported in the status viewer.

**Comment by Draco18s** [comment]
It's not calling `run()` or `exec()`, its using an imported function, so the "script actually doing the work" doesn't appear in the "recently killed" list: only `findcontracts.js`.

(Similarly, the workhorse isn't `contracts/autosolve.js` because it too is calling an imported function from `contracts/wrapper.js` which is where the actual submission happens).

**Comment by quacksouls** [comment]
> It's not calling `run()` or `exec()`, its using an imported function (it was at one time, but I adjusted that as I thought that that might be the case, but finding the instance of `autosolve` that had actually _submitted_ an answer when there were dozens wasn't feasible), so the "script actually doing the work" doesn't appear in the "recently killed" list: only `findcontracts.js`.
> 
> (Similarly, the workhorse isn't `contracts/autosolve.js` because it too is calling an imported function from `contracts/wrapper.js` which is where the actual submission happens; autosolve is just the map from "type of contract" to "solver method").

Thank you for this.  Comment is fixed.  The behaviour you pointed out has been there for a long time.  Maybe it's time for production to include income from Coding Contracts.  Perhaps it's not included because money from solving a Coding Contract is classified as reward.

**Comment by Draco18s** [comment]
> Perhaps it's not included because money from solving a Coding Contract is classified as reward.

Could be! Just thought it was odd that it wasn't included and didn't see an existing report.
