### ISSUE TITLE
The "connect()" function doesn't work like it should in a script

### ISSUE THREAD

**Issue by Foliage-cloud** [danielyxie/bitburner#4099]
I'm playing v2.0.0 on Steam in Easy Mode

If, in a script, I define variable x as string y from array z:

y=1
x=z[y];

and then type the following: 

connect(x);

And save and run the .script file that it's in, the game will throw this error at me:

RUNTIME ERROR
nameofscript@home (PID #)

ReferenceError: connect is not defined (Line Number 23)

It is referencing the correct line number of the first instance of the command. Everything else in the script works perfectly. 

The game gives a RAM cost of 32.00 GB for the connect function when its in the script. I think that might be an issue too.

**Comment by KlauzWayne** [comment]
It was removed in the latest update of the game.
You can instead access all servers directly via scripting, without connecting in the first place.
Simply try something like:
```
brutessh("zer0")
nuke("foodnstuff")
let x = "omega-net"
hack(x)
```

Only exception i know of is the backdoor task, scripting that requires you to have the Singularity bitnode unlocked. That connect feature still works for me as intended.

**Comment by Mughur** [comment]
It's incorrect to say that connect() has been removed, since it, and all other singularity functions, were moved to under the singularity namespace
