### ISSUE TITLE
React300 Error while calling travelToCity after Infiltration

### ISSUE THREAD

**Issue by JoschiGrey** [danielyxie/bitburner#4100]
After programmatically finishing an infiltration, ns.singularity.travelToCity() will return true, but the UI does not update to the new city.
A call to ns.singularity.goToLocation() in this state will cause a React300 Error https://reactjs.org/docs/error-decoder.html/?invariant=300.

Manually clicking on any location while the script is sleeping and before the travel call will prevent the error from happening.
Using goToLocation() to any other location in your current city before the travelToCity() call will also prevent the error.

Steps to reproduce: Start the Save File and run Singularity/Singularity.js
Version:  Bitburner v2.0.2

[NeededScripts.zip](https://github.com/danielyxie/bitburner/files/9548956/NeededScripts.zip)

**Comment by hydroflame** [comment]
This could use some investigation but given it's after programatically doing infiltration (which you're not supposed to do) we might just not care.
