### ISSUE TITLE
Joined Daedalus, Fl1ght.exe says I have work to do

### ISSUE THREAD

**Issue by Draco18s** [danielyxie/bitburner#4108]
[home ~/]> run fl1ght.exe
    Augmentations: 56 / 30
    Money: $26.754t / $100b
    Hacking skill: 1402 / 2500

Despite my hacking skill being 1100 lower than listed, I was still offered an invitation to Daedalus and was able to join. I'm not actually sure when it was offered to me, just sometime after 1100 and at or before 1400.

- [x] Save file [bitburnerSave_1663270432_BN1x1.zip](https://github.com/danielyxie/bitburner/files/9578430/bitburnerSave_1663270432_BN1x1.zip)
- [x] Version of the game, e.g. Bitburner v2.0.2

**Comment by phyzical** [comment]
closable
