### ISSUE TITLE
Suggestion: auto save game on vscode file api interactions

### ISSUE THREAD

**Issue by pimdeheer** [danielyxie/bitburner#4109]
With the ingame editor there is the feature/setting to autosave the game when saving a script. 

A very handy feature when you save a script, run it and you find out you accidentally created an infinite loop.

Suggestion to have this autosave also apply when 'saving' scripts through the vscode integration file api in the electron app.

So saving a file in vscode will call the file api to upload the file. If succesful upload the api will also run the autosave code if the setting is set to true to save the game.

Thank you, love the game !

**Comment by Hoekstraa** [comment]
This sounds relevant for both the Electron/HTTP API, and it's replacement, Remote File API.
