### ISSUE TITLE
Can join opposing city factions if done quickly with singularity functions

### ISSUE THREAD

**Issue by typicalTYLER** [danielyxie/bitburner#411]
I have a script that boils down to this:

```
invitations = checkFactionInvitations();
for (var i = 0; i < invitations.length; i++) {
    joinFaction(invitations[i]);
}
```
And if I have all the city invitations available I'm able to join them all when I run this script. (Sector-12 is left out since I had collected its unique augment before)

![image](https://user-images.githubusercontent.com/6762150/43487308-e258b0a0-94db-11e8-9858-c87cc79d8c84.png)

**Comment by danielyxie** [comment]
Should be fixed in v0.40.2. Let me know if not
