### ISSUE TITLE
Inconsistent probability for generating a Coding Contract

### ISSUE THREAD

**Issue by quacksouls** [danielyxie/bitburner#4110]
At this line

https://github.com/danielyxie/bitburner/blob/dev/src/engine.tsx#L223

it says that while the game is running, there is at most 25% chance (less than or equal to 25%) to generate a CCT every 10 minutes.  At this line

https://github.com/danielyxie/bitburner/blob/dev/src/engine.tsx#L265

it says that after being offline for a while, when you load the game again you have less than 25% chance (any percentage less than 25%) for the game to generate a CCT.  Possible typo fix: change line 265 from

`if (Math.random() < 0.25) numContracts++;`

to

`if (Math.random() <= 0.25) numContracts++;`

**Comment by hydroflame** [comment]
```js
const test = (f) => {
    let success = 0;
    let attempt = 1e9;
    for(let i = 0; i < attempt; i++) {
        if(f(Math.random())) success++;
    }
    console.log(success/attempt);
}

test((x) => x < 0.25); // 0.249984778
test((x) => x <= 0.25); // 0.249987414
```

You're not wrong but the difference is soooo small nobody would ever notice.

**Comment by quacksouls** [comment]
> You're not wrong but the difference is soooo small nobody would ever notice.

You notice the discrepancy and so do I.  At least both of us know this gives an unfair advantage when the game is left running for a long time.  A player should not be penalized with a possibly smaller number of Coding Contracts because they left the game offline for some amount of time.
