### ISSUE TITLE
TypeError: s is undefined (at "Sleeves")

### ISSUE THREAD

**Issue by coding-mic** [danielyxie/bitburner#4112]
### How did this happen?
The error occurs after you quit working for a company during a sleeve is still working for it and you try to switch to the Sleeves page.

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [x] Steps to reproduce
   - get a job for megacorp
   - start working for megacorp  with a sleeve
   - quit the job
   - switch to Sleeves page

### Environment

* Error: TypeError: s is undefined
* Page: Sleeves
* Version: v2.0.2 (3067703c)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0
* Features: lang=de cookiesEnabled=true doNotTrack=1 indexedDb=true
* Source: https://danielyxie.github.io/bitburner/dist/main.bundle.js

### Save
```
Copy your save here if possible
```

**Comment by phyzical** [comment]
unable to reproduce issue in dev or master, i believe this has been fixed and should work as expected in the next release
