### ISSUE TITLE
In gang faction, info icon for The Red Pill is missing info

### ISSUE THREAD

**Issue by quacksouls** [danielyxie/bitburner#4113]
I have a gang within Slum Snakes.  The faction allows me to purchase Augmentations that were previously exclusive to various factions.  If I have enough reputation within Slum Snakes, I can also purchase The Red Pill.

In the interface that shows a list of Augmentations, some Augs have a yellow information star (or icon) next to them.  I hover my mouse over the yellow information icon, it tells me that I can purchase the corresponding Aug from my gang faction as well as the exclusive faction.  For example, hovering my mouse over the yellow info icon for The Red Pill, it should say that I can purchase this Aug from Daedalus and also from my gang faction.  But the yellow info icon for The Red Pill does not say I can purchase it from some gangs.  See the images below for reference.

Version 2.0.2.

![TRP-text](https://user-images.githubusercontent.com/66396308/190844850-c55f3e00-cef6-4293-bc26-8443d6e909f7.png)
![hydroflame-left-arm](https://user-images.githubusercontent.com/66396308/190844854-166b0d92-f566-4c31-bcf7-3c2fc9bafd40.png)

[bitburnerSave_1663397730_BN2x4.zip](https://github.com/danielyxie/bitburner/files/9591154/bitburnerSave_1663397730_BN2x4.zip)

**Comment by hydroflame** [comment]
Technically correct but were going to ignore it because its not very important.

But for those interested it's because TRP is a very special edge case in that it's ONLY available to gangs in BN2
