### ISSUE TITLE
Issue new shares of 100% owned company still allows non-existent private investor buy.

### ISSUE THREAD

**Issue by sircracked** [danielyxie/bitburner#4114]
Corp fully owned by player, when issuing new shares, still has shares claimed by non-existent "Private investors".

Reproduce
Start a corp with your own funding
Go public, and buy back any shares invested.  
Issue new shares
Popup will confirm new shares issues and a percentage taken by private investors, despite having owned 100% of the company and shares

Version 2.0.2 (3067703c)

Presumed correct behavior:
Number of shares available to private investors would be responsive to how many, if any private shares actually exist, if any.  It seems odd that a private investor who presently owns 10% of the present shares would be entitled to purchase more than 10% (or 5% if limited by a 50% margin), of newly issued shares.  But that aside, if there are literally NO current private shares, meaning no private investors, and all public shares are owned by me (this really ought not matter, since even if I don't own 100% of all private shares, publicly tradable shares shouldn't become privately held priority shares entitled to a first right anyway, but, that's moot in this test case by owning 100% of all publicly tradable shares as well), Nobody should have any priority claim to any public share issue besides me, unless someone can explain something really fundamental I'm missing here, or something that's being simulated but not well communicated.

![BitburnCorp1](https://user-images.githubusercontent.com/37780031/190955147-65c51e2e-c4a2-43ab-8d2b-f6c374138ec0.png)
![BitburnCorp2](https://user-images.githubusercontent.com/37780031/190955167-bed718ca-3599-4bad-ba5b-2fc48639baa1.png)

**Comment by phyzical** [comment]
from my testing on dev private investors get nothing unless i choose to take on private investors

**Comment by Mughur** [comment]
https://github.com/danielyxie/bitburner/commit/f3bf872b238307220188cf983fc10d520e01e0c1
This is fixed in April, shouldn't happen 2.x.
