### ISSUE TITLE
I have quit the job while Sleeve was working if this  can be the reason :)

### ISSUE THREAD

**Issue by adrian-vondracek** [danielyxie/bitburner#4116]
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v1.3.0 (216bf616)

**Comment by adrian-vondracek** [comment]
I have quit the job while sleeve was working on it, Nothing unusual else was happening while this chush occured.

**Comment by adrian-vondracek** [comment]
Yup, now when I'm entering Sleeve menu tab I'm generating another crush, also my production in another job is freezed.

**Comment by phyzical** [comment]
unable to reproduce issue in dev or master, i believe this has been fixed and should work as expected in the next release
