### ISSUE TITLE
There's no achievement for completing BN 13

### ISSUE THREAD

**Issue by Zacch** [danielyxie/bitburner#4123]
I guess the title says it all. There  are achievements for acquiring SF1.1, 2.1, 3.1 and so on up to 12.1, but there is no "Acquire SF13.1" achievement – I checked the latest AchievementData.json in the repository. I also checked the BN14 branch here on GitHub but there's no new achievement there either so it might make sense to add an SF14.1 achievement there while you are at it.

Thank you for all your work with this awesome game!

**Comment by phyzical** [comment]
i think the reason interest was lost with achievements was possibly as steam wouldn't allow anymore. i may be wrong though.

**Comment by hydroflame** [comment]
I think were at like 97 / 100 but we could spare one for that.

**Comment by c-goldschmidt** [comment]
Are more achievements a paid feature? i own a lot of games that have like 150+ achievements. Also Bitburner currently has 98.

**Comment by Zacch** [comment]
I found this on [Steamworks](https://partner.steamgames.com/doc/features/achievements):

"By default, games are limited to 100 achievements at first. Reach out to us via the "Support" option at the top of this page if you have questions about this."

**Comment by phyzical** [comment]
i think hydro has tried to up the limit in the past (may be wrong)

**Comment by Zacch** [comment]
Hmm, then we could perhaps have an achievement for completing _all_ the bit nodes? That would continue to be something to aim for when more bit nodes are added in the future.

I guess that once a player has got an achievement they keep it, so you wouldn't lose it every time a new bit node is added.
