### ISSUE TITLE
Game crash in Corp screen when selecting "Food" sector

### ISSUE THREAD

**Issue by ceckert2194** [danielyxie/bitburner#4124]
### How did this happen?
Not sure what's throwing the error, I just clicked on the 'Food' sector in my Corp screen & the game immediately crashes.

Please fill this information with details if relevant.

- [ ] Save file: below
- [ ] Minimal scripts to reproduce the issue: no scripts
- [ ] Steps to reproduce: Select 'poop food' in the Corp screen.

### Environment

* Error: SyntaxError: Unexpected number
* Page: Corporation
* Version: v2.0.2 (3067703c)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/1.6.4 Chrome/93.0.4577.82 Electron/14.2.4 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save

[RECOVERY_BITBURNER_1663708406.zip](https://github.com/danielyxie/bitburner/files/9611363/RECOVERY_BITBURNER_1663708406.zip)

**Comment by Mughur** [comment]
Looking at your corp makes me sad and I couldn't reproduce the issue :(
Random errors do happen, so unless it happens again for you or somebody else, there unfortunately isn't much we can do about it. At least I haven't heard of anyone getting a `Unexpected number` error from corps

**Comment by ceckert2194** [comment]
Well that's good that no one else is getting the same issue.. I did just avoid that tab & it cleared itself up it seems... thanks for taking a look :)
