### ISSUE TITLE
Cannot see/use right edge text/buttons on Hacknet Nodes page at half screen width (1440p)

### ISSUE THREAD

**Issue by OneOfMany07** [danielyxie/bitburner#4128]
When I have 3 purchased Hacknet nodes or more then at least one will be displayed off screen, and there isn't a scroll bar to access them with.

Only way to see the text and buttons is to expand the window beyond half my screen (I often put 2 different windows on the 2 halves of my 1440p screen, like now for the game + bug in a browser).  No idea if other pages have the same issue.  I just started playing again.

Version of the game v2.0.2 (3067703c) off Steam.

![missing-button-offscreen](https://user-images.githubusercontent.com/749208/191672613-3ebba5e1-b24f-4c14-8a77-354d72a0b03f.png)

**Comment by MaWo2** [comment]
Have you tried moving it around?
I sometimes play Bitburner in browser on a tablet and have the same issue. However, I can move the content of the frame around, although no scrollbar is displayed.
Admittedly, I mostly use my touchscreen for this, but a scrollmouse also works.

**Comment by OneOfMany07** [comment]
This is a PC with the steam version.  That was the whole window.  There are no panes or scroll bars (as you can see...I didn't crop anything inside the game window).  I can't grab the UI if that's what you were hoping.  When I click and drag I start to highlight text.

I just realized I have been using the mouse wheel to scroll up/down, and there isn't a scroll bar for that either.  I tried side to side scrolling (tilt wheel right or left) and it moved.  I've never used that in day to day tasks.  It always moves too slowly to be of much use in large areas (can't scroll quicker/slower...could be neat to make a scroll ball on a mouse someday).

I'd think that adding scroll bars in the UI is the best solution.  Assuming we won't/can't shrink the content to the display area instead.

**Comment by borisflagell** [comment]
I've some code that fixed that in an unfinished project.
I'll submit something.
