### ISSUE TITLE
Bug or Feature: membership in Megacorp faction immediately available after augmentation in BN3

### ISSUE THREAD

**Issue by MaWo2** [danielyxie/bitburner#4130]
While in BN 3, I noticed a strange behaviour of the Megacorp factions (Four Sigma and Fulcrum Secret Tech):
- I had worked myself into the two factions (I did not test other megacorps).
- After installing augmentations, I immediately had these factions available again in the factions menu.
- All other factions required fulfiling their requisites (100m for Sector-12, backdooring faction servers, or having 100b and 2500 hacking again for Deadalus). I did not even have to backdoor the fulcrumassets-server again.

Is this behaviour intended?
If so, I suggest to mention it in the faction documentation.

Unfortunately, I have not joined Megacorps in BN1 and am still not long enough in BN10 to test it.
Can somebody test this in other bitnodes?

- [X] Steps to reproduce
  - Become a member of the Megacorp faction
  - install augmentation
  - Megacorp faction is immediately available again, while all other factions first need their requisites fulfiled
- [X] Version of the game, e.g. Bitburner v2.0.2 (3067703c)

**Comment by hydroflame** [comment]
Not a bug

**Comment by MaWo2** [comment]
O.K., good to know.
