### ISSUE TITLE
`ns.scp` results in out-of-date RAM cost on destination server

### ISSUE THREAD

**Issue by alainbryden** [danielyxie/bitburner#4138]
Version: 2.1.0 (87054f61) - Dev

Problem:
If a script exists and is overwritten by `ns.scp`, it retains its old computed RAM cost.

Demonstration:
![image](https://user-images.githubusercontent.com/2285037/191964304-beda99f2-0059-4c47-8ece-b8eba2e67341.png)

Note: Terminal `scp` does not have this issue:
![image](https://user-images.githubusercontent.com/2285037/191963581-24e6c2a8-1ee1-47a2-8b11-b0988bde9fe7.png)

Note: The contents of the script are copied over successfully, only the RAM footprint is out of date:
![image](https://user-images.githubusercontent.com/2285037/191964384-c8e6e06a-20de-42e5-9373-cebe1f3df2d3.png)

**Comment by Snarling** [comment]
![image](https://user-images.githubusercontent.com/84951833/192289623-b76e074d-eb2d-4522-b671-e86611ab2db7.png)
Submitting a PR to fix...
