### ISSUE TITLE
AtExit clashes with ns-await

### ISSUE THREAD

**Issue by Draco18s** [danielyxie/bitburner#4143]
`atExit` is a delegate method that gets called when the script terminates. However, this method can't do anything ***useful*** (such as saving its state data to a file!) if the script being terminated is currently `await`ing for any reason.

For example, this script can only ever terminate with a runtime error when killed with `kill` and will fail to print anything to the console:

	export async function main(ns) {
		ns.atExit(() => {
			ns.tprint('Critical Error'); //this will never print
		});
		while(true) {
			await ns.sleep(200);
		}
	}

Yet there is no way to wait for the `await` to complete before running the atExit portion of the code as (1) the script is already awaiting which would throw an error and (2) there is no control over *when* a script is terminated as it is (usually) an external process.

Suggestions:

1. Ignore any existing await errors when calling atExit (they're going to be interrupted anyway)
2. Interrupt await calls *before* calling atExit
3. Add a `isAwaiting()` method/property (although if this is true and the script still wants to do something on exit, it would have to be awaitable itself, and (1) comes back into play again, although it could be more of a localized "if await was called on isAwaiting, don't error" type of situation).
4. If the await that is active is `sleep`, let it complete first, then exit

- [x] Save file [bitburnerSave_1663868241_BN1x1.zip](https://github.com/danielyxie/bitburner/files/9636331/bitburnerSave_1663868241_BN1x1.zip)
- [x] Minimal scripts to reproduce the issue
  - Run `kill invest.js` upon loading the save
- [x] Version of the game, e.g. Bitburner v2.0.2

**Comment by Snarling** [comment]
The delay was already being killed before atExit, but it was not clearing the runningFn flag, which is what determines whether you get a concurrency error. Submitted a PR to fix.

**Comment by Draco18s** [comment]
That makes sense, I didn't dive into the code to figure out how ns await functions were actually handled. I have for a few other things, but I didn't really feel like examining the JS runtime code. 😅

**Comment by Snarling** [comment]
This is fixed by #4122, which included the fix from #4158
