### ISSUE TITLE
Scripts must be saved after imported scripts are created

### ISSUE THREAD

**Issue by JasonGoemaat** [danielyxie/bitburner#4154]
I found [this problem](https://www.reddit.com/r/Bitburner/comments/g1mbl4/unable_to_use_imports/) searching for my issue and it is pretty old.   I bet it is the same problem I have now (recent 9/20ish dev code).   The script gives an import error if the imported script was created after the running script.  I run into this when using scp() to copy multiple files at once to a remote server, but it has the same problem creating files out-of-order locally.

To reproduce:

1. `nano remote/t1.js` and save contents:
    ```js
    import { default as t } from '/lib/t2.js'
    
    /** @param {NS} ns */
    export async function main(ns) {
    	ns.tprint(t.sayHello('world'))
    }
    ```
2. Attempt to run the script without the library present and an expected error occurs. ***required for the error to occur at step 4***
3. 'nano lib/t2.js' and save contents:
    ```js
    export default {
    	sayHello: name => `Hello, ${name}!`
    }
    ```
4. `run remote/t1.js` and you still get the error even though the library is present ***this is the error***
5. `nano remote/t1.js` and simply save the file without making any changes 
6. `run remote/t1.js` and the script works

Saving the file in step 4 must re-wire the imports

**Comment by Snarling** [comment]
Could not reproduce error on either 2.1.0 or 2.0.2 using your exact scripts.

**Comment by Snarling** [comment]
Looks like this is confirmed to some extent via https://www.reddit.com/r/Bitburner/comments/xoxlsm/bug_error_on_file_import_but_file_is_present/

**Comment by JasonGoemaat** [comment]
I just did it on https://danielyxie.github.io/bitburner with another script where I saved the script first.  I get the error running it when the imported library isn't there as expected.  But then I created the library and still get the error.  I only stopped getting the error once I opened the script and saved it again.

**Comment by Snarling** [comment]
Oh okay that makes sense. When you run it the first time, it compiles and has an error. When you update the imported library, it doesn't realize it needs to recompile and still has the error from the first time. Should be able to fix this.
