### ISSUE TITLE
BN3 - Stuck with $0 in Volhaven with no corp, although I should make money!?

### ISSUE THREAD

**Issue by RipperFox** [danielyxie/bitburner#4177]
Bitburner v2.1.0 running current https://github.com/alainbryden/bitburner-scripts
Problem exists without any script running however.

Seems I somehow produced a deadlock (variable overflow maybe?) because I'm stuck in Volhaven and can't go to Sector-12 to start a corp.
At least working or gangs should make money - but I'm somehow stuck at $0.000

See attached save:

[bitburnerSave_1664381512_BN3x1.zip](https://github.com/danielyxie/bitburner/files/9666946/bitburnerSave_1664381512_BN3x1.zip)

**Comment by borisflagell** [comment]
It has something to do with that error, visible in Browser's developer mode console : 
MoneySourceTracker.record() called with invalid source: hacking

The issue disappear when bitfluming, or doing a soft reset.
