### ISSUE TITLE
Invalid stock symbol for any symbol in most stock functions

### ISSUE THREAD

**Issue by NoctalIvan** [danielyxie/bitburner#4184]
Version : v2.1.0
Noticed today (I'm new so I didn't play stocks until now)

In stock API, for any stock I tried, any `stock` function I tried crashes with error `Invalid stock symbol`

Repro step : 
- Create a script market.js
- In main, paste `ns.stock.getPrice('FISG')` - or any other symbol I tried
- Run

Expected : price got
Actual : crash with `Invalid stock symbol`

Issue exists also with every `stock` method I tried which took a symbol as a parameter (getPrice, getEstimation, getVolatility)

<img width="410" alt="image" src="https://user-images.githubusercontent.com/16665488/193156575-815ceef9-7e06-4803-bba6-c750b01356ee.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/16665488/193156607-08e7e43e-59b1-417e-ad18-9eafc5bd980f.png">

Having a blast on BitBurner, cheers from France !

**Comment by Snarling** [comment]
This is because FISG is not a valid stock symbol.

The "bug" is that the documentation lists invalid symbol `FISG` as the example stock symbol in the getPrice usage example.

**Comment by Draco18s** [comment]
It should be FSIG for **F**our **Sig**ma

**Comment by quacksouls** [comment]
This is probably a weirdness (or bug?) related to the version of Bitburner you used to export your save file.  Attached is a save file that I'm sure was exported using a version prior to v2.1.0.  It's the file `BN1x4_SQLInject.json` from here:

https://github.com/quacksouls/bitburner/tree/main/data/program/intelligence

Load the attached save file into the online version of the game.  Create this script:
```js
/** @param {NS} ns */
export async function main(ns) {
    // The price of a stock.  Require the following:
    //
    // (1) A WSE account.
    // (2) Access to the TIX API.
    const sym = ns.stock.getSymbols()[0];
    ns.tprint(sym);
    ns.tprint(ns.stock.getPrice(sym));
}
```
Run the script and I got the error in the attached image.  Still using the given save file, export it to your computer.  Now load your exported save file into the online version of the game.  Run the script again.

[pre-v2.1.json.zip](https://github.com/danielyxie/bitburner/files/9687984/pre-v2.1.json.zip)
![getPrice-error](https://user-images.githubusercontent.com/66396308/193364845-acd458ce-dd9c-437f-90b4-bb0a552ca8ef.png)

**Comment by Draco18s** [comment]
I'm running on a save exported from 2.0.2 (something wonky happened overnight that caused the stockmarket and contract generation from updating for 11 hours) and that script runs just fine for me.
