### ISSUE TITLE
Employee Energy/Morale/Happiness goes up, not down

### ISSUE THREAD

**Issue by Draco18s** [danielyxie/bitburner#4191]
No upgrades required. Employee happiness, morale, and energy all steadily rise to 100 without having to do anything at all.

This appears to be due to two factors:

Loss is [`0.003` per market cycle](https://github.com/danielyxie/bitburner/blob/dev/src/Corporation/Employee.ts#L60) but the corporation making a profit raises the values [by 1% of current](https://github.com/danielyxie/bitburner/blob/be553f3548b0082794f7aa12c594d6dad8b91336/src/Corporation/OfficeSpace.ts#L113-L140) per market cycle. (Literally it requires the corp to be both bankrupt *and* insolvent for hap/ene/mor to go down, as long as one or the other is positive, the loss per cycle is almost irrelevant)

As long as employee hap/ene/mor are greater than `0.033` (range 0 to 100) then this math will cause steady increases. This causes the autoCoffee and autoParty research upgrades to be completely irrelevant. Even if the loss was meant to be on a 0-1 scale (so multiply it by 100), it still doesn't overcome the 1% rise from a profitable corporation until the initial value falls below `3.3`. Given that employee values are random between [50 and 100](https://github.com/danielyxie/bitburner/blob/dev/src/Corporation/Employee.ts#L42-L44) this will still never occur. The loss per cycle would need to be on the order of `9.1` in order to pull employees down from the base cap of 100 with the 1% rise per cycle intact (a net loss of 0.01).

I don't think this is intended.

- [x] Save file [bitburnerSave_1664403045_BN3x1.zip](https://github.com/danielyxie/bitburner/files/9669201/bitburnerSave_1664403045_BN3x1.zip)
- [x] Version of the game, e.g. Bitburner v2.1.0

**Comment by Herzfinsternis** [comment]
This is intended. The autoCoffee and autoParty upgrades only kick in, when you have new employees (upgrade office size and hire employees).

**Comment by Draco18s** [comment]
But new employees would rise to max values in all of like, 10 minutes.

Lets say they start as the lowest possible value, `50`. 1% of that is `0.5`, which means they hit max at `50 / 0.5 = 100` cycles (less, because multiplicative benefits causing the rise to increase with each step, but this math is easier). 100 cycles is 1000 seconds, or a little over 16 minutes.

Is that really worth the time spent researching autoCoffe and autoParty? You need a minimum of 17,000 research to unlock one of them, (37,000 for both). You generate, eeeh, lets call it 1 research per second with a small to medium size division.

So, 4.7 hours of research time spent skipping 16 minutes of "slightly less than perfect" productivity.

And you have to do that cost-benefit analysis on *each* division. Your research doesn't carry over from division to division. Every industry has to independently figure out how to create coffee machines...
