### ISSUE TITLE
Vitburner went into recovery mode for some reason

### ISSUE THREAD

**Issue by kotenok2000** [danielyxie/bitburner#4192]
# DELETE THIS AFTER READING

# include (where relevant)

- [ ] Save file 

- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v1.3.0 (216bf616)
[RECOVERY_BITBURNER_1664644987.json.txt](https://github.com/danielyxie/bitburner/files/9691276/RECOVERY_BITBURNER_1664644987.json.txt)

**Comment by Snarling** [comment]
I do not get a recovery screen when loading your attached save. Is there any other info you can provide?

**Comment by kotenok2000** [comment]
It happened when Autopilot.js was performing aug install.
