### ISSUE TITLE
Unable to create directories.

### ISSUE THREAD

**Issue by devnuhl** [danielyxie/bitburner#4193]
- Scripts unnecessary
- Reproduce by attempting to cd into nonexistent directory
- Bitburner v2.1.0

It seems that the ability to "create" directories by using `cd` has been lost at some point. Attempted `mkdir` before checking available commands and then checking the help on cd. "Since there's no command for making them, what good is this other command. Let's check." was my thinking.

However, no attempts to change into a directory, having it created in the process seemed to work.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/1120006/193432004-426e2bed-0c5a-434d-9f7b-420fc2c07604.png">

**Comment by Herzfinsternis** [comment]
Directories are created by creating a file within the not existing directory: nano scripts/superhack.js

The "cd"-command does not create directories.

**Comment by devnuhl** [comment]
Apparently, no matter how many times I've read this help in-game, and the online [documentation](https://bitburner.readthedocs.io/en/latest/basicgameplay/terminal.html#cd-terminal-command) , that ONE word has been missed. Literally read both dozens of times, and I read it as `it will be 'created'.` rather than `it will not be 'created'.`

**Comment by phyzical** [comment]
@devnuhl feel free to submit a pr to update the docs to make it more clear if you feel it might be too ambiguous 👍
