### ISSUE TITLE
Shortest Path on a Grid contract via API does not accept an empty string as a solution

### ISSUE THREAD

**Issue by Draco18s** [danielyxie/bitburner#4209]
Open attached save and connect to Syscore if the save doesn't take you there (`home; connect harakiri-sushi; connect CSEC; connect omega-net; connect avmnite-02h; connect syscore`). Run the contract and confirm visually that no path exists. Return home and `run findcontracts.js --submit --oftype "Shortest Path in a Grid"`

Expected output:
 - `findcontracts.js: Result: Gained 17500 faction reputation for Sector-12`

Actual output:
 - `findcontracts.js: Reward blank! syscore contract-384448-Sector-12.cct answer: `

Return to Syscore, run the contract, and click submit, leaving the answer field blank. Note that this was the correct answer.

So not only does `codingcontract.attempt` not return a *success* value for a correct answer, but it doesn't even return a *failed attempt.*

- [x] Save file [bitburnerSave_1665085206_BN3x1.zip](https://github.com/danielyxie/bitburner/files/9728135/bitburnerSave_1665085206_BN3x1.zip)
- [x] Minimal scripts to reproduce the issue [paths2.zip](https://github.com/danielyxie/bitburner/files/9728144/paths2.zip) (`paths2` can be run directly, the same method is imported into the autosolver `findcontracts`).
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v2.1.0

**Comment by Snarling** [comment]
Not a bug, if there is no solution then the expected answer is an empty string, not an empty array.

![image](https://user-images.githubusercontent.com/84951833/194813934-f8dcabca-f790-4d19-aa2f-8ec2679255dd.png)

![image](https://user-images.githubusercontent.com/84951833/194814011-83ea922d-bb1e-4484-8bb3-05e0957811df.png)
