### ISSUE TITLE
Subarray with Maximum Sum does not accept 0 as an answer

### ISSUE THREAD

**Issue by Draco18s** [danielyxie/bitburner#4210]
Open save and connect to defcomm (`home; connect sigma-cosmetics; connect zer0; connect neo-net; connect the-hub; connect rothman-uni; connect aevum-police; connect snap-fitness; connect omnia; connect defcomm`) and run the contract there. Confirm that the maximum possible sum is 0, as all the values of the array are negative, except the lone zero.

Return home and `run findcontracts.js --submit --oftype "Subarray with Maximum Sum"`

Expected output:
 - `findcontracts.js: Result: Contract SUCCESS - Gained $75.000m`

Actual output:
 - `findcontracts.js: Reward blank! defcomm contract-487468.cct answer: 0`

Return to defcomm and submit `0` as an answer to the contract.

So not only does codingcontract.attempt not return a *success* value for a correct answer, but it doesn't even return a *failed attempt.*

- [x] Save file [bitburnerSave_1665085206_BN3x1.zip](https://github.com/danielyxie/bitburner/files/9728135/bitburnerSave_1665085206_BN3x1.zip)
- [x] Minimal scripts to reproduce the issue `contracts/maxsum.js`, `contracts/autosolve.js`, and `contracts/wrapper.js` if needed.
- [x] Steps to reproduce
- [x] Version of the game, e.g. Bitburner v2.1.0

**Comment by quacksouls** [comment]
Honestly, I got lost trying to debug what `findcontracts.js` calls to solve the contract under consideration, and how the solution is passed to the Coding Contract API.  Here's a self-contained script to demonstrate that the game does indeed accept an integer `0` as a solution.
```js
/**
 * A function for assertion.
 *
 * @param cond Assert that this condition is true.
 * @return Throw an assertion error if the given condition is false.
 */
function assert(cond) {
    if (!cond) {
        throw new Error("Assertion failed.");
    }
}

/**
 * The largest sum of a non-empty, contiguous subarray.
 *
 * @param array An array of integers.
 * @return The largest sum of any non-empty, contiguous subarray of the given
 *     array.
 */
function subarray_sum(array) {
    assert(array.length > 0);
    // Use Kadane's algorithm.
    let best = Number.NEGATIVE_INFINITY;
    let current = 0;
    for (const n of array) {
        current = Math.max(n, current + n);
        best = Math.max(best, current);
    }
    return best;
}

/**
 * Usage: run subarray.js [cct] [hostname]
 *
 * @param ns The Netscript API.
 */
export async function main(ns) {
    // The file name of the coding contract.
    const cct = ns.args[0];
    // The hostname of the server where the coding contract is located.
    const host = ns.args[1];
    // Solve the coding contract.
    const array = ns.codingcontract.getData(cct, host);
    const solution = subarray_sum(array);
    assert(0 == solution);
    const result = ns.codingcontract.attempt(
        solution, cct, host, { returnReward: true }
    );
    ns.tprint(host + ", " + cct + ": " + result);
}
```

**Comment by Draco18s** [comment]
`findcontracts` just search all servers for contracts, it forwards those to `autosolve` (this is a result of having written a script that finds them for me and a having a set of scripts which could solve specific puzzles, and those got glued together later), which maps the type of contract to the correct algorithm, which is then passed to `wrapper` to actually get the contract inputs and submit an output.

**Comment by Snarling** [comment]
@Draco18s I could not reproduce your error. I ran the following test and received the following output:

![image](https://user-images.githubusercontent.com/84951833/194812377-7c33a43e-b1ec-40d7-9b0a-79ca74d8fec4.png)

![image](https://user-images.githubusercontent.com/84951833/194812341-df2ec8be-a5ef-47fb-85ec-8b51bb1d324e.png)


In general when reporting a bug, please keep the reproduction method to the simplest terms possible, as in the reproduction method I used above. Do not ask us to use an extremely in depth player script because then we cannot tell whether the error is in your script or in the game (in this case, it's an error in your script because a direct test shows that 0 is accepted and returns a correct reward). So it seems instead of an issue here you should just be debugging your player script.
