### ISSUE TITLE
functions missing ingame

### ISSUE THREAD

**Issue by ElusivePerov** [danielyxie/bitburner#4226]
this is for the first function https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.renamepurchasedserver.md

![bitburner_AeCfrWSmd6](https://user-images.githubusercontent.com/67376330/194978407-3ab91dc5-ce7a-4fe9-bd2d-d2f4a1f1a3b8.png)

	export async function main(ns) {
		var pservers = ns.getPurchasedServers()

		for (var i = 0; i < pservers.length; ++i) {
			var index = pservers[i]
			renamePurchasedServer(index, "pserv" + i)
		}
	}

and this is the second https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.renamepurchasedserver.md
![bitburner_IO5eN17Qfi](https://user-images.githubusercontent.com/67376330/194981654-011ccda7-77c6-4706-84ef-3936863b651f.png)

	export async function main(ns) {
		var ram = ns.args[0]
		var pservs = ns.getPurchasedServers()

		for (var i = 0; i < pservs.length; ++i) {
			var index = pservs[i]

			ns.upgradePurchasedServer(index, ram)
		}
	}

this is on Bitburner v2.1.0 (8f4636cb)

**Comment by quacksouls** [comment]
The function `ns.renamePurchasedServer()` is in the development branch. You're trying to use it in a released version of the game.  Consider this script:
```js
/** @param {NS} ns */
export async function main(ns) {
    const host = "aws";
    const newhost = "pserv";
    const ram = 16;
    ns.purchaseServer(host, ram);
    ns.renamePurchasedServer(host, newhost);
}
```
Running the script using the released version at 

https://danielyxie.github.io/bitburner/

would give an error.  Now clone the `dev` branch at

https://github.com/danielyxie/bitburner/tree/dev

Build the code and start the game.  Then run the above script.

**Comment by ElusivePerov** [comment]
> The function `ns.renamePurchasedServer()` is in the development branch. You're trying to use it in a released version of the game. Consider this script:
> 
> ```js
> /** @param {NS} ns */
> export async function main(ns) {
>     const host = "aws";
>     const newhost = "pserv";
>     const ram = 16;
>     ns.purchaseServer(host, ram);
>     ns.renamePurchasedServer(host, newhost);
> }
> ```
> 
> Running the script using the released version at
> 
> https://danielyxie.github.io/bitburner/
> 
> would give an error. Now clone the `dev` branch at
> 
> https://github.com/danielyxie/bitburner/tree/dev
> 
> Build the code and start the game. Then run the above script.

oh i saw your reply after i finished editing my post
i have to say that it would be nice to have a warning in the documentation that it's not on the release version
thanks for the reply though i'll be switching to that version right now
