### ISSUE TITLE
ns.tFormat() with negative numbers

### ISSUE THREAD

**Issue by Jakob002** [danielyxie/bitburner#4235]
Game version: v2.1.0 (8f4636cb)

I noticed that ns.tFormat() and by extent StringHelperFunctions.ts#convertTimeMsToTimeElapsedString() are producing wrong outputs for negative numbers. _You be the judge if support for negative numbers is an actual use case._

```
// positive numbers, everything fine
// expected output:
// 1 second
// 1 minute 1 second
// 1 hour 1 minute 1 second
// actual output:
// as expected
ns.print(ns.tFormat(+1 * 1000));
ns.print(ns.tFormat(+61 * 1000));
ns.print(ns.tFormat(+3661 * 1000));

// negative numbers, stuff breaks
// expected output*:
// -1 second
// -1 minute 1 second
// -1 hour 1 minute 1 second
// or perhaps undefined or an exception
// actual output:
// -1 seconds
// -1 seconds
// -1 seconds
ns.print(ns.tFormat(-1 * 1000));
ns.print(ns.tFormat(-61 * 1000));
ns.print(ns.tFormat(-3661 * 1000));
```

*Note that this is the output _expected by me_. There is nothing in the docs about what the function is supposed to return for negative args.

**Comment by koutoftimer** [comment]
@Jakob002 well, looking at code, time [supposed to be positive](https://github.com/danielyxie/bitburner/blob/6c84d64e67082e23cd54d38b757ec6a5f5bd1409/src/utils/StringHelperFunctions.ts#L39-L45). 

IMHO, adding support for negative will be awkward: just imagine time like "10 days 4 hours 37 minutes 4 seconds" with negative sight before it. It feels OK to add sight for number but not for spelled time. If you will replace negative sight with some word then you have another problem as words usually have context and you have no idea in what context `tFormat` will be used.

**Comment by koutoftimer** [comment]
@hydroflame IDK, it feels bad to close this issue like this. At least throwing some sort of an error for negative numbers required because it is clearly seen that `tFormat` behaves totally wrong with them.
