### ISSUE TITLE
ns.write() fails for string arrays

### ISSUE THREAD

**Issue by dbachran** [danielyxie/bitburner#4239]
As of Bitburner v2.1.0 (8f4636cb) my NS2 scripts fail when trying to write a string array to a file.

Given a file "input.txt" with some comma-separated values, the following code throws an error.

Example code:

```
/** @param {NS} ns */
export async function main(ns) {
	var file_txt = ns.read("input.txt")
	var list = file_txt.split(",")
	ns.write("output.txt", list, "w")
}
```

Error message:

> RUNTIME ERROR
> /test/readwrite.js@home (PID - 6)
> 
> **write: 'data' should be a string. Is of type 'object', value: '[".","4sigma...'**
> 
> Stack:
> /test/readwrite.js:L5@Module.main

**Comment by hydroflame** [comment]
Not a bug, convert to string first with json

**Comment by dbachran** [comment]
Ok, if this behavior is intended, at least the documentation should be adjusted as well, right?

https://github.com/danielyxie/bitburner/blob/dev/markdown/bitburner.ns.write.md

ciao, daniel :-)

**Comment by dbachran** [comment]
This change got introduced here:
https://github.com/danielyxie/bitburner/commit/823cdf70caad5ce1a9813bf31b50062d025dfcf2#diff-851fc049fdd04e0ee245ab28fd29c8b014069e5bbddeada2c012c3c251e9a0e4
Prior to that change, data was converted into a String later on.
Now, it is expected to be a string, even if the documentation tells otherwise.
If this change is intended, at least the documentation should be adjusted. I will try looking into it...
