### ISSUE TITLE
Augmentation BrachiBlades missing in Gang (Slum Snakes)

### ISSUE THREAD

**Issue by EndrosG** [danielyxie/bitburner#4240]
Version: v2.1.0 (8f4636cb, Steam)
Bug:
I am in recursion bitnode and try using gang mechanics to complete the bitnode. I previously completed BN2.1
I started a gang with Slum Snakes faction and right now I am missing the BrachiBlades augmentation in the gang augmentation section. The augmentation is available in The Syndicate faction and I can buy it there but not in Slum Snakes gang mode.

Save file attached.

[BN12_11.zip](https://github.com/danielyxie/bitburner/files/9768058/BN12_11.zip)

**Comment by hydroflame** [comment]
Not a bug, gangs dont have all augs outside BN2

**Comment by EndrosG** [comment]
@hydroflame : What I do not understand than: Why can I buy it this time? I started the next recursion level and created the same gang with Slum Snakes faction...
![grafik](https://user-images.githubusercontent.com/26883037/195586604-9253db8f-304d-41db-ac73-61434263b221.png)
