### ISSUE TITLE
`ns.prompt()`: array of objects throws into recovery screen

### ISSUE THREAD

**Issue by quacksouls** [danielyxie/bitburner#4246]
The `choices` property of `ns.prompt()` accepts an array of strings or numbers, or a mixture of numbers and strings.  If the array happens to contain an object, then it would trigger the recovery screen.

- [x] Minimal script to reproduce the issue.
- [x] Steps to reproduce.  Open the online version of the game at
  https://danielyxie.github.io/bitburner/
  and run the script below.  Click on the drop-down box and you would be thrown into the recovery screen.
- [x] Version of the game: Bitburner v2.1.0 (8f4636cb)
```js
/** @param {NS} ns */
export async function main(ns) {
    ns.prompt("Please select.", {
        "type": "select",
        "choices": [
            "a",
            {"b": 2}
        ]
    });
}
```

**Comment by Snarling** [comment]
Yeah looks like I just made some changes there, probably my bad, I'll write a fix for this.
