### ISSUE TITLE
Hidden Penalties to Infiltration (both rep & money)

### ISSUE THREAD

**Issue by jz0p** [danielyxie/bitburner#4267]
Bitburner version 2.1.0

Minimal scripts to reproduce? 
   -perhaps just "ai.js". perhaps none.

Penalties to infiltration ocurr when adding a certain number of augmentations (or certain types?).
These penalities reduce infiltration money rewards by a factor of ~15x, and rep rewards by a factor of ~5x.

If this is intended, why?

If not, steps to reproduce:

CASE1: Baseline
1] load savefile, observe rep and money rewards of any infiltration
2] install any 1 augmentation / reset
3] repeat same infiltration as step1. observe rep and money rewards are unchanged

CASE2: Hidden Penalties
1] load savefile, observe rep and money rewards of any infiltration (unneeded if already known from CASE1)
2] buy the following augs from Slum Snakes (gang):
        Graphene Bionic Legs Upgrade
        CordiARC Fusion Reactor
        Graphene Bionic Spine Upgrade
3] buy all augs from Daedalus
4] install augs/reset
5] repeat same infiltration as step1
6] observe the penalties (15x reduction in money. 5x reduction in rep)

note: As I was using an 'auto-infiltrate' script (ai.js), if these penalties happen as a result of using that i'd be curious to know :)

**Comment by quacksouls** [comment]
Please create new issues here:
https://github.com/bitburner-official/bitburner-src
