### ISSUE TITLE
The hospital button doesn't work anymore

### ISSUE THREAD

**Issue by KReinders** [danielyxie/bitburner#4289]
The hospital button doesn't work anymore. I'm on the latest Steam version.

[bitburnerSave_1671720869_BN1x2.zip](https://github.com/danielyxie/bitburner/files/10287787/bitburnerSave_1671720869_BN1x2.zip)

**Comment by elphindacity** [comment]
same issue on my end

**Comment by AlfredSimpson** [comment]
Running into the same issue on my end as well
