### ISSUE TITLE
TypeError: n is undefined (at "Augmentations")

### ISSUE THREAD

**Issue by ajacks01** [danielyxie/bitburner#4299]
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: TypeError: n is undefined
* Page: Augmentations
* Version: v2.1.0 (8f4636cb)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
* Features: lang=en-US cookiesEnabled=true doNotTrack=unspecified indexedDb=true
* Source: https://danielyxie.github.io/bitburner/dist/main.bundle.js

### Save
```
Copy your save here if possible
```

**Comment by Mughur** [comment]
![image](https://user-images.githubusercontent.com/19550056/216737254-e0b9673a-9eb7-4f9c-ac4e-df3494c31b93.png)
guess what you should not do.
