### ISSUE TITLE
getNextHacknetNodeCost() not recognized

### ISSUE THREAD

**Issue by twilde** [danielyxie/bitburner#430]
In 0.40.1 it appears that getNextHacknetNodeCost() is not recognized in traditional netscript (.script file).

Script line 67:

```
    var nextCost = getNextHacknetNodeCost();
```
Error message:

```
Script runtime error: 
Server Ip: 19.6.4.3
Script name: hn-tend.script
Args:[]
ReferenceError: getNextHacknetNodeCost is not defined (Line Number 67. This line number is probably incorrect if your script is importing any functions. This is being worked on)
```

There's no importing or anything funky going on in this script, and I've updated all var declarations. Is this function still supported?

**Comment by kopelli** [comment]
The hacknet API changed in v0.40.0. The documentation needs to be updated, but it was called out in the changelog:

_[* Completely re-designed the Hacknet Node API](https://www.reddit.com/r/Bitburner/comments/92qs4o/v0400_significant_netscript_changes/)_

You want to use `hacknet.getPurchaseNodeCost()`. For now you can look at the [source](https://github.com/danielyxie/bitburner/blob/master/src/NetscriptFunctions.js#L208) to see the methods off of `hacknet`

**Comment by twilde** [comment]
Doh, I missed / forgot that part, thanks.
