### ISSUE TITLE
Netscript 1.0 cannot stringify objects

### ISSUE THREAD

**Issue by thePalindrome** [danielyxie/bitburner#437]
Once you get the ability to use getBitNodeMultipliers, it may be desireable to output those values to the console so you can view them. Unfortunately, print()-ing the object gives you [Object object] and the documentation for getBitNodeMultipliers mentions that the object may change at any time, so hardcoding everything isn't really a good solution.

I'd appreciate some kind of parse() function that simply stringifies an object, as an example:

`print(parse(getBitNodeMultipliers))`
would return
```
{
    ServerMaxMoney: 1,
    ServerStartingMoney: 1,
    ServerGrowthRate: 1,
    ServerWeakenRate: 1,
    ServerStartingSecurity: 1,
    ManualHackMoney: 1,
    ScriptHackMoney: 1,
    CompanyWorkMoney: 1,
    CrimeMoney: 1,
    HacknetNodeMoney: 1,
    CompanyWorkExpGain: 1,
    ClassGymExpGain: 1,
    FactionWorkExpGain: 1,
    HackExpGain: 1,
    CrimeExpGain: 1,
    FactionWorkRepGain: 1,
    FactionPassiveRepGain: 1,
    AugmentationRepCost: 1,
    AugmentationMoneyCost: 1,
}
```

A polyfill *should* be as easy as:
`JSON.stringify(argument)`

**Comment by danielyxie** [comment]
It does support `JSON.parse/stringify`, but right now it doesnt work for objects returned by Netscript functions (i.e. if you create an object in the script then `JSON.stringify` will work, but not for objects returned by Netscript Functions

**Comment by thePalindrome** [comment]
Yes, this is what I wanted. Could you update the docs?

**Comment by danielyxie** [comment]
Where do you want the documentation updated? It already states that Netscript 1.0 is run on a ES5 JavaScript Interpreter. Since `JSON` is supported in ES5 JavaScript, then it is supported in Netscript 1.0 as well

**Comment by thePalindrome** [comment]
Fair enough, just not something quite obvious to me. Never mind me then XD
