### ISSUE TITLE
Process static external dependencies when calculating RAM cost

### ISSUE THREAD

**Issue by Alxandr** [danielyxie/bitburner#453]
I've been trying for a few ways to move my script files out of the game (cause, regardless of how "decent" the ingame code editor is, it's lacking a lot of things, like a proper file system, transpiling of the code etc, which I would never expect the game to support in the first case though). My first attempt used a script that downloaded all of my scripts from github, and wrote them on the home machine. This resulted in a bunch of `.js.txt` files, which is fairly unusable. My next attempt simply made this script:

```js
export { main } from 'https://alxandr.github.io/bitburner/daemon.js';
```

In theory, this would be great, cause it would allow me to update scripts by simply saving and re-loading the game. However, now my scripts crash cause I apparently circumvented RAM calculation. So, my suggestion is that RAM calculation should follow imports.

**Comment by danielyxie** [comment]
I noticed [here](https://alxandr.github.io/bitburner/) that you have it setup to run wget like this:

```
wget https://alxandr.github.io/bitburner/daemon.js daemon.js
```

I thought this wouldn't work due to cross-origin issues, and you'd have to grab it from the githubraw URL:

```
wget https://raw.githubusercontent.com/Alxandr/bitburner/gh-pages/daemon.js daemon.js
```

Not a huge difference either way, was just curious if you somehow got it to work

**Comment by Alxandr** [comment]
Go to https://alxandr.github.io/bitburner/, click copy, paste in game.
Works like a charm.
