### ISSUE TITLE
Analyze displays incorrect % to hack, money available

### ISSUE THREAD

**Issue by Kline-** [danielyxie/bitburner#463]
![image](https://user-images.githubusercontent.com/1126350/45631321-401bf180-ba60-11e8-913b-6cab5b2e7476.png)
Not sure if I'm to blame for this or if it was after the conversion of numeral to the wrapper class.  Knowing me, probably my fault :)

**Comment by kopelli** [comment]
ooo...and there's $$646,760,318.15 money on that server. The double dollar sign means twice the money, right? 😆

**Comment by danielyxie** [comment]
Fixed in v0.40.4
