### ISSUE TITLE
Improve parsing of args

### ISSUE THREAD

**Issue by Alxandr** [danielyxie/bitburner#470]
Doing `run "a b" c` produces 3 args; `"a`, `b"` and `c`, as opposed to 2. In some of my scripts where I do argument parsing, I fix this by first joining the args by space (to get back the original string), and then parsing it myself manually in the script, but I think this should probably be improved in the game itself.

Here is a sample function (I stole from [here](https://github.com/substack/node-shell-quote#readme) and modified).

**Comment by willurd** [comment]
I'd add to this that passing a number as an argument results in a parsed number, not its string representation. Maybe that's by design, but I got tripped up by this a couple times.

**Comment by danielyxie** [comment]
Addressed this in latest update v0.43.1. It has some weird parsing in edge cases but should work for the most part.

[Documented here](https://bitburner.readthedocs.io/en/latest/basicgameplay/terminal.html#argument-parsing)
