### ISSUE TITLE
Bladeburner BlackOps reset on loading save and are repeatable via BB API

### ISSUE THREAD

**Issue by Kline-** [danielyxie/bitburner#483]
![image](https://user-images.githubusercontent.com/1126350/46906140-5e8cd580-cec4-11e8-927d-5deb3f167154.png)

Test script to correlate with the image:

```
export async function main(ns) {
    const bb = ns.bladeburner;
    const ops = bb.getBlackOpNames();
    for( const i in ops )
        ns.tprint( ops[i] + ": " +  bb.getActionCountRemaining( "blackop", ops[i] ) );
}
```

Output:

> test.js: Operation Typhoon: 0
> test.js: Operation Zero: 0
> test.js: Operation X: 0
> test.js: Operation Titan: 0
> test.js: Operation Ares: 0
> test.js: Operation Archangel: 1
> test.js: Operation Juggernaut: 1
> test.js: Operation Red Dragon: 1
> test.js: Operation K: 1
> test.js: Operation Deckard: 1
> test.js: Operation Tyrell: 1
> test.js: Operation Wallace: 1
> test.js: Operation Shoulder of Orion: 1
> test.js: Operation Hyron: 1
> test.js: Operation Morpheus: 1
> test.js: Operation Ion Storm: 1
> test.js: Operation Annihilus: 1
> test.js: Operation Ultron: 1
> test.js: Operation Centurion: 1
> test.js: Operation Vindictus: 1
> test.js: Operation Daedalus: 1

Upon refreshing the tab all BlackOps are reset to 1 count when checked via `bb.getActionCountRemaining()` yet are disabled in the Bladeburner UI.

**Comment by danielyxie** [comment]
Fixed in v0.41.0
