### ISSUE TITLE
Bladeburner BlackOps can be completed without the requisite rank via BB API

### ISSUE THREAD

**Issue by Kline-** [danielyxie/bitburner#486]
![capture](https://user-images.githubusercontent.com/1126350/46908859-b2141900-ceee-11e8-8c3f-030f10762c08.PNG)
![image](https://user-images.githubusercontent.com/1126350/46908857-ade7fb80-ceee-11e8-8361-0cf433e23a08.png)

**Comment by danielyxie** [comment]
Fixed in v0.41.0
