### ISSUE TITLE
Generate IP Addresses solver missing valid solutions

### ISSUE THREAD

**Issue by Kline-** [danielyxie/bitburner#487]
For input  `1938718066` using a re-implementation of the solver in src the only valid solution is `[193.87.180.66]`.

Below is a solver that generates a solution of `[193.87.18.66,193.87.180.66]`, finding a valid IP address the current solver does not.

```js
function generate_ip_addresses( _data )
{
    const data = String( _data );
    const len = data.length - 3;
    var res = [];

    for ( let a = 0; a < 3 && a < len; ++a )
    {
        for ( let b = 0; b < 3 && b < len - a; ++b )
        {
            for ( let c = 0; c < 3 && c < len - a - b; ++c )
            {
                const A = parseInt( data.substring( 0, a + 1 ), 10 );
                const B = parseInt( data.substring( a + 1, a + b + 2 ), 10 );
                const C = parseInt( data.substring( a + b + 2, a + b + c + 3 ), 10 );
                const D = parseInt( data.substring( a + b + c + 3 ), 10 );

                if ( A < 256 && B < 256 && C < 256 && D < 256 )
                    res.push( A + "." + B + "." + C + "." + D );
            }
        }
    }

    return res;
}

**Comment by havocmayhem** [comment]
For what it's worth, I disagree that leading zeros should be part of the valid solution set, except where the octet itself is 0. (e.g. 127.0.0.1)

Either way, the Contract Description should probably be updated to clarify if leading zeros are valid.

**Comment by danielyxie** [comment]
Since I just copied the problem + solution from one of those websites where you practice interview problems, I'm going to use their same constraints/requirements and have leading zeros not be allowed unless the number itself is zero. 

I've updated the problem description in v0.41.0
