### ISSUE TITLE
Static RAM Usage: 0

### ISSUE THREAD

**Issue by q00u** [danielyxie/bitburner#493]
```
Script runtime error: 
Server Ip: 88.3.8.0
Script name: scan.ns
Args:[]
Dynamic RAM usage calculated to be greater than initial RAM usage on fn: scan. This is probably because you somehow circumvented the static RAM calculation.

Please don't do that :(

Dynamic RAM Usage: 1.8
Static RAM Usage: 0
```

When I run the scan.ns scripts posted [here.](https://old.reddit.com/r/Bitburner/comments/9nrz3v/scan_script_v2/) (no modifications made)

Running on Google Chrome version 69.0.3497.100 (Official Build) (64-bit)

[bitburnerSave (14).zip](https://github.com/danielyxie/bitburner/files/2494046/bitburnerSave.14.zip)

**Comment by danielyxie** [comment]
I'm not exactly sure how this happens because whenever a script is saved, it's RAM usage should be re-calculated and updated.

The fix is easy, just open the script and then save it:

```
nano scan.ns
Hit "Save & Close" button at the end or hit Ctrl + b
```

**Comment by sudoBash418** [comment]
> The fix is easy, just open the script and then save it:
> 
> ```
> nano scan.ns
> Hit "Save & Close" button at the end or hit Ctrl + b
> ```
Tried that many times, didn't work for me.
> I'm not exactly sure how this happens because whenever a script is saved, it's RAM usage should be re-calculated and updated.

I'm no expert on this game, so I'm just guessing here, but it seems to me that the RAM usage calculation doesn't work correctly (usually it says "Syntax error", despite the script running fine otherwise), and therefore it doesn't update the static RAM value.

**Comment by danielyxie** [comment]
It works for the script posted here. 

I'd have to see one of the scripts you have issues with to investigate further. "Syntax Error" usually means the [parser](https://github.com/acornjs/acorn) is failing

**Comment by sudoBash418** [comment]
I believe the issue I'm having is different than @q00u's as mine involves external URLs.
To keep things clean, I made a new issue: #501

**Comment by willurd** [comment]
I've been having this same issue off and on (sometimes I get this error, sometimes I don't; I don't know why) for a lot of my scripts:

```
Script runtime error: 
Server Ip: 84.4.9.9
Script name: u-canown.js
Args:[]
Dynamic RAM usage calculated to be greater than initial RAM usage on fn: scan. This is probably because you somehow circumvented the static RAM calculation.

Please don't do that :(

Dynamic RAM Usage: 1.8
Static RAM Usage: 1.6
```

Opening in `nano` and saving/closing as suggested do not work. Here's the script in question:

```js
/**
 * Prints out all hosts that are ownable, but not currently owned.
 */

import { forEachHost } from './lib-hosts.js';
import { hacks } from './constants.js';

export async function main(ns) {
  // TODO: Accept an optional hostname argument. If given, only check that host.

  let ownableHostCount = 0;

  await forEachHost(ns, async (host, path, adjacent) => {
    const isOwned = ns.hasRootAccess(host);

    if (isOwned) {
      return;
    }

    const hackingLevel = ns.getHackingLevel();
    const requiredHackingLevel = ns.getServerRequiredHackingLevel(host);
    const availableHacks = hacks.filter(({ filename }) => ns.fileExists(filename, 'home'));
    const openPorts = availableHacks.length;
    const requiredOpenPorts = ns.getServerNumPortsRequired(host);

    if (hackingLevel >= requiredHackingLevel && openPorts >= requiredOpenPorts) {
      ns.tprint(
        `Host "${host}" is hackable with a required hacking level of ${requiredHackingLevel}, and required open ports of ${requiredOpenPorts}.`,
      );
      ownableHostCount += 1;
    }
  });

  if (ownableHostCount === 0) {
    ns.tprint('There are no hosts that are currently ownable');
  }
}
```

Here's a link to that script, along with the other scripts it imports: https://github.com/willurd/bitburner-scripts/tree/master/src/scripts.

**Comment by willurd** [comment]
One potentially related issue I've identified is that `Script`'s [`updateRamUsage`](https://github.com/danielyxie/bitburner/blob/597c0d004d676888c8812312ecd1a0ffca0d7e70/src/Script.js#L408) function is an async function, but it is used synchronously throughout the codebase: [1](https://github.com/danielyxie/bitburner/blob/597c0d004d676888c8812312ecd1a0ffca0d7e70/src/Server.js#L135) [2](https://github.com/danielyxie/bitburner/blob/597c0d004d676888c8812312ecd1a0ffca0d7e70/src/Server.js#L147) [3](https://github.com/danielyxie/bitburner/blob/597c0d004d676888c8812312ecd1a0ffca0d7e70/src/Script.js#L383) [4](https://github.com/danielyxie/bitburner/blob/597c0d004d676888c8812312ecd1a0ffca0d7e70/src/Script.js#L401) [5](https://github.com/danielyxie/bitburner/blob/597c0d004d676888c8812312ecd1a0ffca0d7e70/src/NetscriptFunctions.js#L2091)

**Comment by willurd** [comment]
Pretty much stuck on this now, unfortunately. Most of my scripts aren't working due to this dynamic RAM issue at the moment (though they have worked before). I'm not sure what I'm doing that's causing this.

**Comment by willurd** [comment]
Very interesting. I removed `./` from my scripts and that didn't work. But then I opened up all of my scripts from the base libraries up to the script I run and saved them all and then it worked! Thanks for looking into this.

**Comment by jaguilar** [comment]
FWIW, I just had this bug manifest, and it was quite interesting. I noted a couple of things.

- The problem script showed as having a syntax error in the dynamic ram calculator in the editor.
- If I copied the script to a new file, then the dynamic ram calculator reported the correct amount of ram usage.
- After saving the copied script and running it, I got the static ram usage zero bug.
- After reopening the script, the dynamic ram calculator in the editor again reports a syntax error.

Weird right? I ended up rewriting the module in type script and no longer get reports of syntax errors on the generated JS. Maybe there was something I was using that could not be handled by the static calculator, but I can't really see what. If I see it again, I'll dive deeper into debugging the issue.

**Comment by ToxicFrog** [comment]
I'm also seeing this. The full script is [here](https://gist.github.com/ToxicFrog/9291895c9cefd8d84ba0f1d963d7f1e5), but I suspect the culprit is this code specifically:

    let spikes = ["brutessh", "ftpcrack", "relaysmtp", "httpworm", "sqlinject"];
    // ...later...
    for (var program of spikes) {
        if (ns.fileExists(program + ".exe")) ns[program](host);
    }

Is there any way around this other than just a bunch of:

    if (ns.fileExists("foo.exe") ns.foo(host);

?

**Comment by Shados** [comment]
I've run into "Dynamic RAM usage calculated to be greater than initial RAM usage" under the following conditions:
1. I have a `A.ns` that imports a function `foo` from `B.ns`
2. I update the exported `foo` in `B.ns`, and the updated version has more RAM usage
3. I haven't re-opened/saved `A.ns`

In other words, it seems like the change in #629 doesn't update RAM usage in dependent scripts, even though it does update the code they call?
