### ISSUE TITLE
Syntax Error when importing from external URLs

### ISSUE THREAD

**Issue by sudoBash418** [danielyxie/bitburner#501]
OS: Arch Linux
Browser: Chromium 70.0.3538.67

My scripts use a "http://localhost:9221/" address to import scripts from my local webserver, and the parser doesn't seem to process them properly.
Note that despite the parser failing, they run fine (except for the fact that the RAM calculation sometimes has to be tricked to avoid tripping the anti-cheat)

However, importing from GitHub Pages works fine (ie. https://alxandr.github.io/bitburner/list.js).
I tested importing that exact same script, but from a different URL: https://raw.githubusercontent.com/Alxandr/bitburner/gh-pages/list.js, and the Syntax Error came back, along with two errors in the console that I've never seen before:

> Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

> Error dynamically importing module from https://raw.githubusercontent.com/Alxandr/bitburner/gh-pages/list.js for RAM calculations: TypeError: Failed to fetch dynamically imported module: https://raw.githubusercontent.com/Alxandr/bitburner/gh-pages/list.js

It doesn't look like that would be an issue for my local webserver though, as it sets the correct MIME type for .js files, and therefore the errors don't appear.

Script used to test (expected behavior being that list.js runs):
```
//import { main as not_main } from "https://raw.githubusercontent.com/Alxandr/bitburner/gh-pages/list.js"; // throws errors in web console and breaks the parser
//import { main as not_main } from "http://localhost:9221/list.js"; // just breaks the parser
import { main as not_main } from "https://alxandr.github.io/bitburner/list.js"; // works fine

export async function main(ns) {
    not_main(ns);
}
```

To reproduce: spin up a local web server with CORS configured to allow all and the MIME type set properly for .js files, and try to import a script from it.

**Comment by danielyxie** [comment]
An issue was that it wasnt properly recognizing _http://_ (only https). This is fixed in v0.41.2 and should hopefully resolve this. Let me know if not
