### ISSUE TITLE
CodingContracts still award money in BN-8

### ISSUE THREAD

**Issue by Kline-** [danielyxie/bitburner#506]
https://github.com/danielyxie/bitburner/blob/013af4e26cd96f79004760abad58a7d7f733d117/src/Player.js#L2332

Wasn't sure if this is intended behavior or not. If BN-8 should _only_ be the stock market then this is a bug. If the money gain from CCTs is small enough to not matter then this is just an extra feature for those willing to work for it.

I was hesitant to just submit a PR to mult by `BitNodeMultipliers.ScriptHackMoney` since CCTs _can_ be manually completed, but I didn't feel CCTs as a whole necessarily needed their own constant per-BN mult when BN-8 is (currently) the only potential issue.

**Comment by danielyxie** [comment]
Fixed in v0.41.2
