### ISSUE TITLE
No upper bound on memory?

### ISSUE THREAD

**Issue by q00u** [danielyxie/bitburner#513]
If you have enough money (as in, deep in $NaNT territory), you can buy so much RAM that:

>getServerRam() returned [151,115,727,451,828,650,000,000.00GB, NaNGB]

Which breaks all kinds of scripts, haha.

($NaNT seems just cosmetic, as it shows an actual number in the Stats screen, and some prices do go NaN after a while but still work as expected)

**Comment by danielyxie** [comment]
Added cap in latest update.

The $NaN is indeed cosmetic. The library used for formatting numbers has a certain upper limit and just displays NaN for everything above it
