### ISSUE TITLE
Can't join Bladeburners in BN1.3?

### ISSUE THREAD

**Issue by q00u** [danielyxie/bitburner#515]
I'm in BiteNode 1 Level 3. Yesterday I completed 1.2 and had joined Bladeburners during that run.

This time, same node, when I try to join nothing happens. No message, popup, or any indication why. I've tried refreshing the page, but it still doesn't work.

**Comment by danielyxie** [comment]
Should be fixed now. It was a bug with the v0.41.2 update. Please let me know if it happens again. Thanks!
