### ISSUE TITLE
price forecast out of [0,1] interval

### ISSUE THREAD

**Issue by Farbdose** [danielyxie/bitburner#528]
The documentation describes the price forcast as the probability of the stock going in that direction...
Shouldn't it be limited to values between 0 and 1?

I'm on my first run ever - 6 days already (no time to augment, have to code) and the KGI price forecast wen't completely nuts:
Its either below 0 or above 1...

I needed to increase the buy amount exponentially to keep up with it:

https://pastebin.com/ErEy18UD

This was running for one night and my money went from around 1t to 10000000t
Sure, this is an idle game, exponential growth is the gist of it... but isn't that a bit much?

[bitburnerSave.zip](https://github.com/danielyxie/bitburner/files/2795820/bitburnerSave.zip)

**Comment by danielyxie** [comment]
Are you saying that the value returned by `getStockForecase()` was below 0 or above 1? Then yes that would be a bug and I'll look into it.

Yeah, the stock market is very overpowered right now once you purchase 4S market data. The next update will address it a bit

**Comment by danielyxie** [comment]
Should be fixed in the latest update v0.43.1. If its not and it happens again let me know
