### ISSUE TITLE
Purchase warehouse does not apply storage upgrades

### ISSUE THREAD

**Issue by seraphina985** [danielyxie/bitburner#534]
When first purchasing a warehouse in a new city or division the corporation's global warehouse size multiplier is not applied. It only gets corrected the next time the multiplier or warehouse level is upgrades after the initial purchase.

I could be wrong but I don't get the impression that this is expected behaviour and that the storage multiplier should apply to all warehouses as it clearly does apply to level 1 warehouses as can be confirmed by upgrading the corporation warehouse multiplier when you own one or more level 1 warehouses already.

Looking at the code looks like there might need to be a call to warehouse.updateSize immediately after or during the creation of the warehouse object.

**Comment by danielyxie** [comment]
Should be fixed in v0.45.0. Let me know if not

Thanks!
