### ISSUE TITLE
[FR/Feedback] Allow creation of programs (.exe) be stopped and resumed

### ISSUE THREAD

**Issue by KurzedMetal** [danielyxie/bitburner#54]
Right now to create a program the player needs to start it and not interrupt it, otherwise it would start over.

I don't see how this behavior adds anything to the game except annoying the player for not letting them do other stuff like checking state of scripts or improving hacknet.

I find the game mechanic a bit bland, maybe you could remove that restriction about doing it uninterruptedly?

BTW, another thing I find a bit annoying about creating programs is that it seems that even if you are at 50 hacking skill or 500 hacking skill, it always takes exactly the same time.
OTOH, I do undestand if this is a idle/incremental wall that the user needs to pass just by waiting some time, but can you consider making the time it takes to build scale with skill?

Programs like DeepscanV2.exe and relaySTMP.exe takes 2 hours to create, which is a lot and can't be reduced, I've been avoiding them in my lasts prestige starts and just kept hacking lower port nodes, and using V1 scans just to avoid those extra hours. I hope at least there's some faction that makes them autounlock like BruteSSH.exe but I didn't find it yet.

Loving your game so far.

**Comment by danielyxie** [comment]
The time it takes to create a program does depend on your hacking skill. Higher hacking skills results in less time.

I agree the mechanic is annoying right now and I will look to change it in the future.

**Comment by danielyxie** [comment]
Done in recent update
