### ISSUE TITLE
Bitnode 2: Attacking yourself

### ISSUE THREAD

**Issue by Kejardon** [danielyxie/bitburner#574]
Your gang (and other gangs I think, but did not check) is able to clash with itself, with a 50% chance of 'winning', causing no territory change but otherwise normal clash damage.

Probable cause in Gang.js (didn't confirm):
        const others = GangNames.filter((e) => {
            return e !== i;
        });
I think e is a string, while i is a number, so this filter will never return false.

**Comment by danielyxie** [comment]
Should be fixed now in v0.46.2. Please let me know if there are still issues
