### ISSUE TITLE
Bitnode 2: Winning against other gangs probably doesn't reduce their power

### ISSUE THREAD

**Issue by Kejardon** [danielyxie/bitburner#575]
I didn't confirm this with testing, but from simple poking and code review of Gang.js Gang.prototype.processTerritoryAndPowerGains it looks like the player's gang clashing with another gang will NEVER reduce that other gang's power. It's not clear if this would be a bug, an oversight, or intentional, but I definitely had the assumption that winning against an enemy gang would directly reduce their power, like it would my own if I lost.

**Comment by KetasDotepasto** [comment]
Especially since if 2 NPC gangs clash, the loosing gang does loose power.

**Comment by danielyxie** [comment]
Should be fixed now in v0.46.2. Please let me know if there are still issues
