### ISSUE TITLE
Number imprecision can lead to unreasonable numbers, esp. with Wanted Level.

### ISSUE THREAD

**Issue by Kejardon** [danielyxie/bitburner#581]
I left my computer on overnight and woke up to this:
Wanted Level: 2,259,842,599,779.705600 (-1,891.584066 / sec)
Doing some quick math, this would take 31 years to get back down to a reasonable value.
I did some code diving and analysis and the most I would _expect_ to get from this would be if a statWeight ended up at 0.01. Even with the worst task for wanted level, I would only expect that to cause maybe 400 per second per gang member, which is not enough to cause that wanted level I woke up to.
I tried debugging a bit too, and I saw that statWeight can suffer from rounding issues. I have to imagine that it ended up as 0.00000000000001 or something at some point and for a short while spiked up the wanted level gain - that does give numbers in the correct range to lead to the wanted level I saw.

The most likely reason I ran into this is because I noticed assigning members to tasks will still give them the EXP for the task, even if money and such don't go up, so assigning members to Terrorism for a while will train them much better than assigning them to training. That's become part of my standard training regime for new gang members, and my scripts switch them off to another task as soon as they would start raising the wanted level.

**Comment by danielyxie** [comment]
Should be fixed in v0.47.0. If not let me know. Thanks!
