### ISSUE TITLE
API for re-sleeving?

### ISSUE THREAD

**Issue by nolanfu** [danielyxie/bitburner#589]
I love the relatively new API for managing duplicate sleeves. I'd also love to have an API available for re-sleeving. If we're following a similar convention as the existing sleeve API, it seems like it we'd want functions that:

- Return the number of re-sleeves available for purchase
- Return the stats and stat experience for a given re-sleeve
- Return the list of augmentations for a given re-sleeve
- Return the purchase cost for a given re-sleeve
- Return the stat multipliers for a given re-sleeve (maybe?)
- Purchase a given re-sleeve, returning a success/failure boolean

Considerations:

- Would this have an acceptable influence on gameplay balance? Re-sleeving is incredibly powerful early on in a run, but that power is currently limited by requiring manual intervention.
- What names should these functions have? I'm assuming they'd be in the `sleeve` namespace, but there might be some confusion with `getNumSleeves()`, `getSleeveStats()`, and `getInformation()`.

**Comment by danielyxie** [comment]
The Re-sleeving mechanic is going to be reworked shortly. Afterwards we can look into an API

**Comment by nolanfu** [comment]
Excellent. Happy weekend.
