### ISSUE TITLE
Recursive functions in netscript 1 do not scope local variables correctly

### ISSUE THREAD

**Issue by MasonD** [danielyxie/bitburner#602]
Recursive functions in netscript 1 do not scope local variables correctly. All calls of the same function share local variables instead of getting their own scopes. Minimum failing test:
```js
function scopeTest(recur) {
    not_scoped_correctly = '';
    if (!recur) {
        not_scoped_correctly = 'correctly scoped';
        scopeTest(true);
        tprint(not_scoped_correctly);
    } else {
        not_scoped_correctly = 'incorrectly scoped';
    }
}

scopeTest();
```

Should output 'correctly scoped' but instead gives 'incorrectly scoped'.

**Comment by sgiandomenico** [comment]
I believe this is because your variable 'not_scoped_correctly' is in fact a global.  In order to declare a local variable, you must precede it with 'var', e.g. 'var local_variable'.

**Comment by MasonD** [comment]
Ah, man. You're right. I could have sworn netscript 1 didn't support the var keyword. I remembered getting syntax errors when using it before.

False alarm, ns1 scopes correctly when actually using local variables.
