### ISSUE TITLE
Frozen game ...

### ISSUE THREAD

**Issue by vbruhn** [danielyxie/bitburner#608]
Loading the attached file (rename .txt into .json) into chrome and falkon: The menu works, but there is neither faction work nor are the scripts running, the corporation is frozen, too.
[bitnode_3_testing.txt](https://github.com/danielyxie/bitburner/files/3167233/bitnode_3_testing.txt)

**Comment by danielyxie** [comment]
This is related to the Corporation mechanic. It has been fixed on the [beta branch](https://bitburner-official.github.io/bitburner-beta/) if you want to play there, but unfortunately it won't be released for a few more days

**Comment by vbruhn** [comment]
Thanks :-)
