### ISSUE TITLE
Beta 046 -> 047: Stockmarket: 'Lag'

### ISSUE THREAD

**Issue by vbruhn** [danielyxie/bitburner#610]
When selling stocks from Portfolio view, the remaining stocks 'forget' their data (showing 0 stocks in long and short position).
They get updated with the next stock's tick, but the feeling of 'lag' is irritating.
**Edit** ... My eyes mismatched something ... the tab of the sold stock is still visible for the remaining tick instead of vanishing immediatly.

**Comment by danielyxie** [comment]
Should be fixed in v0.47.0. If not let me know. Thanks!
