### ISSUE TITLE
Beta 046 -> 047: Stockmarket is misbehaving

### ISSUE THREAD

**Issue by vbruhn** [danielyxie/bitburner#611]
The stockmarket of the attached save is ... weird.
CTYS has a price of $0.00, not recovering

APHE is jumping from + to - immediatly buy buying all available shares and vice versa (which might be on purpose due to the new functionality, but it triggers immediatly).

Else, my simple SMA- and 4SIG-Scripts work better with the new mechanism ... growing more money faster: https://github.com/vbruhn/Bitburner/tree/master/stock
[bitburnerSave_BN1x2_1558036260.txt]
**Edit:** (https://github.com/danielyxie/bitburner/files/3188817/bitburnerSave_BN1x2_1558036260.txt)

**Comment by danielyxie** [comment]
Both of these issues should be fixed in v0.47.1. (The forecast immediately jumping between + and - was expected, but it has now been removed in the new update)
