### ISSUE TITLE
Game crashes when opening stock market tab

### ISSUE THREAD

**Issue by Kalumniatoris** [danielyxie/bitburner#616]
With 64 times

`vendor.bundle.js:126 Uncaught RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at t.StockTickerHeaderText (engine.bundle.js:1)
    at qi (vendor.bundle.js:126)
    at Lo (vendor.bundle.js:126)
    at Us (vendor.bundle.js:126)
    at Vs (vendor.bundle.js:126)
    at Fa (vendor.bundle.js:126)
    at _a (vendor.bundle.js:126)
    at wa (vendor.bundle.js:126)
    at Xs (vendor.bundle.js:126)`

error in browser console.

Manipulating shares through scripts seems to work.

**Comment by danielyxie** [comment]
Could you upload your save file? I can't seem to reproduce this in any of my saves

**Comment by Kalumniatoris** [comment]
https://pastebin.com/raw/C3qxkvsQ 

I probably should note that I had problems with Stock Market since I started playing. All stocks (no portfolio) mode were showing only one position, and 'arrow button' to show options was not responsive (so I wasn't able to buy/sell anything manually anyway, but at least game continued to work). That repaired somehow about week ago (coincidentally at the same time when something definitely unrelated  broke in my computer setup), for few days everything worked fine then.

**Comment by danielyxie** [comment]
This has to do with your locale. The locale you use formats money with a longer length than expected. I'll take this into account with a future update. 

For now, you can fix it by switching to a different locale.

**Comment by Kalumniatoris** [comment]
I can confirm that fixing locale fixed this. I would prefer to use $ anyway, sadly there is no locale that uses $ and long scale at the same time, id like to see currency and format as separate options, but I know that almost (if any) nobody except me would use it so it's rather unimportant thing to do that would probably only add needless additional problems.

**Comment by danielyxie** [comment]
Fixed in v0.47.2
