### ISSUE TITLE
World Daemon no longer spawns in latest patch

### ISSUE THREAD

**Issue by Googleshng** [danielyxie/bitburner#617]
Getting to the end of my first run through Bitnode-2, after installing The Red Pill, there simply is no World Daemon server anywhere. I've tried looking again to see if it would appear, but the issue seems to be persistent.

**Comment by danielyxie** [comment]
Can you upload your save file?

**Comment by Googleshng** [comment]
Sure.

[NoWorldDaemon.zip.zip](https://github.com/danielyxie/bitburner/files/3194816/NoWorldDaemon.zip.zip)

**Comment by danielyxie** [comment]
That's very weird. When I tested, doing a Soft Reset made the server appear. Not sure why it didnt appear in the first place though

**Comment by Googleshng** [comment]
Soft Reset worked for me too just now, but installing augments didn't. Might be an issue there, if I didn't just hit the same fluke lack of spawn twice in a row?

**Comment by danielyxie** [comment]
I tested by 'Installing Augmentations' and the World Daemon server spawned just fine. Also 'Installing Augs' and 'Soft Reset' both essentially call the same code, so it'd be weird if one of them caused a bug but the other did.

It's hard to say anything without being able to reproduce it. I'll continue looking into it.
