### ISSUE TITLE
Singularity API suggestion: tail()

### ISSUE THREAD

**Issue by AustinSpafford** [danielyxie/bitburner#620]
Hello!

There have been a couple of times where I've wanted a script to be able to display its log to the user. This has especially come up while writing an `afk.ns`, which at a minimum is switching between working for multiple factions to make all the augmentations purchasable. Being able to read the log while a script is performing a player-busying action has been extremely useful during development/debugging, or to even just give the user useful information such as time estimates.

I imagine an `ns.tail()` would take parameters similar to `ns.kill()`, and use `findRunningScript()` to locate the instance to pass to `logBoxCreate()`.

Admittedly, I can (and do) currently use `run afk.ns ; tail afk.ns` to get the job done, though its a bit tedious to retype when needed. I'd prefer to just have an `afk` alias for such a common situation, but unfortunately I see that there's a couple of gnarly design conflicts that would make it more complicated than escaping semicolons and moving `substituteAliases()` up one level in the call stack. If there was a `tail()` singularity function, then I could incorporate the tailing behavior into `afk.ns`, thus allowing the script to be aliased.

Another minor use case where it'd be handy is to tail any script being worked on, since that's when restarting the script instance is a common action. Because script-killing is asynchronous, kill/run/tail can't be placed into a single terminal command sequence. Instead, I currently have a `restartProcess.ns` to now handle the first two steps, and a `tail()` would allow the third step to be completed by either `restartProcess.ns` or the script itself.

Thank you for your time! :)

**Comment by danielyxie** [comment]
Fixed in v0.47.2
