### ISSUE TITLE
Missing checks for disableLogs.workForFaction

### ISSUE THREAD

**Issue by AustinSpafford** [danielyxie/bitburner#621]
`ns.workForFaction()` currently does not check `disableLogs.workForFaction` when logging its "Started carrying out..." messages:
https://github.com/danielyxie/bitburner/blob/20ca7533b068a860f752f1d2f7ef1c0c06b162f8/src/NetscriptFunctions.js#L3025

This is only minor, but it'd be nice to be able to fully silence that function! :)

**Comment by danielyxie** [comment]
Fixed in v0.47.2
