### ISSUE TITLE
hacknet.spendHashes should show online money production (when selling)

### ISSUE THREAD

**Issue by thePalindrome** [danielyxie/bitburner#637]
Just as a QoL/Nerd stats thing, I'd personally like to be able to see the money production stats caused by spendHashes() selling hashes, with *maybe* the "production rate" showing an average, if it's not too big of an issue.

**Comment by danielyxie** [comment]
I'm a bit confused by what you're suggesting. Are you asking for the `hacknet.spendHashes()` function to update a script's stats so that in the "Active Scripts" UI, a script's production info accounts for money gained from hashes?

**Comment by hydroflame** [comment]
This can't be done anymore because it could be used to double offline earnings from hacknet servers.
