### ISSUE TITLE
Coding contract "find all valid expressions" has an unstated requirement

### ISSUE THREAD

**Issue by ToxicFrog** [danielyxie/bitburner#641]
Specifically, you are not allowed to have 0-prefixed numbers inside the expression, so given an input like this:

    ["101", 2]

The following are considered valid solutions:

    1+0+1
    1-0+1

But this is not:

    1+01

Despite computing the same value.

This requirement is not documented anywhere in the coding contract itself, and I eventually had to resort to reading the source and comparing helper() to my own solver to figure out where it was going wrong.

**Comment by danielyxie** [comment]
Fixed in v0.47.2
