### ISSUE TITLE
De-inecentivised travel? (Balance)

### ISSUE THREAD

**Issue by AnonTheMouse** [danielyxie/bitburner#74]
After playing for a while in just Sector-12, I decided to play around with other cities. I was pleased to learn that some had their own training locations in the world menu, and that the higher cost came with a higher experience gain. There was just one problem. I had applied for the lowest requirement job I could find in Sector-12, gotten a promotion which _still_ had lower requirements than pretty much any other job I'd found, and was already getting paid a great salary to gain hacking exp at a higher rate than even the most prestigious university, which I'd had to spend a few hundred thousand game-dollars to find in the first place. So I was left wondering, what was even the point in these schools? Sure, if I can get there early I'll have a jump-start, but it's almost immediately surpassed by something that costs me nothing to do.

**Comment by danielyxie** [comment]
Addressed in next update
