### ISSUE TITLE
Weirdness with null comparisons in Netscript, but only sometimes?

### ISSUE THREAD

**Issue by chrisacheson** [danielyxie/bitburner#805]
I'm working on a script to automate hacknet upgrades, and have encountered some very weird and inconsistent behavior when doing comparisons involving `null`. This code snippet:

```javascript
        ns.tprint("====");
        let a = null;
        let b = 10;
        ns.tprint(JSON.stringify([a, b]));
        ns.tprint(JSON.stringify([a === null, a <= b]));
        ns.tprint(a === null);
        ns.tprint(a <= b);
        ns.tprint("====");

        ns.tprint(JSON.stringify([new_node_payoff_time, max_payoff_time]));
        ns.tprint(JSON.stringify([new_node_payoff_time === null, new_node_payoff_time <= max_payoff_time]));
        if(new_node_payoff_time === null || new_node_payoff_time <= max_payoff_time) {
            // If best_upgrade.node remains null, we'll buy a new node
            best_upgrade = { node: null
                           , type: null
                           , payoff_time: new_node_payoff_time
                           , cost: new_node_cost
                           };
        }
        ns.tprint(JSON.stringify(best_upgrade));
```

Results in this output:

```
[12/21 08:14 home ~/]> run hacknet.ns
--
Running script with 1 thread(s) and args: [].
hacknet.ns: ====
hacknet.ns: [null,10]
hacknet.ns: [true,true]
hacknet.ns: true
hacknet.ns: true
hacknet.ns: ====
hacknet.ns: [null,86400]
hacknet.ns: [false,false]
hacknet.ns: null
[home ~/]$
```

The code with `a` and `b` gives the output that one would expect. `a` is `null`, and `a === null` evaluates to `true`. With the `<=` comparson, `null` is treated as `0`. The same comparisons with `new_node_payoff_time` and `max_payoff_time` give different results, though. I tried using the soft reset and delete active scripts options, but they didn't help.

Here's my save file:

[bitburnerSave_BN1x2_1608555717.json.txt](https://github.com/danielyxie/bitburner/files/5724412/bitburnerSave_BN1x2_1608555717.json.txt)

**Comment by hydroflame** [comment]
So while we can all agree this is weird, this has nothing to do with BitBurner. This is how javascript acts and there's nothing we can do about this.
