### ISSUE TITLE
Static ram parser doesn't handle all javascript feature.

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#822]
```
export async function main(ns) {
    ({}).name?.hello
    ns.hack('foodnstuff');
}
```

Perfectly valid javascript code but because of the null propagation operator the static ram parser will crash.

**Comment by sschmidTU** [comment]
Yes, this is called optional chaining, introduced to JS in 2020.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by sschmidTU** [comment]
(Also called the Elvis operator in Typescript, it kind of looks like Elvis hair)
