### ISSUE TITLE
Terminal History Start Cursor on right

### ISSUE THREAD

**Issue by ChaoticWyrme** [danielyxie/bitburner#836]
When you use the up arrow to go up in command history, the cursor starts on the left of the command, and if you want to edit the command, the thing you want to edit is most often on the right, so it would be nice to move the cursor to the right when you go up in the command history.

**Comment by sschmidTU** [comment]
This is also default behavior in (my) unix console. I agree it would be nice.

**Comment by sschmidTU** [comment]
Actually the cursor does locate to the end now when going through history. I could swear it was different a minute ago. maybe a situational result?

**Comment by ChaoticWyrme** [comment]
If you go to the end on a command, it remembers that, you can reliably get the bad behavior by entering a new command, then hitting up.

**Comment by hydroflame** [comment]
@ChaoticWyrme It's easy to fix but I can't reproduce on my mac + chrome. What OS/browser are you using?

**Comment by sschmidTU** [comment]
ctrl+a/ctrl+e doesn't work for me in Windows + Chrome/Firefox/Edge. ctrl+a selects the text, ctrl+e opens a search in the address bar.
but that's okay, my keyboard layout has Pos1 and End in a handy spot anyways. just saying.

**Comment by ChaoticWyrme** [comment]
I'm using Windows + Firefox, and I get the same behavior as @sschmidTU with ctrl+a and ctrl+e. What's more, since I'm on a laptop, I don't have an end key on my keyboard, so I generally have to ctrl+right arrow my way over.

Probably the solution to getting ctrl+a and ctrl+e to working is cancelling the default in the keyboard handler. You can do a similar thing to intercept Ctrl+S in an editor, so that the browser doesn't try to save the page.
