### ISSUE TITLE
Scan crashes when server names are too long.

### ISSUE THREAD

**Issue by Kibble** [danielyxie/bitburner#855]
**Environment:** Chrome 89.0.4389.128 (Official Build) (64-bit), Windows 10 Home

**Save File:** [saveFile.zip](https://github.com/danielyxie/bitburner/files/6360311/saveFile.zip)

**Reproduction Steps (Not sure if can be reliably reproduced):**
- Purchase and name additional servers:
  - lonely-blackwell (8GB)
  - high-curie (8GB)
  - happy-hugle (8GB)
  - insane-pare (8GB)
  - sad-bohr (8GB)
  - backstabbing-archimedes (8GB)
  - sleepy-liskov (64GB)
  - evil-leakey (512GB)
- Run the "scan" command at "home"

**Notes:**
- 8GB servers were purchased in Sector-12, others were purchased in Aevum

**Results:**
- backstabbing-archimedes, sleepy-liskov, and evil-leakey do not show up

**Dev Console:**
```
Uncaught RangeError: Invalid array length
    at Object.executeScanCommand (engine.bundle.js:1)
    at Object.executeCommand (engine.bundle.js:1)
    at Object.executeCommands (engine.bundle.js:1)
    at HTMLDocument.<anonymous> (engine.bundle.js:1)
    at HTMLDocument.dispatch (vendor.bundle.js:46)
    at HTMLDocument.m.handle (vendor.bundle.js:46)
```

**Comment by hydroflame** [comment]
Oh, ok it's because the name for the server `backstabbing-archimedes` is too long for a specifc function in the game. Easy to fix.

**Comment by Kibble** [comment]
Thought that might be it. Also related then, a visual issue with long server names on the Active Scripts view:

![image](https://user-images.githubusercontent.com/670065/115816328-af031900-a3c6-11eb-9ccf-cf1e4a335f87.png)

**Comment by hydroflame** [comment]
Fixed in next patch.
