### ISSUE TITLE
Allow folders to be "created" on the home pc (and other pcs)

### ISSUE THREAD

**Issue by andrew-oliver-genesys** [danielyxie/bitburner#86]
I'm absolutely loving this game, and had a thought I wanted to throw up here because I thought it'd help clean up the home pc some.  

I'm loving the game, and have spent way too much time on it.  But thanks for making it even if you don't take this "issue" into the game.

**Comment by danielyxie** [comment]
I'll do this eventually but its not a priority atm so it might take a while
