### ISSUE TITLE
getServerMaxRam / getServerCurrentRam

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#881]
getServerRam causes quite a lot of confusing because it returns an array. So let's make 2 separate functions.

**Comment by sschmidTU** [comment]
yeah, i also found it confusing in the beginning, though i of course got used to it. Also you write a lot of getServerRam()[0] which is not very obvious to read.

**Comment by sschmidTU** [comment]
These should both use 0.05GB of RAM i guess, not 0.1GB like getServerRam(), otherwise you'd double the cost.
The alternative would be for getServerRam() to return an object with .maxRam and .currentRam, i guess.
