### ISSUE TITLE
The tutorial needs to do a better job of informing programmers to use ns2

### ISSUE THREAD

**Issue by hydroflame** [danielyxie/bitburner#989]
as well as inform players to use backdoor

**Comment by sschmidTU** [comment]
"Note to programmers: Consider using Netscript2, which is [faster and basically Javascript](https://bitburner.readthedocs.io/en/latest/netscript/netscriptlearntoprogram.html#netscript-1-0-vs-netscript-2-0)"

Insert something like this somewhere? ^^
