### ISSUE TITLE
Cannot manually throw errors via throw statement

### ISSUE THREAD

**Issue by Fayti1703** [danielyxie/bitburner#99]
Attempting to use a throw statement, as in
```
throw "the towel";
```
throws an
```
Unrecognized token: ThrowStatement. This is a bug please report to game developer
```
which still crashes the script, but in an unexpected way.

_(I know, this is more of a feature request thing again, I'm sorry, it told me to report it.)_

**Comment by danielyxie** [comment]
Added in v0.35.0. No catch statements (yet) though
